neos/neos-development-collection

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/ContentCache.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/ContentCacheTest.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/ContentCache.ts2

Previously when nesting content with Content Cache mode `cached` within
segments with Content Cache mode `dynamic` the `CONTENT_CACHE` markers
weren't replaced at the second rendering.
Fixes: #1591

BUGFIX: Allow cached content segments to be nested within dynamic ones

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/TemplateImplementation.php

The sprintf() call should only get one parameter, usage of the first
one was dropped inside the message text previously.

BUGFIX: Show object in "missing template" message

---

Neos.Neos/Documentation/CreatingASite/Fusion/InsideFusion.rst

see https://neos-project.slack.com/archives/C050C8FEK/p1509054474000170

TASK: Adds a hint that `@context` cant access context variables on the same level

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Frontend/NodeController.php

A non existing (or hidden) target node would result in an infinite
redirect chain but should actually result in a 404 error delivered.
Fixes: #1668

BUGFIX: Shortcut nodes result in 404 if target is unavailable

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.js

When using too many assets in the inspector (AssetEditor), an error is
triggered, caused by the request URI becoming too long.
This change switches the request to a POST request. The data is sent as
the request body and the issue is solved.
Fixes #1747

BUGFIX: Avoid Request URI Too Large when loading asset metadata

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/NodeTree.js

Make sure the publish button is updated so the new changes can be published.
Additionally selects the newly copied page similar to when inserting a new document.
Resolves #914

BUGFIX: Update publish button when copying page in node tree

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Strategy/AssetUsageInNodePropertiesStrategy.php

Prevent assets referenced in moved nodes from breaking the asset view in the media module.
Fixes #1742

BUGFIX: Assets used in moved nodes don't break media module asset view

---

Neos.Neos/Classes/Routing/Aspects/RouteCacheAspect.php

This fixes #1767 by changing the vendor name from TYPO3 to Neos in
the `RouteCacheAspect` in one place where it was obviously overlooked.

BUGFIX: Fix wrong target class in RouteCacheAspect

---

TYPO3.Neos/Documentation/ExtendingNeos/CustomizingInspector.rst

Based on this post: https://discuss.neos.io/t/solved-remove-properties-from-nodetype-of-included-package/2751/6

TASK: Fix remove a selectbox option from an existing Node Type documentation

---

Neos.NodeTypes/Resources/Private/Fusion/Root.fusion

Just a "beauty correction".
- Removed "typo3" in class naming for alignment in Neos.NodeTypes:Image

TASK: Removed `typo3` in class naming for alignment in Neos.NodeTypes:Image

---

Neos.Media/Classes/Command/MediaCommandController.php

This change
1. Fixes an by checking Doctrine ORM Entity Manager during calling the command.
2. Renames the used table names to the actual names in the database.
3. Uses `ConfigurationAssetModelMappingStrategy` to determine target asset type.

BUGFIX: Adapt media CLI command to import resources after vendor name changes

---

Neos.NodeTypes/Resources/Private/Fusion/Root.fusion

Adjusts the `Neos.NodeTypes:Form` Fusion prototype to make
the current `Fusion\Runtime` available to the Form renderer
via the forms rendering options.
Background:
This is especially useful for forms that are rendererd with
the `neos/form-fusionrenderer` which, otherwise, can't re-use
Fusion prototypes that are not explicitly loaded.
For forms rendered with the `neos/form-builder`, the runtime
is already set.

TASK: Make FusionRuntime available to Form Renderers

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php

This adds the `generateUriPathSegments` identifier to the `node:repair`
help text.

TASK: Add generateUriPathSegments check identifier

---

Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Documentation/References/PropertyEditorReference.rst
Neos.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.html
Neos.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.js
Neos.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditor.html
Neos.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditor.js

Adds two new feature flags, `upload` and `mediaBrowser` that
allow to hide respective buttons in the `Image` and `Asset`
editors.
Usage:
```yaml
'Some.Node:Type':
properties:
'someImageProperty':
type: Neos\Media\Domain\Model\ImageInterface
ui:
inspector:
editorOptions:
features:
upload: false
'someAssetProperty':
type: Neos\Media\Domain\Model\Asset
ui:
inspector:
editorOptions:
features:
mediaBrowser: false
```
Background:
When uploading assets through the property editors, that happens
within the context of a selected node (unlike when it's added
through the media module). This allows us to assign the resulting
asset to a collection/tag based on the node type or path for
example.
Related: #893
Related: #1131

FEATURE: Upload/MediaBrowser flags in Image and Asset editor

---

TYPO3.Neos/Documentation/HowTos/ExtendingPages.rst

Fix exception when following documentation about extending pages.
See detailed description and discussion on https://discuss.neos.io/t/1952

BUGFIX: Fix wrong TS path in extending pages example

---

Neos.Media/Classes/Domain/Service/ImageService.php
Neos.Media/Configuration/Settings.yaml
Neos.Media/Documentation/ConfigureImageGeneration.rst

This change adds a new setting in the Media package to enable image interlacing.
It's disabled by default, but you can change the setting to one of the values in
`Neos.Media.image.defaultOptions.interlace`:
- `%\Imagine\Image\ImageInterface::INTERLACE_NONE%` (default)
- `%\Imagine\Image\ImageInterface::INTERLACE_LINE%`
- `%\Imagine\Image\ImageInterface::INTERLACE_PLANE%`
- `%\Imagine\Image\ImageInterface::INTERLACE_PARTITION%`

TASK: Allow to configure if processed images must be interlaced

---

Neos.Neos/Classes/Controller/Backend/ContentController.php
Neos.Neos/Classes/Domain/Service/SiteService.php
Neos.Neos/Classes/Package.php
Neos.Neos/Documentation/HowTos/TaggingAssetsAutomatically.rst
Neos.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/FileUpload.js

Introduces a signal `ContentController::assetUploaded` that
sends the currently selected `node` and the `siteNodeName`
along with the asset that's about to be persisted.
This allows the asset to be tagged or added to collections
based on the node type or path etc.
For example, the following slot would assign assets of an
`Employee` node type to the corresponding tag:
```php
public function theSlot(Asset $asset, NodeInterface $node, string $propertyName, string $siteNodeName)
{
if (!$node->getNodeType()->isOfType('Some.Package:Employee') || $propertyName !== 'image') {
return;
}
$tag = $this->tagRepository->findOneByLabel('Employee');
if ($tag === null) {
return;
}
$asset->addTag($tag);
}
```
Resolves: #893

FEATURE: Allow modification of uploaded assets based on node

---

Neos.Neos/Classes/Service/BackendRedirectionService.php
Neos.Neos/Configuration/Settings.yaml

This is to allow switching to the new UI seemlessly but
also allows to set a completely different module to be used
after login.

FEATURE: Allow configuring route after login to backend

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/PublishingService.php

`TYPO3\Neos\Service\PublishingService` traverses all children of a node to discard that node recursively. Not all those nodes are actually publishable though, so the following batch discard operation fails with the Exception `#1395841899: Nodes in a in a workspace without a base workspace cannot be discarded`.
So, I added a filter to `TYPO3\Neos\Service\PublishingService::discardNode` that removes all nodes from the to-be-discarded list, that are in a different workspace than the given node.
Resolves: #1710

BUGFIX: Make sure nodes that are to be discarded are actually publishable

---

TYPO3.Neos/Resources/Private/Styles/Foundation/_buttons.scss
TYPO3.Neos/Resources/Public/Styles/Includes-built.css
TYPO3.Neos/Resources/Public/Styles/Neos.css

On Chrome (macOS), all `<button>` elements had a `border-radius` of `4px`, which is now removed.

TASK: Fix border-radius on button elements

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/DimensionsMenuImplementation.php

When using the DimensionsMenuImplementation without a set `dimension`
(yes, there are use cases for that, e.g. hreflang tags for language _and_
country), the following could happen:
Call to a member function getLabel() on null
This change avoids that.

BUGFIX: Avoid error if no dimension is set in DimensionsMenuImplementation

---

Neos.ContentRepository/Classes/Domain/Model/InterDimension/ContentSubgraph.php

Without that accessing getWeight caused a TypeError if no dimensions were configured since the getWeight method enforces the return-type array.

BUGFIX: Add missing default value for weight of InterDimension/ContentSubgraph

---

Neos.NodeTypes.Form/composer.json

This dependency was forgotten in the NodeTypes split.

BUGFIX: Add missing neos/form dependency

---

Neos.Neos/Classes/Controller/Module/Administration/SitesController.php

The title parameter was missing, so the other parameters were used in strange ways.

BUGFIX: Off-by-one error in FlashMessage parameters

---

Neos.Neos/Migrations/Mysql/Version20171206140453.php

Adds an index that should exist but is not picked up by Doctrine, and
thus was deleted by accident in 20170110130253.
See https://github.com/neos/neos-development-collection/pull/1375

BUGFIX: Add index that should exist but does not

---

Neos.NodeTypes/composer.json

This dependency was forgotten in the NodeTypes split.

BUGFIX: Add missing dependency to Neos.NodeTypes.Form to Neos.NodeTypes

---

Neos.NodeTypes.Form/Resources/Private/Fusion/Root.fusion

Initialize ``overrideConfiguration`` as empty ``array`` so it's not ``null`` when passed to the form template.

BUGFIX: Initialize overrideConfiguration in Fusion

---

Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml

The creation dialog has been introduced in the new UI, for more details
see here: https://github.com/neos/neos-ui/issues/1469

TASK: define missing schema for the creation dialog elements

---

Neos.Neos/Resources/Private/Translations/en/Main.xlf

We need to bring all UI labels in one place again to allow them to be translated.
After this PR is merged, there'll be a follow-up PR to update the labels used there.

TASK: merge in labels from the new UI

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Resources/Private/Partials/ListView.html
Neos.Media.Browser/Resources/Private/Partials/ThumbnailView.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html

When you open the media module with a lot of high-res images while the thumbnails are not already generated and cached, loading can take a long time without noticable feedback.
The templates use a setting not available since the media browser was split into it's own package. Instead the setting needs to be read from the Media package.

BUGFIX: Load thumbs in media browser asynchronous

---

Neos.Media/Classes/Domain/Service/AssetService.php

PR #1597 has introduced a missing service injection. 
The ImageService is used but never injected into AssetService.
See: https://github.com/neos/neos-development-collection/blob/master/Neos.Media/Classes/Domain/Service/AssetService.php#L269

BUGFIX Inject missing ImageService into AssetService

---

Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php

The comment for the `ignoreProperties`-variable missed a "not" and thus was misleading.

DOCS: Fix misleading comment in Neos.Fusion:Component implementation

---

.travis.yml

This removes some options no longer needed, since the required PostgreSQL
versions are meanwhile available without any use of sudo in the default
container infrastructure, as shown in
- https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
- https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

TASK: Tweak Travis CI build matrix

---

.travis.yml

As of https://github.com/neos/flow-development-collection/pull/1160
Flow requires PHP 7.1 or higher.
The master of Neos needs to follow, so this adjusts the Travis CI
build matrix to skip PHP 7.0.
Additionally it removes some options no longer needed, since the
required PostgreSQL versions are meanwhile available without any
use of sudo in the default container infrastructure, as shown in
- https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
- https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

TASK: Adjust Travis CI build matrix to use PHP 7.1+

---

Neos.ContentRepository/Classes/Migration/Configuration/YamlConfiguration.php

This makes sure node migrations not named as expected are detected
and rejected properly.

TASK: Check node migration filename before use

---

.composer.json
Neos.ContentRepository/composer.json
composer.json

After the required version of some dependencies have been raised in Flow,
Neos cannot be installed as `dev-master`, since no installable set of
dependencies can be computed.
This raises one suspect blocking this.

TASK: Raise gedmo/doctrine-extensions requirement to ~2.4.0 

---

Neos.Neos/Documentation/ExtendingNeos/CustomEditPreviewMode.rst

**What I did**
I added missing components in documentation for custom preview modes
I analysed the react frontend and found some editable variables for height and width. After searching the code for it, I found some optional variables, which were missing in the documentation. These variables are new and came with the new UI.

TASK: Document canvas width and height in editPreviewMode

---

Neos.ContentRepository/Classes/Migration/Service/NodeTransformation.php

This change allows to create/use node transformations that do not use settings.
Without this change, one always had to provide dummy settings.

BUGFIX: Allow node transformations without setting

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php

When a DateTime property value is either set for the first time or unset the workspace module will now show that change. Previously it would only display the change if the time was set changed to a different time.

TASK: Display changes in workspaces module when setting/unsetting a DateTime values

---

Neos.ContentRepository/Classes/Migration/Command/NodeCommandController.php
Neos.ContentRepository/Classes/Migration/Configuration/YamlConfiguration.php
Neos.Neos/Documentation/References/NodeMigrations.rst

With this change node migrations are expected to be located
in a directory `Migrations/NeosCR`.
For backwards compatibility migrations in `Migrations/TYPO3CR` are
still supported.
Fixes: #1861

TASK: Rename folder for Node Migrations

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Page.ts2
TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentContextBar.js

Preview links are now generated via Fusion instead of Javascript

BUGFIX: Let fusion render preview URIs for the Neos backend

---

Neos.Neos/Classes/Service/XliffService.php
Neos.Neos/Tests/Functional/Service/Fixtures/de/BasePackage.Included.xlf
Neos.Neos/Tests/Functional/Service/Fixtures/de/BasePackage.NotIncluded.xlf
Neos.Neos/Tests/Functional/Service/Fixtures/de/DependentPackage.Included.xlf
Neos.Neos/Tests/Functional/Service/Fixtures/de/DependentPackage.NotIncluded.xlf
Neos.Neos/Tests/Functional/Service/XliffServiceTest.php

Recently (Flow 4.2) introduced the feature to override labels from other packages or add own translations for other packages via neos/flow-development-collection#894. This was formerly suggested in JIRA-issue FLOW-61.
This works nicely but the Neos UI is not using `\Neos\Neos\Service\XliffService`. This Service deliveres a xliff-json that contains labels e.g. for the property editor. Currently you cannot override labels from other packages that are used in the property editor. `\Neos\Neos\Service\XliffService::parseXliffToArray` is annotated (todo) to be changed when FLOW-61 is resolved.
This change refactors the class to make use of `\Neos\Flow\I18n\Xliff\Service\XliffFileProvider::getFile` which handles the overrides.

BUGFIX: Use XliffService label override for Neos UI

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js

Changes the base node type filter used in the context structure tree to explicitly include content collections and content elements instead of everything that's not a document node type.
Resolves #1784

BUGFIX: Context structure tree only shows content

---

Neos.ContentRepository/Classes/Domain/Model/IntraDimension/ContentDimension.php

The use of the ternary operator with a potentially undefined array index
leads to errors, this change uses the null-coalesce operator (`??`) instead.
> In particular, this operator does not emit a notice if the left-hand
> side value does not exist, just like isset(). This is especially useful
> on array keys.
(http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce)

BUGFIX: Avoid errors on undefined array index

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Security/Authorization/Privilege/Node/ReadNodePrivilege.php

The ``ReadNodePrivilege`` evaluates it's EEL evaluator twice unnecessarily,
there's some caching however it should optimize some cases.

TASK: ``ReadNodePrivilege`` evaluates EEL expression only once

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Neos.ContentRepository/Classes/Migration/Service/NodeMigration.php

This adds findAllIterator to the NodeDataRepository
and uses it in the NodeMigration, which makes it
possible to run migrations on large datasets.
Before, a `findAll()` on the NodeDataRepository was used, which does not scale at all
and exceeds even higher memory limits with repositories > 30k nodes.

TASK: Improve node migration for large data sets

---

Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/AbstractNodePrivilege.php
Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/AbstractNodePropertyPrivilege.php
Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/CreateNodePrivilege.php
Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/EditNodePrivilege.php
Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/ReadNodePrivilege.php
Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/RemoveNodePrivilege.php

Node privileges did a lot of unnecessary initialization
and didn't properly fetch the CompilingEvaluator instance
possibly wasting cache hits.
This fixes some of those problems which should improve Node
security performance quite a bit.

TASK: Improve NodePrivilege performance

---

Neos.NodeTypes/Configuration/NodeTypes.Mixins.yaml

The mixins in this package are not declared abstract. This leads to issues with
Elasticsearch indexing. Abstract node types are not mapped, but these mixins
are not abstract, thus they are mapped. Any mapping configuration that is
applied to `Neos.Neos:Node` must therefore also be applied to all mixins,
if any conflicts appear between fields (e.g. `_all`).

BUGFIX: Declare mixin node types as abstract

---

Neos.Neos/Classes/Service/XliffService.php

If a package has no translation files, readDirectoryRecursively
throws an exception. Check for an existing translation directory first.
Fixes: #1887

BUGFIX: Only scan existing translation path

---

Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php
Neos.Neos/Resources/Private/Translations/en/NodeTypes/Document.xlf

In the same time, the "Title" label for a new Document node is
added to the language files. The creationDialog configuration
for this node type is inside Neos.Neos.Ui.
Fixes: neos/neos-ui#1539

TASK: Enable i18n for node creation dialog

---

TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedNodes.html

A call to a VH inside another VH call was not using correctly escaped
single quotes, breaking parsing.

BUGFIX: Fix VH call quote escaping in RelatedAssets.html

---

TYPO3.Neos/Resources/Private/Styles/Media/_Media.scss
TYPO3.Neos/Resources/Public/Styles/Neos.css

Prevent flickering when dragging a file over the label inside the dropzone.
Fixes: #1889

BUGFIX: Flickering upload dropzone in media module

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/View/NodeView.php

When using the search field or node type filter in the node tree,
the NodeTreePrivilege policies aren't taken into account.
Resolves #1867

BUGFIX: Enforce NodeTreePrivilege when filtering node tree

---

Neos.Media.Browser/Resources/Private/Templates/Asset/RelatedNodes.html
Neos.Neos/Classes/Domain/Strategy/AssetUsageInNodePropertiesStrategy.php

This change adds a missing namespace import to `AssetUsageInNodePropertiesStrategy`
and fixes references to label translations and a partial in the
RelatedNodes template.

BUGFIX: Fix two errors in media management caused by upmerge

---

Neos.Neos/Classes/Setup/Step/SiteImportStep.php

The site import step previously deactivated existing sites and only activated
the newly created or selected package. Now that packages can no longer be
activated / deactivated there is only a notice telling the user
about the consequences.

BUGFIX: Fix site import setup step

---

TYPO3.Neos/Resources/Private/Templates/Module/Management/History/NodeLink.html

Without it a space is inserted at first in the quoted link.

TASK: Remove whitespace from history module node link

---

TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Service/EventEmittingService.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Integrations/AbstractIntegrationService.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Integrations/EntityIntegrationService.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Integrations/TYPO3CRIntegrationService.php

For some events (e.g. copying) the account identifier is not set since it's not initialized.
Instead of doing it manually for each event type it's done before generating an event so it's always done.
Resolves: #1914

BUGFIX: Ensure account identifier is always added to events

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js

The "baseNodeType" filtering of allowed child node types was not implemented correctly leading to issues when using multiple allow node type filters.
Fixes: #1933

BUGFIX: Filtering of baseNodeType for create new dialog in trees

---

Neos.Neos/Classes/Controller/Module/Administration/PackagesController.php

The previously called method `getActivePackages` has been removed in a previous commit.

BUGFIX: Call `getAvailablePackages` in packages-module

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php

This avoids a fatal error in case variants of the node are not accessible
for some reason.
Fixes #1896

BUGFIX: Add null check in getOtherNodeVariants()

---

Neos.Fusion/Classes/Core/Parser.php
Neos.Fusion/Migrations/Code/Version20180211175500.php
Neos.Fusion/Migrations/Code/Version20180211184832.php
Neos.Fusion/Tests/Unit/Core/ParserTest.php
Neos.Neos/Classes/Domain/Service/FusionService.php
Neos.Neos/Documentation/CreatingASite/Fusion/InsideFusion.rst
Neos.Neos/Documentation/References/NeosFusionReference.rst

Namespaces were previously transported over `include` boundaries and
thus could end up being declared in packages differently depending on how
the Fusion code was included. This could easily lead to confusion.
With this change namespaces are handled like in PHP and are only valid for the
Fusion file they are declared in.
In addition this removes the overwriting of the `default` namespace `Neos.Fusion` 
with `Neos.Neos` inside of Neos wich could lead to Fusion code failing if used 
in another context.

!!! TASK: Scope fusion-namespaces to current file and remove default `Neos.Neos`-namespace

---

Neos.Neos/Classes/Command/DomainCommandController.php
Neos.Neos/Classes/Command/SiteCommandController.php
Neos.Neos/Classes/Command/UserCommandController.php
Neos.Neos/Documentation/Operations/CommandLine.rst

Add globbing to the follwing cli-commands:
- `site:prune`
- `site:activate`
- `site:deactivate`
- `domain:delete`
- `domain:activate`
- `domain:deactivate`
- `user:delete`
- `user:activate`
- `user:deactivate`
- `user:addrole`
- `user:removerole`
Additionally the `siteNode` is made a required argument for `site:prune`.
To still remove all sites `./flow site:prune "*"` can be used.

FEATURE: Add globbing to `site`,`user` and `domain` cli-commands

---

Neos.ContentRepository/Classes/Domain/Model/NodeData.php

A node can only be moved to one other node, so ManyToOne was never
correct.
See https://github.com/neos/neos-development-collection/issues/1908

TASK: Change NodeData movedTo from ManyToOne to OneToOne

---

Neos.Neos/Classes/EventLog/Domain/Model/Event.php
Neos.Neos/Classes/EventLog/Domain/Model/NodeEvent.php

The `documentnodeidentifier` index defined in `NodeEvent` is not picked
up by Doctrine Migrations when generating a migration. This leads to
it's removal being included in new migrations, and it has actually been
removed unnoticed in the past.
This change adds it to the `Event` class as well, so it is picked up
correctly. See https://github.com/doctrine/doctrine2/issues/6248

TASK: Make sure documentnodeidentifier index is not overlooked

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php

The `NodeDataRepository.persistEntities()` method looped over the
entities and passed them to `flush()` one-by-one. They can be passed
as the array at hand directly.

TASK: Pass affected entities to flush as array, not one-by-one

---

Neos.Neos/Classes/Fusion/ContentElementWrappingImplementation.php
Neos.Neos/Classes/Service/ContentElementWrappingService.php
Neos.Neos/Resources/Private/Fusion/Prototypes/ContentElementWrapping.fusion

This extends the `ContentElementWrapping` in order to allow
additional attributes to be added via Fusion or PHP.
This is useful to augment content and/or to affect its styling
in the Neos backend.
Example (Fusion):
Add the wrapped node's type to a new `data-_node-type` attribute
for all `ContentElementWrapping` instances::
prototype(Neos.Neos:ContentElementWrapping) {
additionalAttributes {
'data-_node-type' = ${node.nodeType.name}
}
}
Example (Fusion):
Add a custom class attribute to a single instance::
@process.contentElementWrapping = Neos.Neos:ContentElementWrapping {
additionalAttributes.class = 'some-additional-class'
}
Example (PHP)::
$this->contentElementWrappingService->wrapContentObject($node, $output, $fusionPath, ['custom-attribute' => 'attribute-value']);
Resolves: #1879

FEATURE: Allow custom attributes to be added to `ContentElementWrapping`

---

Neos.Neos/Classes/Controller/Service/NodesController.php

**What I did**
Added a search for NodeIdentifier when calling `\Neos\Neos\Controller\Service\NodesController::indexAction()`.
That is very helpful, if you have to find one node under thousands (with same NodeType).
See the diff... 
Put an Identifier into a reference/references field in inspector. You should get the correct Node back.

TASK: Also search for $searchTerm as identifier

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php

Even after #1762 showing asset usage sometimes fails, with an error
that can only be explained by `documentNode` being null when trying
to render a reference.
This change adds another safety net for that case.

BUGFIX: Fix asset references detection for nodes even more

---

Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
Neos.Neos/Classes/Command/NodeCommandControllerPlugin.php

When the `/sites` node is missing, Neos can work quite well, but
at least `removeOrphanNodes` will wreck havoc! So this adds a
task to create the sites node if missing.
Note: since `removeOrphanNodes` is in the CR, which has no
notion of what the nodes inside it mean, this check was added
"separately".

FEATURE: Add createMissingSitesNode to node:repair

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/PublishingService.php

BUGFIX: Typo in WorkspaceException #1395841899

---

Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion

The Fusion configuration of `neosBackendMetaData.attributes.data-preview-uri`
lacked a fully qualified Fusion object name, leading to an expansion to
`Neos.Fusion:NodeUri`. That does not exist, leading to an exception right after
login.
Fixes #1971

BUGFIX: Fix Fusion exception after login to Neos

---

Neos.Fusion/Classes/FusionObjects/CanRenderImplementation.php
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Neos/Documentation/References/NeosFusionReference.rst

The prototype checks wether the given type is renderable by fusion. Which means
that the prototype exists and has an implementation class or is based on a prototype that
has one.

FEATURE: Add `CanRender` Fusion prototype

---

Neos.Neos/Classes/Domain/Service/DefaultContentPrototypeGenerator.php
Neos.Neos/Classes/Domain/Service/DefaultDocumentPrototypeGenerator.php
Neos.Neos/Classes/Domain/Service/DefaultPrototypeGenerator.php
Neos.Neos/Configuration/NodeTypes.yaml

The base prototypes and templatePathes are not set by the prototypeGenrator for Neos.Neos:Node and Neos.Neos:Document any more.  For convenience reasons the prototypes for each NodeTypes are declared without base prototype and template all node properties are made accessible as fusion props.

TASK: Remove base prototype and template path from autogenerated fusion for Node and Document

---

Neos.Neos/Documentation/HowTos/SelectingPageTemplate.rst
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion
Neos.NodeTypes/Resources/Private/Fusion/DefaultFusion.fusion

Since the `layout` property is defined in `Neos.NodeTypes`, the `layout`-matcher is
moved to `Neos.NodeTypes` aswell.
If your project relies on the `layout` or `subpageLayout` property but does not use
`Neos.NodeTypes` you have to configure the layout matcher on your own.

!!! TASK: Extract the `layout` root matcher from Neos.Neos and move it over to Neos.NodeTypes

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

When checking for missing child nodes it doesn't check if the existing child nodes are the correct node type. This can happen when a node has been changed to the fallback node type or if the child node type is changed in the configuration.

TASK: Fix incorrect child node types in ``node:repair`` command

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php

Since we overwrite the `logoutAction` from Flow, we need to annotate it with `@Flow\SkipCsrfProtection` here too.
see neos/flow-development-collection#1014

BUGFIX: Skip CSRF protection in logout action

---

Neos.Neos/Classes/Service/LinkingService.php

When the context of the "resolved" node does not have a "current" site
in `LinkingService.createNodeUri()` a fatal error was triggered. This
adds a check and handles the case like a site node path mismatch.

BUGFIX: Avoid getPath() on null in LinkingService

---

Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Projection/GraphProjector.php
Neos.ContentRepository/Classes/Domain/Context/Node/Command/SetNodeReferences.php
Neos.ContentRepository/Classes/Domain/Context/Node/Event/NodeReferencesWereSet.php
Neos.ContentRepository/Classes/Domain/Context/Node/NodeCommandHandler.php
Neos.ContentRepository/Tests/Behavior/Features/EventSourced/NodeReferencesWithDimensions.feature
Neos.ContentRepository/Tests/Behavior/Features/EventSourced/NodeReferencesWithoutDimensions.feature

Remove obsolete letter `t` that was a leftover from previous refactorings.

(Event Sourced) BUGFIX: Fix typo in variable name `DestinationNodeAggregateIdentifiers`

---

Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentSubgraph.php
Neos.ContentRepository/Classes/Domain/Projection/Content/ContentSubgraphInterface.php
Neos.ContentRepository/Tests/Behavior/Features/Bootstrap/EventSourcedTrait.php
Neos.ContentRepository/Tests/Behavior/Features/EventSourced/NodeReferencesWithDimensions.feature
Neos.ContentRepository/Tests/Behavior/Features/EventSourced/NodeReferencesWithoutDimensions.feature

This allows to find all nodes the are referencing the target and optionally filter by propertyName. 
In this case no order of the references can be expected as ordering happens for outgoing references only.

(Event Sourced) FEATURE: Add method `findReferencingNodes` to content-subgraph

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/RuntimeContentCache.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/ContentCache.ts2

Dynamic cache entries are complex and need a lot of information
to be evaluated correctly, therefore the runtime should always take
care of this. This is potentially a bit slower than the original
code but definitely more correct in outcome. Before tags were
definitely wrong as they were based on the parent elements
configuration.

BUGFIX: Dynamic cache entries should be evaluated via runtime

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Basic/MoveNode.feature

Added a filtering for `movedTo` like we already do in `filterNodeDataByBestMatchInContext`.
See description of the discovered behavior in https://github.com/neos/neos-ui/issues/1523#issuecomment-379247165.
Closes #1986

BUGFIX: Exclude shadow nodes in findOneByIdentifier

---

Neos.ContentRepository/Classes/Migration/Filters/DoctrineFilterInterface.php
Neos.ContentRepository/Classes/Migration/Filters/NodeType.php
Neos.ContentRepository/Classes/Migration/Service/NodeFilter.php
Neos.ContentRepository/Classes/Migration/Service/NodeMigration.php
Neos.ContentRepository/Classes/Migration/Transformations/RemoveProperty.php
Neos.ContentRepository/Tests/Functional/Migration/Filters/NodeTypeTest.php
Neos.ContentRepository/Tests/Functional/Migration/MigrationTest.php

Some node migration filters (e.g. the node type filter) should be done via SQL. This can improve performance dramatically as the database engine does the filtering for us, so we don't need to pull and locally filter all the nodes (which can take a long time if you have many nodes).
Fixes #1976

FEATURE: Ability to use SQL in node migration filters

---

Neos.Neos/Classes/Controller/Module/Administration/PackagesController.php
Neos.Neos/Resources/Private/Templates/Module/Administration/Packages/Index.html

The ``protected`` property of packages doesn't make much sense anymore
now that disabling is gone. It will be removed in Flow and in
preparation should no longer be shown here.

TASK: Don't show protected package property as that will go away

---

.travis.yml

This switches builds using PostgreSQL to be sudo-enabled and enlarges
the RAM disk at /var/ramfs to avoid "out of disk space" errors during
the test runs.
Fixes: #2016

TASK: Larger ramfs for PostgreSQL builds on Travis CI

---

Neos.NodeTypes/Resources/Private/Fusion/Documents/Page.fusion
Neos.NodeTypes/Resources/Private/Templates/Documents/Page.html

Add very basic prototype and template to ensure `Neos.NodeTypes:Page` works out of the box.
This is marked breaking since it can lead to unexpected behaviour if you only have the `page` path defined. But it is fairly easy to get your project up to speed with minimal code changes. See: 
https://github.com/neos/Neos.Demo/pull/42 (`page = Neos.NodeTypes:Page` as a fallback)

!!! TASK: Add very basic document prototype and template

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html

Look like `pencil` is only available in the pro version, we need to use `pencil-alt`

TASK: Fix the pencil icon in the mediabrowser

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

Old version still referred developers to Fontawesome 3. Update includes information on including icons with prefix- and icon-class.

Updated Icon Documentation to FA5

---

Neos.Neos/Documentation/CreatingASite/ContentCache.rst

The old namespace was deprecated and is now gone with 4.0

BUGFIX: Use correct cache namespace for redis in documentation

---

Neos.Neos/Tests/Functional/Service/Mapping/NodePropertyConverterServiceTest.php

The UI package comes with a new image serializer that needs to be
configured so the test sees it's expected result.
This change depends on [1b4562c8b71a595b48fec03fac9cd52b9f8c7a5e](https://github.com/neos/neos-ui/pull/1866/commits/1b4562c8b71a595b48fec03fac9cd52b9f8c7a5e) in the
UI package.

TASK: Adjust test to change in Neos.Neos.Ui

---

Neos.ContentRepository/Classes/Migration/Service/NodeMigration.php

This change test if the migration contains a filter before creating the
contrains. Without this change the migration fails with an empty WHERE
clause.
This bug impact the migration `20150716212459`. This migration is used to
define default dimensions on all nodes.

BUGFIX: Fix Node migration without filter

---

Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/PageRendering.rst

Added a colon to make syntax highlighting work.

Tiny documentation typo bugfix

---

Neos.Neos/Documentation/ExtendingNeos/CustomEditPreviewMode.rst

This PR adds documentation for the newlty introduced `backgroundColor` option for custom `editPreviewModes`
related: https://github.com/neos/neos-ui/pull/1864

DOCS: Document custom background color for editPreviewMode

---

Neos.Media.Browser/Resources/Private/Partials/ListView.html

Use `paginatedAssetProxies` instead of `assetProxies` in Neos.Media.Browser ListView to make pagination work again.

BUGFIX: Fix pagination for ListView in Media Browser

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

Resolves: https://github.com/neos/neos-ui/issues/1619
The new UI has this format as the default: https://github.com/neos/neos-ui/blob/9219a78b7bb0e96e1caf7d570c18faef9061423f/packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.js#L192
I think it's time to start officially using it.

DOCS: replace outdated Aloha configuration samples

---

Neos.Media.Browser/Classes/Controller/AssetController.php

assetSourceOptions are used to configure an asset source, but
they are not necessarily needed.

BUGFIX: Do not consist on assetSourceOptions to be set

---

Neos.NodeTypes/Configuration/NodeTypes.Content.Overrides.yaml

The `Neos.NodeTypes:Column` NodeType was always abstract, the 
abtract property isn't inherited down so it must be set again
on any inheriting NodeType. So to have Column abstract it must
declare so (again).
Fixes: #2071

BUGFIX: Column NodeType should be abstract

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/RuntimeContentCache.php

It is necessary to save and restore the `incacheEntryPoint` state in the following situation:
* the dynamic cache segment is evaluated in the **preEvaluate** step of a fusion path which will set `inCacheEntryPoint` to `null`
* the **preEvaluate** returns a "cache miss" because not all segments could be replaced
* Fusion then evaluates the path as usual 
* the runtime content cache then sets `currentPathIsEntryPoint` to `true` in *enter*  bc `inCacheEntryPoint` is still `null`
* the *postProcess* step then processes the cache entry and removes all CONTENT_CACHE markers bc `currentPathIsEntryPoint` is `true`
BTW: In this situation, *uncached* and *dynamic* segments are evaluated twice. But this is outside the scope of this bugfix.

BUGFIX: "inCacheEntryPoint" needs to be saved

---

Neos.Neos/Classes/Controller/Service/NodesController.php
Neos.Neos/Classes/Domain/Service/NodeSearchService.php

Moves the "search by node id" logic from the `NodesController` to the
`NodeSearchService` fixing the following regressions:
* Duplicate results will be filtered
* Respect `$searchableNodeTypeNames` argument
* Don't execute `getNodeByIdentifier()` twice for every search
Fixes: #2079
Related: #1894

BUGFIX: Avoid duplicate results and respect filter in NodeSearchService

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php

Holding a reference to an doctrine object can be dangerous
if something happens to the UOW during that time, so that
a new instance of the entity is produced, resulting in a
stale entity reference that must be considered detached.
We therefore should only cache the persistence identifier of
a user for easier retrieval. If said user was already loaded by
doctrine it will be available in the identity map and should not
trigger another query, making this not less efficient than the
original solution.
Additionally refactored so that the cache is flat.

BUGFIX: Prevent stale object references in user runtime cache

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/Cache/ContentCacheFlusher.php

When using `registerAssetChange()` provided by `ContentCacheFlusher` not all affected
cache entries would always be flushed. This adds flushing of entries tagged `AssetDynamicTag_*`
as done through `ConvertUrisImplementation`–`Runtime`–`RuntimeContentCache` to solve
this.

BUGFIX: On asset change flush entries tagged with AssetDynamicTag

---

Neos.Fusion/Classes/DebugMessage.php
Neos.Fusion/Classes/FusionObjects/DebugDumpImplementation.php
Neos.Fusion/Classes/FusionObjects/DebugImplementation.php
Neos.Fusion/Classes/Service/DebugStack.php
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/FusionObjects/DebugTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Debug.fusion
Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion

This change introduce a DebugStack to store all the debugging
message created with `Neos.Fusion:Debug`, to avoid breaking
the rendering when using var_dump before the HTTP request has
been send, this change flush the DebugStack at the end of the
page rendering. The new `Neos.Fusion:DebugDump` can be used as a
Fusion processor to flush the stack at any point during the
rendering.
The `DebugMessage` is used as a DTO to transport the debugging
informations. It contains a currently unused property `level`.
This property can be used in the future to use a logging backend to
store debugging informations or integrate with protocols like Chrome
Logger to send the debugging informations in the browser directly.

TASK: Improve Fusion debugging experience

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Model/ContextualizedNodeTest.php

For property changes there is no necessity to materialize
auto-created child nodes as well. In projects with deeply
nested auto-created node structures this behaviour could
quickly generate huge amounts of changed nodes therefore
we should only materialize child nodes for structural
changes.
All of this is only valid for workspace materializations though,
in case dimensions need to be materialized as well, we need to
materialize all child nodes as well for consistency.

BUGFIX: Make sure to materialize as few nodes as possible

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

The former`aloha` things need to go under `formatting` and have a new format.

TASK: Fix documentation for inline.editorOptions

---

Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml

Allows to omit some keys that are often (correctly) left out.

BUGFIX: Adjust NodeTypes.schema.yaml in Neos.Neos

---

Neos.Neos/Classes/Fusion/DimensionsMenuImplementation.php

This fixes a regression in dimension menu (introduced by #1159) by 
adding `null` as default arguments back in.

BUGFIX: Fix regression in dimension menu introduced by #1159

---

Neos.Neos/Documentation/References/PropertyEditorReference.rst

Documenting the new `accept`-option.
See: https://github.com/neos/neos-ui/pull/1900

DOCS: Add accept option to Asset- and Image-Editor 

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php

I've found this while going through the code ...
I think there is no reason for this operation

TASK: Remove unneeded ternerary operation

---

Neos.Media/Classes/Domain/Model/AssetCollection.php

As @kitsunet figured out this property should be removed completely as it is not used in any way.

TASK: Remove lastModified as it is not used anywhere

---

Neos.ContentRepository/Classes/Domain/Repository/WorkspaceRepository.php
Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
Neos.Neos/Documentation/CreatingASite/ContentCache.rst
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion
Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion
Neos.Neos/Resources/Private/Fusion/Prototypes/Menu.fusion
Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php
Neos.Neos/Tests/Functional/Fusion/Cache/Fixtures/CacheableNodes.xml
Neos.Neos/Tests/Unit/Fusion/Cache/ContentCacheFlusherTest.php
Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
Neos.NodeTypes.ContentReferences/Resources/Private/Fusion/Root.fusion
Neos.NodeTypes.Navigation/Resources/Private/Fusion/Root.fusion

FEATURE: CacheEntries should respect the workspace they rely on

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

When running the `createMissingChildNodes` in the `node:repair` command, check if a child node exists but has been removed, and if so un-remove it.

TASK: Un-remove removed auto created child nodes in node repair

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

Add the possibility to split the node type definitions into multiple
files to the documentation.

DOCS: Document multiple node type definition files

---

Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php
Neos.ContentRepository/Tests/Unit/Domain/Service/NodeTypeManagerTest.php

The method `NodeTypeManager->getSubNodeTypes(...)` cached results
regardless of the `$includeAbstractNodeTypes` flag. This causes issues
where the first invocation caches results including / not including abstract
node types for further invocations with different flag values.
Fixes #2126

BUGFIX: Fix caching of sub node types in NodeTypeManager

---

Neos.Fusion/Classes/Core/ExceptionHandlers/HtmlMessageHandler.php
Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php

* Return correct HTTP status code of exception screens during Fusion rendering
* Don't hide the exception message in Production Context
* Don't render technical details in Production Context
Fixes: #2133

BUGFIX: Fix rendering of page exceptions

---

Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Resources/Private/Styles/Foundation/_variables.scss
Neos.Neos/Resources/Private/Styles/Login.scss
Neos.Neos/Resources/Private/Styles/Welcome.scss
Neos.Neos/Resources/Private/Templates/Error/Welcome.html
Neos.Neos/Resources/Private/Translations/en/Main.xlf
Neos.Neos/Resources/Public/Styles/Error.css
Neos.Neos/Resources/Public/Styles/Login.css
Neos.Neos/Resources/Public/Styles/Neos.css
Neos.Neos/Resources/Public/Styles/Welcome.css

**What I did**
Changed the error template for "database error" and "missing homepage" to a friendly welcome message, since most users are irritated by the big fat "database error" we greet them with currently.
Old:
New:

FEATURE: Friendlier error pages for setup / missing homepage

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
Neos.ContentRepository/Tests/Functional/Eel/FlowQueryOperations/FindOperationTest.php
Neos.ContentRepository/Tests/Unit/Domain/Model/NodeTypeTest.php

Reverts neos/neos-development-collection#2139 which fixes invalid
behavior but introduced a breaking change.
I will add another PR against the `master` branch to have this in the
next minor release though.

Revert "BUGFIX: Respect disabled superTypes when filtering by Node Type"

---

Neos.Media/Configuration/Settings.yaml

The settings were defined in the wrong namespace and still used `TYPO3` in
some places.

BUGFIX: Fix DocTools settings

---

Neos.Media/Classes/Domain/Service/AssetService.php

This change add a missing use statement for `Neos\RedirectHandler\Storage\RedirectStorageInterface` in `AssetService`. With this statement the replacement of an asset from the medialib browser is not possible.
This bug affect user with the RedirectHandler package, without this package the replacement works fine.

BUGFIX: Unable to replace asset from the media browser

---

Neos.Neos/Classes/Domain/Service/NodeSearchService.php

This change fix a regression introduced by 8667795b8368b052dd71bfe2089ba83254ae2829
The method NodeSearchService::findByProperties must accept term as
string or array. Currently the array support is broken.

BUGFIX: Unable to search nodes with multiple terms

---

Neos.Media/Classes/Command/MediaCommandController.php

Improves the media:removeunused command
- Adds the option "onlyTags", which can be given as comma-separated list of tag labels to filter the assets that should be checked.
- Adds a flag --limit to limit the result of unused assets displayed and removed for a single run.

FEATURE: Improve remove unused assets filter

---

Neos.Fusion/Migrations/Code/Version20180211175500.php

Otherwise prototypes won't get migrated.

BUGFIX: Remove accidental space in code migration

---

Neos.ContentRepository/Classes/Domain/Model/Node.php
Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php

The NodeExistsException was thrown even if the new nodeName does not exist in the new location, because only the old nodeName was checked.
Affected Versions: 3.3+ (I did not check the previous versions because it's not security critical)

BUGFIX: Use the possible new node name to check it's existance in the move to location

---

Neos.Media.Browser/Classes/Controller/AssetController.php

This fixes what is basically a merge error. It lead to a method call
on an unset variable.

BUGFIX: Avoid fatal error when asset not available

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
Neos.ContentRepository/Tests/Functional/Eel/FlowQueryOperations/FindOperationTest.php
Neos.ContentRepository/Tests/Unit/Domain/Model/NodeTypeTest.php

This fixes `NodeType::isOfType()` to return `false` when the given
type is explicitly disabled by the corresponding NodeType or one of
it's super types.
Example:
'Acme:Animal':
superTypes:
'Acme:HasBonesMixin': true
'Acme:Jellyfish':
superTypes:
'Acme:Animal': true
'Acme:HasBonesMixin': false
With this `NodeTypeManager::getNodeType('Acme.Jellyfish')->isOfType('Acme:HasBonesMixin')`
should return `false` but it didn't.
Respectively a FlowQuery like the following should not return any "Jellyfish"-node (or
nodes with a sub-type): `q(node).find('[instanceof Acme:HasBonesMixin]')` but it did.
This might be a breaking change if Fusion or PHP code relies on the broken behavior.
NodeTypes with disabled `superTypes` should be tested for this.
Fixes: #1983

!!! BUGFIX: Respect disabled superTypes when filtering by Node Type

---

Neos.Neos/Documentation/CreatingASite/ContentCache.rst

**What I did**
Fixed a small typo in the caching documentation.
**Checklist**

BUGFIX: Fix typo in cache documentation

---

Neos.Media/Classes/ViewHelpers/FileTypeIconViewHelper.php

If the newly added `$asset` argument is used, it's ignored and overridden to the deprecated `$file` argument.
Resolves #2186

BUGFIX: FileTypeIconViewHelper should work with new $asset argument

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Show.html

solves #2184.
[Label removed](https://github.com/neos/neos-development-collection/pull/1745/files#diff-c7dc0c1301d150887e2fa1d56281f022L149) in #1745 and [wrong property](https://github.com/neos/neos-development-collection/pull/1979/files?w=1#diff-c7dc0c1301d150887e2fa1d56281f022R151) used to link to image in #1979.

BUGFIX: Links to original file in media browser

---

Neos.Neos/Resources/Private/Styles/Neos.scss

This fixes an issue in Neos.scss which referred to wrong filenames
for importing Fontawesome styles.

BUGFIX: Fix SCSS import for Fontawesome files

---

Neos.Neos/Configuration/Settings.yaml

Since switching to a newer version of Font Awesome the icon for the history module has changed to a less detailed version, making it less clear.
Before 4.0:
Before change:
After change:
Be aware that this is not visible in the new UI content module as the icons there are replaced with SVGs where it's actually using the alt version.

TASK: Use correct icon for history module

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Tests/Unit/Domain/Model/NodeTypeTest.php

**What I did**
`NodeType->isOfType()` returned `true` if a node type inherited another node types inherited node type which was declared as `false` in the NodeTypes `superTypes`.
Check existence of node type in inheritance chain instead of recursing through super types.
```yaml
NodeMixin:
abstract: true
NodeA:
superTypes:
NodeMixin: true
NodeB:
superTypes:
NodeA: true
NodeMixin: false
```
Check it with `$nodeB->isOfType('NodeMixin')`.
**Checklist**

BUGFIX: NodeType->isOfType() respects explicitly removed supertypes

---

Neos.Fusion/Classes/Core/Runtime.php
Neos.Fusion/Tests/Functional/FusionObjects/ApplyTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Apply.fusion
Neos.Neos/Documentation/CreatingASite/Fusion/InsideFusion.rst

``@apply`` allows to override multiple properties of a fusion-prototype with a single expression. This is useful when complex data structures are mapped to fusion prototypes.
The example shows the rendering of a ``teaserList``-array by using a Teaser-Component and passing all keys from each teaser to the fusion Object.
```
teasers = Neos.Fusion:Collection {
collection = ${teaserList}
itemName = 'teaser'
itemRenderer = Vendor.Site:Teaser {
@apply.teasers = ${teaser}
}
}
```
The code avoids passing down each fusion-property explicitly to the child component. A similar concept with different syntax from the JavaScript world is known as ES6-Spreads.
Another use-case is to use ``Neos.Fusion:Renderer`` to render a prototype while type and properties are based on data from the context.
``` …
```

FEATURE: Add ``@apply`` meta-keyword to the Fusion-language

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/TypeConverter/NodeConverter.php

This fixes a method signature mistake where
the convertFrom method does not match its
inheritants resp. the interface, leading to errors
in PHP >7.1.
Can you guys do me a favor and and merge this to 2.3 as well as create a tag for the (abandoned) composer package typo3/typo3cr? Need this for a legacy project.
Thanks!

BUGFIX: Make NodeConverter method interface compatible

---

Neos.Neos/Classes/Fusion/DimensionsMenuImplementation.php

**What I did**
Previously the dimensionmenu rendered nodes which
had hidden parents and thus created invalid urls which caused 404 errors.
This also caused the alternate language links in
the neos/seo package to render invalid urls which
caused errors for search engines.
With this change each node is checked if there
is a node missing in its rootline for whatever reason.
1. In the demo site go to a subpage on the 3rd or deeper level
2. Create german translation
3. Hide parent page of german translation
4. Check if link to german translation is still rendered in dimensionmenu on the top right 
**Checklist**

BUGFIX: Hide inaccessible nodes in dimensionmenu

---

Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php

ConvertUris applied to markup containing an
<address> tag and an <a>-tag destroys the address tag
because the regex matches the address tag and inserts
the href there.

BUGFIX: Convert uris destroys address tag

---

Neos.Neos/Classes/Domain/Service/SiteImportService.php

This adds handling of XMLReaders open() returning false
during site import.
Fixes #2199

TASK: Catch error XMLReader when opening XML in site:import

---

Neos.ContentRepository/Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html
Neos.ContentRepository/Resources/Private/Translations/en/Main.xlf

**What I did**
Translate the previous/next links in the paginate widget in Neos.ContentRepository.
Adapt the widget template and copy/adapt Translations from Neos.Media
- use or create a new node type based on a fluid template
- in that node type's fluid template, use the pagination widget from Neos.ContentRepository
- do not override the pagination widget's default template
- create a node of said node type
- translate the page containing it
- visit the frontend in a language other than english
- see how the previous/next links shine
**Checklist**
- PSR-2 yes, but the translation files I copied from are a happy mix of tabs and spaces. Tried to keep that the same for the newly created translation files because I suspect these normally come from a …

FEATURE: Translate paginate widget links

---

Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Edit.html

**What I did**
The user list already allows deleting users, and so does the detail
view (show action). With this change, admins can delete users also
from the *edit* form.
Copied the relevant template parts from the *show* action.
- Log in as user with administrative rights in Neos backend
- navigate to Administration/User Management
- In the user list, click on a users *edit* icon
- below the actual user data a new red button "delete" shows up
**Checklist**
- Cannot run all tests locally due to some gmagick-related issue
- I don't know how to create a test for this feature or whether that is applicable here at all
- I need help with that (https://discuss.neos.io/t/creating-a-pull-request/506 says "features always go to the master branch"?)

FEATURE: Allow deletion of users from edit view

---

Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php

resolves #2081
**What I did**
After a discussion with @daniellienert and @johannessteu we have decided to redirect to a node in backend via Neos.Ui if Neos.Ui is installed. Otherwise, e.g. when the old Ui is used, the node gets redirected through the `NodeController`.
Currently it is loaded always via `NodeController` and in most cases (when Neos.Ui is installed) the node is loaded in frontend without ui.
I have added a check via `PackageManager` for Neos.Ui and redirect the backend links via Neos.Ui `indexAction` if it's installed.
Go into the Neos-Backend Workspace-Module. If you have unpublished changes in a workspace there is an "review"-Button. In the review-Section click on the edit-Link as described in #2081. In case you have installed the new …

TASK: Redirect through Neos.Ui package if it is installed

---

Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/Templating.rst

In the documentation we still use the typo3.org domain for the
xsd files.
Resolves: #1859

TASK: Adjust XSD domain to neos.io

---

Neos.Neos/Classes/Fusion/DimensionsMenuImplementation.php

This fixes a regression not caught by https://github.com/neos/neos-development-collection/pull/2092

BUGFIX: Allow pinnedDimension argument on itemLabel to be null

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Classes/Eel/FlowQueryOperations/FilterOperation.php
Neos.ContentRepository/Tests/Unit/Domain/Model/NodeTypeTest.php

This reverts #2217, since it is potentially breaking.
In #2147 this was fixed for master, and for lower branches it was once fixed in #2139 but reverted through #2145.

BUGFIX: Revert supertype behaviour change

---

Neos.Media/Classes/ViewHelpers/Form/CheckboxViewHelper.php
Neos.Media/Documentation/ThumbnailGenerator/Code.rst
Neos.Media/Documentation/ThumbnailGenerator/Configuration.rst
Neos.Neos/Classes/Command/DomainCommandController.php
Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion
Neos.Neos/Tests/Unit/Domain/Model/DomainTest.php

This change replaces a few occurrences of "TYPO3" with "Neos",
mostly affecting code examples and documentation.

Replace a few occurrences of TYPO3 with Neos

---

Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php

This allows external packages to override those methods with aspects wich in turn allows to implement things like cssModules and propTypes. The behavior of the fusion-component is not modified.

TASK: Extract the methods ``render``, ``prepare`` and ``getProps`` from the ``evaluate`` method of the fusion ComponentImplementation

---

Neos.ContentRepository/Classes/Command/EventDispatchingNodeCommandControllerPluginInterface.php
Neos.ContentRepository/Classes/Command/NodeCommandController.php
Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
Neos.Neos/Classes/Command/NodeCommandControllerPlugin.php

This is a backwards compatible rework of the `node:repair` command.
This introduces a new `EventDispatchingNodeCommandControllerPluginInterface`
that can be implemented by NodeCommandControllerPlugins in order to
dispatch repair events instead of having to interact with the console
output directly.
The two provided core plugins now implement this interface and dispatch
corresponding events.
Background:
This rework allows the Command Controller to control the execution of tasks
and the rendering of their output which allows for a more streamlined
console output and serves as basis for further improvements (e.g. verbosity
flag).
This also fixes the exit code of the command, that is now 1 if one of the
commands triggered an error.
In the long term (next major version) we should finally clean …

FEATURE: Health status and proper exit code for node:repair

---

Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php

In `createChildNodesByNodeType` there is no need to iterate nodes of
types that have no child nodes defined in their type.

TASK: Continue during create missing child nodes if none defined

---

Neos.Media/Classes/Command/MediaCommandController.php

This change fixes a regression introduced in 1804dc8e6edf79045fb318edf3e78c6e17232658 where a new command line flag "--limit" was introduced. The command did not detect any unused assets unless the --limit flag was specified, because the iteration would stop right away.

BUGFIX: media:removeunused only works with limit flag

---

Neos.Neos/Classes/Command/SiteCommandController.php

another tiny hint that should improve usability a bit:

TASK: Add a helpful hint about the parameter expected for site:prune

---

Neos.Neos/Classes/Command/SiteCommandController.php

Just a little hint that avoids frequent errors with the site import command crashing due to a memory limit, and users being confused about a breaky-looking site:

TASK: Add a hint for the user to avoid errors with incomplete site imports

---

Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php

This PR fixes support for I18n labels of editorOptions in the creationDialog.
```yaml
ui:
creationDialog:
elements:
test:
type: string
ui:
label: i18n
editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
editorOptions:
values:
1:
label: i18n
2:
label: i18n
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
<file original="" product-name="Test.Test" source-language="en" datatype="plaintext">
<body>
<trans-unit id="creationDialog.test" xml:space="preserve">
<source>Number of columns</source>
</trans-unit>
<trans-unit id="creationDialog.test.selectBoxEditor.values.1" xml:space="preserve">
<source>1 test</source>
</trans-unit>
<trans-unit id="creationDialog.test.selectBoxEditor.values.2" …
```

BUGFIX: fix generation of i18n lables for the creationDialog

---

Neos.Neos/Resources/Private/Fusion/Backend/History/Root.fusion

In the history module, the translation uses the documents NodeType instead of the actual modified nodes NodeType.
Additionally I trimmed the `linkedNode` and `user` templates to prevent ugly `" linked node label "` cases.
Also intead of using `eventsOfMatchedType[0]` I used `Array.first(eventsOfMatchedType)`, which is less error prone.

BUGFIX: Use nodeType instead of documentNodeType in history translations

---

Neos.Media.Browser/Resources/Public/Styles/MediaBrowser.css

This change just updates the compiled css and the scss source was already correct.

BUGFIX: Broken layout in media browser when using more than 25 tags

---

Neos.Fusion/Resources/Private/Fusion/Root.fusion

This changes the wrong prototype name from `Neos.Fusion:Maping` to `Neos.Fusion:Map`
Fixes #2313

BUGFIX: Fix wrong Fusion Prototype name

---

Neos.ContentRepository/Classes/Domain/Model/Node.php

This checks for existing auto-created child nodes before they
are created in `createVariantForContext($context)`.
Fixes #782

BUGFIX: Don't create duplicate auto-created child nodes

---

Neos.Neos/Documentation/References/NeosFusionReference.rst

`Neos.Fusion:Loop` had a incorrect example using the old Fusion prototype name

BUGFIX: Fix example in the documentation 

---

Neos.ContentRepository/Classes/Domain/Model/Node.php
Neos.ContentRepository/Classes/Domain/Model/NodeInterface.php

Adds `@deprecated` annotations to methods from `NodeInterface`
and `Node` that will be replaced/removed with the CR rewrite.

Add deprecation annotations to methods that will be removed

---

Neos.Media.Browser/Classes/Controller/AssetController.php

The issue described in #2337 is not as bad as it seems. In fact, the
ternary operation is useless *and* no longer needed. The filtering is
applied via `applyAssetCollectionFilterFromBrowserState()` already.
Resolves #2337

TASK: Remove useless ternary operator use

---

Neos.Neos/Classes/Domain/Service/UserService.php

**What I did**
Backend users can now be deleted, even if they have a private workspace.
Wrap deletePersonalWorkspace() in withoutAuthorizationChecks.
Create a backend user, log in and edit something. Log in as administrator and delete this user.
**Checklist**
Fixes #926 
@nezaniel

BUGFIX: Deletion of backend users

---

Neos.Neos/Configuration/NodeTypes.yaml
Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml

*What I did/How I did it*
I added configuration to the shortcut nodetype definition to hide the target-property in the UI when targetMode is not "selectedTarget"
*How to verify it*
Insert a shortcut node. You should not see the target-property untill you change the targetMode to "selectedTarget"

FEATURE: Hide property "target" of Neos.Neos.ShortCut depending on targetMode

---

Readme.rst

Hi everyone!
Over 500 open-source organizations (like yours) use [Pull Reminders](http://pullreminders.com) for free. We've created this README badge so we can hopefully drive some traffic back to our website and continue sustainably providing free accounts to open-source orgazniations.  Let me know if you have any concerns about adding it. Here's [more information](https://pullreminders.com/badge) about the badge program.

Add Pull Reminders badge

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Tests/Unit/Domain/Model/NodeTypeTest.php

I noticed the order of `superTypes` being of importance in one special case: re-adding a super type removed by a super type.
There already was a test, but it didn't catch one case: the re-addition being positioned **before** the super type where it was removed. Run the same test with only the changes in [NodeTypeTest.php](https://github.com/neos/neos-development-collection/pull/2272/files#diff-960a57534a39e75dc45c37535d2ba971R108) and you'll get a [failed test](https://travis-ci.org/ComiR/neos-development-collection/jobs/454551553).
By making the Method `addInheritedSuperTypes()` `static` and slightly modifying it to not handing over the array, I could get rid of `buildInheritanceChain()` completely and renamed the method to `getFlattenedSuperTypes()`.
The `array_unique()` present before …

BUGFIX: Removed super types can be added again regardless of order

---

Neos.Media.Browser/Resources/Private/Styles/Media/_Media.scss

It's unfortunate, that the interactive fields are below the gallery, if the editors use too many tags in the media browser. It results in the odd behavior that the search bar is at the bottom of the page and limits the usability:
I understand that it quickly turns unsightly, if there are too many tags in the side bar, but I've noticed that if we use the button-style tags, rather than the tag list in the aside-bar, it works out quite nicely:

BUGFIX: change aside bar in media browser for many tags

---

Neos.Neos/Classes/Controller/Backend/BackendController.php

This is needed to get rid of https://github.com/neos/neos-ui/blob/2239fe5465a84971d6aa6a94ea2f7a058959bf59/Classes/Aspects/XliffConfigurationCacheHeaderAspect.php in the Neos UI

BUGFIX: Add cache control header to xliffAsJsonAction

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/DynamicConfigurationProcessing.rst

I updated the example for *"Hiding one property when the other one is not set"* in the *"Dynamic Client-side Configuration Processing"* docs (https://neos.readthedocs.io/en/stable/CreatingASite/NodeTypes/DynamicConfigurationProcessing.html). The example didn't work, as stated here (https://github.com/neos/neos-ui/pull/2118#issuecomment-441986052), but the "hidden" property has been introduced with https://github.com/neos/neos-ui/pull/2118.

TASK: Fix documentation example for toggling visibility of properties in inspector

---

Neos.Neos/Tests/Functional/Service/Mapping/NodePropertyConverterServiceTest.php

This adjusts the complexTypesWithGivenTypeConverterAreConvertedByTypeConverter
of NodePropertyConverterServiceTest to behave as if the new UI is installed
which is insalled when test are run on CI and probably the case in all
other installations.

TASK: Adjust behavior of NodePropertyConverterServiceTest

---

Neos.Fusion/Classes/Core/Cache/RuntimeContentCache.php
Neos.Fusion/Tests/Functional/FusionObjects/ContentCacheTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ContentCache.fusion

If a cached prototype had a `maximumLifetime` of 0
configured, which is meant as infinite cache
lifetime, this value is propagated upwards to all
surrounding prototypes as it is the selected
as minimum value

BUGFIX: Handle maximum cache lifetime of 0

---

Neos.Neos/Classes/Controller/Service/NodesController.php

When invalid node-identifiers, are passed to the node-service it mapped the list of identifier to the getNodeByIdentifier call, which rightly returned null. This is triggered especially in the LinkEditor when nodes are referenced that have been deleted in the meantime.
Since the result was not filtered the list containing a mix of null-values and nodeInterfaces is passed to the template of the nodeService where an error is triggered inside the `neos:node.closestDocument` view helper. 
This error in turn triggers the ui showing a red error box with the html content of the server-error that confused editors and is not helpful at all. 
The fix applies array_filter to the nodes array to avoid passing `null` nodes to the template.

BUGFIX: Avoid server-error when invalid/deleted identifiers are passed to the node service

---

Neos.Media/Classes/Domain/Model/AssetCollection.php

This changes how it is checked if an asset is contained
in an asset collection in order to improve performance.
It changes the complexity of O(n) while n is the amount of assets in an asset collection to O(n) where n is the amount of collections of an asset with the assumption that an asset has far less collections than a collection has assets.
close #2375

BUGFIX: Improve performance in assetCollection operations

---

Neos.Media/Classes/Domain/Repository/AssetRepository.php

AssetRepository::findOneByResourceSha1 forced case innsensitivity on the
SHA1 hash of the resource, so the query builder uses MySQL "LOWER"
function in its generated query, and as such the index cannot be used
in the intended way. Now we are just relying on sha1 to create lower
cased hash values.

BUGFIX: Improve performance in findOneByResourceSha1

---

Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion
Neos.Neos/Resources/Private/Fusion/Prototypes/NodeLink.fusion

Add the ``Neos.Neos:NodeLink`` fusion prototype which renders an ``<a>`` tag based on ``Neos.Neos:NodeUri``, similar to ``Neos.Neos:ImageTag`` and ``Neos.Neos:ImageUri``. 
- all properties of ``Neos.Neos:NodeUri`` are supported and passed over
- ``attributes`` (:ref:`Neos_Fusion__Attributes`) Link tag attributes
- ``content`` (string) The label of the link, defaults to the node label ``q(node).property('_label')``.
This helps reducing code lines especially when using fusion-afx, with this prototype you can now directly link nodes in an afx renderer.

FEATURE: Add NodeLink fusion prototype

---

Neos.Neos/Resources/Private/Styles/_Mixins.scss
Neos.Neos/Resources/Public/Styles/Includes-built.css
Neos.Neos/Resources/Public/Styles/Neos.css

This was broken with 4.0 as fontawesome styling changed.
**What I did**
Inherit the font family for the icon pseudo element from the surrounding fa* class.
Use `fab fa-google` as icon for a backend module, f.e. Media Browser.
Instead of an empty square you should see the Google icon.

BUGFIX: Allow using font awesome brand icons in backend modules

---

Neos.Media/Classes/Domain/Model/ThumbnailConfiguration.php
Neos.Media/Classes/Domain/Model/ThumbnailGenerator/ConvertImageThumbnailGenerator.php
Neos.Media/Classes/Domain/Model/ThumbnailGenerator/ImageThumbnailGenerator.php
Neos.Media/Classes/Domain/Service/ImageService.php
Neos.Media/Classes/Domain/Service/ThumbnailService.php
Neos.Media/Classes/ViewHelpers/ImageViewHelper.php
Neos.Media/Classes/ViewHelpers/Uri/ImageViewHelper.php
Neos.Media/Configuration/Settings.yaml
Neos.Media/composer.json
Neos.Neos/Classes/Fusion/ImageUriImplementation.php
Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion
composer.json

The option ``format`` is added to imagePresets, viewHelpers and FusionPrototypes.
The format is passed as string "jpg", "jpeg", "gif", "png", "wbmp", "xbm", "webp" and "bmp" are supported. If no format is given the crops will use the format of the original image.
This allows to to enforce rendering of crops in jpeg or png but also adds support for rendering 
of webp-images as alternate sources.
Additionally this pr adds the ConvertImageThumbnailGenerator that allows to specify images that should be converted for online-presentation to an optimized target format. While the default imageFormat is specified in the settings this can still be overridden via `format` option on
the thumbnail-configurations.
The ConvertImageThumbnailGenerator is configured via settings:
```
Neos:
Media: …
```

FEATURE: Add ``format`` option for image-prototypes, viewHelpers and presets

---

Neos.Neos/Configuration/Testing/Policy.yaml

The policy expression was wrong and leads to initialize*Action functions being included in the AllControllerActions privilege. That is wrong and can lead to errors in tests. Compared to the (non testing) policy the new expression now works as expected.

BUGFIX: Testing Policy has a working expression

---

Neos.ContentRepository/Tests/Functional/Migration/Filters/NodeTypeTest.php
Neos.Neos/Configuration/Testing/NodeTypes.yaml
Neos.Neos/Tests/Functional/AbstractNodeTest.php
Neos.Neos/Tests/Functional/Configuration/ConfigurationValidationTest.php
Neos.Neos/Tests/Functional/Domain/Fixtures/NodeUriTestStructure.xml
Neos.Neos/Tests/Functional/Domain/Service/Fixtures/Sites.xml
Neos.Neos/Tests/Functional/Domain/Service/SiteImportExportServiceTest.php
Neos.Neos/Tests/Functional/Fixtures/NodeStructure.xml
Neos.Neos/Tests/Functional/FlowQueryOperations/Fixtures/SortableNodes.xml
Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php
Neos.Neos/Tests/Functional/Fusion/Cache/Fixtures/CacheableNodes.xml
Neos.Neos/Tests/Functional/Fusion/Fixtures/AssetListTemplate.html
Neos.Neos/Tests/Functional/Fusion/Fixtures/Base.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/HeadlineTemplate.html
Neos.Neos/Tests/Functional/Fusion/Fixtures/HtmlTemplate.html
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_AdditionalProcessorInPrototype.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_AdditionalProcessorInPrototype2.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_AppendingClassesToContent.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_OverriddenValueInNestedPrototype.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_OverriddenValueInNestedPrototype2.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_OverriddenValueInPrototype.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_PrototypeInheritance.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_ReplaceElementRenderingCompletelyBasedOnAdvancedCondition.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_ReplaceElementRenderingCompletelyInSidebar.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/TextTemplate.html
Neos.Neos/Tests/Functional/Fusion/RenderingTest.php

The previous tests tested nodetypes from those external packages which lead to testing errors because of changes to the master of Neos.Demo. This change uses nodetypes local to the testing context of the cr itself. 
This is cleaner and a preparation to move Neos.NodeTypes out of the development collection someday. Right now it allows to run the functional tests without Neos.Demo or Neos.NodeTyoes beeing installed.

BUGFIX: Remove coupling of functional tests to `Neos:Demo` and `Neos.NodeTypes`

---

Neos.Neos/Classes/View/FusionExceptionView.php
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion

This change adds the default fusion path `error` that is used to render status messages
for the status codes 403, 404 and 410.
The matcher receives the context values `exception`, `renderingOptions`, `statusCode`,
`statusMessage` and `referenceCode` and will by default render the previous template.
By extending the `error` Case you can add custom 404 rendering like in the example below.
```
#
#
error {
@context.notfoundDocument = ${q(site).children('[instanceof Neos.Neos:Document]').filter('[uriPathSegment="notfound"]').get(0)}
4xx {
@position = 'start'
condition = ${statusCode >= 400 && statusCode < 500 && notfoundDocument}
renderer = Neos.Fusion:Renderer {
@context.node = ${notfoundDocument}
renderPath = '/root'
}
}
}
```
Resolves: #2325

FEATURE: Add native 404 error rendering that can be controlled via Fusion

---

Neos.Neos/Resources/Private/Partials/Module/Shared/DomainForm.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/Edit.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/EditDomain.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/Index.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/NewDomain.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/NewSite.html
Neos.Neos/Resources/Private/Translations/en/Modules.xlf

The Site Management uses labels both from `Main.xlf` and `Modules.xlf`. For the labels from `Module.xlf`, the `source` attribute must be set. Apart from that, some labels didn't have a translation at all. This change makes the Site Management fully localizable.
Fixes #2394

TASK: Translate Site Management

---

Neos.Fusion/Classes/FusionObjects/MapImplementation.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Map.fusion
Neos.Fusion/Tests/Functional/FusionObjects/MapTest.php
Neos.Neos/Documentation/References/NeosFusionReference.rst

This allows to declare the itemRenderers in `afx` without `@children` annotation and avoids a 
common error in afx code.
Affected prototypes:
-  `Neos.Fusion:Map`
-  `Neos.Fusion:RawCollection`
-  `Neos.Fusion:Loop`
-  `Neos.Fusion:Collection`

FEATURE: Add fallback from `itemRenderer` to `content` for `Neos.Fusion:Map` and derived prototypes

---

Neos.Fusion/Configuration/Settings.yaml

Register the file helper by default so that they can be used in Fusion, without the need of separate registration.
Solves Issue: #2405

BUGFIX: Add missing Eel FileHelper registration

---

Neos.Media.Browser/Resources/Private/Partials/ContentDefaultPreview.html

The previous code must be a leftover from an upmerge and it results in
fatal errors when trying to open the details of an asset coming from a
proxy source.

BUGFIX: Image previews should be rendered for asset proxies as well

---

Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php

**What I did**
I changed the code of the node:repair command to handle the result of node->getProperties() as ArrayObject and not as array, because that recently changed.
Instead of getting the key via array_keys the properties are now iterated to find undefinded properties.
* run the node:repair-command on a content repository that is fine already => it should not complain about anything
* add a undefinded property to a node (by editing a record in the nodedata-table directly) and run node:repair => you should be asked if you want to remove the undefinded property

BUGFIX: node:repair now handles node->getProperties() as ArrayObject

---

Neos.Media.Browser/Classes/Controller/AssetController.php

Sending a redirect code of 201 does not cause the browser to redirect
and leads to a blank page.
Fixes: #2414

BUGFIX: No redirect with status 201

---

Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php

This additionally requires a fix in the ui which will be done in the neos-ui package.
**What I did**
Add the textarea editor for configuration enrichment.
When using i18n in the placeholder it should show the full translation path in the textarea editor instead of just i18n.

BUGFIX: Allow translation of the textareaeditor placeholder

---

Neos.Media/Classes/Domain/Model/Thumbnail.php
Neos.Media/Classes/Domain/Service/ThumbnailService.php

PR for issue #2387 
**What I did**
Added a signal `thumbnailPersisted` and an ORM lifecycle callback that triggers the signal once the thumbnail is persisted.
Added two methods in Neos\Media\Domain\Model\Thumbnail: one for the signal and one for the lifecycle callback that triggers the signal.
**Checklist**

FEATURE: Trigger signal when Thumbnail is persisted

---

Neos.ContentRepository/Classes/Domain/ValueObject/NodeName.php

This adjusts the `NodeName` Value Object to always convert the given
value to lower case when created via the `fromString()` constructor.
Background:
Node names are considered to be case insensitive. Internally they are
stored lower case but the `NodeInterface::MATCH_PATTERN_NAME` does not
allow for camel case names.
Fixes: #2418

BUGFIX: Lowercase Node Names upon creation

---

Neos.Media/Classes/Domain/Service/ImageService.php
Neos.Media/Classes/Domain/Service/ThumbnailService.php

Thumbnail images always returned the original source if allowUpscaling is false and the target size is smaller than the original image. This is unexpected when quality and format are defined.
This change makes sure the new assets are rendered when quality and format is defined.
The dimension calculation of the target images respects the allowUpscaling if the source is smaller that the target dimension.
Resolves: #2416

BUGFIX: Respect settings for quality and format even if images are smaller that target dimensions

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Classes/Controller/ImageController.php
Neos.Media/Classes/Domain/Model/Adjustment/CropImageAdjustment.php
Neos.Media/Classes/Domain/Repository/AssetRepository.php
Neos.Media/Migrations/Mysql/Version20190315122900.php
Neos.Media/Migrations/Postgresql/Version20190315122901.php
Neos.Media/Tests/Unit/Domain/Model/Adjustment/CropImageAdjustmentTest.php

This change introduces a new property "aspectRatio" for the crop image
adjustment. It allows users to set a cropping area simply by providing
an aspect ratio, instead of x, y, width and height.
If an aspect ratio is specified, the x, y, width, and height parameters
are automatically deactivated. Likewise, if x, y, width or height are
specified, a potentially defined aspect ratio value will be reset.

 FEATURE: Set crop image adjustment by aspect ratio

---

Neos.ContentRepository/Tests/Functional/Domain/NodeServiceTest.php
Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php
Neos.ContentRepository/Tests/Functional/TypeConverter/NodeConverterTest.php
Neos.Neos/Tests/Functional/Controller/Backend/BackendControllerSecurityTest.php

The reset to empty array was technically wrong because dimensions were
configured. While this is not an issue at this time, it can be one
when other tests rely on the integrity of configured dimensions and
the repository.

TASK: Contain dimension changes in tests to test case only

---

Neos.Media.Browser/Classes/Controller/AssetController.php

The names of tags were not rendered in the sidebar of the media module since https://github.com/neos/neos-development-collection/pull/2408 was merged because of an incomplete renaming from `tag` to `retrievedTag`

BUGFIX: Fix tag rendering in media module

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Asset/New.html

**What I did**
I add the missing copyright field again and also added a new on for the "new" dialog
I updated the edit.html and the new.html of the asset controller actions 
I test with example data based on the demo package

BUGFIX: add missing and new copyright field to the edit and new dialog in the media manager

---

Neos.SiteKickstarter/Classes/Service/GeneratorService.php

Somehow the classic site generator did not replace the occurrences of the package names
in fusion `reference://{packageKey}/...` strings any more while in other places this still worked.
This works around this by falling back to a very plain search replace based implementation that is only used on the fusion files.
With this change a site package created with the setup tool or the kickstart:site command will not directly welcome the user with fusion-errors which it did before.

BUGFIX: Fix site-package generator

---

Neos.ContentRepository/Classes/Domain/Model/Node.php

The return type annotation for ``getParent()`` was wrong

BUGFIX: Fix return type annotation

---

Neos.Media/Classes/Domain/Model/Asset.php
Neos.Media/Classes/Domain/Model/Image.php
Neos.Media/Classes/Domain/Model/Thumbnail.php
Neos.Media/Tests/Functional/Domain/Model/AssetTest.php

Remove deprecated signals `Asset::emitAssetCreated` and `Thumbnail:: emitThumbnailCreated` which were moved to the according service classes.

TASK: Remove deprecated signals

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php

When calculating constraints for nodeType filter the nodeDataRepository currently puts the nodeType that was given as filter-argument directly as string to the returned constraint-object but all superTypes as NodeType-objects. This later causes trouble once the types are passed to the isOfType method that expects (but not enforces) strings.
The problem exists since ages but is exposed in Neos 4.2 by the altered handling of removed NodeTypes. Before that `isOfType` implicitly accepted a NodeType as argument. The added checks for declaredSuperTypes that are null (removed by subtype) broke this implication.
Resolves: https://github.com/neos/neos-development-collection/issues/2460

BUGFIX: Filtering by nodeType that has subtypes causes a php_error

---

Neos.Neos/Classes/Eel/FlowQueryOperations/ParentsOperation.php
Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php

The test that should verify this behavior failed to mock the root and sites node and thus the exclusion of `/sites` was not verified correctly.
Resolves: #2459

BUGFIX: Fix `parents` flowQuery operation accidentally returning the `/sites` and `/` node

---

Neos.Neos/Documentation/ExtendingNeos/UiExtensibility.rst

The property `node` is not a wired property

Remove wrong property from component wiring property list

---

Neos.ContentRepository/Classes/Domain/Model/NodeData.php

As of Doctrine DBAL 2.9.0 this is actually possible, so we can finally
do it right.
See #2475

TASK: Limit parentpath index length through annotation

---

Neos.Neos/Classes/Eel/FlowQueryOperations/SortOperation.php

For the current use of the sort operation, the element with key 0 must be present in $context. But this is not necessary for the sort itself. Consequently, the sort operation does not work using arrays without key 0. 
Access via pointer avoids this problem in this PR.

Bugfix: Do access objects by key 0 in canEvaluate() of sort-operation

---

.travis.yml

Raise PHP versions from 7.1 to 7.2 and 7.2 to 7.3 in the travis test matrix.

TASK: Raise PHP version by one minor version in travis.yaml

---

Neos.Neos/Classes/Controller/Module/Administration/UsersController.php

Remove the usage of the deprecated and removed `AuthenticationProviderManager::getProviders()`method.
You find this change in https://github.com/neos/neos-development-collection/pull/2501/commits/4492c3d3b2295e2ea01f3a69ad760ba7502da3f1 - a second commit improves the method typing and code style of that class.

BUGFIX: Remove usage of getproviders from UserController

---

Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenu.fusion

Re-add `renderHiddenInIndex` with default `true`, to show also hidden in index nodes in dimensions menu as before.

Show hidden in index nodes in dimensions menu

---

Neos.Fusion/Classes/Core/Runtime.php

The existing exception for non renderable fusion pathes was not very helpful hard to read and missed mentioning likely reasons like a typo in the prototype name. It also suggested a solution that is unlikely to fix the problem.
With this change the prototype name is moved to the front of the error message
as it is the most important information.
The path is removed from the message-body as the fusion exception handler will render it anyway.
The most likely reasons typo + missing prototype are mentioned first and other possible reasons
like missing parent-protopype, missing `@class` and missing `include:` later.
The proposed solution to inherit from `Neos.Fusion:Template` is removed as it was misleading

BUGFIX: Make exception for non renderable fusion path more helpful

---

Neos.ContentRepository/Configuration/Settings.yaml
Neos.Fusion/Configuration/Settings.yaml
Neos.Fusion/Resources/Private/Schema/Settings.schema.yaml

Once the magic `q` method is removed FlowQuery has to be registered in the configuration to have `q` in the defaultContext for Fusion and CR label generation. This makes FlowQuery work as before from an integration perspective.

TASK: Add flowQuery `q` helper to the Eel configuration

---

Neos.Media/Classes/Domain/Model/Asset.php
Neos.Media/Classes/Domain/Model/AssetCollection.php

Fix the behaviour when the asset can't be unassigned from collections
Fixes #2473

BUGFIX: Assigned asset collections cannot be unassigned

---

Neos.Media.Browser/Classes/Controller/AssetController.php

To get count of all assets, we should use the AssetRepository.
Solves #2358

BUGFIX: Use countAll of AssetRepository to get count of all assets

---

Neos.Neos/Classes/Setup/Step/NeosSpecificRequirementsStep.php

Fixes Issue #2488
In this PR I adjusted the somewhat missleading warning text, which is displayed in the image driver setup step, if none of the requiered drivers is installed. Additionaly I added some javascript to the image driver and the database configuration step in the setup package to disable the next button, if an error message is shown. See the PR https://github.com/neos/setup/pull/53

BUGFIX: Adjust warning text in setup

---

Neos.ContentRepository/Classes/Migration/Configuration/YamlConfiguration.php
Neos.ContentRepository/Classes/Package.php
Neos.ContentRepository/Tests/Functional/AbstractNodeTest.php
Neos.Fusion/Classes/Package.php
Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media/Classes/Domain/Service/AssetService.php
Neos.Neos/Classes/Command/SiteCommandController.php
Neos.Neos/Classes/Controller/Module/Administration/PackagesController.php
Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
Neos.Neos/Classes/Domain/Service/FusionService.php
Neos.Neos/Classes/Domain/Service/SiteExportService.php
Neos.Neos/Classes/Domain/Service/SiteImportService.php
Neos.Neos/Classes/Setup/Step/NeosSpecificRequirementsStep.php
Neos.Neos/Classes/Setup/Step/SiteImportStep.php
Neos.SiteKickstarter/Classes/Command/KickstartCommandController.php
Neos.SiteKickstarter/Classes/Service/GeneratorService.php

The `PackageManagerInterface` is deprecated and will be removed with
Flow 6.0, so avoid it and use `PackageManager` directly.

TASK: Use PackageManager, not PackageManagerInterface

---

Neos.Neos/Classes/Service/DataSource/DataSourceInterface.php
Neos.NodeTypes.Form/Classes/Service/DataSource/FormDefinitionDataSource.php

This adjusts the getData method signature of the DataSourceInterface,
because if the first parameter is optional, the following should also be
optional.

TASK: Correct method signature of DataSourceInterface

---

Neos.Neos/Classes/Command/WorkspaceCommandController.php

They were deprecated since Neos 1.2 (!). Use `publish` and `discard`
instead.

!!! TASK: Remove discardall & publishall CLI commands

---

Neos.Neos/Configuration/NodeTypes.yaml

**What I did**
[[^:print:]] resulted in the characters print: followed by ] being removed from the node label. Non-printable characters should be matched with [^[:print:]].
Resolves neos/neos-ui#2496
Output node labels normally including n], i] etc. e.g. in the document tree.
This PR replaces and closes #2515 which was targeting master.

BUGFIX: node label sanitizing regex strips characters

---

Neos.Neos/Classes/Service/LinkingService.php

With `UriConstraints` we have the ability to modify the Host but there is a problem with the `LinkingService` in combination with `UriConstraints`. If you ask the `LinkingService` for a absolut Uri then it add the current base to the Url.
Fixes #2398

BUGFIX: Changed Domains by UriConstraints will not no longer get destroyed by the LinkingService

---

Neos.Media/Classes/TypeConverter/ArrayConverter.php

Notes:
1. I could not find tests covering this part of the code. If you point me to it, I will also add a test case for `caption`.
2. The copyright notice is also missing from the export, but afaik this was added in Neos 4.2, so I will open a separate PR.
3. Relations to tags and collections are also missing from the export, but they seem more complicated, so I will open separate PRs.
**What I did**
Included the caption of assets in exports to `Sites.xml`.
Added `caption` in `ArrayConverter.php` the same way as `title`.
1. Add a caption to an asset.
2. Export to `Sites.xml`.
3. Do a clean import.
4. Check that the caption is preserved.

BUGFIX: The caption of assets is lost when exporting to Sites.xml

---

Neos.Media/Classes/TypeConverter/ArrayConverter.php

see also #2503
**What I did**
Included the copyright notice of assets in exports to `Sites.xml`.
Added `copyrightNotice` in `ArrayConverter.php` the same way as `title`.
1. Add a copyright notice to an asset.
2. Export to `Sites.xml`.
3. Do a clean import.
4. Check that the copyright notice is preserved.

BUGFIX: The copyright notice of assets is lost when exporting to Sites.xml

---

Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php

When an asset is replaced, the content cache is flushed, but in most
cases this does not have an effect. As most content nodes do not have
a cache entry, the cache entry higher in the chain needs to be
flushed.
This is now done by fetching the affected node for an asset usage and
passing that to `registerNodeChange(…)` in the `ContentCacheFlusher`.
Fixes #2061

BUGFIX: Flush affected document node on asset change

---

Neos.Neos/Resources/Private/Installer/Distribution/Defaults/Web/robots.txt
Neos.Neos/Resources/Private/Templates/Login/Index.html

Since the base distribution contains ´´neos/seo´´ 3.x which does a much
better job at providing a more valuable and accurate ``robots.txt`` file.
When the default ``robots.txt`` still remains in the projects Web
folder, this can cause a lot of confusion. To make matters worse, it's
recreated whenever the composer install scripts are executed.
In case a custom distribution does not install the ``neos/seo`` package,
we now have the meta tag within the Neos login page as a fallback, so
even then status quo remains without the standard ``robots.txt`` from a SEO perspective.

!!!TASK: Remove static robots.txt file for fresh installations

---

Neos.Neos/Classes/Domain/Repository/SiteRepository.php

If you have many sites inside a Neos instance it is difficult to find a specific site, because they are ordered by creation date. I added default ordering by name and nodeName to SitesRepository.

TASK: Add sites default ordering

---

Neos.Fusion/Classes/Aspects/FusionCachingAspect.php
Neos.Fusion/Classes/View/FusionView.php
Neos.Fusion/Classes/ViewHelpers/RenderViewHelper.php
Neos.Fusion/Configuration/Caches.yaml
Neos.Fusion/Configuration/Objects.yaml
Neos.Fusion/Configuration/Production/Settings.yaml
Neos.Fusion/Configuration/Settings.yaml
Neos.Fusion/Resources/Private/Schema/Settings.schema.yaml
Neos.Fusion/Tests/Functional/FusionObjects/AbstractFusionObjectTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/View/Fixtures/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/View/FusionViewTest.php
Neos.Neos/Classes/Controller/Module/Management/HistoryController.php

- The `fallbackView` and related options are removed as it only caused confusion and made debugging harder
- The `fusionPathPatterns` are now expected to point to a single fusion file instead of parsing all files in the while directory. If the path points to a directory the `Root.fusion` is loaded as starting point. 
- Below the Root.fusion all other fusion files have to be included explicitly!
- The cache `Neos_Fusion_ObjectTree` is added and connected to the FusionView via aspect. The cache is enabled only for production via Setting `Neos.Fusion.enableObjectTreeCache`
Upgrade Instructions: If you use the standalone FusionView make sure that a `Root.fusion` exist in your `fusionPathPatterns` and that all other fusion files are included from there.

!!! FEATURE Improve standalone FusionView

---

Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php

If a node cannot be resolved in the content cache flusher
skip this node instead of throwing an exception.
Resolves: #2594

BUGFIX: Skip nodes if they cannot be resolved in ContentCacheFlusher

---

.travis.yml

This prevents builds from running doubly on branches created on this repository for PRs, e.g. through the StyleCI bot or by github inline PRs.
See https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
See also https://github.com/neos/flow-development-collection/pull/1660
Retargeted replacement for #2593

TASK: Safelist branches for travis builds

---

Neos.Fusion/Classes/Core/ExceptionHandlers/HtmlMessageHandler.php

Synchronizes the behavior of the Fusion rendering exception handing with the one
from Flow to only render the exception *message* in `Development` Context.
Fixes: #2602

BUGFIX: Don't render exception message in Production Context

---

Neos.Neos/Resources/Private/Templates/Backend/Module/Index.html

With resolution of #2479 javascript blocks were put into CDATA
sections in order to prevent them to break the Fluid parser.
This introduced a regression that prevents Backend Modules to
work properly when `loadMinifiedJavascript` is disabled.
Background:
The string `resource://...` is replaced by the `ResourceInterceptor`
but that behavior is skipped for CDATA sections.
Related: #2479

BUGFIX: Fix broken JS require implementation in Backend Modules

---

Neos.ContentRepository/Classes/Domain/Model/Node.php

The return type in createNodeForVariant must be nullable because 
`$this->nodeFactory->createFromNodeData()` can return null when 
moving a node, even if only an edge case that occurs every
once in a while.
This bug only refers to version 4.3 since all previous versions do not contain a strict return type.

BUGFIX: Nullable return type in Neos\ContentRepository\Domain\Model\Node

---

Neos.Neos/Classes/Command/WorkspaceCommandController.php

Doing so would completely break Neos when resolving
the content of a workspace that is based on live.
Resolves: #2631

BUGFIX: Prevent deleting or rebasing the live workspace

---

Neos.Fusion/Classes/Core/Cache/ContentCache.php
Neos.Fusion/Classes/Core/Parser.php
Neos.Fusion/Classes/Core/Runtime.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ContentCache.fusion
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Unset.fusion
Neos.Fusion/Tests/Functional/FusionObjects/UnsetTest.php
Neos.Fusion/Tests/Unit/Core/ParserTest.php

When Fusion pathes are unset with the `>` operator the operations was previously handled by the parser. The drawback was that the parser unset could not affect inherited pathes which were merged into the prototype by the runtime.
This change adds the internal-key `__stopInheritanceChain` to the fusion ast whenever a value is unset. The fusion runtime will stop merging parent prototypes for the pathes where this key is set.
As a common example the following code does not render an empty body but a will render the 
keys  `site` and `node` from the `Neos.Neos:Page` prototype which is totally unexpected and against the intention.
```
prototype(Vendor.Site:ExampleDocument) < prototype(Neos.Neos:Page) {
body >
body = Neos.Fusion:Array {
@position = 'after bodyTag'
message = "hello world"
}
} …
```

BUGFIX: Avoid inheritance on unset Fusion pathes

---

Neos.ContentRepository/Classes/Domain/Model/NodeInterface.php

The nodeinterface is marked as deprecated with the announcement
to be replaced in Neos 5.0. This will not happen though.
The deprecation of the interface should be announced together
with replacement in the Neos core with one of the next minor versions.

TASK: Postpone deprecation of NodeInterface

---

Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/Templating.rst

its <f:widget.uri> / <f:widget.link> and not <f:uri.widget> / <f:link.widget>

TASK: Fix documentation about f:widget.uri

---

Neos.ContentRepository/Classes/Domain/Model/ExpressionBasedNodeLabelGenerator.php
Neos.ContentRepository/Classes/Domain/Model/NodeInterface.php
Neos.ContentRepository/Classes/Domain/Model/NodeLabelGeneratorInterface.php

`Node::getLabel()` has a return type set to `string` while the interface hasn’t.
The label is built by the ExpressionBasedNodeLabelGenerator which may return null.
Added an explicit string cast to get an empty string in that case.

!!! BUGFIX: Neos\Eel\Utility::evaluateEelExpression may contain null

---

Neos.Media.Browser/Resources/Private/Templates/AssetCollection/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Tag/Edit.html

The Media Browser has at the moment the issue that you get an exception when you change the tag name or the collection name.
**What I did**
I just added the correct controllers to the fluid forms.
1. Go to media browser module
2. click the pencil for tags for instance
3. Choose a tag and click the edit button
4. Change the name and click save
**Checklist**

BUGFIX: Add missing controller to edit forms

---

Neos.Fusion/Classes/Service/HtmlAugmenter.php
Neos.Fusion/Tests/Unit/Service/HtmlAugmenterTest.php

The html augmenter uses the `loadHml` method of php which assumes the html content being iso encoded. This caused attributes with umlauts being broken once on the outermost tag. The previous declaration of the `UTF-8` charset has no effect on the `loadHtml` behavior.
The change applies the mb_convert_encoding method to the html which allows to properly read unicode characters as suggested on  https://www.php.net/manual/en/domdocument.loadhtml.php
In addition this change adds a duck-emoji to the neos test codebase which is an important improvement.
Fixes: #2677

BUGFIX: HTML augmenter preserves multibyte characters in attributes

---

Neos.Media/Classes/TypeConverter/AspectRatioFromStringConverter.php

Aspect ratio is stored as a string and there's no TypeConverter
available to reconstruct the AspectRatio object from a string
Fixes #2538
Replaces https://github.com/neos/neos-development-collection/pull/2598

BUGFIX: Site imports with cropped images

---

Neos.Neos/Resources/Public/JavaScript/LastVisitedNode.js

While the refactoring of the javascript code in the Neos.Neos package the LastVisitedNode.js
file has been deleted. Sadly this is used by the react-ui and the removal leads to errors in the console.
Thanks to @Sebobo for reporting that :)

BUGFIX: Add the last visited node handler

---

Neos.Neos/Resources/Public/JavaScript/Components/TopBar/MenuPanel.js
Neos.Neos/Resources/Public/JavaScript/Helper/getCollectionValueByPath.js
Neos.Neos/Resources/Public/JavaScript/Helper/index.js
Neos.Neos/Resources/Public/JavaScript/Main.min.js

The new vanilla js menu did use the session storage to save the states and it turns out that the react-ui uses the local storage. This patch synchronizes the states and takes care that when you change a menu state in the content module (react-ui) the state is also available in the user module for instance.
**What I did**
Use also the local storage in the vanilla js based menu and adopt the data structure to behave like the react-ui.
Change menu states in the content module an check then if the state is also in the user module. And vice versa.
Fixes: #2682

BUGFIX: Synchronize react-ui menu state with vanilla js

---

Neos.Neos/Documentation/References/NeosFusionReference.rst

**What I did**
The documentation regarding internal arguments for controller-based plugins mentions that internal arguments can be accessed by using `_key`, while `__key` is correct. Besides fixing this, I added an example on how to access it in the controller.

TASK: Fix Plugin reference regarding additional arguments, add example

---

Neos.Media.Browser/Classes/Controller/AddFlashMessageTrait.php
Neos.Media.Browser/Classes/Controller/AssetCollectionController.php
Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Classes/Controller/TagController.php

**What I did**
Allow all media browser controllers to use the modified `addFlashMessage` method.
Use a trait for adding the method to all related controllers.
Add or delete a tag or collection in the media browser.

BUGFIX: Translate labels when modifying tag and collections

---

Neos.Neos/Classes/View/FusionView.php

The fallback order now corresponds to the order from the dimension "language".

!!! BUGFIX: Fix languages fallback order

---

Neos.Diff/Classes/SequenceMatcher.php

BUGFIX: Avoid count() call on null

---

Neos.Fusion/Classes/FusionObjects/AttributesImplementation.php
Neos.Fusion/Classes/FusionObjects/TagImplementation.php
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Tag.fusion
Neos.Fusion/Tests/Functional/FusionObjects/TagTest.php
Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion

In the past integrators often expected to be able to pass data structures to `Tag.attributes` which was not possible since the Tag implementation expected attributes to be a string that usually was rendered by `Neos.Fusion:Attributes`.
This change extends the `Neos.Fusion:Tag` implementation to accept iterables (array and traversables) as `attributes` and changes the default value to `Neos.Fusion:DataStructure`. A fallback to cast non-iterable values to string is in place so if anyone uses Neos.Fusion:Attributes explicitly this will still work.
To control the wether or not empty attributes are allowed the key `allowEmptyAttributes` is added to `Neos.Fusion:Tag` that mimics the behavior of `@allowEmpty` on `Neos.Fusion:Attributes`.
`Neos.Fusion:Attributes` is marked as deprecated but will …

!!! FEATURE: Alter ``Neos.Fusion:Tag.attributes`` to ``Neos.Fusion:DataStructure``

---

Neos.Media/Classes/Domain/Model/Image.php
Neos.Media/Classes/Domain/Model/VariantSupportInterface.php

This adds a new method to the `VariantSupportInterface`, allowing
to fetch a preset-generated variant of an image directly.
public function getVariant(string $presetIdentifier, string $presetVariantName): ?ImageVariant;

!!! FEATURE: Add getVariant(string, string) to VariantSupportInterface

---

Neos.Media/Classes/Domain/Model/Adjustment/CropImageAdjustment.php

This is not a direct problem for Neos 3.3 but it becomes a problem
as soon as PHP type hints come into play. The ratio divided widths
and heights can easily be floats and that is unexpected. Therefore
rounding and casting to int makes sense to prevent problems.
In versions of Neos that include type hints this is an actual major
bug that prevents refitting to work.

BUGFIX: CropIimageAdjustment::refit only produces int sizes

---

Neos.NodeTypes/Migrations/Code/Version20190917101945.php
Neos.NodeTypes/Migrations/ContentRepository/Version20190304111200.yaml

The NodeTypes that were migrated to subpackage namespace via node migration `20190304111200` are now migrated in yaml and fusion files aswell. So existing code that extended or altered those nodetypes will still work. 
In addition a wrong target nodetype for `Neos.NodeTypes:Records` in node migration `20190304111200` is corrected as this migration was not part of a release yet.
This is a follow up to pr: https://github.com/neos/neos-development-collection/pull/2385
Upgrade instructions: Run code migrations via `./flow flow:core:migrate Package.Key` or `./flow flow:core:migrate --version Neos.NodeTypes-20190917101945 Package.Key` to apply the migration to your code.

!!! TASK: Add code migration to rename nodetypes that were extracted from Neos.NodeTypes to subpackages

---

Neos.Neos/Configuration/Testing/NodeTypes.yaml
Neos.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php

Introduced in https://github.com/neos/neos-development-collection/pull/2694
A property with a given name should not be defined as different
value types as this will fail as soon as you try to use
elasticsearch indexing.
With defining that in the Testing index, an elasticsearch mapping
in the tests cannot be build

BUGFIX: Remove introduced integer type setting

---

Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Neos/Documentation/References/NeosFusionReference.rst

A `Fragment` is a `Component` that renders the given `content` without additional markup.
That way conditions can be defined for bigger chunks of afx instead of single tags.
```
renderer = afx`
<Neos.Fusion:Fragment @if.isEnabled={props.enable}>
<h1>Example</h1>
<h2>Content</h2>
</Neos.Fusion:Fragment>
`
```

FEATURE: Add `Neos.Fusion:Fragment` prototype

---

Neos.Media/Classes/Domain/Repository/AssetRepository.php

Any repository extending AssetRepository would need to override the
countAll() method or would always return the count of all assets,
not only the type the repository dealt with.
Now countAll() counts all assets or the specific type as expected.
Fixes #2724

TASK: Make countAll() in AssetRepository work as expected for subclasses

---

Neos.Media/Classes/Domain/Repository/ImportedAssetRepository.php
Neos.Media/Tests/Functional/Domain/Repository/ImportedAssetRepositoryTest.php

Only query for imported assets that are not a variant of an originally imported asset.
Fixes #2742

BUGFIX: Always select local original asset in media browser

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Show.html

Even though the input field is read-only, the type should be given. At least
that makes sure the styling is correct.

BUGFIX: Add type="text" to title input field

---

Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php

This is probably an oversight during upmerges, the `log(…)` call expects
the level as first parameter. By now this should be a `warning(…)` call.

BUGFIX: Adjust wrong parameters for log call

---

Neos.Media/Documentation/VariantPresets.rst

The previous examples were misleading and not helpful since they caused php-errors when used
as mentioned. The adjustments correct this and add a sentence and example about the VariantsTab that has to be enabled.

DOCS: Use working examples in VariantPresets documentation and mention the variants tab settings

---

Neos.Fusion/Classes/View/FusionView.php

This allows to use `FusionView` without manually creating a `ControllerContext`, because `RuntimeFactory` will take an effort to create one itself, if none is provided.

TASK: Use RuntimeFactory to create FusionRuntime

---

Neos.NodeTypes.BaseMixins/composer.json

The BaseMixin package lists itself as a dependency. This obviously doesn't make any sense (unless there is a very specific reason for this that I'm not aware of).

TASK : Remove composer requirement for the BaseMixins package itself

---

Neos.Neos/Classes/Controller/Frontend/NodeController.php

Uses `$this->request` instead of the http request, to stay upwards compatible with PSR-7 changes.
Related: #2711

TASK: Update showInvisible check to be upwards compatible

---

Neos.Neos/Migrations/Mysql/Version20150224171107.php
Neos.Neos/Migrations/Mysql/Version20150309215317.php

See https://jira.mariadb.org/browse/MDEV-19598
This will first rename the existing index before adding
a new primary key as MariaDB 10.4 would complain about
the existing unique key „uid“ and not allow adding
the primary key with the same name.
As the behavior for MariaDB 10.2 and 10.4 is different
we also need to check for the existence of the indices
before changing them or it will cause trouble with 10.2.
Replaces: #2665 
Resolves neos/flow-development-collection#1704

BUGFIX: MariaDB 10.4 compatibility for events migration

---

Neos.ContentRepository/Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html

The labels were only partially translated in https://github.com/neos/neos-development-collection/commit/8d1c98a9999fac1830b78f17c08f87c0f67a6065#diff-86d35dae35fd27aa00b7d0723d538960

BUGFIX: Add missing translation in pagination

---

Neos.Fusion/Classes/Core/Runtime.php
Neos.Fusion/Classes/View/FusionView.php
Neos.Fusion/Classes/ViewHelpers/RenderViewHelper.php

https://github.com/neos/neos-development-collection/commit/ba8d1412f34820971fe6f9c0137fd23196df6612 introduced the return type `string` for Fusions RenderViewHelper, so we must always return a `string` (not `null`).

BUGFIX: Change return types of some Fusion methods to mixed

---

Neos.Neos/Documentation/References/NodeTypeDefinition.rst

Replaces no longer working links in the `NodeTypeDefinition` reference by corresponding docs.neos.io links and marks the `editorListeners` option deprecated

BUGFIX: Fix links and outdated docs in NodeTypeDefinition

---

Neos.Neos/Classes/Fusion/PluginImplementation.php

This prevents the plugin content to end up in the main ActionReponse,
which is a preparation for the fix to plugin redirects and needs to
happen first in order to stay backwards compatible.
This change alone should change absolutely nothing in no circumstance.

TASK: Preparation for fixing plugin redirects

---

Neos.Neos/Classes/Fusion/PluginViewImplementation.php

This results in redirects without delay working not only for Plugins but also for PluginViews.
While updating a Neos Project from 3.3 to 4.3 I encountered an issue with the PluginViewImplementation. Redirects without a delay inside controllers of the plugin views did not work anymore, while redirects in the controllers of the master plugin still worked.
This problem occurred because the implementation of AbstractController::redirectToUri() changed in Neos 4.
In Neos 3 the line `$this->response->setContent('<html><head><meta http-equiv="refresh" content="' . (int)$delay . ';url=' . $escapedUri . '"/></head></html>');` was always executed – in Neos 4 it is only executed if a delay is set. Without a delay only the "Location" in the Response-Header is set. 
The PluginViewImplementation (in …

BUGFIX: setting Headers while evaluating PluginView.

---

Neos.ContentRepository/Resources/Private/Schema/NodeTypes.schema.yaml
Neos.Neos/Classes/NodeTypePostprocessor/CreationDialogPostprocessor.php
Neos.Neos/Configuration/NodeTypes.Content.yaml
Neos.Neos/Configuration/NodeTypes.Document.yaml
Neos.Neos/Documentation/References/NodeTypeDefinition.rst
Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml

Introduces a new Node Type setting `properties.<propertyName>.ui.showInCreationDialog`
that, if `true` will add the corresponding property to the Node Creation Dialog.
Example:
'Some.Package:SomeNodeType':
properties:
'someProperty':
ui:
showInCreationDialog: true
In that case the configuration of the corresponding `ui.inspector.editor` is copied
to the corresponding Creation Dialog element and can be overridden using the already
existing `creationDialog` configuration::
'Some.Package:SomeNodeType':
creationDialog:
elements:
'someProperty':
ui:
label: 'Overridden label'
properties:
'someProperty':
ui:
showInCreationDialog: true
*Note:* This requires https://github.com/neos/neos-ui/pull/2596 to be merged first!
Related: #2173

FEATURE: Allow Node properties to appear in the Creation Dialog

---

Neos.Fusion/Classes/Service/HtmlAugmenter.php
Neos.Fusion/Tests/Unit/Service/HtmlAugmenterTest.php

**What I did**
Regarding #2763 the HtmlAugmenter does not find script tags as root elements. Ths DomDocument->loadHTML() puts them automatically into `html/head` instead of `html/body` as it does with other tags.
Extend XPath query to search in head AND body for root elements.
For script-tag:
```
$html = '<script>console.log("fooo");</script>';
$domDocument = new \DOMDocument('1.0', 'UTF-8');
$domDocument->loadHTML((substr($html, 0, 5) === '<?xml') ? $html : '<?xml encoding="UTF-8"?>' . $html);
var_dump($domDocument->saveHTML());
``` 
it returns:
``` 
string(195) "<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<?xml encoding="UTF-8"?><html><head><script>console.log("fooo");</script></head></ht …
```

BUGFIX: Allow HtmlAugmenter operate on script tags

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html

When an asset is not found, some actions threw an 404 status, which
leads to Neos showing the "404 page" under certain circumstances.
This change assigns the exception just like in the case of a connection
error, leaving handling to the media browser.
Now when an asset is not available, the edit template reacts to the
`connectionError´. This avoids an error with the `format.relativeDate` VH
and informs the user correctly about the fact an asset could not be
found.

BUGFIX: Handle unavailable asset proxies in edit view

---

Neos.Fusion/Classes/FusionObjects/DataStructureImplementation.php
Neos.Fusion/Tests/Functional/FusionObjects/DataStructureTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/DataStructure.fusion
Neos.Fusion/Tests/Unit/FusionObjects/ArrayImplementationTest.php
Neos.Fusion/Tests/Unit/FusionObjects/DataStructureImplementationTest.php

When a `DataStructure` is rendered for nested keys that have no specified type the fusion  type `DataStructure` is assumed. This makes it much easier to describe larger data structure in fusion for instance to create json ld structures or define complex mappings.

FEATURE: `DataStructure` assumes nesting for subkeys without specified type

---

Neos.ContentRepository/Classes/Domain/Model/NodeData.php
Neos.ContentRepository/Migrations/Mysql/Version20190905074145.php
Neos.ContentRepository/Migrations/Postgresql/Version20190905074146.php

This allows for faster results in case of prefixed path queries on the nodedata table. The
index speeds up queries like in `findNodesByPathPrefixAndRelatedEntities()` (used to
determine the asset usage.)
Resolves: #2684

FEATURE: add index to column path on nodedata table

---

Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
Neos.Neos/Resources/Private/Templates/FusionObjects/NeosLicenseHeader.html

This avoids needlessly instantiating the fluid template engine just to render single comment.
Additionally this allows to configure the licenseHeader via setting Neos.Neos.headerComment.

TASK: Render headerComment from Settings instead of fluid-template

---

Neos.Fusion/Classes/Core/Runtime.php

Small bugfix to have an even count of enter and leave calls, even if
apply values cause an early return.
This should be refactored anyway to a more efficient solution (see
#2737) where no cache context is prepared unless an object is
evaluated - but it doesn't hurt and helps the Flowpack.Fusion.Tracing
package to produce correct traces.
Replaces #2739

BUGFIX: Add leave statements for apply early returns

---

Neos.Neos/composer.json

Until the both packages will become part of the dev dist we have to set the version constraints for each branch manually as master requires „*“

TASK: Require concrete versions of fusion afx and forms for the 5.1 branch

---

Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php
Neos.Media/Migrations/Mysql/Version20191125132700.php
Neos.Media/Migrations/Postgresql/Version20191125132701.php

The default was assigned during runtime, but this lead to `getRatioMode()`
potentially failing, since it was declared to return a string, non-nullable.
This is a followup to #2716
Fixes #2811

BUGFIX: Set default ratio mode in ResizeImageAdjustment

---

Neos.Neos/Classes/NodeTypePostprocessor/CreationDialogPostprocessor.php
Neos.Neos/Tests/Unit/Domain/NodeTypePostprocessor/CreationDialogPostprocessorTest.php

Fixes the `CreationDialogPostprocessor` so that it doesn't create
an empty `ui.creationDialog.elements` configuration if no node
properties are flagged with `showInCreationDialog`
Related: #2173

BUGFIX: Don't show empty Creation Dialog

---

Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php

Sigh… This fixes one blocking and one small issue with the ratio mode
that still occurred when importing sites from XML. The error fixed is:
`During the import of the "Sites.xml" from the package "Neos.Demo" an
exception occurred: Error: During import an exception occurred:
"Could not convert target type "Neos\Media\Domain\Model\ImageVariant":
Could not convert target type
"Neos\Media\Domain\Model\Adjustment\ResizeImageAdjustment": Invalid
mode "" specified, supported modes are: "inset", "outbound" (but use
the ImageInterface::RATIOMODE_* constants)"., see log for further
information.`
The fix brings back setting the ratio mode to the default of
ImageInterface::RATIOMODE_INSET when an empty string is given and
fixes the error message sprintf pattern.

BUGFIX: Invalid ratio mode during site import

---

Neos.Media/Classes/Domain/Repository/AssetRepository.php

This fixes `array_map() expects parameter 1 to be a valid callback,
class ‘Neos\Media\Domain\Repository\FlowAnnotationDriver’ not found`

BUGFIX: Add FlowAnnotationDriver import to AssetRepository

---

Neos.Media/Classes/Domain/Service/AssetService.php

BUGFIX: Avoid null as argument to recreateVariant()

---

Neos.Neos/Classes/Fusion/PluginViewImplementation.php

This applies a fix that has been applied to PluginImplementation in
https://github.com/neos/neos-development-collection/pull/2777 to the
PluginViewImplementation. This makes plugin views work again as
expected, instead of replacing the full response content by the plugin
content.

BUGFIX: Adjust PluginViewImplementation to PSR-7

---

Neos.Neos/Classes/Service/PluginService.php

The array returned by getNodes() may have null entries, e.g. if a
node was filtered in createFromNodeData().

BUGFIX: Avoid isRemoved() call on null

---

Neos.Neos/Classes/Service/UserService.php

Use result of first call of getPersonalWorkspaceName() instead of calling it twice.

BUGFIX: Call getPersonalWorkspaceName just once

---

Neos.Neos/Classes/ViewHelpers/Backend/IfModuleAccessibleViewHelper.php
Neos.Neos/Resources/Private/Partials/Module/SubmoduleOverview.html

Adds a ViewHelper `ifModuleAccessible` that allows to evaluate whether a
given (sub) module is accessible to the currently authenticated user and
uses that ViewHelper in the SubmoduleOverview partial in order to hide
inaccessible modules from the module overview.
Background:
With #964 the `module.<submodule>.privilegeTarget` configuration became
deprecated in favor of `ModulePrivilege`s but the partial only checked
the "privilegeTarget" configuration.
Note: This is just a quick fix for the bug. In the long run we should
rewrite the whole backend module logic in order to move such crucial
conditions from the view to the domain layer.
Fixes: #2854

BUGFIX: Hide inaccessible backend modules

---

Neos.Neos/Classes/Controller/LoginController.php

In the latest version of Chrome (79.0.3945.88) the login page will
remain white if it's protected by Basic Authentication.
Until now a 401 status code was returned whenever the login page was
opened, causing a faulty behavior in Chrome and resulting in a white
page in almost all cases.
We now use a custom header instead to identify if Authentication is
necessary to view the content.
resolves: https://github.com/neos/neos-development-collection/issues/2845

BUGFIX: Fix login behind basic auth

---

.travis.yml
Neos.ContentRepository/Classes/TypeConverter/NodeConverter.php
Neos.Fusion/Classes/Core/Runtime.php
Neos.Media/Tests/Unit/Domain/Model/Adjustment/CropImageAdjustmentTest.php
Neos.Neos/Tests/Unit/Fusion/PluginImplementationTest.php

See https://github.com/neos/flow-development-collection/issues/1866

TASK: PHP 7.4 compatibility

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Neos/Classes/Controller/Module/Administration/SitesController.php

Remove left over of rewrite FlashMessages.
See: https://github.com/neos/flow-development-collection/pull/1061

Bugfix: Use controller context to get FlashMessageContainer

---

Neos.Neos/Classes/NodeTypePostprocessor/CreationDialogPostprocessor.php

Keep configured creationDialog elements to keep dialog fields for NodeTemplates.
Fixes: #2882

BUGFIX: Keep configured creationDialog elements

---

Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion

Together with https://github.com/neos/neos-ui/pull/2609 and https://github.com/neos/neos-ui/pull/2667
this change allows to have a `Neos.Neos:Content` nodetype
that is also a `Neos.Neos:ContentCollection` and have one
or more wrapping tags around the Fusion `Neos.Neos:ContentCollection`.
Without the change in the UI new nodes would have been added into
the outer div instead of the collections div.
**What I did**
Add anchor attribute introduced in https://github.com/neos/neos-ui/pull/2609 by default
to the ContentCollection prototype.
Use the following prototype and add a new node. See test in https://github.com/neos/neos-ui/pull/2667
Example:
```
prototype(My.Vendor:Content.ItemContainer) < prototype(Neos.Neos:ContentComponent) {
renderer = afx`
<div …
```

FEATURE: Freely position content collections

---

Neos.Neos/Classes/Fusion/NodeUriImplementation.php
Neos.Neos/Resources/Private/Fusion/Prototypes/NodeUri.fusion

The prototype Neos.Neos:NodeUri defines `arguments = Neos.Fusion:RawArray`
but this value is never processed in the PHP implementation.
Instead, the additionalParams is processed and passed to
the parameter `arguments` of the NodeLiking service.
Now both parameters are used. `additionalParams` should be deprecated.

BUGFIX: Respect arguments value as defined in Neos.Neos:NodeUri

---

Neos.Neos/Classes/Domain/Service/UserService.php

Convert "Now" based on DateTimeImmutable to DateTime, as Account::setExpirationDate expects it.
Fixes #2131

BUGFIX: Convert DateTimeImmutable "Now" into DateTime for account deactivation

---

Neos.NodeTypes/Migrations/Code/Version20200120114136.php

Add missing code migration for nodetypes Neos.NodeTypes:MultiColumn and Neos.NodeTypes:MultiColumnItem for seamless upgrade process.

BUGFIX: Add code migration for MultiColumn* nodetypes

---

Neos.Fusion/Classes/Eel/BaseUriHelper.php
Neos.Fusion/Configuration/Settings.yaml
Neos.Fusion/Resources/Private/Fusion/Root.fusion

Since Flow 6.0 the httpRequest.baseUri is gone and we
need to replace it in the cache identifiers to avoid wrong
cache behavior.

BUGFIX: Replace baseUri in cache identifiers

---

Neos.Media/Classes/Domain/Model/Asset.php
Neos.Media/Classes/Domain/Model/AssetCollection.php
Neos.Media/Classes/TypeConverter/ArrayConverter.php
Neos.Media/Classes/TypeConverter/AssetCollectionToArrayConverter.php
Neos.Media/Classes/TypeConverter/TagConverter.php
Neos.Media/Classes/TypeConverter/TagToArrayConverter.php

With this change tags and collections of assets are included in site exports to XML and are imported properly, too.
See also #2503 and #2537.
Fixes #1097

FEATURE: Keep tags and collections of assets when exporting sites

---

Neos.Media/Classes/Domain/Service/ThumbnailService.php

If the thumbnail strategy failed to generate a valid thumbnail, null
is returned. This needs to be allowed.

BUGFIX: Make getThumbnail() return type nullable

---

.travis.yml

Fixes build config validation complaints:
- W jobs.include: deprecated key sudo (The key `sudo` has no effect anymore.)
- W notifications.slack: unknown key on_start (never)
- I root: missing os, using the default linux
- I root: key matrix is an alias for jobs, using jobs

TASK: Fix validation warnings/errors on .travis.yml

---

Neos.Neos/Documentation/References/CommandReference.rst

The readthedocs command reference formats double dashes
as one long dash. Copying the command into the CLI will therefore
not work properly as f.e. the node-type filter will not apply
and all nodes are repaired.

BUGFIX: Prevent double dash formatting in docs for node:repair command

---

Neos.Neos/Documentation/References/EelHelpersReference.rst

The link given in the documentation leads to a 404, I have set the correct link

TASK: update documentation link for formatCldr formats

---

Neos.Neos/Classes/Validation/Validator/PasswordValidator.php

PasswordValidator was using the property $result of AbstractValidaor. That caused an Error 500 since Flow 6, because AbstractValidator::$result is private now.
**What I did**
Changed to AbstractValidator::addError() method
Use The PasswordValidator with a minimumLength and try to produce a validation-error.

BUGFIX: Don't use AbstractValidator::$result in PasswordValidator

---

Neos.Media.Browser/Resources/Private/Partials/ListView.html

This uses `assetProxy.asset.tags` instead of just `assetProxy.tags`
as a simple way to fix the display of assigned tags in the media
browser list view.
Fixes neos/neos-development-collection#2350

BUGFIX: Access tags of asset in media list view

---

Neos.Media/Classes/Domain/Service/AssetService.php
Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Neos.Neos/Classes/Package.php

If you access an image property in a node and render an ImageVariant
from it via Fusion using an image variant preset, the cache is now
flushed if the image variant is changed afterwards, e.g. when changing
the crop in the media management module.
Fixes #2897

BUGFIX: Flush content cache on image variant change

---

Neos.Media.Browser/Resources/Private/Partials/ContentDefaultPreview.html
Neos.Media.Browser/Resources/Private/Partials/ContentPdfPreview.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Show.html
Neos.Media/Classes/Domain/Model/AssetSource/AssetProxy/ProvidesOriginalUriInterface.php
Neos.Media/Classes/Domain/Model/AssetSource/Neos/NeosAssetProxy.php

The `AssetProxyInterface` declares `getImportStream()` must return
`resource`. The `NeosAssetProxy` returns `?UriInterface` there, which
breaks the contract.
In some places `getImportStream()` is used to access the original URI
(see #2190), but for other proxies, the resulting link target is
`Resource id #x` since the resource is cast to string and used as is.
This fixes the issue by making `getImportStream()` in `NeosAssetProxy`
return `resource` as expected and add (back) `getOriginalUri()` to the
proxy. The URI can be used for a download.
An additional `ProvidesOriginalUriInterface` is added, which can be
implemented by asset sources at will.
Fixes #2918

BUGFIX: Have NeosAssetProxy return resource on getImportStream

---

Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Index.html

The technical name as title can be confusing as it doesn’t 
change when the workspace title is changed.

BUGFIX: Don’t use technical workspace name in the UI

---

Neos.Neos/Configuration/NodeTypes.ContentCollection.yaml
Neos.Neos/Tests/Functional/Fixtures/NodeStructure.xml
Neos.Neos/Tests/Functional/NodeRenamingTest.php

This change makes sure that only nodetypes that inherit from `Neos.Neos:Content` are addable to `Neos.Neos:ContentCollection` as the comment of the nodetype specifically mentions.
Without this other nodetypes are reported as valid child types when getting the configuration from the `NodeType` class.
This caused only a problem when interacting with nodetypes via PHP as the UI already made sure you could not add something else than Content.
Resolves: #2894

BUGFIX: Only allow content nodetypes in content collections

---

Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion

When rewriting the Login form to Neos.Fusion.Form, the `name` attribute of the form has been lost.
This broke the JS code which sets the `lastVisitedNode`.
- open some nested page in the frontend
- open the login form to the backend
- log in
- EXPECTED with this change: you get the exact same page in the backend
- WITHOUT this change: you get the homepage
**Checklist**

BUGFIX: redirect-to-last-visited-page broken with Fusion LoginForm rewrite

---

Neos.Fusion/Tests/Benchmark/RuntimeBench.php
Neos.Fusion/composer.json

**What I did**
* Implemented performance benchmarks for the Fusion runtime with PHPBench
* Slight modification in `Runtime` to have an optional `ControllerContext` (since it's hard to create outside of the bootstraped framework)
* Created PHPBench benchmarks to measure evaluation times and to verify further performance improvements
**Checklist**
Resolves: #2795

TASK: Add Fusion performance benchmarks

---

Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/NodePrivilegeContext.php
Neos.ContentRepository/Tests/Behavior/Features/Security/EditNodePrivilegeBug2865.feature

BUGFIX: fix isDescendantNodeOf permission with UUIDs if specified node is hidden

---

Neos.Neos/Classes/Command/UserCommandController.php
Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
Neos.Neos/Classes/Controller/Module/User/UserSettingsController.php
Neos.Neos/Classes/Domain/Service/UserService.php
Neos.Neos/Classes/ViewHelpers/Backend/AuthenticationProviderLabelViewHelper.php

This change is to support the AccountInterface introduced in neos/flow-development-collection#1939
Cases covered is mentioned in #2938 
Resolves #2938

[TASK] Adjust codebase to support new Account and Roles API

---

Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php

When overriding the FrontendRouterPartHandler with a custom implementation but inheriting from it the configuration was not read from Neos.Neos but from the package that did the override.
This causes the setting to always be false and makes the routing not work properly when
having empty segments for dimensions. This is then quite difficult to debug.
Custom implementations can still decide to override the config and read it from somewhere else if required.

BUGFIX: Use Neos config when overriding FrontendRoutePartHandler

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php

Due to how the query is handled using an integer node identifier in a query by identifier 
will not break but result in severe performance problems as the query will not use 
the index for identifier anymore. Casting to string prevents that.
To expose the problem you can simply try to run such a query with an integer instead 
of a string and you will see extreme performance degradation.
Not giving numbers because it depends on the amount of nodes but it is VERY noticeable.

BUGFIX: Ensure node query by identifier uses strings

---

Neos.Neos/Classes/Controller/Backend/SchemaController.php
Neos.Neos/Configuration/Caches.yaml
Neos.Neos/Configuration/Objects.yaml

This prevents the generation of the nodetype schema on every backend reload.
Load times for Neos instances with lots of nodetypes
are reduced by several seconds depending on the setup.
Also the response has a cache header to allow the browser to keep the result longer.
This also helps in development context as the `version` parameter changes when the nodetypes change. Therefore changing Fusion and reloading is faster ;)
**What I did**
Cache the generated nodetype and vie schema
Use the same caching behaviour as is already used for the xliff translations.
Load the backend twice and check response times.
The difference in projects with many nodetypes is much larger.

FEATURE: Reduce backend load time with nodetype schema cache

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
Neos.ContentRepository/Resources/Private/Schema/NodeTypes.schema.yaml

Allows a `position` to be specified in the NodeType `postprocessors` configuration:
```yaml
'Some.Custom:NodeType':
postprocessors:
SomeCustomTypePostprocessor:
position: 'end'
postprocessor: 'Some\TypePostprocessor'
```
Resolves: #2868

FEATURE: Sortable NodeType Post processors

---

Neos.Media.Browser/Configuration/Settings.yaml
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Resources/Private/Styles/Lite.scss
Neos.Neos/Resources/Private/Styles/Minimal.scss
Neos.Neos/Resources/Private/Styles/Modules/_Modules.scss
Neos.Neos/Resources/Private/Styles/_CSSVariables.scss
Neos.Neos/Resources/Private/Templates/Backend/Module/Index.html
Neos.Neos/Resources/Public/Styles/Lite.css
Neos.Neos/Resources/Public/Styles/Minimal.css
Neos.Neos/Resources/Public/Styles/Welcome.css
Neos.Neos/webpack.config.js

The old stylesheets from pre-react times override a lot of basic styles for backend modules.
This makes it hard to implement custom styles there or use our react ui components.
With this change it's possible to configure a "Lite" and a "Minimal" variant of the Neos backend stylesheet via the module configuration.
The old "Main" stylesheet variant is kept for compatibility reasons.
The "Lite" stylesheet should be used with almost all modules and will also be used for the core modules. It also provides all relevant Neos CSS variables and is about 50% smaller than the old one.
The "Minimal" stylesheet should be used for modules that bring their own styles. For example modules that use the Neos react-components library. It also provides all relevant Neos CSS variables and is about 70% smaller …

FEATURE: Reduced stylesheet for backend modules

---

Neos.Media.Browser/Classes/Controller/AssetController.php

Since collections only show up if the current asset source is local
("Neos"), we should not sum up all assets from external asset sources.
We do not support collections for external asset sources and the
possibly much larger number is irritating, because when clicking
the "All" link the user will only see the local assets.

BUGFIX: Only count local assets within collections

---

Neos.Fusion/Classes/Core/Runtime.php
Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php
Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php
Neos.Fusion/Tests/Functional/FusionObjects/ApplyTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ComponentTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Apply.fusion
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Component.fusion
Neos.Fusion/Tests/Unit/FusionObjects/Helpers/LazyPropsTest.php

**What I did**
* Components provide a nice way to structure Fusion code but prevent lazy evaluation as Fusion does by default by eagerly evaluating all properties as `props`
* If conditions are used inside the `renderer`, it's quite probable that not all props are used - so a large amount of unnecessary evaluations could be performed (we measured that to be in the range of 20-30% in a larger project)
* Introduced a `LazyProps` object implementing `ArrayAccess` that evaluates the actually accessed props lazily (and caches the results)
* Components work as before (there could be edge-cases where explicit `array` type annotations are used for `props`)
* props are only evaluated if used (verified by test)
**Checklist**
Resolves: #2793

TASK: Fusion performance optimization (lazy Component props)

---

Neos.Neos/Classes/Controller/Module/Administration/SitesController.php

https://github.com/neos/flow-development-collection/commit/0cd533a64b44961fbe9e4b43ccc3fcf8e8325ab6 changed the default value of the `$arguments` parameter from `null` to `[]`, so we must change it here too.
I found nowhere else where `AbstractController->redirect()` may be called with `$arguments = null`.

BUGFIX: Use correct default value for redirect in Neos SitesController

---

Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php

fixe the behaviour when the a Tag is inside a Tag with the name beginning with a
Example: `<article> test <a target="_blank" href="http://localhost/_Resources/01">example1</a></article>`
the function replaceLinkTargets returned  `<a target="_blank"rticle> test <a target="_blank" href="http://localhost/_Resources/01">example1</a></article>`
create new test evaluateReplaceResourceLinkTargetsInsideTag
this issue was already fixed in 4.2 release on 5 Nov 2018
Fixes #2395

BUGFIX: change regex for selecting `<a href="">` Tag

---

Neos.NodeTypes.Navigation/Resources/Private/Fusion/Root.fusion

This fixes a previous breaking change where "Menu" node-type is not
getting a default class attribute rendered for instance 'neos-nodetypes-menu'
where a website's stylesheet is relying on this CSS class
**What I did**
In fusion prototype Neos.NodeTypes.Navigation:Navigation loaded fusion  path 'attributes.class.@process' from Neos.Neos:Content.
Add the Menu node type on the page and check in the console/page source it should have css class 'neos-nodetypes-menu'
**Checklist**

BUGFIX: Neos.NodeTypes:Menu has no default class attribute

---

Neos.Media/Classes/Domain/Model/ThumbnailGenerator/DocumentThumbnailGenerator.php

**What I did**
Tested with the following imagick versions:
- V. 6.7.8
- V. 6.9
- V. 7.0
See below
You can verifiy it by running this small code local:
```php
<?php
$filePath = 'pdf.pdf[0]';
$width = 500;
$height = 500;
$im = new \Imagick();
$im->setResolution(120, 120);
$im->readImage($filePath);
$im->setImageFormat('png');
$im->setImageBackgroundColor('white');
$im->setImageCompose(\Imagick::COMPOSITE_OVER);
if (method_exists($im, 'mergeImageLayers')) {
// Replace flattenImages in imagick 3.3.0
// @see https://pecl.php.net/package/imagick/3.3.0RC2
$im = $im->mergeImageLayers(\Imagick::LAYERMETHOD_MERGE);
} else {
$im->flattenImages();
}
if (defined('\Imagick::ALPHACHANNEL_OFF')) {
// ImageMagick >= 7.0, Imagick >= 3.4.3RC1
// @see …
```

BUGFIX: Prevent black shapes in document thumbnails

---

Neos.Neos/Resources/Private/Templates/Service/Nodes/Index.html

This replaces the preview URL by a "breadcrumb" to the homepage
node.
Note: Due to a separate bug in `neos/neos-ui` the breadcrumb is
currently rendered twice, neos/neos-ui#2711 will fix that.
Fixes: #2965

BUGFIX: Fix rendering of URLs in link- end reference editors

---

Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/CreateNodePrivilege.php

Fixes the `createdNodeIsOfType()` matcher so that it works respects
the inheritance chain:
privilegeTargets:
'Neos\ContentRepository\Security\Authorization\Privilege\Node\CreateNodePrivilege':
'Cornelsen.Webkatalog:Nodes.DisableCreation':
matcher: 'createdNodeIsOfType("Some.Package:Some.Mixin")'
Fixes: #2960

BUGFIX: Respect super types in CreateNodePrivilege

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html
Neos.Neos/Resources/Private/Partials/Backend/Menu.html
Neos.Neos/Resources/Private/Styles/Foundation/_buttons.scss
Neos.Neos/Resources/Private/Styles/Modules/_Modules.scss
Neos.Neos/Resources/Private/Styles/Neos.scss
Neos.Neos/Resources/Public/Styles/Lite.css
Neos.Neos/Resources/Public/Styles/Main.css
Neos.Neos/Resources/Public/Styles/Minimal.css

The standard module stylesheet applied a lot of
styles to `<button>`. With this change this only
happens when using the backwards compatible
„Full“ stylesheet as the Lite and Minimal (introduced with 5.2) 
shouldn’t interfere with the modules styles.

BUGFIX: Don’t override default button style in modules

---

Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php

Fixes the test that is failing since merging https://github.com/neos/neos-development-collection/pull/2409

TASK: Fix failing evaluateReplaceResourceLinkTargetsInsideTag test

---

Neos.Fusion/Classes/FusionObjects/MapImplementation.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Map.fusion
Neos.Fusion/Tests/Functional/FusionObjects/MapTest.php
Neos.Neos/Documentation/References/NeosFusionReference.rst

This adds a new fusionPath `keyRenderer` to render
the key of the resulting collection of `Neos.Fusion:Map`
Example:
```
keyRenderer = Neos.Fusion:Map {
items = ${items}
itemName = 'element'
itemRenderer = ${'value-' + element}
keyRenderer = ${'key-' + element}
}
```
will render:
```
['key-element1' => 'value-element1', 'key-element2' => 'value-element2']
```

FEATURE: Add keyRenderer to render the key in the result map

---

Neos.Neos/Configuration/NodeTypes.ContentCollection.yaml

This reverts commit b48660b28c1de596e74d4a95b8547d743b5199f1 as it’s breaking the „constraint“ best practices for node types and allows to many NodeTypes in existing projects suddenly.
As the previous fix is still necessary I will create a new PR for a next Neos version 5.3 or 6.0 depending on the final solution.
Without the fix the actual constraint to only allow Content NodeTypes is done by the Neos.Ui and NOT by our NodeType definition which causes an inconsistency when working with the CR via its API or when analysing the NodeType definitions.

BUGFIX: Revert ContentCollection constraint change

---

Neos.Neos/Classes/View/FusionExceptionView.php
Neos.Neos/Classes/View/FusionView.php
Neos.Neos/Classes/View/FusionViewI18nTrait.php

When Neos finds a content dimension named "language" it uses that
dimension to set the locale fallback order for rendering in the
`FusionView`.
In Neos 5.0 that rule was switched to "strict" mode, meaning the order
was used without falling back to implicit parents in locales. This
broke translations in case the "language" dimension was configured with
e.g. `de_DE` or `en_US` - for those cases translations were never used if
the respective XLIFF files were in `de` (or `en`) folders.
This change makes the `FusionView` use the strict flag from the settings,
giving back control to the user (in case non-strict is really needed).
At the same time it makes translations work as would be expected in
most cases, by using e.g. `de_DE` first, but falling back to `de` later.
Fixes #2963

BUGFIX: Respect fallback rule "strictness" in FusionView

---

Neos.ContentRepository/Classes/Eel/FlowQueryOperations/ChildrenOperation.php

Wrong parameter order leads to deprecation warning and to an exception
in PHP 7.4

BUGFIX: Passing glue string after array is deprecated

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Configuration/Settings.yaml
Neos.Media.Browser/Resources/Private/Templates/Asset/ReplaceAssetResource.html

This feature adds a config parameter for the media browser to disable the option to create redirects for replaced assets resources. Might be useful for some projects, where these kind of redirects don't make any sense and therefore should be disabled by default.

FEATURE: Add option to disable the creation of redirects for assets

---

Neos.Neos/Resources/Private/Templates/Backend/Module/Index.html

**What I did**
Remove the `/` in front of the Path for the resource.
Open Neos backend, e.g. User Manager and inspect the path in the HTML head for Lite.css
Closes #2996

BUGFIX: Fix path to Styles/<Lite.css>

---

Neos.ContentRepository/Classes/Domain/Model/Node.php

Pass copied node instead of current node instance to `emitAfterNodeCopy` signal.
This fixes #2994

BUGFIX: pass copied node to emitAfterNodeCopy signal

---

Neos.ContentRepository/Classes/Domain/Model/NodeInterface.php
Neos.ContentRepository/Classes/Domain/Projection/Content/TraversableNodeInterface.php

Also improves deprecation warning for NodeInterface#getParent
1. The NodeInterface#getParent method is not fully equivalent to its deprecation replacement TraversableNodeInterface#findParentNode -> it should be at least mentioned on the deprecation waring, that those behaviors differ from each other
2. The comment on findParentNode was telling "two truths" about root node handling

TASK: Update code documentation for TraversableNodeInterface

---

Neos.Diff/Classes/Renderer/Html/HtmlArrayRenderer.php

**What I did**
I changed string offset access from curly-braces to brackets

PHP 7.4 compatibility: Remove curly brace string offset access

---

Neos.Media.Browser/Classes/Controller/AssetCollectionController.php
Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Classes/Controller/ImageController.php
Neos.Media.Browser/Classes/Controller/TagController.php
Neos.Media.Browser/Resources/Private/Partials/ConstraintsHiddenFields.html
Neos.Media.Browser/Resources/Private/Partials/ListView.html
Neos.Media.Browser/Resources/Private/Partials/ThumbnailView.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html
Neos.Media.Browser/Resources/Private/Templates/Asset/New.html
Neos.Media.Browser/Resources/Private/Templates/Asset/ReplaceAssetResource.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Show.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Variants.html
Neos.Media.Browser/Resources/Private/Templates/AssetCollection/Edit.html
Neos.Media.Browser/Resources/Private/Templates/Tag/Edit.html
Neos.Media.Browser/Resources/Public/JavaScript/upload.js
Neos.Media/Classes/Domain/Model/AssetSource/AssetTypeFilter.php
Neos.Media/Classes/Domain/Model/Dto/AssetConstraints.php
Neos.Media/Tests/Unit/Domain/Model/Dto/AssetConstraintsTest.php
Neos.Neos/Classes/Controller/Service/AssetProxiesController.php
Neos.Neos/Documentation/References/PropertyEditorReference.rst

Extends the Media Browser and Asset proxy search endpoint so
that it supports *constraints* that filter the asset lists
(on top of the user-specified filters).
This makes it possible to constraint asset source(s) and
media type(s) per node type property.
Example:
'Some.Node:Type':
properties:
'asset':
type: 'Neos\Media\Domain\Model\Asset'
ui:
inspector:
group: 'asset'
editorOptions:
constraints:
mediaTypes: ['audio/*']
assetSources: ['neos', 'wikipedia_de']
(restricts the asset editor to only allow audio files of the `neos` or `wikipedia_de`
asset source when using the media browser modal, searchbox or file upload).
Resolves: #2984

FEATURE: Configurable Asset Constraints

---

Neos.ContentRepository/Classes/Domain/Model/Node.php
Neos.ContentRepository/Classes/Domain/Model/NodeData.php
Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Neos.ContentRepository/Tests/Functional/Domain/LayeredWorkspacesTest.php
Neos.ContentRepository/Tests/Functional/Domain/WorkspacesTest.php

Due to an issue in how Doctrine 2.x handles the computation of changesets when given
entities to commit it recomputed the changesets for all entities for every entity.
Leading to n^2 change computations.
In a large project this improved the moving of ~750 nodes from 1.7m to 8.5s.
In the demo site moving the "features" page from 4s to 1.65s. 
Publishing seems to be only slightly (~10%) faster to its different behaviour in the CR.
**What I did**
Which this change this behaviour is circumvented by commiting all
entities at once. Including entities which might not have been included
with the previous code but would have been persisted at the end of the request
anyway.
**What is breaking**
This change leads to all entities scheduled for persistence to actually persist when a node is changed, …

!!! BUGFIX: Speed up node move actions

---

Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php

Since a couple of months child nodes of hidden nodes are accessible (outside the Neos backend). This change restores the initial behavior and makes sure that accessing child nodes from hidden nodes will lead to a 404 response.
resolves: https://github.com/neos/neos-development-collection/issues/2983

BUGFIX: Make child nodes of hidden parents inaccessible

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media.Browser/Resources/Private/Templates/Asset/Variants.html

This adds a condition for using the parentRequest only if it is not the mainRequest already.
Fixes #3005

BUGFIX: Variants tab does not use mainRequest in form when opened from inspector

---

Neos.Neos/Classes/Controller/LoginController.php
Neos.Neos/Configuration/Views.yaml

The login controller view was not configurable using a `Views.yaml` (as was the case for Neos 3 & 4.)
This is fixed by adding a `Views.yaml` and removing `initializeView()` from `LoginController`.
Now the Login screen can be customized again by creating custom Fusion for rendering it (see
`Neos.Neos/Resources/Private/Fusion/Backend` for inspiration) and adjusting the path used
through `Views.yaml`, e.g.
-
requestFilter: 'isPackage("Neos.Neos") && isController("Login") && isAction("index") && isFormat("html")'
options:
fusionPathPatterns:
- 'resource://Acme.Com/Private/Fusion/NeosLogin'
Resolves: #3041

FEATURE: Make login controller view configurable using Views.yaml

---

Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion

This replaces the use of `Neos.Fusion:Collection` with `Neos.Fusion:Loop`
and `Neos.Fusion:Array` with `Neos.Fusion:Join`.
To ensure backwards compatibility there is a processor which overrides
`items` if the property `collection` is set.

TASK: Remove deprecated code use from ContentCollectionRenderer

---

Neos.Media/Migrations/Mysql/Version20200823164700.php
Neos.Media/Migrations/Postgresql/Version20200823164701.php

In Neos prior to 4.1, the media browser uses PNG resources to show thumbnails for non graphical documents from `…/Public/Icons/`, like `ppt.png`. In 4.1 the PNG ressources were removed and replaced by SVG resources from `…/Resources/Public/IconSets/vivid/`. When you add new files after the upgrade, the valid SVG resources are used, but old assets still refer to their old resources, which are missing. As a result, the media browser shows the rotating “loading” icon for these old documents.
This adds Doctrine migrations to replace the old with the  new icons in the database.
Fixes #2341

BUGFIX: Migrate media browser icons

---

Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/TransientNodeCache.php

This is an important bugfix because right now non existing nodes will result in a fatal error 
due to the type hint, when the $getter() actually doesn't resolve a node but null, which can happen.
The current behavior is therefore broken for many installations.
Relate #2301

BUGFIX: TransientNodeCache must be able to return null

---

Neos.Neos/Classes/Eel/FlowQueryOperations/SortOperation.php
Neos.Neos/Tests/Functional/FlowQueryOperations/Fixtures/SortableNodes.xml
Neos.Neos/Tests/Functional/FlowQueryOperations/SortOperationTest.php

On enabling Psmb/FlatNav I stumbled over the FlowQuery sort operation having the demand for case insensitive sort.
Here's the solution: a third optional `sort()` parameter for sortOptions.
The FlowQuery `sort()` is executed utilizing PHP `arsort()`. According to the sort flags of `arsort()` (see [https://www.php.net/manual/en/function.sort](https://www.php.net/manual/en/function.sort)) the sort options are:
```
'SORT_REGULAR'
'SORT_NUMERIC'
'SORT_STRING'
'SORT_LOCALE_STRING'
'SORT_NATURAL'
'SORT_FLAG_CASE' (use as last option with SORT_STRING, SORT_LOCALE_STRING or SORT_NATURAL)
```
A single sort option can be supplied as string. Multiple sort options are supplied as array.
Other than the above listed sort options shall throw an error.
Omitting the third parameter leaves FlowQuery …

FEATURE: third parameter "sortFlags" for FlowQuery sort()

---

Neos.Fusion/Classes/Core/Runtime.php
Neos.Fusion/Tests/Functional/FusionObjects/ComponentTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Component.fusion

With the introduction of lazy evaluation the apply values are stored as
an array of (absolute) paths and popped accordingly to the evaluation
stack. When an object is instantiated only the effective apply values
for this object must be set (and not all currently set apply values).
Fixes #3003
**What I did**
Adjusted the code in Runtime to only set applicable (stored) apply values when instantiating an object.
- Reproduced the error
- Analyzed the rendering of the broken case with some added debugging output
- Found the case where `Case` will be instantiated with wrong props and spotted the issue introduced with 0642115d529237bd30ae1502a78409e7739c4718
- Implemented a minimal functional test case that reproduces the error
- Implemented the fix by only setting the actual …

BUGFIX: Correctly set apply values for instantiated array objects

---

Neos.Neos/Resources/Private/Templates/Service/Nodes/Index.html

This replaces the (preview) URL by a "breadcrumb" to the homepage node.
Essentially applies https://github.com/neos/neos-development-collection/pull/2966
to the 4.3 branch, since the breadcrumb is a lot more user-friendly than the
URL.

FEATURE: Use breadcrumb for URL preview

---

Neos.Media.Browser/Configuration/Settings.yaml

After the https://github.com/neos/neos-development-collection/pull/3023 the image selector in the backend was broken.

BUGFIX: Require jQuery Version 3.5.1

---

Neos.Neos/Classes/Service/LinkingService.php

Specifies the HTTP request from the ControllerContext as
fallback for the `BaseUriProvider` in order to prevent an
exception when trying to create Node URIs on the CLI.
Note: This requires https://github.com/neos/flow-development-collection/pull/2158
Fixes: #3128
Related: https://github.com/neos/flow-development-collection/issues/2084

BUGFIX: Fix LinkingService for CLI mode

---

Neos.Neos/Classes/Controller/Backend/BackendController.php
Neos.Neos/Classes/Controller/Backend/MenuHelper.php
Neos.Neos/Classes/Service/BackendRedirectionService.php
Neos.Neos/Configuration/Policy.yaml
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Resources/Private/Partials/Backend/Menu.html

Before, it was not possible to log in to the Neos backend without having access to the content module, as the user was automatically redirected to the content module.
With this feature, an available module is determined when a user logs in and the user is redirected to that module.
- Users no longer need to have access to the content module to be able to log in
- There is a setting `Neos.Neos.moduleConfiguration.preferredStartModules` available to define the preferred start modules. The first module of that list, which a user has access to is chosen for the start module. If none of the listed modules can be accessed, the first module of the list of accessible modules of a user is chosen:
- The backend modules and sub modules can now be sorted using the positional array sorter
```
Neos: …
```

FEATURE: Allow users to log in without access to the content module

---

Neos.Neos/Configuration/NodeTypes.ContentCollection.yaml
Neos.Neos/Configuration/Testing/NodeTypes.yaml
Neos.Neos/Tests/Functional/Fixtures/NodeStructure.xml

A ContentCollection did allow all children but Documents in the past which is unexpected and makes it needlessly harder to create derived nodetypes with custom constraints. 
This constraint is now adjusted to allow nodes of `Neos.Neos:Content` inside a `Neos.Neos:ContentCollection` as anyone would expect given the nodetype name. 
Additionally the test fixtures are adjusted as in one test a `ContentCollection` was moved into another. Now the respective node has a type that inherits from Content and ContentCollection.
**How to update:**  If you created derive content collections that altered the constraints to forbid `*`  you have to adjust the constraints and now forbid `Neos.Neos:Content` instead of `*`:
```
'Vendor.Site:ContentCollection':
superTypes:
'Neos.Neos:ContentCollection': true …
```

!!!TASK: Adjust constraints of `Neos.Neos:ContentCollection` to allow `Content` instead of denying `Document`

---

Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php
Neos.Neos/Classes/NodeTypePostprocessor/DefaultPropertyEditorPostprocessor.php
Neos.Neos/Classes/NodeTypePostprocessor/IconNameMappingPostprocessor.php
Neos.Neos/Classes/NodeTypePostprocessor/NodeTypePresetPostprocessor.php
Neos.Neos/Configuration/NodeTypes.Node.yaml

Introduce `NodeTypePresetPostprocessor` and extract `IconNameMappingPostprocessor` and `DefaultPropertyEditorPostprocessor` from `NodeTypeConfigurationEnrichmentAspect`.
This allows to configure nodeType presets via settings and apply them to nodeTypes via. Other than mixins this allows to ensure consistent configurations across differently named properties to ensure a consistent editor experience.
Note: This is mainly a core adaptation of the Sitegeist.Silhoettes package https://github.com/sitegeist/Sitegeist.Silhouettes.
The presets can be applied by definining the `options.preset` for childNodes or properties.
```
Neos:
Neos:
nodeTypes:
presets:
childNodes:
vendor:
defaultConstraints:
constraints:
'Neos.Neos:Content': true
'Neos.NodeTypes.BaseMixins:TitleMixin': true
properties: …
```

FEATURE: Introduce NodeTypePresetPostprocessor

---

Neos.Fusion/Configuration/Settings.yaml

Add the StaticResource EEL Helper from https://github.com/neos/flow-development-collection/pull/2174 to the Fusion defaultContext. 
StaticResource.uri (packageKey, pathAndFilename, localize)
- (string) packageKey
- (string) pathAndFilename
- (boolean, optional) localize = false
StaticResource.content (packageKey, pathAndFilename, localize)
- (string) packageKey
- (string) pathAndFilename
- (boolean, optional) localize = false
This makes this helper available in afx:
```
<link rel="stylesheet" href={StaticResource.uri('Neos.Demo', 'Public/Styles/Main.css')} media="all" />
<style>{StaticResource.content('Neos.Demo', 'Public/Styles/Main.css')}</style>
```
Resolves: #3133

FEATURE: Add StaticResource helper to Fusion defaults

---

Neos.Neos/Migrations/Code/Version20201108113821.php

In PR #2715 the constraints in the `Neos.Neos:ContentCollection` were altered from allow `*` and disallow `Neos.Neos:Document` to disallow `*` and allowing `Neos.Neos:Content`.
This change adds an automatic migration to alter NodeTypes that are derived from `Neos.Neos:ContentCollection` and constraints of childNodes that are of type `Neos.Neos:ContentCollection`.
The migration will replace constraints for `*` with constraints for `Neos.Neos:Content` while preserving order.
Limitations: This will not run on nodeTypes that indirectly inherit from `Neos.Neos:ContentCollection` and `childNodes`
that are of a derived ContentCollection nodeType. However i consider such cases exotic and hope this catches 99% of the cases.
Resolves: #3164

TASK: Add migration to adjust constraints of `Neos.Neos:ContentCollections`

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html

**What I did**
I set the collection mode explicitly to 0 to correct the argument in the url for switching to a custom collection. This Fixes Issue https://github.com/neos/neos-development-collection/issues/3161 
I adjusted the arguments in the link generation in the template for the index action. 
Switch to the All collection and than by clicking on an link for a custom collection the view switches to the selected collection. 
**Checklist**
- [ x] Code follows the PSR-2 coding style
- [ x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html) with the bug (5.3)

BUGFIX: set collection mode explicitly for custom collection links

---

Neos.Neos/Migrations/Code/Version20201108113821.php

The adjustments were applied to all nodes with constraints because the existence of the superType "Neos.Neos:ContentCollection" was not properly checked. 
The fixed migration was introduced in #3163

BUGFIX: Correct bug in migration of ContentCollectionConstraints

---

Neos.Neos/Classes/Service/LinkingService.php
Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
Neos.Neos/Classes/ViewHelpers/Uri/NodeViewHelper.php

The LinkingService.createNodeUri() no longer uses/accepts this
parameter…
See https://github.com/neos/neos-development-collection/pull/3168

TASK: Remove use of resolveShortcuts argument

---

Neos.ContentRepository/Classes/Package.php

When a fresh variant is published outdated URLs may be generated if
the urlPathSegment was changed on the variant.
Fixes #3173

BUGFIX: Flush 1st level node caches after publishing

---

Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php
Neos.Media/Classes/Domain/Service/ImageService.php

The autorotate is applied before calculating the resize dimensions to work with correct size values.
How to test:
- Go to the media module
- Upload an image with exif orientation like https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_6.jpg
- Look at the generated thumbnails (without this change the thumbnail is rotated 90°)
Resolves: #3148

BUGFIX: Use autorotate filter to apply resize adjustments properly to images with exif-orientations

---

Neos.ContentRepository/Classes/Domain/Model/Node.php
Neos.ContentRepository/Classes/Domain/Model/NodeInterface.php

* Reword the deprecation message in the interface doc comment
* For deprecated methods with a replacement (e.g. `getDepth()`):
* Don't remove the method but keep the deprecation annotation
* Remove any `@api` annotation from the method
* For deprecated methods without replacement (e.g. `getContextPath()`):
* Don't remove the method
* replace the `@deprecated` annotation by some comment
Related: #3137

TASK: Adjust Node and NodeInterface deprecation annotations

---

Neos.ContentRepository/Classes/Domain/Model/Node.php
Neos.ContentRepository/Classes/Domain/Model/NodeInterface.php

Tweaks some doc comments that were introduced with #3187 and referred to a non-existing class `TraversableNode`

Fix doc comments in Node and NodeInterface

---

Neos.Fusion/Classes/Core/Parser.php

In many cases the currently parsed resource and line is known and it would help to
editors to show this information in the parser exception.
Resolves: #3206

BUGFIX: Add file and line information to fusion parser exceptions where possible

---

Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
Neos.Neos/Resources/Private/Fusion/Prototypes/ConvertUris.fusion
Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php

* The `rel` value get merged with existent`rel` attributes
* If a value already exists, it will not get overridden. Example `<a href="https://external.site" target="external">` the target stays `external`
* When you set the external target to something different (e.g. `'external'`) or disable it with false, the `rel` attribute will still be set
* If you have `data-target` set, this will not be overwritten
Fixes: #2942

BUGFIX: Respect already defined attributes in Neos.Neos:ConvertUris

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html

Add `tagMode: 0` to tag links rendered in Media.Browser.
Fixes #3196

BUGFIX: set tagMode explicitly for tag links in Media.Browser

---

Neos.Media/Classes/Domain/Model/AssetSource/AssetSourceInterface.php
Neos.Media/Classes/Domain/Model/AssetSource/Neos/NeosAssetSource.php
Neos.Neos/Documentation/Appendixes/ReleaseNotes/520.rst

Extends the `Neos\Media\Domain\Model\AssetSource\ AssetSourceInterface` by the two methods `getIconUri()` and `getDescription()`.
This is a breaking change if you created a custom Asset source (implementing the `AssetSourceInterface`) and didn't implement these methods yet.
Related to #3137

!!! FEATURE: Add getIconUri & getDescription to AssetSourceInterface

---

Neos.Media.Browser/package.json
Neos.Media.Browser/yarn.lock

Semantic-release has been added 2 years ago with the image variant change. But it was never used and as we need a changelog ruleset for Neos commit messages before we are able to use it we can just drop it.
When we plan to use it we can add it again anyways.
Resolves: #3209

TASK: Removes unused semantic-release

---

Neos.Fusion/Tests/Unit/FusionObjects/DataStructureImplementationTest.php
Neos.Fusion/Tests/Unit/FusionObjects/JoinImplementationTest.php

Invalid positions has been skipped silently. Since https://github.com/neos/flow-development-collection/pull/2214 this leads to an InvalidPositionException.
This change adjusts the tests, so that the expected errors are also respected in the tests.
Related: https://github.com/neos/flow-development-collection/pull/2214

BUGFIX: Adjust fusion tests to match the InvalidPositionException

---

Neos.Neos/Documentation/References/NodeTypeDefinition.rst

The aloha configuration is not working anymore as we removed that compatibility
layer in the neos-ui. So we can also remove the information in the docs.
The aloha editor served us well but now it is time to remove the last legacy pieces.
Relates to https://github.com/neos/neos-ui/pull/2802

TASK: Remove aloha legacy information

---

Neos.Neos/Documentation/Contribute/Code/EmberUI.rst

The most parts of the EmberUI has been already removed. So we should mention that.
Releates: #2531

TASK: Extend the warning for the EmberUI

---

Neos.Fusion.Afx/Classes/Dsl/AfxDslImplementation.php

Previously only AfxExceptions were converted to fusion exceptions which hid valuable information about the error source from the user. This change will also catch for AfxParserExceptions and convert those to Fusion\Exceptions
This is non critical as the fusion side will catch this aswell but it should help to create error messages that are slightly easier to understand.
This replaces pr: https://github.com/neos/fusion-afx/pull/35 after moving afx to the neos development collection

TASK: Throw fusion exception with explanation also for afx parser errors

---

Neos.Neos/Classes/Eel/FlowQueryOperations/SortOperation.php

Without this, the reference documentation can not be parsed. The Eel helper was not updated since version 4.3!!!

BUGFIX: Add missing return tag for the flow query operation

---

Neos.Neos/Documentation/Appendixes/ReleaseNotes/520.rst

The headline "What has changed" is one level to high, so it will generate the wrong menu on the sidebar.

BUGFIX: Fix headline in release notes (5.2)

---

Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion

Add alt attribute (empty by default) for full HTML conformance with validity checkers.
See https://www.w3.org/wiki/HTML/Usage/TextAlternatives
Bonus effect: Since screen readers will read the full file name when no
alt attribute is set at all, this will improve accessibility.
It is recommended to provide meaningful alternative texts for non-decorative images.

BUGFIX: Set ``alt`` attribute per default for ``Neos.Neos:ImageTag``

---

Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php

hen rendering the XML sitemap with Neos.Seo sometimes an exception
occurs:
No operation which satisfies the runtime constraints found for
"context"
See https://github.com/neos/neos-development-collection/issues/2968
for more details.
This change should fix that by returning null early, if there is no
"current" node.
Fixes #2968

BUGFIX: Avoid possible exception during sitemap rendering

---

Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion

While experimenting with PSR-15 middlewares I found out that no content type is returned from the Fusion rendering step when using the Neos default page prototype.
This keeps those middlewares from applying their effects as they do not know what kind of content they get.
This can be easily fixed in custom packages, but it makes sense to just have this as default for the future.

TASK: Set text/html as default content type in Fusion

---

Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion

Before this change only `resource://…` urls were supported.
**What I did**
Check whether the configured path is a resource uri or a simple url.
Use Fusion case object and condition to check the type.
Set `https://source.unsplash.com/random` as background image and enjoy a nice random picture for every login.
**Checklist**

FEATURE: Allow http image urls as login wallpapers

---

Neos.Neos/Classes/Routing/Exception/InvalidShortcutException.php
Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php

Adjusts the `FrontendNodeRoutePartHandler`  such that it doesn't throw an
exception if the URL to a Shortcut node can't be resolved.
Instead the handler just won't handle this case, passing its handling on to the
next route (usually leading to a `NoMatchingRouteException` when no custom
route handles broken shortcuts).
Background:
When creating Shortcut nodes, the `mode` defaults to "first child node". If that new node
is published without a child node, the shortcut points to a non-existing node which
led to the exception.
Related: #3256

BUGFIX: Prevent exception when shortcut nodes can't be resolved

---

Neos.Media/Configuration/Settings.yaml
Neos.Neos/Configuration/Settings.yaml

Moves the `Neos.Neos` reference from the `Neos.Media` routing configuration
to the Neos package.
**NOTE:** This removes the `Neos.Media` route positioning, so that it depends solely on the package
loading order.
To set the position explicitly, this configuration can be overridden with a few lines of `Settings.yaml`, for example:
```yaml
Neos:
Flow:
mvc:
routes:
'Neos.Media':
position: 'after Some.Package'
```
Fixes: #3258

BUGFIX: Allow Neos.Media package to be installed without Neos

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html

This fixes parsing of the Fluid template on PHP 7.3+ so the upload
URL is correctly set.
Fixes #2906
Fixes #3096

BUGIX: Fix drag-n-drop upload of assets in media browser

---

Neos.Fusion/Classes/Aspects/FusionCachingAspect.php
Neos.Fusion/Classes/View/FusionView.php

The `Neos_Fusion_ObjectTree` cache is used to store parsed fusion ASTs, the identifier is calculated from the configured fusionPathPatterns. Previously the string `@package` was replaced at runtime and thus became not part of the cache identifier calculation. That way two packages using the same fusionPathPatterns would end up with the same cacheIdentifier.
This change extracts the replacement of the `@package` into a separate method that is called from the CachingAspect.
That way if the package key is used in the current path pattern it becomes part of the cache identifier.
Resolves: #3288

BUGFIX: Fix cache identifier collision in `Neos_Fusion_ObjectTree` cache.

---

Neos.Fusion/Classes/FusionObjects/AbstractFusionObject.php

TASK: Rename tsValue to fusionValue

---

Neos.Neos/Classes/Routing/Aspects/RouteCacheAspect.php

Allow array wrapped node context paths
similar to the adjusted implementation
in `FrontendNodeRoutePartHandler->resolveValue`.
Resolves: #3276 
**What I did**
Check if node is an array and extract context path.
The behaviour is now the same as in `FrontendNodeRoutePartHandler->resolveValue`.
I had a Fluid template with a paginate widget that threw an exception without this change.
**Checklist**

BUGFIX: Prevent error in route cache aspect

---

Neos.Neos/Resources/Private/Styles/Foundation/_dropdowns.scss
Neos.Neos/Resources/Public/Styles/Includes-built.css
Neos.Neos/Resources/Public/Styles/Neos.css

Limit the minimum width of the dropdown to the width of the trigger button
and make it possible to become wider and float from right side of the trigger button to the left.
Fixes: #3297

BUGFIX: Adjust user menu dropdown width

---

Neos.Neos/Classes/NodeTypePostprocessor/CreationDialogPostprocessor.php
Neos.Neos/Tests/Unit/Domain/NodeTypePostprocessor/CreationDialogPostprocessorTest.php

Hi there,
this PR accompanies https://github.com/neos/neos-ui/pull/2870 and re-enables editor functionalities that were disabled in https://github.com/neos/neos-development-collection/commit/029572e38c163a5475c0ed3a8a29a988a60e4f4c#diff-5dcd744af0bf44e044a96b272818323abc9ed49d284f5e40ff33f62b440ff801R91 ff. due to a lack of support for secondary editor views in the NodeCreationDialog.

BUGFIX: Re-Enable formerly unsupported editors for NodeCreationDialog

---

Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Edit.html

On the edit view of the user management module it was not possible to delete the user caused by the missing confirmation dialog. This has not been open caused by a wrong if condition.
Fixes: #3310

BUGFIX: Open delete dialog on edit user view

---

Neos.Fusion/Classes/FusionObjects/DebugConsoleImplementation.php
Neos.Fusion/Resources/Private/Fusion/DebugConsole.fusion
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/FusionObjects/DebugConsoleTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/DebugConsole.fusion
Neos.Neos/Documentation/References/NeosFusionReference.rst

With this new Fusion object it’s possible to debug to the browser console via an inserted script tag instead of showing a big dump that breaks the layout.
It optionally allows setting a title, method and additional arguments.
Resolves: #3319
**What I did**
Added a new Fusion object that returns a script tag with a script that calls the browser console and 
prints the given json serialized value.
Run the provided tests or add the following script to a visible Fusion component and play with it:
```
renderer.@process.debug = Neos.Fusion:Debug.Console {
value = '%cfoo'
method = 'table'
color = 'color: green'
}
```
**Checklist**

FEATURE: Fusion debug to browser console

---

Neos.Fusion/Classes/FusionObjects/MatchImplementation.php
Neos.Fusion/Resources/Private/Fusion/Match.fusion
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Match.fusion
Neos.Fusion/Tests/Functional/FusionObjects/MatchTest.php
Neos.Neos/Documentation/References/NeosFusionReference.rst

This change adds a new Fusion object to replace many situations where the Case object was used just to return a value based on a string.
The idea is based on the new match method in PHP 8 https://www.php.net/manual/tr/control-structures.match.php.
Resolves: #3318
**What I did**
Added a new Fusion object that returns the value for a key that matches the given subject or optionally a default if no match was found.
Run included tests.
**Checklist**

FEATURE: Fusion match object

---

Neos.Neos/composer.json
composer.json

Starting with Neos 5.2 the Neos Package required Neos.Fusion.Form `^1.0` instead of `*` which will not allow to use version 2.0+ of said package.
This change adjusts the constraint to `^1.0 || ^2.0` to allow projects to benefit from the Fusion.Form Runtime. 
Hint: When upmerged to master constraint should be adjusted to `^2.0`. If this is forgotten i will take care in a second pr.
Relates: https://github.com/neos/fusion-form/issues/42

TASK: Relax version constraint and allow Neos.Fusion.Form 2.0

---

Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
Neos.Neos/Classes/Fusion/Helper/NodeLabelToken.php
Neos.Neos/Configuration/NodeTypes.Node.yaml
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Tests/Functional/Fusion/Fixtures/Fusion/NodeHelper.fusion
Neos.Neos/Tests/Functional/Fusion/Fixtures/Fusion/Root.fusion
Neos.Neos/Tests/Functional/Fusion/NodeHelperTest.php

With this helper it’s easier to define custom node label schemas in nodetypes.
**What I did**
Moved the previously used Eel expression from the main `Neos.Neos:Node` nodetype into the NodeHelper.
Similar to the TranslationParameterToken it provides a chainable interface to simplify custom nodetype naming.
All labels in the Neos document and content tree should still be the same.
Override the nodetype label by copying the expression from `Neos.Neos:Node` and modifying it.
Examples: 
Use properties as label with fallback chain (replaces the previous default)
```
'Neos.Neos:Node':
label: "${Neos.Node.labelForNode(node).properties('title', 'text')}"
```
Show number of elements in a multicolumn next to its label
```
'Neos.Demo:Content.Columns.Two':
label: …
```

FEATURE: Add node label helper

---

Neos.Neos/Configuration/NodeTypes.Content.yaml
Neos.Neos/Configuration/NodeTypes.Document.yaml

This change makes sure that the `CreationDialogPostprocessor` is
executed _after_ the `NodeTypePresetPostprocessor` so that the
presets are replaced before the Creation Dialog fields are generated.
Fixes: #3329

BUGFIX: Fix support for NodeType presets in the Creation Dialog

---

Neos.ContentRepository/Classes/Domain/Service/NodeService.php

Since ``node:repair`` uses the ``buildAutoCreatedChildNodeIdentifier``, it would
best to ensure the ``identifier`` is already correct when auto-creating child nodes.
Otherwise the identifier will be changed to a so called "stable"
identifier during a ``node:repair`` run which can lead to unwanted
behaviour in certain applications.

BUGFIX: Use "stable" identifier when auto-creating child nodes

---

Neos.Media/Classes/Domain/Model/Asset.php
Neos.Media/Tests/Functional/Domain/Model/AssetTest.php

With 836d739fa4f92b3c87c0fcaccd54f2909e188773 a condition was added that prevented getting an AssetProxy for assets in the Neos AssetSource. But they all have one and therefore the query for an imported AssetProxy is not skipped for local assets.
**What I did**
Return AssetProxy for local assets.
Check if the AssetSource is Neos itself.
Added functional test

BUGFIX: getAssetProxy failed for local assets

---

Neos.ContentRepository/Classes/Domain/Model/NodeData.php
Neos.ContentRepository/Tests/Functional/Domain/NodesTest.php
Neos.ContentRepository/Tests/Unit/Domain/Service/NodeServiceTest.php
Neos.Fusion/Classes/Core/Cache/ContentCache.php
Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetAssetCollectionConditionGenerator.php
Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetTagConditionGenerator.php
Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetWithoutAssetCollectionConditionGenerator.php
Neos.Neos/Tests/Functional/Domain/Service/Fixtures/Sites.xml

Updates the ClassMetadata Namespace from
Doctrine\Common\Persistence\Mapping\ClassMetadata to
Doctrine\Persistence\Mapping\ClassMetadata.
Fixes Unit-Tests.
Removes optional parameters after mandatory parameters.

PHP 8 Changes

---

Neos.Neos/Classes/Service/Controller/NodeController.php

This has obviously been forgotten in the past… and since it's not used
by the new UI, that wasn't noticed yet.

BUGFIX: Avoid use of removed isMethodSafe()

---

Neos.Media.Browser/Resources/Public/JavaScript/collections-and-tagging.js
Neos.Media.Browser/Resources/Public/JavaScript/new.js
Neos.Media.Browser/Resources/Public/JavaScript/upload.js

The usage of `window.Typo3Neos` has been replaces with `window.NeosCMS` and with version 8 the old Typo3Neos will not work anymore. So we as core should use the latest version of course.
**What I did**
Just replaced the old `window.Typo3Neos` with `window.NeosCMS`
Just edit tags, create tags or images.
**Checklist**

TASK: Replace deprecated window.Typo3Neos

---

Readme.rst

When installing for development purposes, `--prefer-install=auto` needs
to be used since Composer 2.1, see https://getcomposer.org/doc/06-config.md#preferred-install

BUGFIX: Adjust contributing section to composer changes

---

Neos.Neos/Classes/Fusion/DimensionsMenuItemsImplementation.php

The comparison in this is wrong. Because the depth is 0-based, but the nodes returned by getNodesOnPath(…) contain the root node, less-than-or-equal must be used.
Fixes #3363

BUGFIX: Fix depth comparison in hasHiddenNodeParent(…)

---

Neos.ContentRepository/Classes/Domain/Service/NodeService.php

As the NodeAggregateIdentifier class is final and not mockable in unit tests.

TASK: Use nodeIdentifier instead of getNodeAggregateIdentifier

---

Neos.Fusion/Classes/FusionObjects/HttpResponseImplementation.php
Neos.Fusion/Tests/Unit/FusionObjects/Http/ResponseHeadImplementationTest.php
Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php
Neos.Neos/Classes/View/FusionView.php

See https://github.com/guzzle/psr7/pull/345
Related to https://github.com/neos/flow-development-collection/pull/2455 - hence why this targets 7.1 instead of master

TASK: Replace deprecated guzzle functions with static methods

---

Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php

If you run `removeUndefinedProperties` of the `./flow node:repair` command not all undefined properties get removed.
Currently the affected nodes get indexed by the node identifier. But this identifier is the same for all dimensions. So the list of nodes reflects all dimensions, but the actual removal just run on ONE node of any dimension. So you have to run the command n-times (n = number of dimensions).
**Expected behavior**
Remove all undefined properties in all dimensions
**Actual behavior**
Removes just undefinded properties of a node in one dimension
**How to test**
* Set up with more than one dimension
* Create a node with properties in more than one dimension
* Remove a property definition of that node
* run `./flow node:repair`
* run again to see, if it had removed all properties …

Collect affected nodes for each dimension to remove undefined properties

---

Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenuItems.fusion

When rendering the Breadcrumb menu in a Content node, the Content node itself is no longer added to the menu.
This is done by replacing `q(node).add(...)` with `q(documentNode).add(...)`

BUGFIX: Only document Nodes should appear in Breadcrumb

---

Neos.ContentRepository/Classes/Domain/Service/Context.php

This fixes the following error on master:
```
Argument 1 passed to Neos\Flow\Annotations\IgnoreValidation::__construct() must be of the type string, null given, called in /var/www/html/Packages/Libraries/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 971
Type: TypeError
File:
Packages/Framework/Neos.Flow/Classes/Annotations/IgnoreValidation.php
Line: 41
Type: Neos\Flow\Core\Booting\Exception\SubProcessException
Code: 1355480641
File: Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
Line: 712
```
Since the variable with the annotation is populated in the constructor with a fresh instance the need of this annotation is at least questionable.

BUGFIX: Remove broken @Flow\IgnoreValidation from ContentRepository context

---

.composer.json
composer.json

Some constraints of the 7.1 branch seem to have been accidentally upmerged to master. 
This change reset those to dev-master again.

BUGFIX: Reset accidentally upmerged branch version constraints

---

Neos.Fusion/Classes/Package.php

The NodeTypes folder was just added to have a hierarchical structure for the nodeTypes. Since nodetypes are often tightly coupled to the integration it makes sense to put the fusion prototypes that implement the rendering of for the prototype there aswell. Especially when presentation and integration are seperated.
This can already be done via `include: ../../../NodeTypes/**/*.fusion` in the Root.fusion. However changes to fusion files in the `NodeTypes` folder are not detected yet.
To support this pattern this change adds the folder `NodeTypes` to the folders that are monitored for fusion file changes.
See: https://github.com/neos/neos-development-collection/issues/3000

TASK: Add  `NodeTypes` folder to fusion file monitoring for cache invalidation

---

Neos.Neos/Classes/Service/PublishingService.php

Previously autocreated childnodes like ContentCollections were ignored
when discarding selected nodes via the workspace module.
When deleting a node and discarding the change the auto created children
would then stay deleted in the database and the backend would show no
content/errors.
The behaviour is now the same as for publishing nodes and the direct
child nodes are included in the discard if the node has auto-created
child nodes or is a document.
Fixes: #3274, #3387
See: #3275
**Checklist**

BUGFIX: Don’t skip childnodes when discarding nodes

---

Neos.Neos/Tests/Functional/Controller/Backend/BackendControllerSecurityTest.php

The BackendControllerSecurityTest did not assert the login actually
works in the test indexActionIsGrantedForAdministrator().

BUGFIX: Make test actually test what is says it tests

---

.github/workflows/build.yml

The command `FLOW_CONTEXT=Testing/Behat ./flow behat:setup && ./flow doctrine:create && ./flow doctrine:migrationversion --add --version all` is broken, because the context is only active for the `behat:setup` call, not the `doctrine:…` calls later.

BUGFIX: Use Testing/Behat for DB setup in Behat steps

---

Neos.Media/Classes/Domain/Service/ThumbnailService.php

Packages like MOC.ImageOptimizer that are necessary for achieving optimal performance currently have to use unstable apis (aspects) to get access to freshly created image-crops. The existing signals ThumbnailPersisted and ThumbnailCreated do not cover this usecase yet.
This change introduces the ThumbnailRefreshed signal to the Neos.Media package that can be used by package authors to optimize the rendered thumbnails further before they are presented to the user.

FEATURE: Introduce ThumbnailRefreshed signal to the Neos.Media package

---

Neos.Neos/Classes/Domain/Service/UserService.php

Since Neos 5.2.0 the use of frontend logins is broken. When logging in, an exception is thrown. The exact exception varies, but can be traced to `Unexpected user type "". An account with the identifier "…" exists, but the corresponding party is not a Neos User.` eventually.
This change fixes that by not using `getUser()` directly, but doing more checks and eventually just returning `null` if no Neos user can be found for the authenticated tokens.
Related: #2577
Fixes: #3088

BUGFIX: Only use accounts that have Neos users attached

---

Neos.Fusion/Resources/Private/Fusion/Root.fusion

The Neos.Fusion:Memo object was introduced with Neos 7.2 but the include somehow slipped through.
This change adds the missing include to the Root.fusion
Resolves: #3510

BUGFIX: Include Memo fusion

---

Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html

Asset sources have a method `isReadOnly()` to tell whether they are read-only or not. A read-only asset source does not allow their content to be changed.
With this change, that read-only state is no longer coupled to the display of asset collections and tags in the media browser. Asset sources thus are free to implement a "connection" to asset collections and tags in any reasonable way.
Fixes #3480

FEATURE: Show asset collections and tag for read-only asset sources

---

Neos.Neos/Classes/Controller/Module/Administration/UsersController.php

When you delete an electronic address we throw a flash message that the address has been delete for the given user. We had the issue that the PersonName object could not be transformed to a string that is needed for the flash message.
**What I did**
Use the full name of the PersonName object instead of the direct PersonName object for the flash message.
1. Open the user module
2. Edit a user
3. Optionally create a electronic address
4. Delete a electronic address
5. check the flash message 
**Checklist**
Fixes: #3435

BUGFIX: Prevent exception when deleting an electronic address

---

Neos.ContentRepository/Classes/Configuration/NodeTypesLoader.php
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/NodeTypes.SomeSuffix.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/Testing/NodeTypes.SomeSuffix.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/Testing/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/Testing/SomeOtherSubContext/NodeTypes.SomeSuffix.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/Testing/SomeOtherSubContext/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Configuration/Testing/SomeSubContext/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/NodeTypes/Bar.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/NodeTypes/Foo.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Neos.Seo/Configuration/NodeTypes.Mixin.TitleTag.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/Configuration/NodeTypes.SomeSuffix.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/Configuration/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/Configuration/SomeOtherSubContext/NodeTypes.SomeSuffix.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/Configuration/SomeOtherSubContext/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/Configuration/SomeSubContext/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/NodeTypes/Bar.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package1/NodeTypes/Foo.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package2/Configuration/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package2/Configuration/SomeOtherSubContext/NodeTypes.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Package2/NodeTypes/Foo.yaml
Neos.ContentRepository/Tests/Unit/Configuration/Fixture/Packages/Some.Package/NodeTypes/NodeTypes.Override.Seo.yaml
Neos.ContentRepository/Tests/Unit/Configuration/NodeTypesLoaderTest.php

**What I did**
The NodeTypesLoader introduced in FLOW 7.2 does not allow to override NodeTypes in the newly introduced `NodeTypes` directory. This is because, the `Configuration` directory is loaded in a separate loop after the `NodeTypes` directory.  
For example, the NodeType `Neos.Neos:ContentCollection` cannot be overriden in the `NodeTypes` directory, because it is loaded in `Neos.Neos/Configuration`. This means, everything defined in the `NodeTypes` directory of a custom package is overriden by the `Neos.Neos/Configuration` NodeType.
This PR uses a single `$packages` loop to first load from the `NodeTypes` directory, directly followed by the `Configuration` for a given `$package`.
Try to modify `Neos.Neos:ContentCollection` like this
``` …
```

BUGFIX: NodeTypesLoader respect package overrides

---

Neos.Neos/Documentation/References/FlowQueryOperationReference.rst

With the merge of https://github.com/neos/flow-development-collection/pull/2600 new case-insensitive operators are introduced and also documented
Fixes: #3511

TASK: Document new case-insensitve operators

---

Neos.Neos/Classes/NodeTypePostprocessor/DefaultPropertyEditorPostprocessor.php
Neos.Neos/Tests/Unit/NodeTypePostprocessor/DefaultPropertyEditorPostprocessorTest.php

Adjusts the `DefaultPropertyEditorPostprocessor` such that it respects the configured
property editor defaults not only for node _properties_ but for _creationDialog elements_ too.
This also fixes the default behavior for properties slightly by making sure that editor defaults
from `Neos.Neos.userInterface.inspector.editors` are applied even if no corresponding `Neos.Neos.userInterface.inspector.dataTypes` exists
Fixes: #3471

BUGFIX: apply editor defaults in creation dialog elements

---

Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
Neos.Neos/Resources/Private/Templates/Module/Administration/Users/New.html

**What I did**
Extended the array that is used in the view. So that we have the provider identifier and the label.
So we use a structure like
`
[
{
identifier: 'Neos.Neos:Backend'
label: 'Neos Backend label'
},
{
identifier: 'Neos.Neos:FooName'
label: 'Neos Backend Foo'
}
]
`
1. Configure a second authentication provider
2. go to the user management in the backend
3. create a new user
4. check the drop down
Fixes: #3488

BUGFIX: Render labels of authentication providers

---

Neos.Media/Classes/Domain/Model/ThumbnailConfiguration.php
Neos.Media/Classes/Domain/Service/ImageService.php

As with `webp` the format has to be supported by the library behind imagine aswell.
Currently `avif` is only supported by imagick > 7.0.10-25 and libheif > 1.7.0.
Resolves: #3132

FEATURE: Allow the format `avif` for thumbnail generation.

---

Neos.ContentRepository/Classes/Domain/Service/Context.php

Reverts neos/neos-development-collection#3411 since this introduced a regression.
The new fix has been implemented in Flow: https://github.com/neos/flow-development-collection/pull/2632
Fixes: #3515

Revert "BUGFIX: Remove broken @Flow\IgnoreValidation from ContentRepository context"

---

Neos.CliSetup/Classes/Command/SetupCommandController.php
Neos.CliSetup/Classes/Command/WelcomeCommandController.php
Neos.CliSetup/Classes/Exception.php
Neos.CliSetup/Classes/Infrastructure/Database/DatabaseConnectionService.php
Neos.CliSetup/Classes/Infrastructure/ImageHandler/ImageHandlerService.php
Neos.CliSetup/Configuration/Settings.yaml
Neos.CliSetup/LICENSE
Neos.CliSetup/Readme.rst
Neos.CliSetup/composer.json
composer.json

The package contains the commands
`./flow welcome` - Show a welcome message with informations how to setup neos via cli. This should be used later as post-create-project-cmd for the neos-distributions.
`./flow setup:database` - Configure the database connection interactively
`./flow setup:imagehandler` - Configure the image handling interactively
The solution is implemented as a separate package in the development collection for the following reasons:
- The browser based setup tools `Neos.Setup` + `Neos.NeosSetup` may get deprecated one day
- The commands are not added to an existing package as they should be uninstallable
- The development should happen in the dev-collection to be able to evolve with Neos
Resolves: #3506
Todos after merging:

FEATURE: Add Neos.CliSetup package

---

Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php

When there are disabled `superTypes` in NodeTypes, an exception is thrown.
This happens when a superType is disabled in a NodeType and no specific editor is defined.
```yaml
'My.Package:FormElement':
superTypes:
'Neos.Form.Builder:FormElement': true
'Neos.Form.Builder:LabelMixin': false
properties:
property:
type: string
ui:
label: i18n
```
This issue was introduced in neos/neos-development-collection#3395
Closes neos/neos-development-collection#3520

BUGFIX: prevent failure for disabled superTypes

---

Neos.Neos/Configuration/NodeTypes.Shortcut.yaml

Currently the default is firstChidNode which leads to error
when adding a new shortcut, as there will never be a
child node in this case while targeting the parent
in this case
Related: #3256

!!! BUGFIX: Set the default for new shortcut nodes to "parent"

---

Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenu.fusion
Neos.Neos/Resources/Private/Fusion/Prototypes/BreadcrumbMenuItems.fusion

Fix #3407
* `Neos.Neos:BreadcrumbMenu` was using `node`, this is fixed and use `documentNode` now
* `Neos.Neos:BreadcrumbMenuItems ` returned the nodes in the wrong order
* On both prototypes the current node is now always rendered, even when it is hidden in index

!!! BUGFIX: Always show current node in breadcrumb

---

Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php

The indentation of heredoc and nowdoc was added in PHP 7.3 which is the minimal supported version of php.
This change adjusts the tests of the afx service to use the indented syntax to improve readability a lot.
https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

TASK: Use indented heredoc syntax for AFX tests

---

Neos.Media/Classes/Domain/Model/Tag.php

Update the Doctrine Mapping of the Tag model, for `./flow doctrine:validate` to not fail
Fixes: #3264

TASK: Add missing inversedBy Doctrine mapping

---

Neos.Neos/Classes/Domain/Service/NodeSearchService.php

I just stumbled upon an issue, which was partly solved by [this PR](https://github.com/neos/neos-development-collection/pull/3165).
In short, the parameter `$term` is modified by the `foreach` loop and thus another value than the original parameter is forwarded to `$this->nodeDataRepository->findByProperties($term`. Thus the `findByProperties` from `NodeSearchService` doesn't work anymore as it was long time ago.
I've also considered the notes from @kdambekalns, except from
>     * pass `$searchTerm` (not `$term`) to the `NodeDataRepository` to fix the actual bug
Instead of using `$searchTerm` I introduced a separate variable.The idea was to revert the overwritten `$term` and keep the original intention of the method as it was before and the search for an identifier is just an additional …

BUGFIX: Make NodeSearchService use new variable to search for identifier patterns

---

.github/workflows/build.yml

Sometimes the build process doesn't start on a new pull request. With this change, we could trigger it manually and don't have to close and reopen the pull request

BUGFIX: Add possibility to trigger build manually

---

Neos.Fusion/Classes/Core/Parser.php
Neos.Fusion/Classes/Core/ParserInterface.php

related #3498
Add deprecation notice for the namespace to the parser and corresponding interface.
```
namespace: Foo = Acme.Demo
video = Foo:YouTube
```
you will need to fully declare the namespace (add `Neos.Fusion:` infront)
```
content = DataStructure
```
or
```
root = Page
```

!!! TASK: Fusion Parser deprecate namespace alias

---

Neos.Fusion/Classes/Core/ExceptionHandlers/AbsorbingHandler.php

Without this, it's a lot harder to debug absorbed exceptions.

TASK: Create trace for absorbed exception

---

Neos.Neos/Classes/Controller/Frontend/NodeController.php

When using Neos 7.2+ with the Flowpack.Neos.FrontendLogin package trying to login with a frontend leads to a CSRF protection error:
`21-12-12 10:29:27 6580       DEBUG                          CSRF: token was empty but a valid token is required for Neos\Neos\Controller\Frontend\NodeController::showAction()`
See neos/flow-development-collection#2612 – that discusses a change from Neos 7.1 to 7.2 where the tag changes in combination with a comment.
This PR allows to use the FrontendLogin again.

BUGFIX: move comment on @Flow\SkipCsrfProtection tag

---

Neos.Media.Browser/Classes/Controller/AssetController.php
Neos.Media/Classes/Domain/Model/AssetSource/Neos/NeosAssetProxyRepository.php
Neos.Media/Classes/Domain/Model/AssetSource/SupportsTaggingInterface.php

**What I did**
Currently classes that implement the SupportsTaggingInterface can only count untagged Assets. 
When using the interface with external Assets, this leads to the MediaBrowser displaying the count of Neos Media Assets for the external Source, not the count of the Assets matching that Tag in the external source. 
I extended the SupportsTaggingInterface so that Classes using this interface can change the count of the Tags that are displayed in the Media Browser, just like they can change the count of untagged Assets. 
I added the countByTag method to the SupportsTaggingInterface and implemented it in the Neos MediaBrowser where the count happens. 
Since I am new to Neos I was not sure if countByTags should also pass the active AssetCollection, but I decided …

!!! FEATURE: Neos.Media: Extend SupportsTaggingInterface by countByTag

---

Neos.Fusion.Afx/Classes/Service/AfxService.php
Neos.Fusion.Afx/README.md
Neos.Fusion.Afx/Tests/Functional/AfxServiceTest.php

Neos.Fusion:Array and Neos.Fusion:RawArray are deprected for a while now but are still used in AFX. This change makes afx use:
- Neos.Fusion:Join instead of Neos.Fusion:Array
- Neos.Fusion:DataStructure instead of Neos.Fusion:RawArray
Resolves: #3558

TASK: Replace deprecated fusion protoypes from transpiled AFX code

---

Neos.Fusion/Classes/Core/Runtime.php
Neos.Fusion/Tests/Functional/FusionObjects/ExpressionsTest.php
Neos.Fusion/Tests/Unit/Core/RuntimeTest.php

fixes: #3548
fixes: #3556
added tests, that verify that the runtime context stack is working correctly.

BUGFIX: Fusion Runtime when no context is set, preparing it for Eel will fail

---

Neos.Fusion/Classes/FusionObjects/MatchImplementation.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Match.fusion
Neos.Fusion/Tests/Functional/FusionObjects/MatchTest.php

**What I did**
I removed the return type declaration of the `Neos\Fusion\FusionObjects\MatchImplementation::getDefault()` method. This allows developers to return other types then string when using `Neos.Fusion:Match`. 
Create a new fusion value and use a value that is not a string, for example:
```
prototype(Vendor.Prefix:Component) {
value = Neos.Fusion:Match {
@subject = ${q(node).property('someProp')}
valueA = Neos.Fusion:DataStructure {
key = 'valueA'
}
@default = Neos.Fusion:DataStructure {
key = 'valueB'
}
}
}
```
**Checklist**

TASK: Allow Neos.Fusion:Match to return a default value with a type other than string

---

Neos.Neos/Resources/Private/Templates/Error/NeosBackendMessage.html

**What I did**
Fix error the circumstances leading to:
```
The partial files "resource://Neos.Neos/Private/Templates/FusionObjects/NeosBackendHeaderData.html", "resource://Neos.Neos/Private/Templates/FusionObjects/NeosBackendHeaderData" could not be loaded.
```
This error message is hiding the actual error message I need to see.
Remove usage of partials that had been deleted already in 2019 in 86088dc 
Go to various page in backend with a certain content Node Type on it. Go to this Node Type's yaml and change its Name from, e.g. `Vendor.Site:Box` to `Vendor.Site:Boxers`. Reload the backend and find the partial error above occur. After applying this bugfix, you'll find the real error message, `An exception was thrown while Neos tried to render your …

BUGFIX: backend message partials not found

---

Neos.Media/Classes/Domain/Model/ThumbnailGenerator/DocumentThumbnailGenerator.php

Since there is no use of the ImagineService within the DocumentThumbnailGenerator, the availability of the native PHP extension for Imagick should be checked instead. This allows the use of the DocumentThumbnailGenerator with Imagick and the use of other Imagine based thumbnail generators using GDlib, for example.

BUGFIX: Check for the native PHP extension instead of the ImagineService, since ImageService is not used further in this generator.

---

.github/workflows/build.yml
Neos.ContentRepository/Classes/Domain/ContentSubgraph/NodePath.php
Neos.ContentRepository/Classes/Domain/NodeAggregate/NodeAggregateIdentifier.php
Neos.ContentRepository/Classes/Domain/NodeType/NodeTypeName.php
Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php
Neos.Diff/Classes/SequenceMatcher.php
Neos.Neos/Classes/Domain/Service/SiteExportService.php
Neos.Neos/Classes/ViewHelpers/Backend/IfModuleAccessibleViewHelper.php

This adds additional type hints where required in PHP 8.1 ~while maintaining support for 7.4~.
These are only the adjustments required fir the ESCR test suite, more are to follow

Make adjustments to support PHP8.1's stricter type system

---

Neos.Diff/Classes/SequenceMatcher.php
Neos.Neos/Classes/Domain/Service/SiteExportService.php
Neos.Neos/Classes/ViewHelpers/Backend/IfModuleAccessibleViewHelper.php

This fixes the following deprecation warnings by removing optional arguments that were placed before non optional ones.
While this changes the api it should not break any code as the optional arguments could not be used that way anyways.
```
PHP Deprecated:  Optional parameter $junkCallback declared before required parameter $options is implicitly treated as a required parameter in /var/www/html/Packages/Neos/Neos.Diff/Classes/SequenceMatcher.php on line 83
PHP Deprecated:  Optional parameter $arguments declared before required parameter $renderingContext is implicitly treated as a required parameter in /var/www/html/Packages/Neos/Neos.Neos/Classes/ViewHelpers/Backend/IfModuleAccessibleViewHelper.php on line 66
PHP Deprecated:  Optional parameter $tidy declared before required parameter …
```

TASK: Address PHP 8 deprecation warnings

---

Neos.Media/Classes/Domain/Repository/ThumbnailRepository.php
Neos.Media/Classes/Domain/Service/ThumbnailService.php

This uses a direct SQL INSERT via DBAL to store Thumbnails. Doing this
avoid unique constraint exceptions that otherwise occur when multiple
concurrent requests trigger Thumbnail creation.
Fixes #3479

BUGFIX: Persist Thumbnail using DBAL to avoid unique constraint errors

---

Neos.Neos/Configuration/Settings.yaml

resolves: #3644
bound to: https://github.com/neos/flow-development-collection/pull/2743
Concerning:
`Neos.Flow.error.exceptionHandler.renderingGroups.{exampleGroup}.options`
`templatePathAndFilename`, `layoutRootPath`, and `format` are legacy and should be removed: https://github.com/neos/flow-development-collection/issues/2742
migrate them to the `viewOptions`.
the difficulty is that 'Neos.Flow' will also define for the 'renderingGroups' `notFoundExceptions` and `databaseConnectionExceptions`  view specific 'viewOptions' that will be merged with the 'Neos.Neos' config and
thus an error will occur if another view is used and doesnt support a merged option - e.g. for the `notFoundExceptions` 'Neos.Neos' swaps the viewClassName to 'FusionExceptionView' which does not support the option 'tem …

Remove @deprecated error renderingGroups options.

---

Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion

resolves: #3642
```diff
Neos.Neos:ContentCollectionRenderer {
-    collection = ${[]}
+    items = ${[]}
}
```
With 5.3 https://github.com/neos/neos-development-collection/pull/2772
`Neos.Neos:ContentCollectionRenderer` was changed from `Neos.Fusion:Collection` to `Neos.Fusion:Loop`
for backwards compatibility, the prop `collection` was also allowed to be set as alias for `items`
but the `collection` prop alias doenst fully work as 1:1 replacement fx. it doesnt work if it was set to an empty array:
https://github.com/neos/neos-development-collection/issues/3114
this pr removes this this legacy fallback with 8.0

!!! TASK: Fusion ContentCollectionRenderer remove legacy 'collection' prop

---

Neos.Neos/Resources/Private/Fusion/Prototypes/ConvertNodeUris.fusion

This has been replaced by `ConvertUris` since 1.1

!!! TASK: Remove (long) deprecated ConvertNodeUris

---

Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion

this makes it easier for us to maintain those lists. As when adding or removing prototypes this can be forgotten.

TASK: Fusion use glob includes.

---

Neos.Fusion/Classes/Core/Cache/ContentCache.php
Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Neos.Neos/Classes/Routing/Cache/RouteCacheFlusher.php
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Tests/Unit/Fusion/Cache/ContentCacheFlusherTest.php

**What I did**
Instead of calling the cache backend for each tag to flush
individually, the list of tags is passed to the backend with
the newly introduced `flushByTags` method in
https://github.com/neos/flow-development-collection/pull/2718.
This allows each type of backend to optimise the flushing
of all tags, which can lead to huge performance improvements.
Especially when content is published to the live workspace
which leads to large numbers of cache tags that will be flushed.
Also the messages stored with individual content cache tags
take up a lot of unnecessary memory in production
context and not are even used there.
With this change the behaviour can be enabled via
the setting `Neos.Neos.fusion.contentCacheDebugMode`.
Resolves: #3640
The `ContentCacheFlusher` …

FEATURE: Pass tags to be flushed to content cache backend

---

Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Neos.Neos/Migrations/Code/Version20220318111600.php
Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php
Neos.Neos/Tests/Unit/Fusion/Cache/ContentCacheFlusherTest.php

**What I did**
In Neos 4.1 new Eel helpers were introduced to generate content cache tags in Fusion. Those make sure that the cache tags provided by the integrator are valid. 
Until Neos 4.0 they needed to be written manually as string which was error prone. 
But to support old cache tags that were lacking the workspace context the `ContentCacheFlusher` still cleared them.
This change removes that support. So this is breaking and projects need to be adjusted when upgrading and still using those old cache tags.
The advantage of removing them is that the number of cache tags to be flushed during publishing is lower. TODO: Add number.
This change requires #3631 to be merged first.
Removed the legacy cache tag generation.
The change also include a new code migration version …

!!! FEATURE: Remove legacy cache tag support

---

Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php

**What I did**
The generation of cache tags is quite slow for a large number of published changes as many operations
are done for each involved node and workspace.
I improved the performance by skipping repeated operations on the same node with the same context
and by caching the result of nodetype related calculations.
* Reuse calculated list of implemented nodetypes for each node changed by introducing a variable to store each calculation
* Stop traversal through a nodes parents if one of the parents was already traversed before to generate `DescendantOf` cache tags.
* Tests still run fine

FEATURE: Optimise cache tag generation before flushing content cache after publishing

---

Neos.Neos/Documentation/References/NodeTypeDefinition.rst

**What I did**
The neos-ui introduces a new NodeType setting called `previewIcon` and `previewIconSize`.
As the neos-ui does not contain documentation, the PR will add the new options here.
The change also adjust the icon description, as we are now able to use custom SVG icons.
Related PR: https://github.com/neos/neos-ui/pull/3042

TASK: Add documentation for previewIcon

---

Neos.Fusion/Classes/Core/Cache/FusionParserCache.php
Neos.Fusion/Classes/Core/Cache/ParserCache.php
Neos.Fusion/Classes/Core/Parser.php
Neos.Fusion/Classes/Package.php
Neos.Fusion/Configuration/Caches.yaml
Neos.Fusion/Configuration/Development/Settings.yaml
Neos.Fusion/Configuration/Objects.yaml
Neos.Fusion/Configuration/Production/Settings.yaml
Neos.Fusion/Configuration/Settings.yaml
Neos.Fusion/Configuration/Testing/Settings.yaml
Neos.Fusion/Resources/Private/Schema/Settings.Neos.Fusion.schema.yaml
Neos.Fusion/Tests/Unit/Core/Parser/ParserExceptionTest.php
Neos.Fusion/Tests/Unit/Core/Parser/ParserIncludeTest.php
Neos.Fusion/Tests/Unit/Core/Parser/ParserTest.php
Neos.Fusion/Tests/Unit/Core/ParserTest.php

Resolves: #3661
The New Fusion Parser now uses a `Neos_Fusion_ParsePartials` cache to store the generated FileAst _*_ for each Fusion File. Those File partials are flushed via file monitor when the source Fusion file was changed.
The generated merged array Fusion tree for a Fusion DSL is also cached seperately in this cache.
With this cache layer in place, only changed files are reparsed which **speeds up Fusion parsing** in Development mode by **factor of 2 to 8** depending on context. _**_
The ParsePartials cache is disabled in Production mode as this one already uses the ObjectTreeCache.
since we cache mostly AstNode objects its recommended to have the php extension `igbinary` installed.
the cache can be turned of by disabling: `Neos.Fusion.enableParsePartialsCache`
_*_ there are now …

FEATURE: Add ParsePartials cache to the fusion parser

---

Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
Neos.ContentRepository/Classes/Domain/Service/ImportExport/NodeExportService.php
Neos.Fusion/Classes/Core/Cache/ContentCache.php

The `Doctrine\ORM\Proxy\Proxy` is deprecated and extends the
`Doctrine\Persistence\Proxy`.

TASK: Avoid deprecated Doctrine ORM proxy

---

Neos.Fusion/Migrations/Code/Version20220326120900.php

Fusion Objects without namespace were located in Neos.Fusion namespace in the past.
The namespace support is dropped with Neos 8 and this migration migrates Object names that
made use of this to the fully qualified names.
Note: This converts the only the default namespace. If custom namespaces are used they 
are not touched but have to be removed manually. The new Fusion parser tell you that.
Relates: #3497
This is based on an older migration when we changed the default Namespace to Neos.Fusion with Neos 4.0
see: https://github.com/neos/neos-development-collection/blob/4.0/Neos.Fusion/Migrations/Code/Version20180211175500.php
Run the migration with some fusion code that  uses FusionObjects without the Neos.Fusion namespace
```
./flow core:migrate Neos.Demo --force …
```

TASK: Introduce migration to convert Fusion objects without namespace

---

composer.json

as is in the 7.3 branch already

TASK: Correct class loading for Neos Cli setup in master and restore alphabetical order

---

Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php
Neos.ContentRepository/Configuration/Caches.yaml
Neos.ContentRepository/Configuration/Objects.yaml
Neos.ContentRepository/Configuration/Production/Caches.yaml
Neos.ContentRepository/Tests/Unit/Domain/Service/NodeTypeManagerTest.php

The cache with its current implementation actually
hurts performance as it forces loading of all
nodetypes instead of lazy loading the required ones.
Also the cached data is never used.
In development context all nodetypes are reloaded
on every request accessing the nodetypemanager.
Therefore its better to remove the cache until there
is a proper implementation.
Resolves: #3681

BUGFIX: Remove unused nodetype configuration cache

---

Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/NestedOverwritesAndProcessors.fusion
Neos.Fusion/Tests/Functional/FusionObjects/NestedOverwritesAndProcessorsTest.php

currently, when testing this locally:
```
NestedOverwritesAndProcessorsTest::applyingProcessorToNonExistingValueWorks
```
one gets a:
```
Array to string conversion
```
this is because the test is lying in our faces.
the fixture `NestedOverwritesAndProcessors.fusion` is telling us, that `Neos.Fusion:Tag` uses as attributes `Neos.Fusion:Attributes`.
but it's not!
`Neos.Fusion:Tag` uses `Neos.Fusion:DataStructure` because the fixtures are all merged together and not namespaced. So someplace this was changed to a DataStructure, and now we have a `Tag` with a `DataStructure`.
This *was* fine until we changed the behaviour of the `DataStructure` with: https://github.com/neos/neos-development-collection/pull/3645
so when a `DataStructure`
previously didn't make nested DataStructures here:
``` …
```

TASK: Fix Fusion Test And Make Them Test What They Say

---

Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php

In removeBrokenEntityReferences the number of placeholders did not
match the number of variables given.

BUGFIX: Add missing placeholder to sprintf call

---

Neos.Neos/Configuration/Policy.yaml

**What I did**
I streamlined the role labels and description and ensured gender neutrality. The descriptions are now a bit shorted, using less space in the Neos backend.

TASK: Streamline role description, ensure gender neutrality

---

Neos.Fusion/Classes/Core/Cache/ParserCache.php
Neos.Fusion/Classes/Core/Cache/ParserCacheFlusher.php
Neos.Fusion/Classes/Core/Cache/ParserCacheIdentifierTrait.php
Neos.Fusion/Classes/Package.php
Neos.Fusion/Configuration/Objects.yaml

This fixes a race condition described in #3685. When PHP code was changed at the same time as Fusion code, the parse partial cache tried to flush before the cache was injected which lead to a PHP error.
The change extracts the logic for flushing the partial cache into a very simple object with the generating of identifiers kept as a shared trait between `ParserCacheFlusher` and `ParserCache`.
resolves: https://github.com/neos/neos-development-collection/issues/3685
related: https://github.com/neos/neos-development-collection/pull/3659
replaces: https://github.com/neos/neos-development-collection/pull/3688

BUGFIX: Separate fusion parserCache and parserCacheFlusher 

---

Neos.Fusion/Classes/FusionObjects/AugmenterImplementation.php

Originally the fusion augmenter only passed non falsy values to the HtmlAugmenter.
This was changed by using the evaluateNestedProperties method (inherited from AbstractArrayFusionObject) instead ob the previously used sortNestedFusionKeys (inherited from JoinImplementation) plus custom loop.
See: https://github.com/neos/neos-development-collection/pull/3645/files#diff-40c9edd185fdb14a7c3b4b89b78f32b4fa58eba26d5e750b236ce730f45342b6
This is fixed by applying array_filter that will filter all falsy values (null | false).

BUGFIX: Apply array_filter to augmenter values to prevent rendering attributes for null values

---

Neos.Neos/Resources/Private/Styles/Error.scss
Neos.Neos/Resources/Private/Templates/Error/Index.html
Neos.Neos/Resources/Private/Templates/FusionObjects/FallbackNode.html
Neos.Neos/Resources/Public/Styles/Error.css

When you see this error message style (`resource://Neos.Neos/Private/Templates/Error/Index.html`), an icon is missing.  
Before:  
After:  
**Checklist**

TASK: Add missing exclamation-triangle icon to error message

---

Neos.ContentRepository/composer.json
composer.json

This avoids errors caused by calls to the deprecated
`AbstractClassMetadataFactory::getCacheDriver()` method.

BUGFIX: Raise gedmo/doctrine-extensions dependency to ^3.5

---

Neos.Fusion/Classes/FusionObjects/CanRenderImplementation.php
Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion

The Neos backend will fallback to the RawContent mode as last resort if no other document rendering is possible. In the frontend a last try to render the via the `documentType` is done to create at least helpful error message that encourages good practices.
To implement this the `path` option is added to the `Neos.Fusion:CanRender` prototype to check wether the `/page` is available.
The whole feature is a building block to eventually allow content first workflows where no fusion rendering gas to be defined to edit content.
**Checklist**

FEATURE: Display the rawContent-mode in the backend when neither documentType nor `/page` can be rendered

---

Neos.Neos/Documentation/References/NeosFusionReference.rst

- spaces and tabs were mixed up
- came up while working on the neos fusion plugin for vscode
No code changes.

TASK: Equalize indentation of Neos.Fusion:Match example in docs

---

Neos.Neos/Documentation/References/NodeMigrations.rst

In Neos 7.0 we introduced the  `PropertyValue` filter for node migrations. With this change, we extend the documentation as well.
**Review instructions**
Please proofread the documentation change.
**Checklist**

BUGFIX: Adds missing documentation

---

.github/workflows/build.yml
.github/workflows/postgresql-versions.yml

This change
- updates the MariaDB version used for testing from 10.2 to 10.6. The former reaches EOL in May 2022 but 10.6 is the current LTS version supported until July 2026
- updates the PostgreSQL version used for testing from 9.5 (reached EOL in February 2021) to 10.x, the oldest still supported release
- adds a nighty test against all supported PostgreSQL versions (10.x to 14.x)

TASK: Run checks against current database versions

---

Neos.Fusion/Classes/FusionObjects/AbstractArrayFusionObject.php
Neos.Fusion/Classes/FusionObjects/CaseImplementation.php
Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php
Neos.Fusion/Classes/FusionObjects/DataStructureImplementation.php
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Fusion/Tests/Unit/FusionObjects/CaseImplementationTest.php
Neos.Fusion/Tests/Unit/FusionObjects/DataStructureImplementationTest.php
Neos.Fusion/Tests/Unit/FusionObjects/JoinImplementationTest.php

The new meta property `@sortProperties` can now be used to define
if properties should adhere to the `@sorting` meta and general
order of definition or if that is irrelevant.
Sorting itself is time consuming, and while that does not matter
for a single sort, a bigger site might have so many fusion objects
to render that the sorting can have massive influence on the render
performance. Therefore it's advisable to disable it whenever possible.
Specifically `Neos.Fusion:Component` as well as attributes in
`Neos.Fusion:Tag` are now unsorted. Also http headers are unsorted.
Fixes: #3792

FEATURE: Implement choice to sort properties for array objects

---

Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion

https://neos-project.slack.com/archives/C050C8FEK/p1657807863902929
For example when using Fusion in an ajax request, with cache enabled - but no documentNode provided as context, then the calculation of the GlobalCacheIdentifiers fails due to the Eel helper beeing incorrectly used.

BUGFIX: Fusion Array.keys() on null if documentNode doesnt exist in GlobalCacheIdentifiers

---

Neos.Fusion/Classes/FusionObjects/ActionUriImplementation.php
Neos.Fusion/Resources/Private/Fusion/Root.fusion
Neos.Fusion/Tests/Functional/FusionObjects/ActionUriTest.php
Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ActionUri.fusion
Neos.Neos/Documentation/References/NeosFusionReference.rst

The name  `Neos.Fusion:UriBuilder` stands out from other fusion prototypes because it describes what the prototype does
instead of what will be the result. This contradicts the declarative nature of fusion. In addition it is not possible render links from a subrequests to other main-requests without manipulating the controllerContext. A common case for that is fusion-backend modules that want to render links to the content or other modules.
This change adds the prototype `Neos.Fusion:ActionUri` as a 1:1 replacement that implements the same api but allows to configure the `request` the uri is to be built from. This allows to create links from subrequests into other contexts.
`Neos.Fusion:ActionUri`:
- `request`: (ActionRequest, defaults to the the current ``request``) The action request …

FEATURE: Introduce `Neos.Fusion:ActionUri` as replacement for `Neos.Fusion:UriBuilder`

---

Neos.Neos/Resources/Private/Fusion/RawContentMode.fusion

Before Neos 5 it was only necessary to have a Fluid template and no Fusion prototype to work with nodes in Neos incl. the raw content mode.
As the default Fusion prototype generator was disabled in Neos 5 and later removed in Neos 7, even a Fluid template was not enough anymore and this broke the old behaviour.
Therefore a fallback renderer was added that will render a simple Fusion prototype which shows the elements label and editable properties and images. This way exceptions in the raw content mode due to missing prototypes should not happen anymore.
The whole raw content mode will then be later refactored as new feature in #376

BUGFIX: Add raw content fallback renderer to prevent rendering exceptions

---

Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php
Neos.Media/Classes/Domain/Service/ImageService.php

Applies the Imagine autorotate filter before doing image adjustments,
so images are consistently rotated from metadata also for crop
operations.
Fixes #3300
**Checklist**

BUGFIX: Apply autorotate before image adjustments

---

.github/workflows/build.yml
.github/workflows/postgresql-versions.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening
