neos/neos-development-collection

- .codeclimate.yml
Adds a codeclimate configuration excluding Migrations, Tests and
JavaScript libraries.
> [TASK] Create .codeclimate.yml

- .composer.json
Adds the template composer.json used to autogenerate
the joined composer.json for this joined repository.
Releases: master, 2.0, 1.2
> [TASK] Add composer manifest template

- .travis.yml
> [TASK] Add .travis.yml

- Readme.rst
> [TASK] Add Readme with Travis CI badge

- .travis.yml
> [TASK] Test multiple DBs in Travis CI

- .travis.yml
> [TASK] Use specific build matrix for less tests

- Readme.rst
> [TASK] Add Code Climate to Readme

- .travis.yml
> [TASK] Run only tests for Neos dev collection packages on Travis CI

- .codeclimate.yml
> [TASK] TYPO3.Media: Exclude 3rd party JS libraries from Code Climate

- TYPO3.Media/Readme.rst
- TYPO3.Neos.Kickstarter/Readme.rst
- TYPO3.Neos.NodeTypes/Readme.rst
- TYPO3.Neos/Readme.rst
- TYPO3.TYPO3CR/Readme.rst
- TYPO3.TypoScript/Readme.rst
This adds a Readme.rst to each package, so that the read-only subplit
repositories have a readme file for GitHub to show and for the users
to read.
> [TASK] Add Readme.rst files for individual packages

- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/PluginViewDefinition.php
> [BUGFIX] Make PluginView label translatable

- TYPO3.Neos/Classes/TYPO3/Neos/Service/PluginService.php
Combine plugin search query when getting all plugin nodes
for the master plugin selection in PluginView, which is not
optimal when having many plugin types.
Resolves: NEOS-1545
> [TASK] Combine plugin search query in PluginService

- .travis.yml
Additionally includes a couple of general improvements.
> [TASK] Enable Behat Travis tests

- .travis.yml
- TYPO3.Neos/Tests/Behavior/Features/Administration/SiteManagement/ListSites.feature
- TYPO3.Neos/Tests/Behavior/Features/BackendLogin.feature
- TYPO3.Neos/Tests/Behavior/Features/Content/InlineEditing.feature
- TYPO3.Neos/Tests/Behavior/Features/Content/PreviewMode.feature
Adds a ``@browser`` tag used to skip those since they require
Selenium and take very long to run.
> [TASK] Enable Behat Neos Behat tests for Travis

- TYPO3.Neos/Documentation/GettingStarted/FeatureList.rst
The text was shortened and updated to provide a starting point for technically advanced readers that want to get into neos. For the editing part references to the user guide were added.
Change-Id: I4e09f94ae8df84d9b132f5c5765c45d2684b41cb
Releases: master, 2.0
> [TASK] Update the feature list of the documentation

- TYPO3.Neos/Configuration/Settings.yaml
Adding Spanish, Khmer, Portuguese (Brazilian), Norwegian & Chinese Simplified
Related: NEOS-1486
> [TASK] Update list of available user interface languages

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php
- TYPO3.Neos/Resources/Private/Translations/en/Main.xlf
> [BUGFIX] Translate node type label in PluginView master plugin selection

- apigen.yml
This adds an apigen.yml file for use when generating API docs.
> [TASK] Add apigen.yml

- TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
Add the missing documentation for the positioning of child nodes in the structure tree.
Resolves: NEOS-1629
> [TASK] Add documentation for child node positioning.

- TYPO3.Neos/Documentation/CreatingASite/Security.rst
- TYPO3.Neos/Documentation/CreatingASite/index.rst
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Security/Authorization/Privilege/Node/PropertyAwareNodePrivilegeContext.php
This documents node privileges and their matchers, as well as how to restrict
access to backend modules.
> [TASK] Security documentation

- TYPO3.Neos/Documentation/CreatingASite/NodeTypes/DependingProperties.rst
- TYPO3.Neos/Documentation/References/PropertyEditorReference.rst
- TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/SelectBoxEditor.js
- TYPO3.Neos/Resources/Public/JavaScript/Shared/MapObject.js
- TYPO3.Neos/Resources/Public/JavaScript/Shared/Utility.js
This is a follow up to allow dependent SelectBoxes together with
the change that implements property listeners.
> [TASK] Allow SelectBoxEditor sending data to DataSource

- TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Index.html
The security fixes produced a merge that broke the index template of the
workspace management module.
> [BUGFIX] Fix broken Workspace module index template

- TYPO3.Neos/Classes/TYPO3/Neos/Routing/Aspects/RouteCacheAspect.php
> [BUGFIX] Fix code style issue in RouteCacheAspect

- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js
- TYPO3.Neos/Resources/Public/JavaScript/Shared/Configuration.js
Regression introduced with c8ee304082e4b5bea28beec33f1f7bd8f7730225
Resolves: NEOS-1722
> [BUGFIX] Loading content dimensions for dimensions selector

- TYPO3.Neos/Documentation/CreatingASite/RenderingCustomMarkup/Templating.rst
- TYPO3.Neos/Documentation/ExtendingNeos/CustomViewHelpers.rst
Was missing “ViewHelper\” part
> Fix AbstractViewHelper FQCN

- TYPO3.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php
This adjusts the test to test what it actually is saying it does.
> [TASK] Fix nodeTypesContainCorrectSuperTypes unit test

- TYPO3.Neos/Documentation/HowTos/CreatingContentElement.rst
Fix spelling mistake in the first paragraph
> [TASK] Fix spelling mistake in CreatingContentElement.rst

- TYPO3.Neos/Tests/Unit/Service/VieSchemaBuilderTest.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeType.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/NodeTypeManager.php
- TYPO3.TYPO3CR/Configuration/Caches.yaml
- TYPO3.TYPO3CR/Configuration/Objects.yaml
- TYPO3.TYPO3CR/Configuration/Production/Caches.yaml
- TYPO3.TYPO3CR/Tests/Unit/Domain/Service/NodeTypeManagerTest.php
Breaking if you rely on post processors to be applied on each request.
> [!!!][TASK] Cache fully build NodeType configurations in production

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php
- TYPO3.Neos/Configuration/Settings.yaml
- TYPO3.Neos/Documentation/HowTos/CustomLoginScreen.rst
- TYPO3.Neos/Resources/Private/Templates/Login/Index.html
This change add a new setting to include custom stylesheets in the Neos
backend login form with documentation.
> FEATURE: Add settings to customize login screen stylesheets

- TYPO3.Neos/Documentation/References/NodeMigrations.rst
- TYPO3.Neos/Documentation/References/index.rst
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Migration/Filters/NodeType.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Migration/Filters/Workspace.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Migration/Transformations/ChangePropertyValue.php
This adds documentation for node migrations (filters and transformations).
> TASK: Documentation for node migrations

- TYPO3.Media/Classes/TYPO3/Media/Domain/Model/ThumbnailGenerator/FontDocumentThumbnailGenerator.php
The ``FontDocumentThumbnailGenerator`` returned a fixed width/height image, this change fixes that bug and respects the width/height of the current Thumbnail.
NEOS-1165
> BUGFIX: FontDocumentThumbnailGenerator must respect thumbnail width/height

- TYPO3.Neos/Documentation/HowTos/RenderingMetaNavigation.rst
- TYPO3.Neos/Documentation/HowTos/SelectingPageTemplate.rst
source: https://discuss.neos.io/t/document-node-type-best-practices/242
The credit for this approach goes to Christopher Hlubek.
> [TASK] Add section about the ``DefaultPage`` prototype approach

- TYPO3.Neos/Documentation/HowTos/TranslatingContent.rst
> TASK: Update TranslatingContent.rst

- TYPO3.Neos/Documentation/HowTos/AddingSimpleContactForm.rst
> TASK: Update AddingSimpleContactForm.rst

- TYPO3.Neos/Resources/Private/Styles/Foundation/_forms.scss
- TYPO3.Neos/Resources/Private/Styles/TopBar/_PublishMenu.scss
- TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Edit.html
- TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/New.html
- TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosBackendEndpoints.html
- TYPO3.Neos/Resources/Private/Translations/en/Main.xlf
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/PublishMenu.html
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/PublishMenu.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/TargetWorkspaceSelector.js
- TYPO3.Neos/Resources/Public/Styles/Login.css
- TYPO3.Neos/Resources/Public/Styles/Neos.css
- Add review changes button to publish menu
- Styling improvements in workspaces new and edit forms
- Styling improvement to publish menu count badge
- Add missing jQuery dependency in TargetWorkspaceSelector
- Close target workspace selector when closing publish menu
> TASK: Workspaces UX improvements

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
NEOS-1740 #comment This PR is a follow up
NEOS-1742 #close
> BUGFIX: WorkspacesController uses slugified usernames

- TYPO3.Neos/Documentation/GettingStarted/FeatureList.rst
This fixes some spellings in the FeatureList
> TASK: Fix spelling mistakes in ``FeatureList`` documentation

- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/TargetWorkspaceController.js
If you switch the workspace the NodeTree will be reloaded.
NEOS-1753 #close
> TASK: Refresh NodeTree if Workspace is switched

- TYPO3.Neos/Documentation/CreatingASite/TypoScript/EelFlowQuery.rst
Added info about the request object in the EEL defaultContext
> TASK: EEL defaultContext contains request Object too

- TYPO3.Neos/Classes/TYPO3/Neos/Aspects/NodeTypeConfigurationEnrichmentAspect.php
This adds a safeguard and some type hints to the aspect.
> TASK: Tweak PolicyConfigurationEnrichmentAspect

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
- TYPO3.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html
Workspace review module will show changes for node properties of type DateTime.
NEOS-1771 #close
> TASK: Workspace review module respects datetime properties

- TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Runtime.php
This is a pure code refactoring not changing any behavior.
The code was split into smaller methods and slightly restructured.
No new features or behavioral changes were introduced.
> [TASK] Refactor TypoScript Runtime

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/NodesController.php
The calculation of missing node variants along the breadcrumb to
the site root is used for the translation "helper" in the Neos UI.
The old calculation depended on a lot of implicit knowledge about
nodes and paths, all this was refactored to use appropriate methods
available resulting in a more robust implementation that will never
return a value lower or equal 0.
> BUGFIX: Missing breadcrumb node variant calculation more robust

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/BackendController.php
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/MenuHelper.php
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php
- TYPO3.Neos/Configuration/Caches.yaml
- TYPO3.Neos/Configuration/Objects.yaml
- TYPO3.Neos/Configuration/Policy.yaml
- TYPO3.Neos/Configuration/Routes.Authentication.yaml
- TYPO3.Neos/Configuration/Routes.Backend.yaml
This eliminates the need for logging in repeatedly when switching between sites in a multi-site
setup.
NEOS-248 #close Fixes the issue
NEOS-240 #comment Solves part two of this issue
> FEATURE: Switch between sites without logging in again

- TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Runtime.php
- TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/ConditionsTest.php
- TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/Conditions.ts2
NEOS-1777 #close Fixes the issue
> BUGFIX: Consistently skip processors if ``@if`` evaluated to false

- TYPO3.TYPO3CR/Migrations/Postgresql/Version20160223103919.php
Drops the default value for pathhash and renames one index.
> TASK: Adjust some leftovers related to TYPO3CR PostgreSQL schema

- TYPO3.Media/Migrations/Mysql/Version20160223165602.php
- TYPO3.Neos/Migrations/Mysql/Version20150309215317.php
- TYPO3.Neos/Migrations/Mysql/Version20160212141523.php
- TYPO3.Neos/Migrations/Mysql/Version20160223165603.php
- TYPO3.Neos/Migrations/Postgresql/Version20150309212115.php
- TYPO3.Neos/Migrations/Postgresql/Version20160212141533.php
- TYPO3.TYPO3CR/Migrations/Mysql/Version20150309215316.php
- TYPO3.TYPO3CR/Migrations/Mysql/Version20160212141524.php
- TYPO3.TYPO3CR/Migrations/Mysql/Version20160223165604.php
- TYPO3.TYPO3CR/Migrations/Postgresql/Version20150309212114.php
- TYPO3.TYPO3CR/Migrations/Postgresql/Version20160212141534.php
- TYPO3.TYPO3CR/Migrations/Postgresql/Version20160223103919.php
This merges changes from 1.2 into 2.0 and follows up with some needed
adjustments.
> TASK: Migration adjustments

- TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
> TASK: Incorrect label id for users module widget action button title

- TYPO3.Neos/Documentation/CreatingASite/Security.rst
Documents the roles that are defined in Neos and how to extend them.
> TASK: Document predefined roles in Neos

- TYPO3.Neos/Resources/Private/Styles/Inspector/_Inspector.scss
- TYPO3.Neos/Resources/Private/Styles/Shared/_Select2.scss
- TYPO3.Neos/Resources/Private/Styles/Shared/_Sortable.scss
- TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferencesEditor.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/SelectBoxEditor.js
- TYPO3.Neos/Resources/Public/Library/sortable/Sortable.js
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Enables drag and drop sorting of selected elements in selector, references and assets list.
All select lists with multiple selections are made sortable.
NEOS-374 #resolve
NEOS-1521 #resolve
>  FEATURE: Sortable options in selector editors (select, references, asset list)

- TYPO3.Neos/Resources/Private/Templates/Backend/Module/Index.html
When using minified resources.
> BUGFIX: Missing styling in backend modules

- TYPO3.Neos/Documentation/CreatingASite/NodeTypes/TranslateNodeTypes.rst
This PR is a fixed Version of #402 
Now agains 2.0 branch :)
> BUGFIX: Translation file ending

- TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Session/BrowserState.php
- TYPO3.Media/Resources/Private/Partials/ListView.html
- TYPO3.Media/Resources/Private/Templates/Asset/Index.html
- TYPO3.Neos/Resources/Private/Partials/Media/ListView.html
- TYPO3.Neos/Resources/Private/Styles/Foundation/_dropdowns.scss
- TYPO3.Neos/Resources/Private/Styles/_Icons.scss
- TYPO3.Neos/Resources/Private/Templates/Media/Asset/Index.html
- TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
- TYPO3.Neos/Resources/Public/Styles/Neos.css
More flexible sorting in the media browser. The sorting is now split in sort by and sort direction to sort the asset list independently.
NEOS-1765 #close
> FEATURE: Sort direction options in media browser

- TYPO3.Neos/Configuration/Settings.yaml
> TASK: Display database error for additional exceptions

- TYPO3.Neos/Resources/Private/Styles/Content/_InsertNodePanel.scss
- TYPO3.Neos/Resources/Private/Translations/en/Main.xlf
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.html
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
Display the selected position in the insert new panel header.
NEOS-1121 #close
> TASK: Display insert position in insert new panel

- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php
- TYPO3.Neos/Configuration/Policy.yaml
- TYPO3.Neos/Resources/Private/Styles/Media/_Media.scss
- TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html
- TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedDocumentNodes.html
- TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Adds a new view in the media browser to display information about which nodes an asset is referenced in.
NEOS-47 #close
> FEATURE: Media related document nodes

- TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/AbstractServiceController.php
- TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/NodeController.php
- TYPO3.Neos/Configuration/Routes.Service.yaml
- TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosBackendEndpoints.html
- TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionSelector.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/TargetWorkspaceController.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/EditPreviewPanel/EditPreviewPanelController.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Menu/MenuPanelController.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeActions.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Model/PublishableNodes.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/NodeTree.js
- TYPO3.Neos/Resources/Public/JavaScript/ContentModuleBootstrap.js
- TYPO3.Neos/Resources/Public/JavaScript/Shared/Notification.js
- TYPO3.Neos/Resources/Public/JavaScript/storage.js
Generalises and improves the output of exception errors.
Removes unuseful custom AJAX error handling and thus avoids displaying multiple error notifications for a single error.
NEOS-185 #close
> TASK: Improve exception error notifications

- TYPO3.Neos/Resources/Private/Styles/Content/_InsertNodePanel.scss
- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/HelpMessage.js
- TYPO3.Neos/Resources/Public/JavaScript/Shared/Popover.js
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Adds a hover effect and increases the size in the insert new panels
> TASK: Make help message icon more visible

- TYPO3.Neos/Classes/TYPO3/Neos/Command/DomainCommandController.php
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/BackendController.php
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/MenuHelper.php
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Administration/SitesController.php
- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/Domain.php
- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/Site.php
- TYPO3.Neos/Classes/TYPO3/Neos/Service/LinkingService.php
- TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/ContainerViewHelper.php
- TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/JavascriptConfigurationViewHelper.php
- TYPO3.Neos/Configuration/Routes.Backend.yaml
- TYPO3.Neos/Migrations/Mysql/Version20160411101457.php
- TYPO3.Neos/Migrations/Mysql/Version20160411101458.php
- TYPO3.Neos/Migrations/Postgresql/Version20160411101639.php
- TYPO3.Neos/Migrations/Postgresql/Version20160411101640.php
- TYPO3.Neos/Resources/Private/Partials/Module/Shared/DomainForm.html
- TYPO3.Neos/Resources/Private/Styles/Modules/Administration/_Sites.scss
- TYPO3.Neos/Resources/Private/Styles/_Constants.scss
- TYPO3.Neos/Resources/Private/Templates/Module/Administration/Sites/Edit.html
- TYPO3.Neos/Resources/Private/Templates/Module/Administration/Sites/Index.html
- TYPO3.Neos/Resources/Private/Templates/Module/Administration/Sites/NewDomain.html
- TYPO3.Neos/Resources/Private/Translations/en/Main.xlf
- TYPO3.Neos/Resources/Public/JavaScript/Content/Menu/MenuPanelController.js
- TYPO3.Neos/Resources/Public/Styles/Login.css
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Adds ``scheme`` and ``port`` parameters to site domains to enable setting them for cross-site linking.
Additionally adds a primary flag to site domains to enable selecting the primary domain for a site.
Lastly linking to a node using the ``LinkingService`` the primary domain of the site the node belongs
to is taking into account. This allows cross-site linking instead of creating an invalid link to a non-existing
node with the existing site's URL.
NEOS-976 #close
NEOS-178 #close
> FEATURE: Cross-site linking

- TYPO3.Neos/Resources/Private/Styles/Inspector/_Inspector.scss
- TYPO3.Neos/Resources/Private/Styles/Shared/_Checkboxes.scss
- TYPO3.Neos/Resources/Public/Styles/Neos.css
- Changes the check icon
- Always show a check icon
- Improves hover / focus states
> TASK: Improve styling of checkboxes

- TYPO3.Neos/Resources/Private/Styles/Inspector/_Inspector.scss
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Fixes an overflow issue caused the border of the active tab not to change.
Additionally adds a hover effect.
> BUGFIX: Indicate active inspector tab

- TYPO3.Neos/Configuration/NodeTypes.yaml
- TYPO3.Neos/Resources/Public/JavaScript/Content/Model/Node.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Model/PublishableNodes.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
- TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js
Use the newly available node label in more parts of the UI and improve how the default node label
is generated.
NEOS-1811 #close
> TASK: Use and improve node label

- TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
Before that the nodeType validation produced some errors.
> TASK: Add schema definition for the inspector group icons

- TYPO3.Neos/Classes/TYPO3/Neos/Command/SiteCommandController.php
- TYPO3.Neos/Documentation/CreatingASite/NodeTypes/DependingProperties.rst
- TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeConstraints.rst
- TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
- TYPO3.Neos/Documentation/CreatingASite/Security.rst
- TYPO3.Neos/Documentation/ExtendingNeos/CustomEditPreviewMode.rst
- TYPO3.Neos/Documentation/ExtendingNeos/Tests/Behat.rst
- TYPO3.Neos/Documentation/HowTos/AddingSimpleContactForm.rst
- TYPO3.Neos/Tests/Behavior/Features/Administration/SiteManagement/ListSites.feature
- TYPO3.Neos/Tests/Behavior/Features/BackendLogin.feature
- TYPO3.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php
- TYPO3.Neos/Tests/Behavior/Features/Content/InlineEditing.feature
- TYPO3.Neos/Tests/Behavior/Features/Content/PreviewMode.feature
- TYPO3.Neos/Tests/JavaScript/Shared/NodeTypeServiceTest.js
Adjusts Behat tests and documentation to the new Neos.Demo site package.
> BUGFIX: Adjust to new Neos.Demo site package

- TYPO3.Neos/Resources/Private/Styles/Shared/_Checkboxes.scss
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Fixes the styling of the radio buttons and synchronizes
the styling with the new styling for the checkboxes.
> BUGFIX: Radio buttons active state

- TYPO3.Neos/Resources/Private/Styles/Inspector/_Inspector.scss
- TYPO3.Neos/Resources/Private/Styles/Shared/_Select2.scss
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Regression from the new dropdown styling.
> BUGFIX: Select box editor unselect styling

- TYPO3.Neos/Configuration/Settings.yaml
Add ``Neos.RedirectHandler`` to command reference settings so it will be added to the general command reference
> TASK: Add ``Neos.RedirectHandler`` to command reference settings

- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.js
Regression of 8ec441266bd7fac9a99539bc78c6ae36d382a1b9
> BUGFIX: Close insert node panel when pressing esc button

- TYPO3.Media/Classes/TYPO3/Media/Command/MediaCommandController.php
- TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Asset.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Dto/UsageReference.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Repository/AssetRepository.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Service/AssetService.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Strategy/AbstractAssetUsageStrategy.php
- TYPO3.Media/Classes/TYPO3/Media/Domain/Strategy/AssetUsageStrategyInterface.php
- TYPO3.Media/Documentation/DeveloperInformation/index.rst
- TYPO3.Media/Documentation/index.rst
- TYPO3.Media/Tests/Unit/Domain/Service/AssetServiceTest.php
- TYPO3.Media/Tests/Unit/Fixtures/AssetTypeWithoutRepository.php
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php
- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/Dto/AssetUsageInNodeProperties.php
- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/LegacySiteImportService.php
- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Strategy/AssetUsageInNodePropertiesStrategy.php
- TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html
This change allows to register asset usage strategies that
define if an asset is still in use and how many times.
> FEATURE: Asset usage strategies

- TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
- TYPO3.Media/Configuration/Policy.yaml
- TYPO3.Media/Resources/Private/Templates/Asset/ReplaceAssetResource.html
- TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php
- TYPO3.Neos/Configuration/Policy.yaml
- TYPO3.Neos/Resources/Private/Partials/Media/ThumbnailView.html
- TYPO3.Neos/Resources/Private/Styles/Foundation/_utilities.scss
- TYPO3.Neos/Resources/Private/Styles/Media/_Media.scss
- TYPO3.Neos/Resources/Private/Templates/Media/Asset/ReplaceAssetResource.html
- TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
- TYPO3.Neos/Resources/Public/Styles/Neos.css
- Unhides the action buttons in the media browser
- Use bigger filetype icon
- Made action names more consistent
- Made typehinting more consistent
> TASK: Small improvements for the replace asset feature

- TYPO3.Neos/Documentation/CreatingASite/TypoScript/InsideTypoScript.rst
Add documentation describing how to use node, documentNode, site and request within TS
> TASK: Add documentation for default TypoScript context variables

- TYPO3.Media/Tests/Functional/Domain/Model/AssetTest.php
Add functional testcase for asset model with tests for
adding / setting tags
> TASK: Add functional test class for asset model

- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/Site.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/Context.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ContextFactory.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Service/Utility/NodePublishingDependencySolver.php
- TYPO3.TYPO3CR/Tests/Functional/Domain/NodesTest.php
This pull request applies code style fixes from an analysis carried out by StyleCI.
For details see https://styleci.io/analyses/zGPEL2
> TASK: Apply fixes from StyleCI

- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
Even when removed nodes were requested, the method looking for the best match
in a context (``filterNodeDataByBestMatchInContext``) excluded them. This made it
impossible to fetch those nodes, e.g. for publishing changes.
This change fixes that by passing on the request for removed nodes so they can
be included as needed.
NEOS-1858 #close
NEOS-1841 #comment Fixes regression introduced by this fix
> BUGFIX: Include removed nodes if requested in ``filterNodeDataByBestMatchInContext``

- TYPO3.Neos/Resources/Private/Styles/Modules/_Modules.scss
- TYPO3.Neos/Resources/Public/Styles/Neos.css
Add background color to select option for the electronic addresses select box, because it was white text on white background for Windows users.
NEOS-1823 #close
> BUGFIX: Add background color to select option

- TYPO3.Neos/Classes/TYPO3/Neos/Eel/FlowQueryOperations/SortOperation.php
- TYPO3.Neos/Documentation/References/FlowQueryOperationReference.rst
- TYPO3.Neos/Tests/Functional/FlowQueryOperations/Fixtures/SortableNodes.xml
- TYPO3.Neos/Tests/Functional/FlowQueryOperations/SortOperationTest.php
Adds a sort FlowQuery operation to sort TYPO3CR nodes by given property and ``ASC`` or ``DESC`` sort order: ``sort(propertyName, order)``
> FEATURE: ``sort()`` FlowQuery operation

- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php
This change adds an additional safeguard to the node:repair task which
adds missing default node properties. Previously, when multiple nodes
existed with the same path and identifier but invalid dimension values,
this task could result in SQL unique constraint errors.
Invalid dimension values could result, for example, from nodes not
being migrated after a second dimension has been introduced.
> TASK: Harden node:repair against nodes with invalid dimension values

- TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php
This will reconstruct missing shadow nodes in case something went
wrong in creating or publishing them.
Important is to select a workspace other than live to repair as
shadow nodes only appear in non base workspaces.
> FEATURE: Implement repair of shadow nodes 

- TYPO3.Neos/Configuration/Settings.yaml
Adjusts the ``requestPattern`` configuration to the new
syntax introduced with https://github.com/neos/flow-development-collection/pull/130
Related: FLOW-412
> TASK: Adjust requestPattern settings to new syntax

- TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditor.js
Check that asset is selected before reloading the preview image.
NEOS-1882 #close
> BUGFIX: fix sorting in Media module

- TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedNodes.html
This change check if the relatedNode.contextDocumentNode exist before
creating the link. Without this change the editor is in front of
an exception.
> TASK: RelatedNodes template need to be more solid

- TYPO3.Neos/Documentation/CreatingASite/TypoScript/InsideTypoScript.rst
@aertmann @hlubek To cleanup also the source of the content for the TS Reference.
> TASK: Fixed typos in documention

- TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
This is already used by the GoogleAnalytics package.
Please upmerge.
Ticket: NEOS-1529
> FIX: add viewOptions in NodeTypes schema

- TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js
Resets state after creating of a new page is canceled
NEOS-1884 #close
> BUGFIX: BE Dimension Selector

- TYPO3.Neos/Classes/TYPO3/Neos/Command/DomainCommandController.php
- TYPO3.Neos/Tests/Unit/Domain/Service/DomainMatchingStrategyTest.php
- TYPO3.TypoScript/Tests/Unit/Core/Parser/PatternTest.php
- TYPO3.TypoScript/Tests/Unit/Core/ParserTest.php
Replaces references to typo3.org with matching references to neos.io.
> TASK: Remove references to typo3.org

- TYPO3.Neos/composer.json
This will fix the dependency for the Flow version to correct one and prevent `composer update` to upgrade to unwanted minor releases.
> BUGFIX: Fix wrong Flow version in ``composer.json``

- TYPO3.Neos/Resources/Private/Styles/Media/_Media.scss
- TYPO3.Neos/Resources/Public/Styles/Neos.css
This fixes the appearance of the asset details within the media browser.
> BUGFIX: Fix styling for asset details in thumbnail view

- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php
> BUGFIX: node:repair breaks at dimensions with fallbacks

- TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Security/Authorization/Privilege/Node/ReadNodePrivilege.php
Previously the ``ReadNodePrivilege`` did not implement a ``matchesSubject()``
method falling back to the default behavior of *not* matching any subject.
Usually this is not an issue because nodes protected by this privilege will
normally not be loaded anyways, but it prevents "pro-active" lookups for
this privilege using the `PrivilegeManager`::
$privilegeManager->isGranted(ReadNodePrivilege::class, $node)
Without this fix, the above will always return FALSE.
Related: NEOS-945
> BUGFIX: Allow determination of ``ReadNodePrivilege``

- TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php
Adds new features for behat tests using nodes
> FEATURE: New behat node operation features

- TYPO3.Neos/Documentation/Appendixes/ReleaseNotes/230.rst
Added warning about breaking change in 2.3
> TASK: Add warning about breaking change in 2.3

- TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst
- TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/RendererImplementation.php
- TYPO3.TypoScript/Resources/Private/TypoScript/Root.ts2
- TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/Renderer.ts2
- TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/RendererTest.php
The Renderer object will evaluate to a result using either ``renderer``, ``renderPath`` or ``type`` on the configuration.
> FEATURE: Add prototype ``TYPO3.TypoScript:Renderer``

- TYPO3.Neos/Tests/Functional/Controller/Backend/BackendControllerSecurityTest.php
Related to neos/flow-development-collection#457
> BUGFIX: Adjust test to removed setParty() method

- Neos.ContentRepository/Migrations/Mysql/Version20161125093820.php
- Neos.ContentRepository/Migrations/Postgresql/Version20161125093821.php
- Neos.Media/Migrations/Mysql/Version20161125093810.php
- Neos.Media/Migrations/Postgresql/Version20161125093811.php
- Neos.Neos/Migrations/Mysql/Version20161125093800.php
- Neos.Neos/Migrations/Postgresql/Version20161125093801.php
Related to the vendor name change, see neosneos-development-collection#1240
> TASK: Add Doctrine migrations to rename tables

- Neos.Neos/Migrations/Mysql/Version20161125124749.php
- Neos.Neos/Migrations/Postgresql/Version20161125125249.php
- Neos.NodeTypes/Migrations/Mysql/Version20161125123504.php
- Neos.NodeTypes/Migrations/Postgresql/Version20161125125004.php
Adds mysql and postgresql migrations to change NodeType names in existing databases to the new namespace.
> TASK: Add database migrations for Neos and NodeTypes packages

- Neos.Fusion/Classes/Exception/UnsupportedProxyMethodException.php
- Neos.Fusion/Classes/TypoScriptObjects/Helpers/FusionPathProxy.php
- Neos.Fusion/Classes/TypoScriptObjects/TemplateImplementation.php
> TASK: Rename TypoScriptPathProxy to FusionPathProxy

- Neos.SiteKickstarter/Classes/Service/GeneratorService.php
- Neos.SiteKickstarter/Resources/Private/Generator/Configuration/NodeTypes.yaml
- Neos.SiteKickstarter/Resources/Private/Generator/Template/SiteTemplate.html
Fixes some wrong paths and internal method names.
> TASK: Adapt Kickstarter to Fusion renaming

- TYPO3.Neos/Documentation/References/PropertyEditorReference.rst
Added missing configuration option "required" for the BooleanEditor
> TASK: Update documentation for boolean editor in property editor reference

- Neos.Fusion/Tests/Unit/Core/ParserTest.php
- Neos.Neos/Classes/Aspects/TypoScriptCachingAspect.php
- Neos.Neos/Classes/Domain/Service/FusionService.php
- Neos.Neos/Classes/Domain/Service/TypoScriptService.php
- Neos.Neos/Classes/View/TypoScriptView.php
- Neos.Neos/Migrations/Code/Version20161219122512.php
- Neos.Neos/Tests/Functional/Fusion/RenderingTest.php
- Neos.Neos/Tests/Unit/View/TypoScriptViewTest.php
This should resolve #1297. I did not change the settings path yet (still reads from Neos.typoScript) as that would probably have side effects on other classes.
> TASK: Replace TypoScriptService by FusionService

- Neos.Media.Browser/Classes/Controller/Module/Management/AssetController.php
This avoid code duplication by using the central AssetUsageStrategies to
detect if an Asset is used in the current website. This change also remove
a dependency to NodeDataRepository in the controller.
> TASK: Use AssetUsageStrategies in AssetController::deleteAction

- Neos.Media.Browser/Resources/Private/Partials/ThumbnailView.html
- Neos.Media.Browser/Resources/Public/JavaScript/upload.js
Regression of f169275c9a05071531dc5bd9b3d2533ebf093184
> BUGFIX: Selecting image in media browser thumbnail view

- TYPO3.Media/Classes/TYPO3/Media/Package.php
Merge regression of d03079cb90fbade6fae5748c0dd9acb94543c761
> BUGFIX: Creating thumbnails on asset creation

- TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst
This documents changes that were introduced in Neos 2.0 with revision 75430099fe2dbd3646eb549dac5e9778abf4c82a.
> TASK: Document width and height property in ImageUri Fusion-prototype

- Neos.Neos/Classes/Fusion/ImageUriImplementation.php
- Neos.Neos/Documentation/References/NeosFusionReference.rst
- Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion
Add image preset support for `Neos.Neos:ImageUri` and `Neos.Neos:ImageTag`.
> FEATURE: Add support for image presets in Fusion

- Neos.ContentRepository/Classes/Domain/Model/NodeType.php
- Neos.ContentRepository/Tests/Unit/Domain/Service/NodeTypeManagerTest.php
- Neos.Media/Classes/Domain/Repository/AssetRepository.php
- Neos.Media/Classes/Domain/Service/AssetService.php
- Neos.Media/Classes/TypeConverter/ImageVariantConverter.php
- Neos.Neos/Classes/TYPO3CR/Transformations/ImageVariantTransformation.php
- Neos.Neos/Classes/View/TypoScriptView.php
- Neos.Neos/Tests/Unit/Service/HtmlAugmenterTest.php
Mostly fixes comments, but some use statements as well.
Also removes some dead code that was not removed along with the
deprecated NodeDataLabelGeneratorInterface.
> TASK: Fix "undefined class" warnings

- TYPO3.Neos/Classes/TYPO3/Neos/Domain/Strategy/AssetUsageInNodePropertiesStrategy.php
> BUGFIX: Use findNodesByPathPrefixAndRelatedEntities

- Neos.Neos/Classes/Service/Mapping/NodePropertyConverterService.php
- Neos.Neos/Configuration/Settings.yaml
- Neos.Neos/Configuration/Testing/Settings.yaml
- Neos.Neos/Tests/Functional/Service/Mapping/NodePropertyConverterServiceTest.php
Hi @kitsunet,
this refactoring was done at the NEOS Sprint. Let's review it together.
Best
Jo (@joachimmathes) and Dani (@dgrammlich)
> TASK: Set `ArrayConverter` as node property default type converter

- TYPO3.Neos/Configuration/Settings.yaml
- TYPO3.Neos/Documentation/References/PropertyEditorReference.rst
Add default editorOptions to settings for the new react ui [https://github.com/neos/neos-ui/issues/641](https://github.com/neos/neos-ui/issues/641)
> FEATURE: Add default editorOptions to settings

- Neos.Neos/Documentation/Appendixes/ReleaseNotes/310.rst
Release notes for Neos 3.1
Fixes #1488
> TASK: Add release notes for 3.1

- Neos.Neos/Documentation/Appendixes/ReleaseNotes/300.rst
> TASK: Add content to 3.0.0 release notes

- Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeConstraints.rst
Completely rewrote that chapter of the docs in order to make it more explicit and understandable.
> TASK: Rewrite Node Type Constraint docs for correctness and clarity

- Neos.Neos/Documentation/GettingStarted/Installation.rst
Replaced 5.5.0 with 7.0.0
_Please note that this should be also changed in 3.1 and master branch_
> TASK: Corrected required php version in documentation

- Neos.Media/Classes/ViewHelpers/Form/CheckboxViewHelper.php
- Neos.Media/Classes/ViewHelpers/ImageViewHelper.php
- Neos.Media/Classes/ViewHelpers/ThumbnailViewHelper.php
- Neos.Media/Classes/ViewHelpers/Uri/ImageViewHelper.php
- Neos.Media/Classes/ViewHelpers/Uri/ThumbnailViewHelper.php
- Neos.Neos/Documentation/References/CommandReference.rst
- Neos.Neos/Documentation/References/FlowQueryOperationReference.rst
- Neos.Neos/Documentation/References/ViewHelpers/Media.rst
- Neos.Neos/Documentation/References/ViewHelpers/Neos.rst
Replaces some left over occurrences of "typo3" and updates
ViewHelper and Command references accordingly.
Fixes: #1558
> TASK: Update ViewHelper and Command references

- Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
- Neos.ContentRepository/Resources/Private/Schema/NodeTypes.schema.yaml
- Neos.Fusion/Configuration/Testing/Caches.yaml
- Neos.Neos/Configuration/Testing/NodeTypes.yaml
- Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
- Neos.Neos/Tests/Functional/Configuration/ConfigurationValidationTest.php
- Neos.Neos/Tests/Functional/Configuration/SchemaValidationTest.php
- Neos.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php
This change adds a functional test to neos to validate that the configurations defined in the packages that are part of the flow base distribution are all valid and that the contained schema files are valid as well.
This extends a flow test case with an extended set of packages and configurations that is taken into account.
> TASK: Add functional-test that validates the integrity of the configuration and schemas in neos-packages

- TYPO3.Media/Classes/TYPO3/Media/Domain/Service/AssetService.php
The redirects for replaced resources were created using full URLs,
but the redirect handler expects relative URL paths to be given.
Fixes #1573
> BUGFIX: Create resource redirects correctly

- TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedNodes.html
- TYPO3.Neos/Resources/Private/Translations/de/Modules.xlf
- TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
Fixed some misleading text on the listing page and added i18n.
related to #1578.
for 3.x upmerge have a look at https://github.com/ComiR/neos-development-collection/commit/e2d0e44dd6f21179b2e9eeeac1481ae3a4f8a3f6.
> BUGFIX: Only show link to accessible nodes

- Neos.Neos/Documentation/CreatingASite/NodeTypes/DisableNodeTypes.rst
- Neos.Neos/Documentation/CreatingASite/NodeTypes/index.rst
This adds documentation about how to disable NodeTypes. This was discussed
in https://github.com/neos/neos-development-collection/issues/1674
> TASK: Explain how to disable NodeTypes in documentation

- Neos.Neos/Documentation/CreatingASite/Fusion/InsideFusion.rst
Based on input from Aftab, improved the clarity of this docs section.
> TASK: Make Fusion file inclusion docs more clear

- TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/NodeController.php
This makes it possible to use your own implementation of the NodeSearchService.
> TASK: Use interface to inject NodeSearchService in NodeController

- Neos.Neos/Documentation/References/NeosFusionReference.rst
**What I did**
Removed TYPO3 from fusion reference
> TASK: Remove TYPO3 from Neos Fusion Reference

- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetAssetCollectionConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetCollectionConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetTagConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetWithoutAssetCollectionConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/TagConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/ReadAssetCollectionPrivilege.php
- Neos.Media/Classes/Security/Authorization/Privilege/ReadAssetPrivilege.php
- Neos.Media/Classes/Security/Authorization/Privilege/ReadTagPrivilege.php
- Neos.Media/Documentation/AssetPrivileges.rst
- Neos.Media/Documentation/index.rst
- Neos.Neos/Documentation/CreatingASite/Security.rst
This introduces the following Privileges:
* `ReadAssetPrivilege`
* `ReadTagPrivilege`
* `ReadAssetCollectionPrivilege`
see added documentation.
Note:
The code for this change has been taken from
https://github.com/bwaidelich/Wwwision.AssetConstraints
> FEATURE: Asset Constraints

- Neos.Neos/Resources/Private/Templates/Module/Administration/Users/New.html
Streamlines the role selection layout for create new user view with
edit user account view.
> TASK: Streamline role selection for new user view

- Neos.SiteKickstarter/Classes/Service/GeneratorService.php
**What I did**
Refactor the siteNodeName generation. It is now based on the complete package key.
Also i did some code cleanup.
Simple use the `./flow kickstart:site` command. You can verify the siteNodeName inside the generated `Resources/Private/Content/Sites.xml`
> TASK: Use whole package key for generating site node name

- .travis.yml
- Neos.ContentRepository/Classes/TypeConverter/NodeTemplateConverter.php
- Neos.ContentRepository/Tests/Functional/Eel/FlowQueryOperations/ChildrenOperationTest.php
This enables PHP 7.2 testing on Travis CI, fixes a functional test that broke
and adjusts one actual code error.
> TASK: Adjust Neos to work with PHP 7.2

- TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/NodePropertyConverterService.php
Apply property mapping to default value fallbacks in ``NodePropertyConverterService``
Resolves #1781
> BUGFIX: ``NodePropertyConverterService`` converts default values

- Neos.ContentRepository/Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html
Keep classes backwards compatible by adding neos-* classes in addition to typo3-* classes.
> Add neos-* classes regarding to typo3-* classes

- .composer.json
Maybe we can automate that within the create-branch script
> BUGFIX: Fix Flow dev dependency for 3.1

- .composer.json
Maybe we can automate that within the create-branch script
> BUGFIX: Fix Flow dev dependency for 3.2

- Neos.Neos/Classes/Routing/Aspects/RouteCacheAspect.php
This extracts the part of https://github.com/neos/neos-development-collection/pull/1769 that is needed for neos to work with the adjusted flow-routing.
> TASK: Adjust the RouteCacheAspect to work with recent changes in Flow-routing

- Neos.Neos/Documentation/ExtendingNeos/CustomTypoScriptObjects.rst
> Replace deprecated method tsValue with fusionValue

- Neos.Neos/Documentation/CreatingASite/ContentCache.rst
- Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/CustomContentElements.rst
- Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/PageRendering.rst
- Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/Templating.rst
- Neos.Neos/Documentation/ExtendingNeos/CustomTypoScriptObjects.rst
- Neos.Neos/Documentation/ExtendingNeos/InteractionWithTheNeosBackend.rst
- Neos.Neos/Documentation/HowTos/IntegratingJavaScriptSlider.rst
- Neos.Neos/Documentation/References/ViewHelpers/FluidAdaptor.rst
- Neos.Neos/Documentation/References/ViewHelpers/Media.rst
> TASK: Fix legacy mentions of TYPO3 in the documentation

- Neos.Fusion/composer.json
> BUGFIX: Remove duplicate entry in composer.json (neos/fluid-adaptor)

- Neos.Neos/Classes/Controller/Module/Administration/PackagesController.php
- Neos.Neos/Resources/Private/Templates/Module/Administration/Packages/Index.html
In preparation of removing active/deactivated states for packages
we remove notion of that in the Neos package module.
> TASK: Remove any notion of `active` packages in package module

- Neos.Neos/Configuration/Routes.Service.yaml
> TASK: make format configurable of ContentDimensions controller

- Neos.Neos/Documentation/CreatingASite/NodeTypes/DependingProperties.rst
- Neos.Neos/Documentation/CreatingASite/NodeTypes/DynamicConfigurationProcessing.rst
- Neos.Neos/Documentation/CreatingASite/NodeTypes/index.rst
- Neos.Neos/Documentation/References/PropertyEditorReference.rst
Documentation for https://github.com/neos/neos-ui/pull/1618
> DOCS: document dynamic client-side configuration processing

- Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeCreationDialog.rst
- Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
- Neos.Neos/Documentation/CreatingASite/NodeTypes/index.rst
> DOCS: document creationDialog

- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/NodeFactory.php
- Neos.ContentRepository/Classes/Domain/Context/Importing/Event/ImportingSessionWasFinalized.php
- Neos.ContentRepository/Classes/Domain/Context/Importing/Event/NodeWasImported.php
- Neos.ContentRepositoryMigration/Classes/Service/ContentRepositoryExportService.php
This just cleans up stuff a bit so that import from the old content repository works again
> TASK: Clean up stuff and adjust to new interfaces

- Neos.Neos/Classes/Http/BasicContentDimensionResolutionMode.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/BackendUriContentDimensionValueDetector.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/ContentDimensionValueDetectorInterface.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/ContentDimensionValueDetectorResolver.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/Exception/InvalidContentDimensionValueDetectorException.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/Exception/InvalidDimensionValueDetectorException.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/HostPrefixContentDimensionValueDetector.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/HostSuffixContentDimensionValueDetector.php
- Neos.Neos/Classes/Http/ContentDimensionDetection/UriPathSegmentContentDimensionValueDetector.php
- Neos.Neos/Classes/Http/DetectContentSubgraphComponent.php
- Neos.Neos/Configuration/Settings.yaml
- Neos.Neos/Tests/Functional/Http/DetectContentSubgraphComponentTest.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/BackendUriContentDimensionValueDetectorTest.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/ContentDimensionValueDetectorResolverTest.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/Fixtures/InvalidDummyContentDimensionValueDetector.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/Fixtures/ValidDummyContentDimensionValueDetector.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/HostPrefixContentDimensionValueDetectorTest.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/HostSuffixContentDimensionValueDetectorTest.php
- Neos.Neos/Tests/Unit/Http/ContentDimensionDetection/UriPathSegmentContentDimensionValueDetectorTest.php
This introduces dimension value detection via HTTP compontents using the new building blocks
> (Event sourced CR) Dimension value detection

- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Projection/GraphProjector.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentGraph.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentSubgraph.php
- Neos.ContentRepository/Classes/Domain/Context/Node/Command/CreateRootNode.php
- Neos.ContentRepository/Classes/Domain/Context/Node/Event/RootNodeWasCreated.php
- Neos.ContentRepository/Classes/Domain/Context/Node/NodeCommandHandler.php
- Neos.ContentRepository/Classes/Domain/Projection/Content/ContentGraphInterface.php
- Neos.ContentRepositoryMigration/Classes/Service/ContentRepositoryExportService.php
- Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php
> (Event Sourced CR) WIP

- Neos.ContentRepositoryMigration/Classes/Service/ContentRepositoryExportService.php
Properties of type `reference` and `references` are still ignored since they will be rendered as edges.
> (Event Sourced CR) TASK: import non string properties

- TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Model/Event.php
Ensure that child events are ordered by their uid to ensure chronological order
> TASK: Order event log child events by their uid

- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Projection/GraphProjector.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentGraph.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentSubgraph.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ProjectionContentGraph.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/Subtree.php
- Neos.ContentRepository/Classes/Domain/Context/Node/SubtreeInterface.php
- Neos.ContentRepository/Classes/Domain/Model/Workspace.php
- Neos.ContentRepository/Classes/Domain/Projection/Changes/Change.php
- Neos.ContentRepository/Classes/Domain/Projection/Changes/ChangeFinder.php
- Neos.ContentRepository/Classes/Domain/Projection/Changes/ChangeProjector.php
- Neos.ContentRepository/Classes/Domain/Projection/Content/ContentSubgraphInterface.php
- Neos.ContentRepository/Classes/Domain/Service/PublishingService.php
- Neos.ContentRepository/Classes/Service/Infrastructure/Service/DbalClient.php
- Neos.ContentRepository/Migrations/Mysql/Version20180227202343.php
- Neos.Neos/Classes/Fusion/MenuImplementation.php
- Neos.Neos/Classes/Service/PublishingService.php
> (Event Sourced CR) FEATURE: ChangeProjection

- TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
Improves the labels by adding "the" to give it a better flow.
Additionally ensures all labels are in quotation marks.
> TASK: Improve history module event labels

- TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/UserInitialsViewHelper.php
Improves the UserInitials view helper a bit by removing the odd dot and the end of "fullFirstName" and trims the result. Additionally strips special characters from "initials".
> TASK: Improvements to the UserInitials view helper

- Neos.ContentRepository/Classes/Domain/Model/Workspace.php
- Neos.ContentRepository/Classes/Domain/Service/PublishingService.php
- Neos.ContentRepository/Classes/Domain/Service/PublishingServiceInterface.php
- Neos.ContentRepository/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php
- Neos.Neos/Classes/Command/WorkspaceCommandController.php
- Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
- Neos.Neos/Classes/Service/Controller/WorkspaceController.php
- Neos.Neos/Classes/Service/PublishingService.php
> (Event Sourced CR) TASK: Introduce publishAll for workspaces

- Neos.ContentRepository/Classes/Domain/Projection/Content/InMemoryCache/AllChildNodesByNodeIdentifierCache.php
- Neos.ContentRepository/Classes/Domain/Projection/Content/InMemoryCache/NamedChildNodeByNodeIdentifierCache.php
> (Event Sourced CR) BUGFIX: Ignore Nodes without context in cache

- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Projection/GraphProjector.php
- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentSubgraph.php
- Neos.ContentRepository/Tests/Behavior/Features/EventSourced/NodeOperationsOnMultipleWorkspaces.feature
> (Event sourced CR) Copy on write

- Neos.ContentGraph.DoctrineDbalAdapter/Classes/Domain/Repository/ContentSubgraph.php
> (Event Sourced) BUGFIX: Fix SQL-Statements in ContentSubgraph

- TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/ContentCache.php
- TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/ContentCacheTest.php
- TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/ContentCache.ts2
...
Only a test to expose the wrong behavior at this point.
Fixes: #1958
> BUGFIX: Dynamic cache segments not correctly re-evaluated

- Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
This introduces the Node.isOfType() eel method to check
if a node is of a given type
> FEATURE: Expose NodeType.isOfType in Node eel helper

- Neos.Neos/Resources/Private/Translations/en/Main.xlf
**What I did**
Added label translations for button aria labels
Check labels introduced in neos/neos-ui#1595
> TASK: Add translation for aria-labels of buttons introduced in neos/neos-ui#1595

- Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
- Neos.ContentRepository/Classes/Domain/Service/ImportExport/NodeExportService.php
- Neos.ContentRepository/Classes/Domain/Service/ImportExport/NodeImportService.php
- Neos.Media/Classes/Command/MediaCommandController.php
- Neos.Media/Classes/Domain/Repository/AssetRepository.php
- Neos.Media/Classes/Domain/Repository/ThumbnailRepository.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetAssetCollectionConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetTagConditionGenerator.php
- Neos.Media/Classes/Security/Authorization/Privilege/Doctrine/AssetWithoutAssetCollectionConditionGenerator.php
- Neos.Neos/Classes/EventLog/Integrations/ContentRepositoryIntegrationService.php
- Neos.Neos/Classes/EventLog/Integrations/EntityIntegrationService.php
- Neos.Neos/Classes/TYPO3CR/Transformations/AssetTransformation.php
- Neos.Neos/Classes/TYPO3CR/Transformations/ImageVariantTransformation.php
This adjusts some code in Neos to match the updated Doctrine DBAL and ORM libraries.
> BUGFIX: Adjustments after Doctrine updates

- Neos.Neos/Resources/Private/Styles/Login.scss
- Neos.Neos/Resources/Private/Templates/Login/Index.html
- Neos.Neos/Resources/Public/Styles/Login.css
- Added aria-label attributes to form fields
- Added role=alert to error message to improve screen reader accessibility
- Changed header tag to h1 (could break custom CSS that relies on the header tag)
> TASK: Improve login screen accessibility

- .travis.yml
- Neos.Neos/Resources/Private/Partials/Module/Shared/NodeContentDimensionsInformation.html
> BUGFIX: Show content dimensions with asset usages

- Neos.Neos/Documentation/References/PropertyEditorReference.rst
This PR adds documentation regarding the ability to disable Editors, which is added in this PR:
https://github.com/neos/neos-ui/pull/1665
> DOCS: Disable editors

- Neos.Neos/composer.json
I run the core migrations for Neos.Neos
#2014
> Task/core migrations Neos.Neos

- Neos.Neos/Configuration/Settings.yaml
See discussion there for more details.
Related: https://github.com/neos/neos-development-collection/pull/2021
https://github.com/neos/neos-ui/pull/1809
> TASK: Set default setting to enable the switch to old UI switch

- TYPO3.Neos/Documentation/CreatingASite/ContentCache.rst
- [ x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
> TASK: Document usage of Security Context in Content Cache

- Neos.Media.Browser/Configuration/Settings.yaml
- Neos.Neos/Configuration/Settings.yaml
- Neos.Neos/Resources/Private/Styles/Modules/_Modules.scss
> BUGFIX: Fix icons in modules after FA5 change

- Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
- Neos.Fusion/Classes/Core/Cache/RuntimeContentCache.php
- Neos.Media.Browser/Classes/Controller/AssetProxyController.php
- Neos.Media/Classes/Command/MediaCommandController.php
- Neos.Media/Classes/Domain/Model/AssetCollection.php
- Neos.Media/Classes/Domain/Service/ThumbnailService.php
- Neos.Neos/Classes/Routing/Aspects/RouteCacheAspect.php
- Neos.Neos/Classes/Service/LinkingService.php
I enhanced code quality with stuff I noticed and grouped them by commit, should be pretty clear (:
> TASK: Enhance Code quality

- Neos.Fusion/Resources/Private/Fusion/Root.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Conditions.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Debug.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ExceptionHandler.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/NestedOverwritesAndProcessors.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/SimpleTypes.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Tag.fusion
- Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestFusionFixture19.fusion
- Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestFusionFixture20.fusion
- Neos.Neos/Resources/Private/Fusion/Backend/History/Root.fusion
- Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCase.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/ContentElementWrapping.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/DimensionsMenu.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/DocumentMetadata.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/PrimaryContent.fusion
This was a thing at some time I remember and I've found many leftover uppercase true and false.
related to #2098
> TASK: Change all uppercase TRUE and FALSE to lowercase in fusion

- Neos.ContentRepository/Configuration/NodeTypes.yaml
- Neos.ContentRepository/Configuration/Policy.yaml
- Neos.ContentRepository/Configuration/Testing/NodeTypes.yaml
- Neos.ContentRepository/Migrations/TYPO3CR/Version20140326143834.yaml
- Neos.ContentRepository/Migrations/TYPO3CR/Version20150716212459.yaml
- Neos.ContentRepository/Resources/Private/Schema/NodeTypes.schema.yaml
- Neos.Fusion/Configuration/Settings.yaml
- Neos.Fusion/Resources/Private/Schema/Settings.schema.yaml
- Neos.Neos/Configuration/NodeTypes.yaml
- Neos.Neos/Configuration/Routes.Authentication.yaml
- Neos.Neos/Configuration/Routes.Backend.yaml
- Neos.Neos/Configuration/Routes.Service.yaml
- Neos.Neos/Configuration/Settings.yaml
- Neos.Neos/Configuration/Testing/NodeTypes.yaml
- Neos.Neos/Migrations/TYPO3CR/Version20150907194505.yaml
- Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
This was a thing at some time I remember and I've found many leftover uppercase true and false.
> TASK: Change all uppercase TRUE and FALSE to lowercase in YAML

- Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php
The oprhanRemoval in `node:repair` ignored the `--node-type` flag, leading
to confusion. This adds the needed code to use a given node type flag.
> TASK: Support --node-type for orphanRemoval in node:repair

- Neos.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
- Neos.Neos/Documentation/ExtendingNeos/UiExtensibility.rst
Documents https://github.com/neos/neos-ui/issues/2002
> DOCS: document CKeditor5 integration

- TYPO3.Neos/Documentation/References/FlowQueryOperationReference.rst
Resolves issue #1322
Corresponds to PR #2113, but for Neos 2.3
> TASK: Corrected description of the slice operation

- Neos.Neos/Classes/Command/WorkspaceCommandController.php
**What I did**
Added a timestamp and progress indicator to the publish command of the WorkspaceCommandController
./flow workspace:publish --workspace foo --verbose
**Checklist**
> FEATURE: Add progress and time to workspace:publish command

- Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
Fixes a merge regression introduced with 0481f5980fa64810178827b9d02a68b88caaf552
> BUGFIX: Fix NodeTypes.schema.yaml broken by merge

- Neos.Media/Classes/Domain/Model/Asset.php
- Neos.Media/Tests/Functional/Domain/Model/AssetTest.php
> BUGFIX: Add null checks to Asset::getAssetProxy()

- Neos.Neos/Documentation/References/CommandReference.rst
Fixes wrong order in documentation and adds missing task name
> TASK: Minor fixes in command documentation

- Neos.Media.Browser/Resources/Private/Layouts/Default.html
- Neos.Media.Browser/Resources/Private/Layouts/EditImage.html
- Neos.Media.Browser/Resources/Private/Layouts/UploadImage.html
- Neos.Media.Browser/Resources/Private/Templates/Asset/RelatedNodes.html
This fix a regressing introduced by https://github.com/neos/neos-development-collection/pull/1745
Fixes: #2170
> BUGFIX: Add missing Layout to access mediabrowser from inspector

- Neos.Neos/Resources/Private/Styles/Neos.scss
Reverts neos/neos-development-collection#2195
> Revert "BUGFIX: Fix SCSS import for Fontawesome files"

- Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
- Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php
- Neos.Neos/Tests/Unit/Fusion/Cache/ContentCacheFlusherTest.php
> TASK: Make sure that legacy cache configuration tags are still supported

- Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
- Neos.Neos/Classes/Package.php
- Neos.Neos/Tests/Functional/Fusion/Cache/ContentCacheFlusherTest.php
> TASK: Add option to flush an optional workspace as well as the nodes workspace

- Neos.Neos/Resources/Private/Styles/Login.scss
- Neos.Neos/Resources/Public/Styles/Login.css
> BUGFIX: Set min-height to make errors visible

- Neos.Fusion/Classes/FusionObjects/DebugDumpImplementation.php
- Neos.Fusion/Classes/Service/DebugStack.php
- Neos.Fusion/Tests/Functional/FusionObjects/DebugTest.php
Solves #2176
To change from direct output to returning a string worked out for me.
> BUGFIX: Return complete Neos.Fusion:Debug / DebugDump

- Neos.Media.Browser/Resources/Private/Styles/Media/_Media.scss
- Neos.Media.Browser/Resources/Private/Styles/MediaBrowser.scss
- Neos.Media.Browser/Resources/Public/Styles/MediaBrowser.css
- Neos.Neos/Resources/Private/Styles/Components/_PositionSelector.scss
- Neos.Neos/Resources/Private/Styles/ContextBar/_AlohaInlineTable.scss
- Neos.Neos/Resources/Private/Styles/ContextBar/_AlohaMenu.scss
- Neos.Neos/Resources/Private/Styles/ContextBar/_ContentDimensionSelector.scss
- Neos.Neos/Resources/Private/Styles/Foundation/_buttons.scss
- Neos.Neos/Resources/Private/Styles/Foundation/_modals.scss
- Neos.Neos/Resources/Private/Styles/Inspector/Editors/_AssetEditor.scss
- Neos.Neos/Resources/Private/Styles/Inspector/Editors/_ImageEditor.scss
- Neos.Neos/Resources/Private/Styles/Inspector/_Inspector.scss
- Neos.Neos/Resources/Private/Styles/Inspector/_SecondaryInspector.scss
- Neos.Neos/Resources/Private/Styles/Modules/_Modules.scss
- Neos.Neos/Resources/Private/Styles/Shared/_Checkboxes.scss
- Neos.Neos/Resources/Private/Styles/Shared/_Chosen.scss
- Neos.Neos/Resources/Private/Styles/Shared/_Select2.scss
- Neos.Neos/Resources/Private/Styles/TopBar/_PublishMenu.scss
- Neos.Neos/Resources/Private/Styles/_Tree.scss
- Neos.Neos/Resources/Public/Styles/Neos.css
The old ui and some dialogs still use the old fontawesome integration and broke due to the last fontawesome update as the mixins changed.
> BUGFIX: Render icons in old ui parts

- Neos.Neos/Classes/Fusion/Helper/CachingHelper.php
- Neos.Neos/Documentation/CreatingASite/ContentCache.rst
- Neos.Neos/Tests/Unit/Fusion/Helper/CachingHelperTest.php
> TASK: Add new nodeTagForIdentifier() method to CachingHelper

- Neos.Neos/Classes/Command/DomainCommandController.php
> BUGFIX: Allow primary domains to be removed via CLI

- Neos.Media.Browser/Classes/Controller/AssetController.php
- Neos.Media.Browser/Resources/Private/Partials/ListView.html
- Neos.Media.Browser/Resources/Private/Partials/ThumbnailView.html
- Neos.Media.Browser/Resources/Private/Templates/Asset/Edit.html
- Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html
- Neos.Media.Browser/Resources/Private/Templates/Asset/ReplaceAssetResource.html
- Neos.Media.Browser/Resources/Private/Templates/Asset/Show.html
Reverts neos/neos-development-collection#2331
> BUGFIX: Revert "BUGFIX: Asynchronous and presets for media browser thumbnails"

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/Model/NodeType.php
- Neos.ContentRepository/Classes/Domain/ValueObject/ContentStreamIdentifier.php
- Neos.ContentRepository/Classes/Domain/ValueObject/NodeAggregateIdentifier.php
- Neos.ContentRepository/Classes/Domain/ValueObject/NodeIdentifier.php
- Neos.ContentRepository/Classes/Domain/ValueObject/NodeName.php
- Neos.ContentRepository/Classes/Domain/ValueObject/NodePath.php
- Neos.ContentRepository/Classes/Domain/ValueObject/NodeTypeConstraints.php
- Neos.ContentRepository/Classes/Domain/ValueObject/NodeTypeName.php
- Neos.ContentRepository/Classes/Domain/ValueObject/RootNodeIdentifiers.php
- Neos.ContentRepository/Classes/Eel/FlowQueryOperations/ChildrenOperation.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/FilterOperationTest.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/NextAllOperationTest.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/NextOperationTest.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/ParentOperationTest.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/PrevAllOperationTest.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/PrevOperationTest.php
- Neos.ContentRepository/Tests/Unit/FlowQueryOperations/SiblingsOperationTest.php
- Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php
for better type safety and interoperability
> !!! TASK: Tweak CR Value Objects

- Neos.ContentRepository/Classes/Domain/Service/Context.php
> BUGFIX: Forward `removedContentShown` in Context->getNodeByIdentifier()

- Neos.Fusion/Classes/Core/RuntimeFactory.php
- Neos.Fusion/Classes/FusionObjects/Http/ResponseHeadImplementation.php
- Neos.Fusion/Tests/Functional/FusionObjects/AbstractFusionObjectTest.php
- Neos.Neos/Classes/Controller/Backend/ModuleController.php
- Neos.Neos/Classes/Fusion/PluginImplementation.php
- Neos.Neos/Classes/Fusion/PluginViewImplementation.php
- Neos.Neos/Classes/View/FusionExceptionView.php
This changes responses created in various areas of Neos to be
of the new ``ActionResponse`` class in preparation of the next
major version.
Related: #2437
> TASK: Adjust created responses to ``ActionResponse``

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
> WIP: Merge 3.3 into 4.0

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
> WIP: Merge 4.0 into 4.1

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
> WIP: Merge 4.1 into  4.2

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
> WIP: Merge 4.2 into 4.3

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
- Neos.Neos/Classes/Eel/FlowQueryOperations/ParentsOperation.php
- Neos.Neos/Documentation/Appendixes/ReleaseNotes/430.rst
- Neos.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php
> WIP: Merge 4.3 to master

- Neos.Neos/Resources/Private/Templates/Backend/Module/Index.html
Related to neos/neos-development-collection#2479
> BUGFIX: Avoid PHP exception in NamespaceDetectionTemplateProcessor

- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
- Neos.ContentRepository/Classes/Domain/Service/Context.php
- Neos.Fusion/Classes/Core/ExceptionHandlers/AbsorbingHandler.php
- Neos.Media/Classes/Domain/Model/Asset.php
- Neos.Media/Classes/Domain/Model/ImportedAssetManager.php
- Neos.Media/Classes/Domain/Service/AssetSourceService.php
- Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php
- Neos.Neos/Classes/Service/LinkingService.php
- Neos.Neos/Classes/Service/View/NodeView.php
- Neos.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php
With Flow 6.0 PsrSystemLoggerInterface gets deprecated, so we exchange the PsrSystemLoggerInterface with LoggerInterface.
> TASK: Exchange injection of PsrSystemLoggerInterface to LoggerInterface

- Neos.Neos/Resources/Private/Translations/en/Main.xlf
Fixes https://github.com/neos/neos-ui/issues/2283
> BUGFIX: Add translation for discard confirmation

- Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
- Neos.Neos/Classes/Domain/Repository/UserRepository.php
- Neos.Neos/Classes/Domain/Service/UserService.php
- Neos.Neos/Resources/Private/Styles/Modules/_Modules.scss
- Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
- Neos.Neos/Resources/Public/Styles/Includes-built.css
- Neos.Neos/Resources/Public/Styles/Neos.css
This orders the results in the backend user management module by username and introduces a pager. Furthermore I implemented a search field to search in usernames and full names
> FEATURE: Implement pager, ordering and search in user management module

- .github/stale.yaml
Add Stalebot configuration.
See https://discuss.neos.io/t/rfc-introduce-stale-bot-on-dev-collections/4371
> TASK: Add StaleBot configuration file

- Neos.Neos/Resources/Private/Fusion/Prototypes/Menu.fusion
**What I did**
Correctly pass the current node to menu templates in a way that does not cause an infinite loop
See also: #2532 
- Revert back to behaviour removed in https://github.com/neos/neos-development-collection/commit/6f302f19d2d6dcf4293223d801d867d9fd1d208e#diff-033bf88345978204633d4a60db6f410cL5
See #2532
> BUGFIX: Correctly pass current node to menu templates

- Neos.Neos/Classes/Utility/BackendAssetsUtility.php
**What I did**
Removed a elseif condition that was exactly the same than the if condition before.
> TASK: Removes duplicate condition

- Neos.ContentRepository/Classes/Migration/Filters/PropertyValue.php
Adds a new filter to match against property values in node migrations.
> FEATURE: Add PropertyValue node migration filter

- Neos.ContentRepository/Tests/Unit/Domain/Service/ImportExport/NodeExportServiceTest.php
- Neos.Media/Tests/Functional/Domain/Model/AssetTest.php
- Neos.Neos/Classes/Fusion/Helper/NodeHelper.php
- Neos.Neos/Classes/ViewHelpers/Backend/ContainerViewHelper.php
- Neos.Neos/Documentation/References/PropertyEditorReference.rst
- Neos.Neos/Tests/Functional/Configuration/ConfigurationValidationTest.php
Merge after https://github.com/neos/neos-ui/pull/2538
> TASK: Update documentation about inline validators

- Neos.Neos/Documentation/References/NodeMigrations.rst
**What I did**
Fix option name for NodeName filter in the documentation
Check that the doc is accurate with the source code of the Filter
> TASK: Fix option name for NodeName filter

- Neos.Neos/Documentation/References/EelHelpersReference.rst
**What I did**
Add more information for Eel Translation helper:
- existence of I18n alias
- add more doc for Translation.translate's source argument
- add an example
Check that the doc is accurate
> TASK: Add more doc for Eel Translation.translate

- Neos.Neos/Documentation/CreatingASite/ContentCache.rst
> TASK: Fixed Typo in  ContentCache.rst

- Neos.Neos/Documentation/References/PropertyEditorReference.rst
Merge after https://github.com/neos/neos-ui/pull/2546
> TASK: Document RichTextEditor

- Neos.Media.Browser/Classes/Controller/AssetController.php
> BUGFIX: Updating an asset throws an exception due to unavailable translation

- Neos.Neos/Tests/Unit/Fusion/PluginImplementationTest.php
This adjusts the test to the PSR-7 changes.
> BUGFIX: Fix PluginImplementation unit test

- Neos.ContentRepository/Classes/ViewHelpers/Widget/PaginateViewHelper.php
> BUGFIX: PaginateViewHelper in CR calls method on string

- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
This "fixes" https://github.com/doctrine/orm/issues/7827, by
actually passing the correct type as parameter. And the "type
hint" can be removed, as well.
> BUGFIX: Remove Connection::PARAM_STR_ARRAY hint

- Neos.Media/Classes/Domain/Model/Image.php
- Neos.Media/Classes/Domain/Model/VariantSupportInterface.php
This is one way to solve the shortcoming of #2701 - or we leave out the
return type in the interface and implementations can specify their
concrete return type.
> !!!TASK: Fix getVariant() return type

- Readme.rst
This should help people onboard for contribution, as it is not obvious that one has to install the development-distribution and the information for that is not that easy to find and then very elaborate. This is the perfect place to have it in a TL;DR style
> TASK: Mention the basic development setup steps in the readme

- Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
> BUGFIX: Call PSR logger with warning directly

- Neos.Media/Classes/Command/MediaCommandController.php
This unifies the CLI interface and makes the quiet flag available
consistently with all media commands.
> TASK: Add quiet flag to all Neos.Media CLI commands

- Neos.Media/Classes/Domain/Model/Adjustment/AbstractAdjustment.php
- Neos.Media/Classes/Domain/Model/Adjustment/AbstractImageAdjustment.php
- Neos.Media/Classes/Domain/Model/Adjustment/AdjustmentInterface.php
- Neos.Media/Classes/Domain/Model/Adjustment/CropImageAdjustment.php
- Neos.Media/Classes/Domain/Model/Adjustment/ImageAdjustmentInterface.php
- Neos.Media/Classes/Domain/Model/Adjustment/QualityImageAdjustment.php
- Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php
- Neos.Media/Classes/Domain/Model/Dto/UsageReference.php
- Neos.Media/Classes/Domain/ValueObject/Configuration/Adjustment.php
- Neos.Media/Classes/Domain/ValueObject/Configuration/README.md
- Neos.Media/Classes/Domain/ValueObject/Configuration/Variant.php
This PR
- cleans up code, applies (strict) typing
- allows numbers and dash in adjustment and variant identifiers
- tweaks value object README a bit
> TASK: Asset variant tweaks

- Neos.Fusion/Classes/Core/Runtime.php
- Neos.Fusion/Tests/Unit/Core/RuntimeTest.php
**What I did**
* Fusion performance optimizations for less function calls and faster code paths for expression and value evaluation
* Inlined some functions
* Removed usage of `end()` to get last item in array (needs a micro benchmark)
* Introduced fast checks around apply, if and processors
* Implemented fast path for expressions and values
* Less function calls, smaller call stack
* Needs a benchmark to measure micro optimizations
> TASK: Fusion performance optimizations (less calls)

- Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
Fixes https://github.com/neos/neos-development-collection/issues/2775
> BUGFIX: Fix default variable value

- Neos.Neos/Classes/Controller/LoginController.php
**What I did**
Replaced the old systemLogger by logger in LoginController in Neos.Neos.
See code changes.
Run tests.
**Checklist**
> BUGFIX: Replace $this->systemLogger by $this->logger in LoginController

- Neos.Neos/Classes/Controller/Frontend/NodeController.php
The correct preview of a hidden document is not showing it, after all…
> TASK: Remove showInvisible query parameter handling again

- Neos.Media/Classes/TypeConverter/AssetInterfaceConverter.php
> TASK: Prevent AssetInterfaceConverter to run into an exception

- Neos.Neos/Classes/Controller/LoginController.php
push already merged #2769 code into 5.0 branch
> BUGFIX: Prevent exception from logger in login controller

- Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Asset change leads to exception if unpublished changes in others users workspaces exists, which are referenced to affected asset. Neos tries to access the others user workspace to get the node with the reference to flush there caches. By privilege `Neos.Neos:Backend.OtherUsersPersonalWorkspaceAccess` this is not allowed.
```
Access denied for method
Method: Neos\ContentRepository\Domain\Service\Context::validateWorkspace()
Evaluated following 1 privilege target(s):
"Neos.Neos:Backend.OtherUsersPersonalWorkspaceAccess": ABSTAIN
(0 granted, 0 denied, 1 abstained)
Authenticated roles: Neos.Flow:Everybody, Neos.Flow:AuthenticatedUser, Neos.Neos:Editor, Neos.Neos:AbstractEditor, Neos.ContentRepository:Administrator, Neos.ContentRepository:InternalWorkspaceAccess, Neos.Neos:LivePublisher, …
```
> BUGFIX: Allow content cache flush for asset references in other use workspaces

- Neos.Fusion/Classes/Service/HtmlAugmenter.php
- Neos.Fusion/Tests/Unit/Service/HtmlAugmenterTest.php
- Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
> 4.0 - 4.1 Upmerge

- Neos.ContentRepository/Classes/Domain/Model/Node.php
- Neos.ContentRepository/Classes/Domain/NodeAggregate/Exception/NodeAggregateIdentifierIsInvalid.php
- Neos.ContentRepository/Classes/Domain/NodeType/NodeTypeName.php
- Neos.ContentRepository/Classes/Domain/Projection/Content/NodeInterface.php
This adds support for explicit OriginDimensionSpacePoints as well as utility methods
> Make adjustments to the latest ES CR version

- .composer.json
Did miss that while up merging
> BUGFIX: Fix version constraint after upmerge

- Neos.Neos/Classes/NodeTypePostprocessor/CreationDialogPostprocessor.php
- Neos.Neos/Tests/Unit/Domain/NodeTypePostprocessor/CreationDialogPostprocessorTest.php
Improves the `CreationDialogPostprocessor` so that it...
* does not access the `NodeType::getConfiguration()` but acts
solely on the passed in `$configuration` array
* works for properties without `ui.inspector` configuration (for
example inline editable properties)
Related: #2173
> BUGFIX: Improve CreationDialogPostprocessor

- Neos.Neos/Classes/Controller/LoginController.php
> BUGFIX: Fix regression breaking login to Neos

- Neos.Media.Browser/Classes/Controller/AssetController.php
This code should have been removed when the `ImageVariantController`
was introduced in 0aa2eed015e02a468f9b2e8e1d08f8275349edde. Which
means it should have never been there. ;)
> TASK: Remove unused code

- Neos.ContentRepository/Classes/Domain/Model/NodeType.php
- Neos.Neos/Classes/Aspects/NodeTypeConfigurationEnrichmentAspect.php
> BUGFIX: NodeType inheritance is not working correct

- Neos.Media.Browser/Configuration/Views.yaml
> BUGFIX: Prevent exception in asset usage view via editor

- Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php
As per discussion in https://github.com/neos/neos-development-collection/pull/2738#discussion_r403867758
/cc @bwaidelich
> TASK: Throw exception when lazy props are attempted to be changed

- Neos.Neos/Resources/Private/Styles/Lite.scss
- Neos.Neos/Resources/Public/Styles/Lite.css
They got lost in the style split for 5.2 in #2874
> BUGFIX: Add missing pagination styles for media browser

- Neos.Neos/Classes/Controller/LoginController.php
**What I did**
Check view type before setting fusion paths
See above
Close #2990
> BUGFIX: Resolve error when backend session times out

- Neos.Neos/Resources/Private/Fusion/Backend/Views/Login.fusion
> BUGFIX: Fix login screen if no background image is set

- Neos.ContentRepository/Classes/Domain/NodeType/NodeTypeConstraintFactory.php
- Neos.ContentRepository/Classes/Domain/NodeType/NodeTypeConstraints.php
- Neos.ContentRepository/Tests/Behavior/Features/Security/EditNodePrivilegeBasedOnDimension.feature
- Neos.Media.Browser/Resources/Public/JavaScript/Main.js
- Neos.Media/Classes/Domain/Model/Asset.php
- Neos.Media/Classes/Domain/Model/ImageVariant.php
- Neos.Media/Classes/Domain/Service/ThumbnailService.php
- Neos.Neos/Classes/EventLog/Integrations/ContentRepositoryIntegrationService.php
- Neos.Neos/Classes/Service/BackendRedirectionService.php
- Neos.Neos/Classes/Service/NodeTypeSchemaBuilder.php
- Neos.Neos/Documentation/CreatingASite/Security.rst
Matching change with https://github.com/neos/flow-development-collection/pull/2024
> TASK: Improve wording of include/exclude concepts where possible

- Neos.Neos/Resources/Private/Styles/_Notifications.scss
- Neos.Neos/Resources/Public/Styles/Lite.css
- Neos.Neos/Resources/Public/Styles/Main.css
- Neos.Neos/Resources/Public/Styles/Minimal.css
**What I did**
Changed the font-family to the correct value `Font Awesome 5 Free`
Change a user in the backend for instance and check the flashmessage.
Fixes: #3069
> BUGFIX: Repair icon rendering for flash messages

- Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
- Neos.Neos/Classes/Domain/Service/UserService.php
- Neos.Neos/Classes/ViewHelpers/Backend/IsAllowedToEditUserViewHelper.php
- Neos.Neos/Configuration/Policy.yaml
- Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
- Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Show.html
- Neos.Neos/Resources/Private/Translations/en/Modules.xlf
This introduces a new role `Neos.Neos:UserManager`. When an editor has that role, he is able to manage users with roles not exceeding his own, without being an Administrator.
> FEATURE: User management for non-admins

- Neos.Media/Migrations/Mysql/Version20200828170100.php
- Neos.Media/Migrations/Postgresql/Version20200828170101.php
> BUGFIX: Migrate icons from TYPO3.Media to Neos.Media

- Neos.Neos/Classes/Controller/Backend/BackendController.php
- Neos.Neos/Classes/Controller/LoginController.php
- Neos.Neos/Classes/Service/BackendRedirectionService.php
- Neos.Neos/Classes/Service/XliffService.php
Code cleanup and method typing in preparation of #2351 
No functional changes.
> TASK: Code cleanup in backend login area

- Neos.Neos/Configuration/Settings.yaml
> TASK: Remove unused legacy UI setting

- Neos.Media/Classes/ViewHelpers/ImageViewHelper.php
- Neos.Media/Documentation/References/ViewHelpers.rst
- Neos.Neos/Documentation/References/NeosFusionReference.rst
- Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion
- Neos.NodeTypes/Resources/Private/Fusion/NodeTypes/Image.fusion
- Neos.NodeTypes/Resources/Private/Templates/NodeTypes/Partials/SimpleImage.html
> FEATURE: Lazy loading images

- Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion
> BUGFIX: Fix Compatibility fallback after switching from Neos.Fusion:Collection to Neos.Fusion:Loop

- .travis.yml
See https://github.com/neos/flow-development-collection/issues/2236
> TASK: Remove PHP 7.2 builds

- Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
- Neos.Media/Classes/Domain/Repository/AssetRepository.php
- Neos.Neos/Classes/EventLog/Domain/Repository/EventRepository.php
See https://github.com/neos/flow-development-collection/issues/2231
> BUGFIX: Adjust to typed persistence code

- Neos.ContentRepository/composer.json
- composer.json
depends on #3177
Related to neos/flow-development-collection#2122
Required for neos/flow-development-collection#2247 et.al.
> TASK: Update gedmo/doctrine-extensions to 3.0

- Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php
- Neos.Neos/Classes/Routing/NodeIdentityConverterAspect.php
> BUGFIX: Adjust NodeIdentityConverterAspect to typed persistence

- Neos.Fusion/Classes/Core/Parser.php
- Neos.Fusion/Classes/FusionObjects/CollectionImplementation.php
- Neos.Fusion/Classes/FusionObjects/RawCollectionImplementation.php
- Neos.Fusion/Classes/FusionObjects/TagImplementation.php
- Neos.Fusion/Classes/FusionObjects/TemplateImplementation.php
- Neos.Fusion/Classes/FusionObjects/ValueImplementation.php
- Neos.Fusion/Tests/Functional/FusionObjects/CaseTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/CollectionTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/ExceptionHandlerTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/WrappedNestedObjectRenderer.php
- Neos.Fusion/Tests/Functional/FusionObjects/RawCollectionTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/RendererTest.php
> FEATURE: Replace TS in comments with Fusion

- Neos.Fusion/Classes/FusionObjects/AttributesImplementation.php
- Neos.Fusion/Resources/Private/Fusion/Root.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/ApplyTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/ConditionsTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Apply.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Conditions.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ContentCache.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/NestedOverwritesAndProcessors.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/QuotedKeys.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ReservedKeys.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Tag.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/QuotedKeysTest.php
- Neos.Fusion/Tests/Unit/FusionObjects/DataStructureImplementationTest.php
- Neos.Neos/Resources/Private/Fusion/Prototypes/ContentElementWrapping.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/NodeLink.fusion
- Neos.Neos/Resources/Private/Fusion/Prototypes/NodeUri.fusion
- Neos.Neos/Tests/Functional/Fusion/Fixtures/Test_AppendingClassesToContent.fusion
- Neos.NodeTypes.Form/Resources/Private/Fusion/Root.fusion
> FEATURE: Replace RawArray with DataStructure

- Neos.Fusion/Tests/Functional/FusionObjects/MapTest.php
> FEATURE: Replace test function names to map prototype name in Map test

- Neos.Fusion/Classes/FusionObjects/AbstractArrayFusionObject.php
- Neos.Fusion/Classes/FusionObjects/AugmenterImplementation.php
- Neos.Fusion/Classes/FusionObjects/CaseImplementation.php
- Neos.Fusion/Classes/FusionObjects/ComponentImplementation.php
- Neos.Fusion/Classes/FusionObjects/DebugImplementation.php
- Neos.Fusion/Resources/Private/Fusion/Root.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/ApplyTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/ContentCacheTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Apply.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ContentCache.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ContextOverride.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ExceptionHandler.fusion
- Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestFusionFixture18.fusion
- Neos.Fusion/Tests/Unit/Core/ParserTest.php
- Neos.Fusion/Tests/Unit/FusionObjects/JoinImplementationTest.php
- Neos.Neos/Resources/Private/Fusion/Prototypes/Page.fusion
> FEATURE: Replace Neos.Fusion:Array with Neos.Fusion:Join

- Neos.Fusion/Tests/Functional/FusionObjects/ApplyTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/ExceptionHandlerTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Apply.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ContentCache.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/ExceptionHandler.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/Template.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/LoopTest.php
- Neos.Neos/Resources/Private/Fusion/RawContentMode.fusion
- Neos.NodeTypes.ColumnLayouts/Resources/Private/Fusion/Root.fusion
- Neos.NodeTypes.ContentReferences/Resources/Private/Fusion/Root.fusion
> FEATURE: Replace Fusion:Collection with Fusion:Loop

- Neos.Neos/Classes/Aspects/FusionCachingAspect.php
- Neos.Neos/Tests/Unit/Aspects/FusionCachingAspectTest.php
> BUGFIX: Align fusion caching and service

- Neos.Neos/Classes/Routing/FrontendNodeRoutePartHandler.php
- Neos.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php
This adjusts the `FrontendNodeRoutePartHandler` so that it
can more easily be used for custom routes:
route parts
An `uriPattern` of "{node}/some/custom/part" did not work with
the previous version since the `uriPath` was replaced completely
when the route resolved a given node.
With the bug above fixed the route part handler can be used in
custom routes, but it would work for all nodes.
So for every `valid/uri` a corresponding `valid/uri/some/custom/part`
would match to the same node.
To prevent that, a new option `nodeType` was added that allows the
route to only apply for nodes of the specified type:
```yaml
-
name:  'Custom'
uriPattern: '{node}/custom.html'
defaults:
'@package':    'Neos.Neos'
'@controller': 'Frontend\Node'
'@action':     'show'
'@format':     'html'
custom: …
```
> FEATURE: Stabilize and extend Frontend Routing

- Neos.ContentRepository/Tests/Unit/Domain/Model/NodeDataTest.php
- Neos.ContentRepository/Tests/Unit/Domain/Service/NodeServiceTest.php
- Neos.ContentRepository/Tests/Unit/TypeConverter/NodeConverterTest.php
- Neos.Fusion/Tests/Unit/Core/Cache/ContentCacheTest.php
- Neos.Neos/Tests/Functional/Service/NodeTypeSchemaBuilderTest.php
- Neos.Neos/Tests/Unit/Service/PublishingServiceTest.php
- composer.json
> TASK: Use PhpUnit 9

- Neos.Neos/Resources/Private/Styles/TopBar/_TopBar.scss
- Neos.Neos/Resources/Public/Styles/Includes-built.css
- Neos.Neos/Resources/Public/Styles/Lite.css
- Neos.Neos/Resources/Public/Styles/Main.css
- Neos.Neos/Resources/Public/Styles/Minimal.css
- Neos.Neos/Resources/Public/Styles/Neos.css
Remove border from logout button in the user menu ot the top nav.
Fixes: #3296
> BUGFIX: Adjust logout button style

- .github/workflows/build.yml
This should work around an edge-case regression in doctrine/migrations 3.1.1 - see https://github.com/neos/neos-development-collection/pull/3311#issuecomment-803560353
> TASK: Mark migrations as applied after behat setup

- Readme.rst
Fix the latest maintained LTS version and the increase the current version.
> TASK: Adjust versions in Readme

- Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/Index.html
> FEATURE: Show the default asset-collection in the sites listing

- Neos.Neos/Classes/Controller/LoginController.php
- Neos.Neos/Classes/Controller/Module/Administration/ConfigurationController.php
- Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
- Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
- Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
- Neos.Neos/Classes/Controller/Module/User/UserSettingsController.php
- Neos.Neos/Resources/Private/Translations/de/Main.xlf
- Neos.Neos/Resources/Private/Translations/de/Modules.xlf
- Neos.Neos/Resources/Private/Translations/en/Main.xlf
- Neos.Neos/Resources/Private/Translations/en/Modules.xlf
**What I did**
added translation to all flash messages
added translator and translation units to all flash messages
Fixes: #3334
> FEATURE: Add missing translation to flash messages

- Neos.Fusion/Classes/FusionObjects/HttpResponseImplementation.php
- Neos.Neos/Classes/Fusion/ExceptionHandlers/PageHandler.php
see #3368
Tested with the Neos.Demo Site.
> TASK: Replace depreated guzzle functions

- Neos.Neos/Classes/EventLog/Domain/Model/Event.php
#3341 build failures made me aware of this
> BUGFIX: Fix cascade argument of childEvents relation

- Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
- Neos.Neos/Resources/Private/Translations/en/Modules.xlf
> FEATURE: Show the last login date in the user/account list

- Neos.Neos/Classes/Service/IconNameMappingService.php
Show hotel icon instead of bed
Relates: #2697
> BUGFIX: Use correct hotel icon mapping

- .editorconfig
Aligns the file with the one in the Flow development collection.
> TASK: Simplify rules, handle markdown files in .editorconfig

- Neos.Neos/Resources/Private/Translations/en/Main.xlf
- Neos.Neos/Resources/Private/Translations/en/Modules.xlf
Fixes a duplicate id and the use of literal HTML tags in XLIFF.
> BUGFIX: Fix two errors in Modules.xlf

- Neos.Neos/Resources/Private/Translations/en/Modules.xlf
> BUGFIX: Fix wrong translation strings

- Neos.ContentRepository/Migrations/TYPO3CR/Version20150716212459.yaml
> BUGFIX: Exclude "/sites"-node from dimension-migration

- Neos.Neos/Classes/Eel/FlowQueryOperations/SortOperation.php
> BUGFIX: Add missing documentation of third parameter in sort operation

- Neos.Neos/Documentation/References/PropertyEditorReference.rst
Add documentation  for newly added range slider https://github.com/neos/neos-ui/pull/2986
> TASK: Add documentation of range slider

- Neos.CliSetup/Classes/Command/WelcomeCommandController.php
**What I did**
I have adapted the description for the `user:create` command.
I have customized the `WelcomeCommandController.php`.
> TASK: improve admin command description

- Neos.Fusion/Classes/Core/Parser.php
- Neos.Fusion/Classes/Core/Runtime.php
- Neos.Fusion/Classes/FusionObjects/ResourceUriImplementation.php
- Neos.Fusion/Classes/FusionObjects/UriBuilderImplementation.php
- Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestFusionFixture03.fusion
- Neos.Fusion/Tests/Unit/Core/Parser/PatternTest.php
- Neos.Neos/Tests/Functional/Fusion/RenderingTest.php
- Neos.NodeTypes.ColumnLayouts/Resources/Private/Fusion/Root.fusion
- Neos.NodeTypes.ContentReferences/Resources/Private/Fusion/Root.fusion
- Neos.NodeTypes.Form/Resources/Private/Fusion/Root.fusion
I've found some old `TS` (TypoScript) wording in the code. I replaced it with `Fusion`
> TASK: Replace TS (TypoScript) with Fusion

- Neos.Neos/Documentation/References/NodeTypeDefinition.rst
fixes: #3612
Thanks to MonTea from Slack reporting that, we appreciate it!
> BUGFIX: Remove unused formatting options

- .github/workflows/build.yml
- Neos.CliSetup/composer.json
- Neos.ContentRepository/composer.json
- Neos.Diff/composer.json
- Neos.Fusion/composer.json
- Neos.Media.Browser/composer.json
- Neos.Media/composer.json
- Neos.Neos/composer.json
- Neos.NodeTypes.Form/composer.json
- Neos.SiteKickstarter/composer.json
- composer.json
Adjust composer json and test matrix to match raised version requirements for flow.
Resolves: #3625
> !!! TASK: Raise minimal supported PHP version to 8.0.0

- Neos.Media/Classes/Domain/Service/ThumbnailService.php
> BUGFIX: Only emit thumbnailCreated when successful

- Neos.Media/Classes/Domain/Model/ImageVariant.php
> BUGFIX: Initialize assetCollections in ImageVariant

- Neos.Neos/Classes/Controller/Module/Administration/SitesController.php
See neos/flow-development-collection#2774
> TASK: Drop $packagePath from getFilteredPackages()

- Neos.Fusion/Classes/FusionObjects/AbstractArrayFusionObject.php
- Neos.Fusion/Classes/FusionObjects/AbstractFusionObject.php
- Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php
- Neos.Fusion/Tests/Unit/Core/Parser/ParserTest.php
- Neos.Fusion/Tests/Unit/Core/ParserTest.php
- Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php
- Neos.Neos/Tests/Unit/Domain/Service/DomainMatchingStrategyTest.php
- Neos.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php
> BUGFIX: Adjust code leading to deprecation warnings with PHP 8.1

- Neos.ContentRepository/Classes/Domain/Service/NodeTypeManager.php
- Neos.ContentRepository/Configuration/Caches.yaml
- Neos.ContentRepository/Configuration/Objects.yaml
- Neos.ContentRepository/Configuration/Production/Caches.yaml
- Neos.ContentRepository/Tests/Unit/Domain/Service/NodeTypeManagerTest.php
- Neos.Fusion/Tests/Functional/FusionObjects/Fixtures/Fusion/NestedOverwritesAndProcessors.fusion
- Neos.Fusion/Tests/Functional/FusionObjects/NestedOverwritesAndProcessorsTest.php
> 7.0 - Test upmerges

- Neos.Neos/Classes/Controller/Module/Administration/UsersController.php
- Neos.Neos/Classes/Domain/Repository/UserRepository.php
- Neos.Neos/Classes/Domain/Service/UserService.php
- Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
If you go to the User Management Backend Module: Administration -> User Management, it's now possible to sort by the Name, The Accounts, and the last login by clicking on the specific header.
> FEATURE: allow sorting in user management backend module

- Neos.ContentRepository/Classes/Migration/Transformations/ChangePropertyValue.php
> BUGFIX: Do not treat every given value as string

- Neos.Media/Classes/Domain/Strategy/ThumbnailGeneratorStrategy.php
This makes the `ThumbnailGeneratorStrategy` continue with the next
available thumbnail generator in case `refresh()` failed. This allows
for a "fallback" to be used in case thumbnail generation fails.
Errors are logged to aid with debugging and if all generators fail
another separate error is logged.
See neos/neos-development-collection#3678 for some background info.
**Upgrade instructions**
**Review instructions**
**Checklist**
> TASK: Continue on error in ThumbnailGeneratorStrategy

- Neos.Neos/Classes/Controller/Service/NodesController.php
- Neos.Neos/Resources/Private/Templates/Service/Nodes/Show.html
Basis for https://github.com/neos/neos-ui/pull/3173
Related: #3862
> 9.0 Fix dimension switching

- Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php
Adjusts the `NodeDataToEventsProcessor` such that it creates/augments a `meta.json` file
that contains the export format version and details about the exported site.
Resolves: #3868
> 9.0: FEATURE: Add Migration Metadata to export format

- Neos.ContentRepository.Export/src/Processors/EventStoreImportProcessor.php
- Neos.ContentRepository.LegacyNodeMigration/Classes/Command/ContentRepositoryMigrateCommandController.php
- Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationService.php
- Neos.ContentRepository.LegacyNodeMigration/Classes/LegacyMigrationServiceFactory.php
- Neos.ContentRepository/src/Factory/ContentRepositoryIdentifier.php
- Neos.ContentRepository/src/Service/ContentRepositoryBootstrapper.php
- Neos.Neos/Classes/Domain/Service/SiteServiceInternals.php
> 9.0: FEATURE: Legacy migration: Allow target site to be specified/pruned

- Neos.Media/Configuration/Settings.yaml
- Neos.Neos/Configuration/Settings.yaml
See https://github.com/neos/doctools/pull/4
**Checklist**
> TASK: Adjust Neos.DocTools settings

- .github/workflows/build.yml
**Review instructions**
The build on PHP 8.1 should succeed.
> TASK: Add PHP 8.1 to build matrix
