neos/neos-development-collection

TYPO3.Neos/Tests/Functional/Command/BehatTestHelper.php
TYPO3.TYPO3CR/Tests/Functional/Command/BehatTestHelper.php

In order to accomodate running the tests with the new joined
repositories as well as the read-only ones the require path
must be relative to the current path to avoid passing the
Application/Neos folder.
Releases: master, 3.0

[TASK] Resolve test trait paths relatively

---

TYPO3.Neos/composer.json

Adapts the Neos composer.json to the new configuration for
installer resources that works with joined repositories.
The old configuration (which won't be used anymore) is
kept for backwards compatibility reasons but should be removed
soon.
Releases: master, 2.0, 1.2

[TASK] Adapt Neos composer.json to new installer script

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/NodesController.php

The ``Service\NodesController`` should refer to the
``NodeSearchServiceInterface`` instead of the implementation class
to avoid hard dependencies and allow overwriting the implementation
from the outside.
Change-Id: I4ae7222e195d3fdfa4fd1b5b21ef17b878538e6d
Releases: master, 2.0

[BUGFIX] Service\NodesController should stick to interfaces

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/AssetCollection.php

When running a doctrine:validate an error is shown for the Tag model
since it does not contain the required inversedBy attribute. This
change fixes that by adding it.
Fixes: NEOS-1507
Releases: master, 2.0

[BUGFIX] Add inversedBy attribute to association

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/DateTimeEditor.js

If reset to null, the date picker would default to 1899 instead of the
current date when being opened again.
Fixes: NEOS-1351

[BUGFIX] Reset date picker to current date instead of null

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This change introduces a new sub command for node:repair which detects
and removes node property references to entities which don't exist.
One practical example are Image nodes whose "image" property points to
ImageVariant objects which, for whatever reason, have been removed
in the meantime. For these nodes, node:repair will now set the "image"
property to NULL.
Releases: master

[FEATURE] node:repair sub command for removing broken entity references

---

TYPO3.Neos/Documentation/HowTos/IntegratingJavaScriptSlider.rst

Since Neos 2.0 you have to write content.iterationName instead of iterationName.

[BUGFIX] Adjust carousel node type example

---

CodeOfConduct.rst

This adds a reStructuredText version of the Contributor Covenant
code of conduct, to make it clear the project is governed by that.
See also http://contributor-covenant.org/version/1/2/0/

[TASK] Add Code of Conduct

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/PluginViewImplementation.php

Prevents PluginViews with a master plugin selected that cannot be found
from throwing a fatal error. This can happen when the master plugin is
removed/moved or is not available in the context.
Fixes: NEOS-1530

[BUGFIX] Prevent fatal error for missing master plugin in PluginViews

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/LinkingService.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ConvertUrisImplementation.php
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/ConvertUris.ts2
TYPO3.Neos/Tests/Unit/TypoScript/ConvertUrisImplementationTest.php

Previously the ConvertUris helper just created relative links.
This change introduces a new setting `createAbsoluteUris`:
someTextProperty.@process.1 = TYPO3.Neos:ConvertUris {
absolute = true
}
Resolves: NEOS-1534

[FEATURE] Support creating absolute node uris

---

TYPO3.Neos/Configuration/NodeTypes.yaml
TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/InspectorView.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Section.js

This change introduces a new option for the Nodetypes configuration
which defines if a specific inspector group should be collapsed by
default. If a user decides to expand a group in the inspector, this
state (which is stored in Local Storage) takes precedence.
Example:
```yaml
groups:
nodeInfo:
label: i18n
tab: 'meta'
position: 1000
collapsed: true
```
Related: NEOS-1045
Releases: master

[FEATURE] Nodetype option for collapsing inspector group by default

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/LinkEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/MasterPluginEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/NodeTypeEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/PluginViewEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/PluginViewsEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferenceEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferencesEditor.js

Changes the usage of "Loading ..." labels to be used consistently
across the user interface.
Resolves: NEOS-1539

[TASK] Streamline "Loading ..." labels

---

TYPO3.Neos/Documentation/ExtendingNeos/InteractionWithTheNeosBackend.rst
TYPO3.Neos/Resources/Public/JavaScript/Content/FullScreenController.js

This change introduces two new JavaScript events triggered when toggling fullscreen mode.
``Neos.FullscreenModeActivated`` will be dispatched when the backend switches to fullscreen mode.
``Neos.FullscreenModeDeactivated`` will dispatch if the backend leaves the fullscreen mode.
Fixes: NEOS-1546

[TASK] Introduce new JavaScript events for fullscreen mode

---

TYPO3.Neos/Classes/TYPO3/Neos/Setup/Step/FinalStep.php

If you want to try out Neos and you just run the setup your installation
will afterwards still run in development context and you might be
disappointed of the speed. So we add a hint, that there's additional
action required in order to run Neos in production context and experience
its full speed.
Resolves: NEOS-1429

[TASK] add hint for application context in last setup step

---

TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosLicenseHeader.html
TYPO3.Neos/Tests/Functional/TypoScript/RenderingTest.php

Removes a superfluous "the" in the license header, it's
not "THE Neos".

[BUGFIX] Fix license header text

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/Helper/CachingHelper.php

Cache entry tags are case sensitive.

[BUGFIX] CachingHelper generation of entry tags for descendants of a node

---

TYPO3.Neos.NodeTypes/Resources/Private/Templates/NodeTypes/Form.html

This change allow to override the Form configuration from TypoScript::
prototype(TYPO3.Neos.NodeTypes:Form) {
overrideConfiguration = TYPO3.TYPO3TypoScript:RawArray {
finishers = TYPO3.TypoScript:RawArray {
copy = TYPO3.TypoScript:RawArray {
options = TYPO3.TypoScript:RawArray {
recipientAddress = ${q(node).property('email')}
}
}
}
}
}
Change-Id: Ic82428c61992ae6c2729806360bbeccfda1fabd1
Releases: master
Depends: I51b4ad9f2c1e4abed271e7586f4c828137842c1f

[TASK] Allow to override TYPO3.Form configuration from TS

---

TYPO3.Neos.NodeTypes/Resources/Private/TypoScript/Root.ts2

Add descendants of referenced nodes to cache tags of the "Content References"
node type. This ensures that nested nodes inside a node inserted as a reference
will be updated when those nodes are flushed.

[BUGFIX] Flush on change of descendants of referenced node

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php

Removes superfluous quotes around PluginView label seen in the plugin view editor for plugin views.

[TASK] Remove superfluous quotes from PluginView label

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/PluginViewEditor.js

When changing the master view selection for a PluginView,
the selected plugin view is not unset causing confusion.
Fixes: NEOS-1541

[BUGFIX] Unset selected plugin view when changing master view

---

TYPO3.Neos/Configuration/NodeTypes.yaml

Positions the master plugin selection in the inspector for a PluginView above
instead of undernearth the plugin view selection, to avoid confusion since
the plugin view selection depends on the master plugin selection.
Fixes: NEOS-1544

[BUGFIX] Position master plugin selection above plugin view selection

---

TYPO3.Neos/Classes/TYPO3/Neos/View/TypoScriptView.php

When the fallback node mode is triggered, the ``documentNode`` TypoScript
variable is empty leading to various issues. This solves that by using the
current node as the document node in that case.
Fixes: NEOS-1624

[BUGFIX] Use current node as document node if no document node is found

---

TYPO3.TYPO3CR/Tests/Functional/Migration/Domain/Repository/MigrationStatusRepositoryTest.php

The MigrationStatusRepositoryTest used invalid fixture data, the
direction was filled with strings that were too long for the related
DB column. On MySQL this is silently truncated, but on PostgreSQL it
leads to an error.
Now the expected class constants are used in the test.

[BUGFIX] No longer use invalid data in functional test

---

.gitattributes

When merging a lower branch to an upper one the built files often conflict.
To avoid that the file in the current branch is used when solving conflicts.
This is done using ``.gitattributes`` stored in the root of the repository.
Enable this with::
git config merge.ours.driver true

[TASK] Ignore built JavaScript/CSS files during merge

---

TYPO3.Neos/Tests/Behavior/Features/Bootstrap/HistoryDefinitionsTrait.php
TYPO3.Neos/Tests/Behavior/Features/Content/PublishUserWorkspace.feature
TYPO3.Neos/Tests/Behavior/Features/EventLog/Entities/AccountsUsers.feature
TYPO3.Neos/Tests/Functional/Command/BehatTestHelper.php
TYPO3.TYPO3CR/Tests/Functional/Command/BehatTestHelper.php

Using relative paths fails when using isolated tests that are run
in a subprocess. To support the development collection and
read-only repositories full paths are used by checking which
structure is present.
Related: cdbffb7f5ab28d630601c733e97568c27a8b0cbf

[BUGFIX] Behat tests

---

TYPO3.Neos/Documentation/References/PropertyEditorReference.rst

Documentation of the `defaultValue` option for the `DateTime` property type.

[TASK] Document `defaultValue` for `DateTimeEditor`

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php

When the "/sites" root node or it's children cannot be found a fatal error
is thrown or it's silently ignored. Instead output an error message that the
nodes could not be found.

[BUGFIX] Prevent fatal error in ``node:repair`` with broken node structure

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Link/NodeViewHelper.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Uri/NodeViewHelper.php
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Breadcrumb.ts2
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Menu.ts2
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/NodeUri.ts2

- Gracefully handle exceptions in the NodeUri TS object
- Gracefully handle exceptions in node linking view helpers
Resolves: NEOS-1625

[BUGFIX] Graceful handling of node linking exceptions

---

TYPO3.Neos/Documentation/References/PropertyEditorReference.rst
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/SelectBoxEditor.js

The JavaScript widget we use for select boxes supports a search
feature to quickly find an entry. The threshold for showing the
search box was hardcoded with a value of 5 entries, but different
values can make sense depending on the project. Therefore this
value now becomes configurable with the default still being ``5``.
```
editorOptions:
minimumResultsForSearch: -1
```
This example configuration would set the minimum to -1 effectively
deactivating the search box. Any value greater or equal ``0`` will
show the search box when the entries in the select are more than
the configured value.

[FEATURE] Make SelectBoxEditor search configurable

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ExceptionHandlers/PageHandler.php

If an exception is thrown while rendering a page with an alternative format
like .json, the ExceptionHandlers\PageHandler tries to fetch a layout for this alternative
format which raises another exception: `#1288092555: Could not load layout file`
Switching the setters of the RequestHandler and the format always renders the
exception as HTML.

[BUGFIX] Render exception in HTML even if an other format is given

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ImportExport/NodeImportService.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/ImportExport/Fixtures/SingleNode.xml
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/ImportExport/NodeImportServiceTest.php

The closing tags for the ``hiddenBeforeDateTime`` and ``hiddenAfterDateTime``
properties were not handled in the node import service.
Resolves: NEOS-1554

[BUGFIX] Hidden before/after properties breaks site import

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/NodeTypeManager.php

Splits the NodeTypeManager into smaller methods and reduces
overall complexity.

[TASK] Make NodeTypeManager easier to read

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/PluginViewImplementation.php
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/PluginView.ts2

Removes the custom handling of exceptions for PluginViews, which is limited
and unnecessary. Instead the general NodeWrapping exception handler is used.
Resolves: NEOS-1537

[TASK] Remove custom exception handling in PluginViewImplementation

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/PluginViewImplementation.php

Regression introduced in 13517506b9ae5ac0050b5336266677b2ee4e3963
by using wrong variable name for the current node in the ``PluginViewImplementation``.

[BUGFIX] Use correct object property in PluginViewImplementation

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/PluginImplementation.php
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/PluginView.ts2

Removes the custom handling of exceptions for PluginViews, which is unnecessary.
Instead the general ``NodeWrapping`` exception handler is used.
Additionally removes redundant ``@exceptionHandler`` from plugin view,
since it's inherited from the content prototype.

[TASK] Remove custom exception handling in ``PluginImplementation``

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/PluginImplementation.php

Regression of 57025d40e65c6f43d528b317ab4c583b5a476f52 resulted in
plugins not returning any output.

[BUGFIX] Output plugin content

---

TYPO3.Neos/Documentation/ExtendingNeos/CustomizingInspector.rst
TYPO3.Neos/Documentation/ExtendingNeos/DataSources.rst

Fix doubled quotes in CustomizingInspector.rst
Change the example in DataSources.rst - the example now makes sens for the use
in an inspector select box. Also adjust the code style.

[TASK] Change documentation for data sources

---

TYPO3.Neos/Documentation/References/PropertyEditorReference.rst
TYPO3.Neos/Resources/Private/Templates/Service/Nodes/Index.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferenceEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferencesEditor.js

With this feature the starting point for finding possible nodes
to create a reference becomes configurable via ``NodeTypes``
configuration. This allows to search for nodes outside the
current site.
For all nodes outside the current site the node path is shown instead
of the url path.

[FEATURE] Make reference starting point configurable

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ModuleController.php

The response of a module loses the status code if it contains a Location
header. This is caused by the ModuleController redirecting to the found
location but ignoring any status code that may have been set. This means
that a module will only create 303 redirects.
This change takes the status code of a module response and applies it to
the generated redirect, fixing this behavior.

[BUGFIX] Keep status code from module response on redirect

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js

Prevents loading links to static resources using AJAX in the backend interface,
which fail when loaded.

[BUGFIX] if in backend, do not intercept links to static resources

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php

When the Node Route Part Handler wasn't able to find a site node,
the exception now contains information about if at least a domain
could be detected and if so, which one matched.
Additionally, `matchValue()` will now also log an exception if the
request path was empty (that is, the user requested the homepage) and
not only for sub pages.

[TASK] Improve logging for "no homepage found" situations

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeActions.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeSelection.js

When inserting new content the first inline editable property is
focussed if one exists. This enables the editor to start typing
directly without having to place the cursor first.
Resolves: NEOS-602

[TASK] Focus first inline editable property when creating content

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php

This change is needed when using configurable review workflows.
Without this change, the user gets very often an exception when publishing
his content changes to review: "The specified workspace "foo" is not a base
workspace of "foo"."; and once this exception appears, there is no way
to get rid of this exception except removing all content changes and starting
all over again, and then hope for the best.
The error often occured not with simple content changes (a single content
element), but moreover if you tried to edit a few content elements, create
new content, or delete content and then tried to publish a bunch of these
changes.
After some investigation, it showed up that the $targetWorkspace was a
doctrine proxy, while the $baseWorkspace was not (or the other way around)
in the cases …

[BUGFIX] Compare base workspaces by name instead of identity

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/MoveNodeWithDimensions.feature

How to Reproduce:
- have a website with dimension fallbacks configured; e.g. Language "de"
which falls back to "en".
- Your content should be in German (no content in English actually needed)
- Try to move nodes across the tree with changing the Node's Parent Node
- watch the exception "Could not convert array to Node object because
[the-old-node-path] does not exist" in the get-child-nodes-for-tree
endpoint.
This error happens because the "move" operation, which is supposed to return
the *new* node path of the moved node, still returns the old path.
And this error, in turn, is triggered by some bug inside Node->setPath
(see inline comments for a full description).
Resolves: NEOS-1652

[BUGFIX] Fix transient error when moving of nodes in Node Tree

---

TYPO3.Neos/Documentation/ExtendingNeos/CreatingAPlugin.rst

Wrong ViewHelper was used in an example.

[TASK] Fixed documentation for creating a plugin

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/ContentCollection.ts2

Content collection handles are not shown since the meta data
added is using the document node instead of the actual node.
Regression introduced with 4672697b9477ceca53ee7b4e47c4def002e50e32
causing the node not to be set correctly for the
``contentElementWrapping`` processor.
Related: NEOS-1326

[BUGFIX] Use correct node for content collection metadata

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Administration/SitesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/NodesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/ContentContext.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/LegacySiteImportService.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/SiteImportService.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/SiteService.php

The base path for sites '/sites' shouldn't be hidden in strings as
it is an important building block for Neos. Therefore I put it into
a defined location as constant to refer to.
The path may never change but this way there is a defined reference
point to it.

[TASK] Make sites path explicit domain knowledge

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/DependingProperties.rst
TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
TYPO3.Neos/Documentation/CreatingASite/NodeTypes/index.rst
TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/InspectorController.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/PropertyEditor.js

This feature allows configuring listeners to other properties
for editors. The listener will be triggered on any change of the
observed property even without applying the change. To keep the
usage flexible you can define a handler that will be triggered
on change.
Example configuration:
subpageLayout:
type: string
ui:
inspector:
editorListeners:
activeWithNonEmptyValue:
property: 'layout'
handler: 'TYPO3.NeosDemoTypo3Org/Handlers/LayoutHandler'
The handler would be an Ember.Object or more specifically the handler
should be loadable via require and return an object with a create()
method that in turn returns an object with a handle method with the
following signature:
handle: function(listeningEditor, newValue, property, listenerName)
The ``listeningEditor`` is the Ember editor object for …

[FEATURE] Allow property editors to listen to changes

---

TYPO3.Neos/Configuration/NodeTypes.yaml
TYPO3.Neos/Configuration/Settings.yaml
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Handlers/ShortcutHandler.js

This changes automates the following when editing a Shortcut:
1. If the target is set to a non-empty value, the target mode is set
to "Selected Target"
2. If the target mode is set to not use the selected target, the target
is removed.

[FEATURE] Auto-update shortcut properties when editing

---

TYPO3.Media/Classes/TYPO3/Media/TypeConverter/AssetInterfaceConverter.php

The type converter would always call ``buildObject()`` on the parent,
even if the possible constructor arguments were empty. This lead to:
Missing constructor argument "resource" for object of type
``TYPO3\Media\Domain\Model\Asset``.
A check is added to avoid that.

[BUGFIX] Avoid "Missing constructor argument" exception

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php

Regression introduced in 8c87918e41cd0d445869f5acc77ece01b0a0764a
causing the selection of master view to cause a fatal error in plugin views.

[BUGFIX] Fix selecting master view option in plugin view

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js

Instead of fetching the content dimensions every time the backend is loaded,
the request is cached using the ``ResourceCache``. This eliminates a request
for something that rarely changes and is automatically updated when the
configuration changes.

[TASK] Cache content dimensions backend request client side

---

TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ConvertUrisImplementation.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/RuntimeContentCache.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Runtime.php

This change add a new service in the TypoScript package to add dynamic tag
to the current TS rendering path.
This new service is used in the Neos ConvertUrisImplementation to keep
track of link to node and asset and tag the current patch correctly.
Resolves: NEOS-1640

[TASK] Keep track of link during TS rendering

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/SiteService.php

This change fixes an issue with the "site:prune" command related to
workspaces which could result in an inaccessible Neos backend for all
existing users, even after a new site had been imported.
In addition to the actual nodes and domains, the site:prune command also
removed all existing workspaces. Since personal workspaces are not
re-generated automatically (anymore), existing users wouldn't be able
to login even if a new site had been imported because they were lacking
a personal workspace.
Instead of simply removing all data from the domain repositories, the
site:prune command now iterates over all existing sites and calls the
pruneSite() method, which leaves workspaces intact.

[BUGFIX] site:prune also removes all personal workspaces

---

TYPO3.Media/Migrations/Postgresql/Version20150701113247.php

A schema migration allowing NULL values for image dimensions was missing
for PostgreSQL.

[BUGFIX] Add a missing PostgreSQL migration

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php
TYPO3.Neos/Configuration/Policy.yaml
TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Edit.html
TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php

This fixes a couple of issues with the new workspace management features
and improves the user interface in the workspace review screen.
Editing the owner of a workspace resulted in a fatal error due to
a wrong method signature. Ownership can now be transferred as intended.
The rebase and redirect action (which can conveniently be triggered
through an edit button in the review screen) complained about a wrong
"$this" in a fatal error. Removed $this and now that works.
At the bottom of the review workspace changes screen a small help
message explained what would happen when a user presses one of the
buttons. Removed that fine print and now let the buttons speak for
themselves.

[BUGFIX] Broken workspace managment backend module

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

Using `ImageVariant` as node property type as suggested in this section of the documentation results in errors in the Neos backend:
> Couldn't create editor for property "image" (no editor configured). Please check your NodeTypes.yaml configuration.

Fix documentation typo: Image{Variant => Interface}

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php

This solves an issue with the automatically generated suffix for
names of workpsaces created through the Workspace Management module.
Previously, workspace suffixes (like "-7603") were identical or very
close to previously generated names, because they were derived from
the first four characters of the output of uniqid(), which is based
on microtime.
The new solution converts the current microtime into an alpha-numeric
string and takes the last 5 characters, which change very often.
Resolves: NEOS-1683

[BUGFIX] Workspace identifier suffixes are not random (enough)

---

TYPO3.Media/Migrations/Postgresql/Version20150701113247.php

In cb89c7a053b00a0dd3b2b538fdb5c41c668ef226 a missing migration was
added. That migration works fine when migrating up, but in the down
migration one line too much causes it to break.

[BUGFIX] Fix a PostgreSQL down migration

---

TYPO3.Neos/Classes/TYPO3/Neos/Package.php
TYPO3.Neos/Classes/TYPO3/Neos/Routing/Aspects/RouteCacheAspect.php
TYPO3.Neos/Classes/TYPO3/Neos/Routing/Cache/RouteCacheFlusher.php

To avoid loading all documents in a Neos instance the route cache
for a node will be tagged will all parent node identifiers so that
flushing the cache for a particular node identifier will automatically
flush all child node entries as well.

[BUGFIX] Route cache flush shouldn't load all documents

---

TYPO3.Neos/Classes/TYPO3/Neos/Package.php

If a node is inaccessible (hidden) an exception is thrown
when trying to move it.

[BUGFIX] Allow moving of inaccessible nodes

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeInterface.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Model/NodeTest.php

The original match pattern for context paths would match dimensions
like ``@user;language=de,en=bar`` just fine even though in fact it
is not a valid context path.
The adapted pattern uses recursion to exactly match parts of the
dimensions string. Additionally it introduces atomic groups around
parts of the path to reduce backtracking amount in case of a non
matching path.
This increases matching speed while reducing possible sources of error
by disallowing more invalid cases.

[BUGFIX] Improve Node context path match pattern

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php

The change ccb1c0e contained a regression because the adapted
pattern for NodeContextPath now only matches if there is actually
a path and not only a context (which is correct in regards to the
naming), but the FrontendNodeRoutePartHandler used it with request
paths that might start only with the context information. These would
no longer match and therefore the request path is prepended with a
`/` before filtering out the context information.

[BUGFIX] NodeContextPath should contain a node path

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Utility/NodePaths.php

The dimensions have to be an Array instead of null.
Fixes: NEOS-1697

[BUGFIX] Set dimension to array() instead of null

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php

[BUGFIX] Prevent exception when tag already exists in the active or another asset collection

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeInterface.php

The ContextPath match pattern would either match an absolute path
containing at least one segment or a relative path but not the root
node path ``/``. This change fixes that so that now all valid node
path variants are supported.

[BUGFIX] ContextPath match pattern should match only slash

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php

Follow up for the changes of the
``\TYPO3\TYPO3CR\Domain\Model\NodeInterface::MATCH_PATTERN_CONTEXTPATH``
which turned out to be breaking because the RoutePartHandler does not deal
with valid context paths.
This hotfix finally fixes the problem for now.

[BUGFIX] RoutePartHandler needs to deal with non empty node path

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/UserService.php
TYPO3.Neos/Tests/Unit/Service/UserServiceTest.php

To prevent making a database lookup every time a user is requested
through the ``UserService`` a runtime cache is used. This prevents
lots of lookups since the user is requested many times in the backend,
e.g. once for every translate view helper.

[TASK] Use runtime cache in user service

---

TYPO3.Neos/Configuration/NodeTypes.yaml

The label inherited from the Node nodetype included the node name, which
is not very helpful for content nodes and can be confusing.
With this change, the (default) label for nodes no longer includes the
node name unless the node has been auto-created. That means that for
ContentCollection nodes it will still be shown like before in most cases.

[TASK] Adjust default label for nodes

---

.travis.yml

This makes sure the travis tests run as planned by using a github
API token to circumvent the bandwith limit and additionally run
composer update after composer install to make sure the latest
package versions get installed for testing.

[TASK] Adjust Travis tests

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/CreateContentContextTrait.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/NodesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/PluginService.php
TYPO3.Neos/Classes/TYPO3/Neos/TYPO3CR/Transformations/PluginViewTransformation.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/PluginViewImplementation.php
TYPO3.Neos/Migrations/TYPO3CR/Version20150907194505.yaml
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/MasterPluginEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/PluginViewEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/PluginViewsEditor.js

Replaces the usage of node path for referencing the master plugin in PluginView.
Instead the identifier is used, like with node linking/reference properties.
This is done to make it more bulletproof in case the master plugin is moved.
Run the following node migration to adjust existing PluginViews::
./flow node:migrate 20150907194505
Resolves: NEOS-1501

[!!!][TASK] Use identifier instead of node path for PluginView reference

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/ContentElement/EditableViewHelper.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Link/NodeViewHelper.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Uri/NodeViewHelper.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/AbstractTypoScriptObject.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/TemplateImplementation.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/ViewHelpers/TypoScriptContextTrait.php

The new ``TypoScriptContextTrait`` can be used to get
variables from the TypoScript runtime context inside a
ViewHelper as long as it's used inside a
``TypoScriptAwareView``. This helps to avoid code duplication
while avoiding long inheritance chains.

[TASK] Add trait to avoid duplicate code in ViewHelpers

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php

When reviewing changes in one's own workspace, the "Edit" button would
always show an error about the personal workspace not being clean.
Because in this case a rebase of the workspace is not needed (and would
not be possible), that check and the rebase can be skipped if the
target workspace is the personal workspace.

[BUGFIX] Allow to edit in own workspace from Workspaces module

---

TYPO3.Neos/Resources/Private/Templates/Media/Asset/Index.html

When the condensed aside media library layout is shown (more than 25 tags),
the search field is automatically focussed causing the view to jump down to
the search field. This is annoying and unexpected and thus disabled for that view.

[BUGFIX] Remove autofocus from search field on condensed media library layout

---

TYPO3.Neos/Classes/TYPO3/Neos/Aspects/NodeTypeConfigurationEnrichmentAspect.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/NodeTypeSchemaBuilder.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/VieSchemaBuilder.php
TYPO3.Neos/Configuration/Objects.yaml
TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
TYPO3.Neos/Documentation/CreatingASite/NodeTypes/TranslateNodeTypes.rst
TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
TYPO3.Neos/Resources/Private/Styles/Components/_HelpMessage.scss
TYPO3.Neos/Resources/Private/Styles/Content/_InsertNodePanel.scss
TYPO3.Neos/Resources/Private/Styles/Foundation/_popovers.scss
TYPO3.Neos/Resources/Private/Styles/Foundation/_variables.scss
TYPO3.Neos/Resources/Private/Styles/Inspector/_Inspector.scss
TYPO3.Neos/Resources/Private/Styles/Neos.scss
TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Components/HelpMessage.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/InspectorView.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Section.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/InsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/Shared/Popover.js
TYPO3.Neos/composer.json
composer.json

Allows to show contextual help messages in a popover element for node
types and node properties.
Supports markdown for styling message text.
Usage:
For node types:
```
'My.Package:SpecialHeadline':
ui:
help:
message: 'Special headline displays text in **gold color**.'
```
For node properties:
```
'My.Package:SpecialHeadline':
properties:
title:
ui:
help:
message: 'Lorem ipsum `dolor` sit amet'
```
Releases: master
Resolves: NEOS-1303

[FEATURE] Contextual help messages for node types and node properties

---

TYPO3.Neos/Documentation/ExtendingNeos/InteractionWithTheNeosBackend.rst
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeSelection.js

This change adds a new event ``Neos.NodeSelected`` that will
be triggered when a node was selected on the page.
Resolves: NEOS-407

[FEATURE] External event for node selection

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Parser.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/QuotedKeys.ts2
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/QuotedKeysTest.php
TYPO3.TypoScript/Tests/Unit/Core/Parser/PatternTest.php

To allow for more flexible keys support for quoted keys is introduced.
Example::
foo."bar@baz" = "bla"
foo.'bar.baz' = "other"
Resolves: NEOS-1410

[FEATURE] Support keys / paths with special characters in quoted keys

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php
TYPO3.Neos/Configuration/Settings.yaml
TYPO3.Neos/Documentation/CreatingASite/ContentDimensions.rst
TYPO3.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php

Introduce ``supportEmptySegmentForDimensions`` settings switch that would
allow uriSegment to be empty for default preset. If the option is on,
there are two restrictions:
* uriSegment must be unique across all dimensions
* empty uriSegment may only be set for default preset
Without this setting old behavior is used: uriSegment doesn't
have to be unique, but can't be empty.
Resolves: NEOS-295

[FEATURE] Allow uriSegment to be empty for default presets

---

TYPO3.Neos/Resources/Private/Templates/Service/Nodes/Index.html
TYPO3.Neos/Resources/Private/Templates/Service/Nodes/Show.html
TYPO3.Neos/Resources/Private/Translations/en/Main.xlf

This checks whether a documentNode has been found before rendering a
link to the frontend for nodes that have been found by the nodes
service controller.
Fixes NEOS-1695

[BUGFIX] Allow to search for nodes without a Document parent

---

TYPO3.TYPO3CR/Tests/Functional/Domain/WorkspacesTest.php

Needed for ``doctrine/orm`` 2.4 compatibility (already done in 2.0)

[BUGFIX] Prevent fetching unmanaged entity in ``WorkspacesTest``

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Repository/AssetRepository.php
TYPO3.Media/Resources/Public/Scripts/collections-and-tagging.js
TYPO3.Neos/Resources/Private/Partials/Media/ListView.html
TYPO3.Neos/Resources/Private/Partials/Media/ThumbnailView.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/Index.html

Optimizes rendering performance of the media browser/module by
re-using modals, optimizing and using count queries.
Brings 0,5x-3x+ speed improvement depending on the selected view
and amount of assets and tags/asset collections visible.
No functional difference.
Additionally fixes a couple of bugs in the asset repository.
Resolves: NEOS-1698

[TASK] Media browser performance improvements

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php

The method didn't have any obvious benefit and was only used in a
single place, removing it and directly calling the method that was
called inside removes a bit of clutter.

[TASK] Remove unnecessary method from RoutePartHandler

---

TYPO3.Neos/Resources/Private/Styles/_Content.scss

This change adds a dashed border around inline-editable elements when
hovering over them. This it becomes easier to see what exactly can be
edited in an element with multiple editable parts.

TASK: Mark editable content on hover

---

TYPO3.Neos/Configuration/NodeTypes.yaml

During the change to add translation support to the inspector tabs/groups, this appears to have been missed.
See: https://github.com/neos/neos-development-collection/commit/421c8218f54627a175bba3af1f7aa08150b56ac4#diff-3b7b31a90bfc18f8fbbdec4e8f83424f

BUGFIX: Re-add missing inspector tab label for 'metadata'

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/ContentElement/EditableViewHelper.php
TYPO3.Neos/Resources/Public/JavaScript/aloha.js
TYPO3.Neos/Tests/Unit/ViewHelpers/ContentElement/EditableViewHelperTest.php

Current selector to match property editor of given node type is
extremely slow, because it has to use very inefficient selector.
Add additional `data-neos-node-type` attribute to editable property wrap
to simplify the selector.
This brings a huge performance improvement on pages with a lot of
editable properties.

BUGFIX: Improve slow aloha settings selector 

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Eel/FlowQueryOperations/ParentsUntilOperation.php
TYPO3.TYPO3CR/Tests/Functional/Eel/FlowQueryOperations/ParentsUntilOperationTest.php

Since the current parentsUntil operation does not return the correct parent nodes, this will fix the behaviour. `$until` did not return the first matched parent node.

[BUGFIX] Fix parentsUntil operation

---

.travis.yml
TYPO3.Neos/Migrations/Postgresql/Version20151120170812.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/AbstractNodeData.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php

This changes the type of the properties `AbstractNodeData.accessRoles`
and the `NodeData.dimensionValues` from `json_array` to the Flow type
`flow_json_array`.
While those properties only hold plain arrays and can be stored just fine
with the Doctrine `json_array` type, Neos uses distinct in a query on
the NodeData table which leads to errors due to the `json` type in
PostgreSQL not being comparable. The Flow type uses `jsonb` instead,
which can be compared and makes the query work as expected.
NEOS-1726 #comment Fixes exporting on PostgreSQL

BUGFIX: Change column type to flow_json_array on NodeData

---

.travis.yml
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Model/Event.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Model/NodeEvent.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Repository/EventRepository.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Integrations/TYPO3CRIntegrationService.php
TYPO3.Neos/Migrations/Postgresql/Version20151126122252.php
TYPO3.Neos/Tests/Behavior/Features/EventLog/Entities/AccountsUsers.feature

This fixes a few issues with event logging:
- removes MySQL-specific SQL from the EventRepository
- fixes an invalid type error when setting the parentevent to null
- adjusts the data column to use the flow_json_array type to allow
storing objects correctly.
- adjusts the event logging configuration (only used in Behat tests)
to not extract the collection of electronic addresses associated with a
Neos user, but only the primary electronic address.
NEOS-1726 #comment Removes MySQL-specific code and adjusts schema to be PostgreSQL compatible

BUGFIX: Event logging fixes

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/BackendController.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/XliffService.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/InterfaceLanguageViewHelper.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/JavascriptConfigurationViewHelper.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/XliffCacheVersionViewHelper.php
TYPO3.Neos/Configuration/Policy.yaml
TYPO3.Neos/Configuration/Routes.Backend.yaml
TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosBackendEndpoints.html
TYPO3.Neos/Resources/Public/JavaScript/ContentModuleBootstrap.js
TYPO3.Neos/Resources/Public/JavaScript/Shared/Configuration.js

Makes the backend interface labels cacheable by storing the version
XLIFF cache and generating a URI using that version. When a label is
changed or the selected language is changed, the URI is automatically
updated.

[TASK] Cache backend interface labels client side

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/PublishMenu.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferenceEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferencesEditor.js

This removes a console log call from PublishMenu.js and tweaks the
reference(s) editor to be a tiny bit nicer and allow to display node
suggestions even if the node in question does not have any ui
configuration in it's nodetype (can happen with startingPoint set for
the editor to select "nodes without a UI").

TASK: Small cleanup in reference(s) editor and publish menu

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/NodeService.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Package.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Basic/PublishUserWorkspace.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/FeatureContext.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Model/WorkspaceTest.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/NodeServiceTest.php

When changing node types on existing nodes, the following publication would
fail under certain circumstances (see issue NEOS-1172 for details). This
change fixes those problems.
Adds a behat test as well: "When changing the node type of a node in my
workspace to one that has fewer properties it is still possible to publish it"
Resolves: NEOS-1172

[BUGFIX] Allow publishing of nodes with modified schema

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php

Removing a Neos user with user:delete resulted in an error, because
setting the owner of a workspace requires an argument.
This fixes that by passing null.

BUGFIX: Allow to delete a user from the CLI

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php

When a user is created, the corresponding account was added directly.
This lead to the party not being found when asking the account for it,
unless changes were persisted in between.
This uses the PartyService method assignAccountToParty() now.

BUGFIX: Correctly assign account to party in UserService

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Functional/Domain/NodesTest.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Repository/NodeDataRepositoryTest.php

When inserting a node inside another node in the document node tree, non-document nodes were displayed as children incorrectly.

BUGFIX: ``Node->getChildNodes`` bypasses node type filter for newly added nodes

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js

The request returns JSON instead of HTML and thus doesn't need to be parsed
NEOS-1722

BUGFIX: Loading content dimensions for dimensions selector

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/HistoryController.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Model/NodeEvent.php
TYPO3.Neos/Classes/TYPO3/Neos/EventLog/Domain/Repository/EventRepository.php
TYPO3.Neos/Resources/Private/Templates/Module/Management/History/Index.html
TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf

This fixes the following issue with the history module:
- The "load more" button label is now translateable
- The NodeEvent won't call the SiteRepository if there is no "site"
- The EventRepository allows to filter correctly by Events
- HistoryController will correctly paginate due to the fixed Repository
NEOS-1221 #comment some cleanup to the implementation

BUGFIX: Fix some issues with the history module

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Parser.php
TYPO3.TypoScript/Tests/Unit/Core/Fixtures/ParserTestTypoScriptFixture05.ts2
TYPO3.TypoScript/Tests/Unit/Core/ParserTest.php

Fix regression caused by multi-line EEL support.
NEOS-60 #comment fixes a regression introduced by this

BUGFIX: Allow to have no space between value and opening confinement

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Eel/FlowQueryOperations/FilterOperation.php
TYPO3.TYPO3CR/Tests/Functional/Eel/FlowQueryOperations/FilterOperationTest.php

Checks if the value is not an instance of the operand.
Example of usage:
node = ${q(node).filter('[!instanceof Acme:Node]')}
NEOS-1321 #close

FEATURE: New FlowQuery filter operation ``!instanceof``

---

TYPO3.Neos/Resources/Private/Styles/TopBar/_PublishMenu.scss

This fixes a regression introduced in pull request #275 which led to
an wrongly styled number badge in the Publish button.

BUGFIX: Number of unpublished changes in Publish button is blemished

---

TYPO3.Media/Migrations/Mysql/Version20151216144408.php
TYPO3.Media/Migrations/Postgresql/Version20151216144435.php

To avoid unique constraint errors on applying the new index the
thumbnail table should be cleared beforehand.
Any left over resources can be cleared by executing::
./flow resource:clean

BUGFIX: Thumbnail migration should clear thumbnails

---

TYPO3.TYPO3CR/Migrations/Code/Version20150510103823.php

If superTypes were defined using string representation of true or false, the
nodetypes file would get corrupted.
E.g. this:
superTypes:
'Some:NodeTypes': "TRUE"
Would be transformed into::
superTypes:
1: true
Related: NEOS-1253

BUGFIX: Prevent core migration from damaging badly formatted superTypes

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ThumbnailService.php

Prevents issues with database constraints caused by new assets being added to persistence, since
the asset would be added through the thumbnail as a related object as well.
Due to the automatic creation of thumbnails on asset creation, this caused problems for the site import.
NEOS-1671

BUGFIX: Do not automatically persist thumbnails for new asset objects

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ThumbnailService.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php
TYPO3.Neos/Configuration/Settings.yaml

This change adapts ``ContentController::getAssetProperties`` to use the new Thumbnail API.
With this change the AssetList node type is fixed, the selection of a new asset would fail because the controller called a method that no longer existed existed.
NEOS-1165 #comment fixes a regression

BUGFIX: ContentController::getAssetProperties must use the new Thumbnail API

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Migration/Transformations/RenameNode.php

The ``RenameNode`` transformation for node migrations used
the non existing method ``setName`` on the ``NodeData`` object.
It now uses ``setPath`` instead which exists.
NEOS-1727 #close fixed with this change

BUGFIX: RenameNode Transformation uses existing method

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/ThumbnailGenerator/SvgThumbnailGenerator.php

Every generator should update the requested width and height of the generated thumbnail.
NEOS-1165

BUGFIX: SVG Thumbnail Generator should keep track of width / height

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

The ``node:repair`` command would currently apply any configured default
value as node property value if the property did not exist. This is
wrong for properties prefixed with an underscore as we use this
prefix for internal properties.
This is now changed so that any property starting with underscore
is ignored.
As this prefix is currently implicit knowledge a small note was added
to the documentation, stating that property names should not start
with underscores as we use them internally.
NEOS-1721 #close

TASK: node:repair doesn't mix internal node properties

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ThumbnailService.php

When an asset is uploaded and a thumbnail is generated for it,
the thumbnail object might not have been persisted already leading
to issues when the thumbnail is updated after rendering.
This fixes an issue in the asset list when uploading document assets.

BUGFIX: Do not automatically persist new thumbnails

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ThumbnailService.php

Allow using the return value of ``thumbnailService->getThumbnail`` of type
``ImageInterface`` in the ``thumbnailService->getUriForThumbnail`` for
convenience.
This occurs when uploading an image in a image property that doesn't need to be
scaled.

BUGFIX: Accept ``ImageInterface`` in ``getUriForThumbnail``

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php

This fix a bug when the editor choose two times the same settings for an
image variant of the same image. In this condition, the $asset object is
not new, and should not be passed to the add method.

BUGFIX: ImageVariant can be reused

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionSelector.html

The dimension label could not be translated, because the translate
helper was used incorrect.

BUGFIX: Allow translation of dimension label

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Index.html
TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf

Following up on https://github.com/neos/neos-development-collection/pull/298 this change
removes the display of the number of unpublished changes again from the review button and the
change overview page.

TASK: Remove display of unpublished changes count

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/NodeController.php
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeActions.js

Fixes copy pasting of content elements where the new element wouldn't be displayed until
reloading the page.
Additionally fixes an issue where cutting an element caused a page reload.
NEOS-1506 #close

BUGFIX: Show content element after copy paste inline

---

TYPO3.Neos/Classes/TYPO3/Neos/Aspects/NodeTypeConfigurationEnrichmentAspect.php

Currently help messages are broken with unicode strings, because
`DOMDocument::loadHTML` needs correct encoding declaration to handle
unicode correctly.
Append the encoding declaration to fix this issue.

BUGFIX: Fix unicode handling in help messages

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/UserService.php
TYPO3.Neos/Classes/TYPO3/Neos/Utility/User.php
TYPO3.Neos/Migrations/Mysql/Version20151223125909.php
TYPO3.Neos/Migrations/Postgresql/Version20151223125946.php

This fixes some inconsistencies with the naming of user workspaces,
which resulted in duplicate workspaces being created for users with
special characters in their username.
Additionally a migration that can correctly set the owner for users
with usernames containing special characters was added.
NEOS-1740 #close Fixes the issue with a new migration

BUGFIX: User workspace names should be deterministic

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/WorkspaceCommandController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/UserService.php
TYPO3.Neos/Classes/TYPO3/Neos/Utility/User.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php

Just moves code around to avoid string concatentation all over
the place. Also uses the ``isPersonalWorkspace()`` in appropriate
places.

TASK: Make personal workspace names explicit domain knowledge

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Service/PublishingService.php

The PublishingService was moved from TYPO3\TYPO3CR\Service to
the TYPO3\TYPO3CR\Domain\Service namespace in commit
23b162fa737cd56eb065b71e76a11ee823cdec7a. As the class was annotated
with @api that change was actually breaking and should not have been
released in a minor release.
This change introduces the class again and immediately deprecates it
to be removed in a later version.

TASK: Reintroduce PublishingService

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Repository/DomainRepository.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/DomainMatchingStrategy.php
TYPO3.Neos/Resources/Private/Partials/Module/Shared/DomainForm.html
TYPO3.Neos/Tests/Unit/Domain/Service/DomainMatchingStrategyTest.php

This change replaces www.typo3.org which is given as an example in the
"add new domain" dialog by www.neos.io, and also replaces it in a couple
of unit tests. The VIE namespace is not modified by this change.

TASK: Replace visible occurrences of www.typo3.org with www.neos.io

---

TYPO3.Neos/Migrations/Mysql/Version20160104121311.php
TYPO3.Neos/Migrations/Postgresql/Version20160104121413.php

The fixes issued for NEOS-1740 didn't consider the case of an installation
were previous migrations ran and set the owner of workspaces to an
empty string instead of NULL which made the first bugfix migration ignore
those workspaces. This migration now targets those specifically, together
migrating all workspaces to having the correct ownership.
NEOS-1740 #close

BUGFIX: Migration for workspaces with empty owners

---

TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst

Documents a missing property ``absolute`` for the ``ConvertUris`` TypoScript object

TASK: Document missing ``ConvertUris`` property ``absolute``

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/NodeTree.js

If you move a parent node of the node in the NodeTree you are currently on the node tree
will break because the pageNodePath for your current node is not set to the new path.
NEOS-1752 #close

BUGFIX: Load moved page if moving parent page

---

TYPO3.Neos/Configuration/NodeTypes.yaml

This change remove the 'i18n' prefix from the inspector group label.

BUGFIX: Wrong label visibility inspector group

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/SiteCommandController.php

Adds a better help text for the `site:export` command when calling `help`

TASK: Add better help text for ``site:export`` command

---

TYPO3.Neos/Classes/TYPO3/Neos/Eel/FlowQueryOperations/ParentsOperation.php
TYPO3.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php

There is site logic within the parents operation inside the TYPO3.CR package. There is a seperate operation especially for Neos now.
NEOS-1628 #resolve

BUGFIX: Remove site logic from parents operation

---

TYPO3.Neos/Classes/TYPO3/Neos/Eel/FlowQueryOperations/ParentsUntilOperation.php

There is site logic within the parentsUntil operation inside the TYPO3.CR package. There is a seperate operation especially for Neos now.
NEOS-1628 #close

BUGFIX: Remove site logic from parentsUntil operation

---

TYPO3.Neos/Documentation/References/PropertyEditorReference.rst

"date" isn't working anymore, but "DateTime" does.

BUGFIX: date renamed in DateTime

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractPositionSelectorButton.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InlineEditingHandles.js

The position selector for creating or pasting elements used to appear when click-and-holding the button for 300ms. This is not very intuitive for a web interface. Now the option menu will appear on hover after 700ms. The click-and-hold behaviour will still work, so touch support is still given.
NEOS-1691 #close

FEATURE: Make position selector appear on hover

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Menu.ts2
TYPO3.Neos/Tests/Functional/TypoScript/Fixtures/BaseTypoScript.ts2

Menu should have useful defaults for ``entryLevel`` and ``maximumLevels``
to make it usable in it's default state without changing too much.
The ``entryLevel`` is therefore set to 1 and maximumLevels to 2.
Maximum shouldn't be too high to avoid loading a lot of nodes unnecessarily.
This is breaking if you rely on the previous behavior with no defaults
set for the two values.

[!!!][TASK] Set useful defaults for Menu

---

TYPO3.Neos/Documentation/CreatingASite/Security.rst

Otherwise following error appears:
#1355480641: PHP Fatal error: Class  
'TYPO3\\TYPO3CR\\Security\\Authorization\\Privilege\\Node\\ReadNodePrivilege' not found 
in /var/www/Neos/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Security/Authorization/Privilege/PrivilegeTarget.php on line 136

BUGFIX: Corrected \\ to \ in Security Document

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Model/WorkspaceTest.php

This fixes an issue with the publishing mechanism which can result in
removed Content Collection nodes when documents are published to a
workspace other than the live workspace.
The root cause for this issue is that during publishing Neos will publish
Content Collection nodes twice (the first time because they may exist
in the personal workspace and the second time because all Content
Collection nodes are published automatically when a Document node is
published). Because the workspace of the Content Collection node is
changed to the target workspace on the first publish iteration, the
source and target workspace will be the same on the second publish
iteration. That results in `replaceNodeData()` to remove the "existing"
Content Collection node, which is actually the very same object …

BUGFIX: Content Collection nodes vanish when publishing to nested workspace

---

TYPO3.Neos/Documentation/HowTos/RenderingMetaNavigation.rst

Tweaks the documentation on rendering meta navigation a bit.

TASK: <nav> does not need a role attribute

---

TYPO3.Neos/Resources/Private/Styles/_InlineEditing.scss

The css property ``inline-offset`` doesn't exist, it should be
``outline-offset``.

BUGFIX: Fixed a typo in ``_InlineEditing.scss``

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/AbstractNodeData.php

The ``AbstractNodeData::removeProperty()`` method checked
the existence of the given property with ``isset`` but that
leads to an exception if the property has a ``null`` value.
The check has been changed to ``array_key_exists``.
NEOS-1719 #close

BUGFIX: Node property can be null in removeProperty

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/Helpers/TypoScriptPathProxy.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/Templates/JsonEncodedValueTemplate.html
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/Template.ts2
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/TemplateTest.php

This will check for an overriden value when using object access in a
Fluid template on a TypoScript path proxy.
NEOS-1776 #close Fixes the issue

BUGFIX: Fix ObjectAccess to overriden expression value in Fluid proxy

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

Adds documentation on how to customize the generated label for nodes.

TASK: Document ``label`` option for NodeTypes.yaml

---

TYPO3.Neos/Migrations/Postgresql/Version20151120170812.php
TYPO3.Neos/Migrations/Postgresql/Version20151126122252.php

This fixes issues when migrating to 2.1 that affect some, but not all, running PostgreSQL:
- JSON to JSONB column type change not possible
- column type change on event log not possible
NEOS-1763 #close

BUGFIX: Fix issues with PostgreSQL migrations

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js

The demo site specifies an i18n label but the implementation didn't use
any client-side translation for the dimension label yet.

BUGFIX: Translate dimension label in dimension choice dialog

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/NodeTypeManager.php

When a NodeType is unset using ```'My.Package:NodeType': ~``` the
NodeTypeManager complains the NodeType is undefined.
This change makes the NodeTypeManager ignore NodeType configurations
which are no array. This way the NodeType does not end up in the schema
definitions at all meaning a more lightweight UI.

TASK: Ignore empty NodeType configurations

---

TYPO3.Neos/Migrations/Mysql/Version20160212141523.php
TYPO3.Neos/Migrations/Postgresql/Version20160212141533.php
TYPO3.TYPO3CR/Migrations/Mysql/Version20160212141524.php
TYPO3.TYPO3CR/Migrations/Postgresql/Version20160212141534.php

The use of Doctrine 2.5 (instead of 2.4) exposes the fact that some
(old) index names in the Neos database schema do not match the names
that are generated currently.
This adjusts those index names, something that is a one-time adjustment.

BUGFIX: Adjust index names to match Doctrine DBAL 2.5

---

TYPO3.Neos/Resources/Private/Templates/Module/Widget.html

Enables translation of the title attribute used for action buttons in module widgets.
NEOS-1536 #close

BUGFIX: Translate title attribute on module widget action buttons

---

TYPO3.Neos/Resources/Private/Templates/Backend/Module/Index.html

Via `additionalResources.styleSheets` a map of additional
stylesheet files can be defined that are loaded in the module
the configuration was made for. Unfortunately they were loaded
before the Neos default styles which makes overwriting of some of
those styles cumbersome and more difficult than necessary.
This change switches the loading order so that the Neos styles
are loaded before any additional resources.

BUGFIX: Additional styles for modules loaded after Neos

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Page.ts2

`LastVisitedNode.js` should run asynchronously as soon as it is available, since some speed testing tools consider it to be render blocking.

FEATURE: Load ``LastVisitedNode.js`` asynchronously

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/NodesController.php

This fixes an issue for sites with single or multiple dimensions which
have no fallback defined. When trying to translate content from an
existing dimension to a variant which does not exist yet, the
`NodesController` will fail with a fatal error due to the missing
Site Node in the respective dimension.
The solution in this change works for the given situation. A more
generic approach may be implemented as part of #156.
NEOS-1786 #close

BUGFIX: Translate process is broken for dimensions without fallbacks

---

TYPO3.TypoScript/Configuration/Testing/Caches.yaml

Fixes a bug that occurs if there is a custom configuration for ``TYPO3_TypoScript_Content`` cache with ``backendOptions`` set. This fix will unset the ``backendOptions`` in testing context which are not allowed for the ``TYPO3\Flow\Cache\Backend\TransientMemoryBackend`` backend.
NEOS-1781 #close

BUGFIX: Reset ``backendOptions`` for TypoScript content cache in testing context

---

TYPO3.Neos/Resources/Private/Styles/Inspector/_SecondaryInspector.scss
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditorCrop.html
TYPO3.Neos/Resources/Public/Styles/Neos.css

When the cropping area in the secondary inspector isn't wide enough,
the coordinates of the cropping area are miscalculated. To solve this
the cropping area now has a minimum width and scroll is added, when
the area is too small.
NEOS-1787 #close

BUGFIX: Image crop selection incorrect on small screens

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js

The node type was not updated when a new page was loaded, leading to
incorrect constraints being applied to auto created child nodes.
NEOS-1728 #close

BUGFIX: Node constraints for auto created node types in structure tree

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/NodeOperations.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/TransliterationService.php
TYPO3.Neos/Classes/TYPO3/Neos/Utility/NodeUriPathSegmentGenerator.php
TYPO3.Neos/Configuration/Settings.yaml
TYPO3.Neos/composer.json
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Utility.php
TYPO3.TYPO3CR/Tests/Unit/UtilityTest.php
TYPO3.TYPO3CR/composer.json
composer.json

When a page is created in the node tree the title is automatically
transliterated to a valid URL. However when using non-latin characters,
the characters weren't transliterated. This lead to the pages having
special characters in their URL, making them inaccessible.
To fix this a new transliteration service is introduced which adds support for Chinese, Japanese,
Korean, Vietnamese, Khmer, Thai, Arabic, Hebrew, Hindi, Burmese and Greek.
NEOS-1791 #close
NEOS-1280 #close

BUGFIX: Creating pages using non-latin characters

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Utility.php

If auto-created child nodes are added via `node:repair`, the generated identifiers are not the same across different variants. This will cause problems when publishing these node variants later.
This change synchronizes the behavior between `node:repair` and regular node creation.
Running `node:repair` will now check identifiers of auto-created child nodes and adjust them accordingly. This is potentially breaking if a child node was referenced from another node but that should very rarely happen.
NEOS-1783 #close

BUGFIX: Use stable identifier for auto-created child nodes in repair

---

TYPO3.Neos/Configuration/Settings.yaml

This change sets the application key and application name to TYPO3.Neos
and Neos respectively.

TASK: Set the application key and name to Neos

---

TYPO3.Neos/Tests/Unit/View/TypoScriptViewTest.php
TYPO3.TYPO3CR/Tests/Unit/FlowQueryOperations/NextOperationTest.php
TYPO3.TYPO3CR/Tests/Unit/FlowQueryOperations/ParentOperationTest.php
TYPO3.TYPO3CR/Tests/Unit/FlowQueryOperations/PrevOperationTest.php
TYPO3.TYPO3CR/Tests/Unit/FlowQueryOperations/SiblingsOperationTest.php

Since ``phpunit-mock-objects`` 3.1.0 errors are thrown when a mocked
method is not allowed, non-existing, final or private.
This change adjusts to that change by getting rid of such mistakes in
the tests, which are made visible due to the change.

TASK: Adjust unit tests mocks to new errors

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js

When a page takes long to load it can happen that a new page is requested instead.
If the new page loads before the previous slow request, the new page is loaded
first and then replaced with the old request once it finishes. This is a confusing
to the user and thus the last request should always take precedence.

BUGFIX: Cancel previous load page requests

---

TYPO3.Neos/Resources/Public/JavaScript/Shared/Validation/StringLengthValidator.js

Fixed maximum string length validation error message

BUGFIX: Use correct value in ``StringLengthValidator`` error message

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/TypeConverter/NodeConverter.php

If a DateTime property is not parseable,
$nodePropertyValue->setTimezone() is called on a none-object.

BUGFIX: Verify DateTime parsing in nodeConverter

---

TYPO3.Neos/Classes/TYPO3/Neos/Utility/NodeUriPathSegmentGenerator.php

The uninitialized variable ``$language`` results in an exception
when the user tries to add a page on PHP 7 due to
``Notice: Undefined variable: language``.

BUGFIX: Page creation without ``language`` dimension

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/JavascriptConfigurationViewHelper.php
TYPO3.Neos/Configuration/Settings.yaml
TYPO3.Neos/Documentation/CreatingASite/RenderingCustomMarkup/CustomContentElements.rst
TYPO3.Neos/Resources/Private/Styles/Content/_InsertNodePanel.scss
TYPO3.Neos/Resources/Private/Styles/Foundation/_modals.scss
TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Components/AbstractInsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Menu/MenuPanel.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/InsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InlineEditingHandles.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InsertNodePanel.js
TYPO3.Neos/Resources/Public/Styles/Neos.css

Makes the node type groups in the insert node type panel collapsible.
The initial state can be configured using configuration::
TYPO3.Neos.nodeTypes.groups.general.collapsed: true
When the user toggles a group it is remembered and stored in local storage,
so the user has to toggle the group again to reset it.
Additionally optimizes the sizes of modal windows.
NEOS-786 #close
NEOS-614 #comment Optimized modals windows

FEATURE: Collapsible insert panel groups

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/ContentElementWrappingService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/NodeController.php
TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Breadcrumb.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/InspectorController.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/Node.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeSelection.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/PublishableNodes.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/CreateJs/jquery.typo3.collectionWidget.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/Dialogs/DeleteNodeDialog.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InlineEditingHandles.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/Shared/Configuration.js
TYPO3.Neos/Resources/Public/JavaScript/Shared/ResourceCache.js
TYPO3.Neos/Resources/Public/JavaScript/storage.js
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/FallbackNodeDataLabelGenerator.php

Instead of using the node type name the label of the node is used instead. This helps avoid confusing the breadcrumb in the inspector from a node type selector.
Additionally the label is now updated using the server side rendered label in the inspector breadcrumb, context structure tree and node tree.
NEOS-1141 #comment replaced the node type name with the node label, which should help a little

TASK: Use node label in inspector breadcrumb

---

TYPO3.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html

The node type label doesn't really represent the actual node making it difficult to identity,
instead the node label is used and the node type label is available on hover.

TASK: Display node label instead of node type label in workspace overview

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Views/NodeInfoView.js

The time shown in the `Additional info` box now respects the timezone for the `Created`, `Last modification` and `Last publication` date of a node. Until now the time was shown in UTC and therefore off a couple of hours for most of the world.
NEOS-1807 #close

BUGFIX: Correct timezone offset in node info inspector view

---

TYPO3.Neos/Documentation/References/PropertyEditorReference.rst

switched from "strings" to "entries" for select box and extended the introduction to clarify that datasources can be used as a source for select boxes

TASK: Update PropertyEditorReference.rst

---

TYPO3.Neos/Resources/Private/TypoScript/DefaultTypoScript.ts2

When a edit / preview mode with a rendering path is selected it can affect the
front-end view for the logged in user. To prevent this edit / preview modes now
only apply in the backend.
NEOS-1758 #close

BUGFIX: Prevent edit / preview rendering path from applying to front-end

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/NodeTree.js

- Prevent fatal error in node tree if title is undefined
- Show node type for newly created nodes in trees
- Editing a title in the node tree displays old title

BUGFIX: Creating new nodes in trees

---

TYPO3.Neos/Documentation/References/NodeMigrations.rst

The node migration transformation "CreateNodes" does not exist,
so it is removed from the documentation.

TASK: Remove "CreateNodes" from documentation

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js

This makes it more clear which structure node is selected and more in sync with the document node tree.
Visually the title is blue instead of just the background being color being lighter.
This corresponds with the blue outline the selected inline element has.

TASK: Make nodes selectable in context structure tree

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/NodeTree.js

When moving a page in the trees, the new custom tooltips could get stuck.
To prevent that the tooltips are hidden and disabled during dragging.
NEOS-1122

BUGFIX: Prevent tooltips getting stuck on tree moves

---

TYPO3.Neos/Resources/Public/JavaScript/storage.js

When a node type is changed for a node, the context structure
tree needs to be updated accordingly.
NEOS-1395 #close

BUGFIX: Update structure tree when changing node type

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js

Due to the improved AJAX error handling an error was shown for
cancelled requests.

BUGFIX: Don't show error notification on cancelled page loads

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Model/NodeSelection.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/ContentCommands.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/Editors/Aloha/UiPlugin/tabInSecondaryContainer.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InlineEditingHandles.js

Fix broken insert/cut/copy/paste actions when the Aloha table mode is active.
Prevent Aloha table mode from remaining active after selecting a new node
in the structure tree.

BUGFIX: Aloha table mode issues

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php

Two places use workspaces in `array_search` to find find the positions of a
workspace. This fails if two instances of the same workspace are used,
and even though this should not happen, the error is not "needed". When
using the name to compare the workspaces, everything works fine (as is to
be expected, since the name is the identifier).

TASK: Find workspacePosition by comparing names

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/InspectorController.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Model/Node.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InlineEditingHandles.js
TYPO3.Neos/Resources/Public/JavaScript/storage.js

When updating a properties for a node, only post the properties
that have actually changed. This improves performance since
fewer ``setProperty`` calls are needed. The more node properties
the bigger the impact.

TASK: Only update changed model properties

---

TYPO3.Neos/Configuration/Settings.yaml
TYPO3.Neos/Documentation/References/Configuration/Configuration.rst
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js

Like the node tree the structure tree has a configurable initial loading
depth now.
NEOS-1361 #comment Adjust structure tree handling

TASK: Make loadingDepth of structure tree configurable

---

TYPO3.Neos/Configuration/Settings.yaml
TYPO3.Neos/Resources/Public/JavaScript/ContentModuleBootstrap.js
TYPO3.Neos/Resources/Public/JavaScript/aloha.js

On slow internet connections in combination with large documents it can happen that the 
inspector editors and Aloha timeout while loading. This is solved by increasing the default
timeout from 7 seconds to 30.

BUGFIX: Backend fails to load due to RequireJS timeout

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Functional/Domain/NodesTest.php

If a node is inserted at a given position between nodes and no free sorting index is available, the sortindices on
that level are renumbered. The previous code for that could lead to unexpected node reordering and sortingindex
value escalation if workspaces or dimensions were used.
The following steps reproduce the error:
* In dimension A create nodes between other nodes until there are no free sortindices available
* Create a variant of those nodes in dimension B
* In dimension B add a new node in a place where no free sort index is available
Since the previous code is only repositioning one item of a given index and does not take workspaces and dimensions
into account this results in the following unwanted effects:
* Unwanted reordering of the nodes in dimension A
* In dimension B two …

BUGFIX: Free index space at target position if no free index space is available

---

TYPO3.Neos/Configuration/NodeTypes.yaml

The PR #448 changed the default expression used to generate the label by
adding a preg_replace. The way the pattern is specified breaks with the
php-yaml extension.
This changes fixes it by removing the backslash characters before the
slashes delimiting the pattern.
NEOS-1818 #close

BUGFIX: Fix default expression to generate node labels

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/DefaultPrototypeGenerator.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/DefaultPrototypeGeneratorInterface.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/TypoScriptService.php

This change introduces a new interface ``DefaultPrototypeGeneratorInterface``.
By implementing this interface you can change the default TypoScript prototypes
generated by Neos for every NodeType.

TASK: Introduce interface to customize the default TS prototype

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/AssetCollection.php

Prevents an exception thrown while property mapping for the title constructor parameter.

BUGFIX: Editing asset collection

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php
TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedNodes.html

In the usages overview for assets in the media module a list is rendered
with a path to the node where an asset is still used. This leads to a
call to getIdentifier() on a non object if the parent document node
is removed in the live / current users workspace.
As we can not display the title of the document in the other users workspace
this change leaves out the breadcrumb to the node in the overview.

BUGFIX: Call to getIdentifier on non object in usage references

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php

Adds a JSON output of ``"success" => false`` if authentication failed.
NEOS-1510 #close

TASK: ``LoginController`` respects JSON on authentication failure

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/SiteService.php

Deleting a site, e.g. using the ``site:prune`` command, fails due a database constraint violation.
This is due to Doctrine delete ordering, the site is deleted before the domains.
NEOS-178

BUGFIX: Prevent database constraint violation during site prune with existing domains

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/WorkspacesController.php
TYPO3.Neos/Classes/TYPO3/Neos/View/Service/WorkspaceJsonView.php

When requesting workspace data in JSON format from the WorkspacesController
null would be returned, since the controller was configured to use the
NodeJsonView.
This adds the missing WorkspaceJsonView and configures it to be used.

BUGFIX: WorkspacesController uses NodeJsonView

---

TYPO3.Neos/Configuration/Testing/Policy.yaml

We should always exclude initialize*Actions from method policy
matchers and this didn't happen in the Testing ``Policy.yaml``.
For unit and functional tests this does not pose a big problem
but behat tests fail when trying to call the backend login for
example.

BUGFIX: Exclude initialize*Actions from Testing Policy

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/ThumbnailGenerator/IconThumbnailGenerator.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Service/FileTypeIconService.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/FileTypeIconViewHelper.php

This change introduces a Filetype icon viewhelper
that renders a simple image tag with an icon for the
type of a given asset based on it's mediatypes and
given maximum dimensions.
Besides that it moves the logic for retrieving the icon
to a service that can be used outside of the thumbnail
generator service too.

FEATURE: Filetype icon view helper

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php

This change fixes a hardcoded place holder in the log message which warns
about invalid content dimension constraint usage. Also fixes a duplicate
exception code.

BUGFIX: Fix log message for invalid content dimension constraints

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Video.php
TYPO3.Media/Tests/Unit/Domain/Model/VideoTest.php

The Video model has an incompatible constructor as the Asset
model require a $resource argument. This change adds the argument
to the constructor and adds a test to prevent regressions.

BUGFIX: Incompatible constructor in Video model

---

TYPO3.Neos/Classes/TYPO3/Neos/Eel/FlowQueryOperations/ParentsOperation.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/Context.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ContextFactory.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/EmptyDimensionValues.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/FindSiteNode.feature

Implement support for empty dimension values (for any number of dimensions) of a node variant.
This allows to have nodes like ``/sites`` that will always be found, independent from the dimensions
of the context.
Another case is the transition to new dimensions that will be much easier because existing nodes
are already visible.
NEOS-1633 #close

BUGFIX: Support empty dimension values for default fallbacks

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/InsertNodePanel.js
TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/InsertNodePanel.js

Gracefully handle a node type configured configured with a non-existing
node type group.
Additionally changes the behavior when the group is set to null,
making it possible to hide the node type. If the group is not set,
it will default to the "general" group as previously.
Regression of 54aa91f19c8776a96003a631c23d8c1556fb33fe
NEOS-786 #comment Fix regression

BUGFIX: Handle missing node type group gracefully

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
TYPO3.Media/Resources/Private/Translations/en/Main.xlf
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php

This change translates flash messages for the AssetController by
translation id. The Neos backend module controller first resolves to
translations in the Modules.xlf of the TYPO3.Neos package, if no
translation is found transaltions are done based on the TYPO3.Media
package translations.
The Neos module take the users language preference into account.

TASK: Translate flash messages for asset management

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php

This change removes the redundant fetching of user locale introduced
in 8b5c9ff395d6a5ff54aa2f861b2a13a310ffac08.

TASK: Remove redundant fetching of user locale

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Administration/PackagesController.php

Show the actually installed version of each package instead of the defined version in the composer manifest.
NEOS-1826 #close

BUGFIX: Show installed version of packages in package manager backend module

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Validator/AssetValidator.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Validator/AssetValidatorInterface.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Validator/AudioValidator.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Validator/ImageValidator.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Validator/VideoValidator.php
TYPO3.Media/Documentation/DeveloperInformation/index.rst
TYPO3.Media/Documentation/index.rst

This change allows extending the validation of assets. It is done by
creating a model validator for asset entity types. The validator
extends the conjunction validator and loads all validators that implement
the ``\TYPO3\Media\Domain\Validator\AssetValidatorInterface``.

FEATURE: Extensible asset validation

---

TYPO3.Neos/Tests/Unit/Service/PublishingServiceTest.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ConfigurationContentDimensionPresetSource.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ContentDimensionPresetSourceInterface.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Service/PublishingService.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/MoveNodeWithDimensions.feature

The Context created for Nodes in a workspace in the ``PublishingService``
was derived from the ``NodeData`` entities dimension values, which should only
be the target values of the context but (wrongly) doesn't consider fallbacks
configured in presets.
To solve this a new method in the PresetSource allows to find best matching
presets based on target values for dimensions. Those are then used to
get a ``Context`` with fallback rules for dimensions, avoiding errors with
missing nodes in the root path as these might only exist within a ``Context``
that considers fallback rules.
The ``ContentDimensionPresetSourceInterface`` is not declared public ``@api``
so the change is not marked breaking.

BUGFIX: Publishable Node Context considers dimension fallbacks

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/SelectBoxEditor.js

When options are populated asynchronously to the select box editor (e.g.
when using data source or in the plugin view editors) the value wasn't
updated properly.
Regression introduced in 2b79b585b63f3d07153af404721a77798e47cf3a

BUGFIX: Values not selected in select box editor when added asynchronously

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ReferencesEditor.js

When a references editor has no selected values it queries the
backend without any identifiers, leading to an exception on the
server side.
Regression of b906930ca056823c75462fffddefa6278ef54e16
NEOS-1828 #close
NEOS-1261 #regression

BUGFIX: Empty references editor should not send query

---

TYPO3.Neos/Configuration/Settings.yaml

In 6cc5ad24997a55cc31fceacb62188e5c6feec640 the configuration for the rendering of the neos-viewhelpers was added. This commit adds this configuration to the list of references that is automatically updated for neos.

TASK: Adjust configuration to render the neos-viewhelper reference automatically

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Adjustment/CropImageAdjustment.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Service/AssetService.php
TYPO3.Media/Configuration/Policy.yaml
TYPO3.Media/Resources/Private/Templates/Asset/ReplaceAssetResource.html
TYPO3.Media/Resources/Private/Translations/en/Main.xlf
TYPO3.Media/Resources/Public/Scripts/edit.js
TYPO3.Media/Tests/Unit/Domain/Model/Adjustment/CropImageAdjustmentTest.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php
TYPO3.Neos/Classes/TYPO3/Neos/Package.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/Cache/ContentCacheFlusher.php
TYPO3.Neos/Configuration/Policy.yaml
TYPO3.Neos/Resources/Private/Partials/Media/ListView.html
TYPO3.Neos/Resources/Private/Partials/Media/ThumbnailView.html
TYPO3.Neos/Resources/Private/Styles/Foundation/_utilities.scss
TYPO3.Neos/Resources/Private/Styles/Media/_Media.scss
TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/Index.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedNodes.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/ReplaceAssetResource.html
TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/SecondaryInspectorController.js
TYPO3.Neos/Resources/Public/Styles/Neos.css

Introduce replacement of files in Neos. When an asset
is replaced the content cache for nodes that use the
asset or a variant is flushed. Also a 301 redirect from
the old resource url to the new url is created.
Because the changes are applied to the asset model directly
the changes will be live immediately. For this reason
the replace functionality is restricted to live publishers
in Neos.
In case image variants have cropping instructions they
will be reset to the maximum bounds for the new image.

FEATURE: Replace existing assets with new version

---

TYPO3.Neos/Resources/Private/Styles/Inspector/_SecondaryInspector.scss
TYPO3.Neos/Resources/Public/Styles/Includes-built.css
TYPO3.Neos/Resources/Public/Styles/Neos.css
TYPO3.Neos/Scripts/Gruntfile.js

The built CSS file concatenated library CSS files without
rewriting the relative URLs, leading to missing assets.
One example is the missing down caret for the Aloha list styles.
NEOS-1618 #close

BUGFIX: Use correct relative paths in built CSS files

---

TYPO3.Neos/Resources/Public/JavaScript/aloha.js

When using Aloha list styles, the class attribute was sanitized automatically making the feature unusable.
NEOS-854

BUGFIX: Aloha list style class not sanitized

---

TYPO3.Neos.NodeTypes/Classes/TYPO3/Neos/NodeTypes/Service/DataSource/FormDefinitionDataSource.php
TYPO3.Neos.NodeTypes/Configuration/NodeTypes.Content.yaml
TYPO3.Neos/Documentation/HowTos/AddingSimpleContactForm.rst

Currently form identifiers need to be defined manually extending
the properties of ``TYPO3.Neos.NodeTypes:Form`` .
This change adds a data source which uses the
`TYPO3\Form\Persistence\YamlPersistenceManager::listForms`
to list all available forms automatically.

FEATURE: Use data source to list forms in inspector

---

TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml

The schema was altered before to allow setting the properties to NULL in a derived nodeType. This was done incompletely and lead the situation where the schema validation only validates that the
value of properties was a dictionary or null.
The ``additionalProperties`` were ignored because that property is only evaluated inside
a dictionary schema.
The underlying intent to allow resetting the properties in derived node types by setting ``NodeType.properties: null`` is not supported any more. The correct syntax to achieve this
is instead ``NodeType.properties: []``.
This is not marked as breaking since it will not break functionality. Nevertheless it alters
what is marked as a defect configuration.

BUGFIX: Fix schema error that prevented the validation of aloha configurations

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/AssetEditor.js

If the ``AssetInspector`` is used for a single asset used and the asset is removed the inspector will call the ``assetMetadataEndpoint`` without any asset identifier. This changes it to only call the fetch the meta data if there is an asset.

BUGFIX: Avoid fetching meta data when ``AssetEditor`` is empty

---

TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/Editors/Aloha/LinkPlugin/lib/neos-link-plugin.js
TYPO3.Neos/Resources/Public/Library/aloha/aloha.js
TYPO3.Neos/Scripts/Gruntfile.js

When creating a multi-line link to using inline editing, only the
first link is created correctly unless a whole URL is specified.
The issue lies in Aloha and an issue with a fix has been pushed to
their backlog. Until that is merged it is hotfixed in Neos.
https://github.com/alohaeditor/Aloha-Editor/issues/1525

BUGFIX: Multi-line links in inline editing

---

TYPO3.Neos/Resources/Private/Partials/Module/Shared/EditAccount.html

This cleans up the UI and improves the contrast when displaying the role identifiers.

TASK: Use tooltip for additional information about account roles

---

TYPO3.Neos/Resources/Public/JavaScript/aloha.js

Allows the user to link telephone numbers and Skype usernames with Aloha.
NEOS-512 #close

BUGFIX: Allow ``tel:`` and ``callto:`` link protocols in inline editing

---

TYPO3.Neos.NodeTypes/composer.json

In a86591d459cb9a0f87daae72839019415b6fb1a6 the autoload
section was removed, as there had been no classes at that time.

BUGFIX: Add autoload to composer again

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Repository/AssetRepository.php

The caption field is not respected, when you are searching for assets.
NEOS-1837 #close

TASK: Respect caption field for asset search

---

TYPO3.Media/Migrations/Mysql/Version20110925123120.php
TYPO3.Media/Migrations/Postgresql/Version20120412194612.php

When installing ``typo3/media`` into an existing Flow 2.x project, a schema
migration relies on an old table name, which does not exist anymore.
This change fixes that by checking for the table name and target the
FK to create on the correct table.
NEOS-1341 #close

BUGFIX: Allow installation of typo3/media into Flow 2.x project

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js

This fixes an issue that causes the backend UI to recursively find a valid URI
in the document tree and load it, whenever a 404 response occurs to the
HTTPClient or HTTPRestClient.
That behavior is now only applied, when an actual page load is requested
and remains silent for all other requests.
NEOS-1533 #close
NEOS-1831 #close

BUGFIX: Restrict global 404 handling in UI to page loads only

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/NodeController.php

The service `NodeController` does not add the `currentSite` and `currentDomain` properties to the node context if a page is searched with `searchPageAction()`. Without them the uri can not be resolved.

BUGFIX: Service/NodeController does not set all context properties

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/Controller/NodeController.php

The service `NodeController` does not add the `currentSite` and `currentDomain` properties to the node context if a page is searched with `searchPageAction()`. Without them the uri can not be resolved.
This methos is also marked as deprecated with this change since it is never used and will be removed with 3.0

BUGFIX: Service NodeController does not set all context properties

---

TYPO3.Neos/Documentation/CreatingASite/ContentCache.rst

Update content cache documentation to include a remark that the
node identifier of the current node should be included in most cases.

TASK: Update content cache docs

---

TYPO3.Neos.Kickstarter/Resources/Private/Generator/Content/Sites.xml
TYPO3.Neos.Kickstarter/Resources/Private/Generator/Template/SiteTemplate.html
TYPO3.Neos.Kickstarter/Resources/Private/Generator/TypoScript/Root.ts2

Removes useless text node to prevent complications with dimensions,
the breadcrumb that these days is seldom used and uses fully qualified
prototype names for all used TypoScript objects to make understanding
easier.

TASK: Streamline generated Site packages

---

TYPO3.TYPO3CR/Configuration/Objects.yaml

The ConfigurationContentDimensionPresetSource in TYPO3CR did not have its
configuration set by default (as opposed to the Neos implementation).

BUGFIX: Add missing default configuration

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/ContentElementEditableService.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ContentElementEditableImplementation.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ContentElementWrappingImplementation.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/ContentElement/EditableViewHelper.php
TYPO3.Neos/Resources/Private/TypoScript/DefaultTypoScript.ts2
TYPO3.Neos/Resources/Private/TypoScript/Prototypes/ContentElementEditable.ts2
TYPO3.Neos/Tests/Unit/Service/ContentElementEditableServiceTest.php
TYPO3.Neos/Tests/Unit/ViewHelpers/ContentElement/EditableViewHelperTest.php

This change extracts the functionality of the neos:contentElement.editable viewHelper into a service and adds an equivalent TypoScript-Prototype.
TypoScript Example:
```
element = TYPO3.TypoScript:Array {
title = TYPO3.TypoScript:Tag {
tagName = 'h1'
content = ${q(node).property('title')}
@process.contentElementEditable = TYPO3.Neos:ContentElementEditable
@process.contentElementEditable.property = 'title'
}
@process.contentElementWrapping = TYPO3.Neos:ContentElementWrapping
}
```

FEATURE: Add ``TYPO3.Neos:ContentElementEditable`` TypoScript-Object

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Functional/Domain/NodesTest.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Repository/NodeDataRepositoryTest.php

This adds a check for better matching node variants to path traversal
queries of the NodeDataRepository to prevent fallbacks showing up
even if a better matching variant exists.
NEOS-1841 #resolve

BUGFIX: Node fallbacks not properly checking for variants

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Parser.php

When writing `include: NodeTypes/**/*` in `Root.ts2` a misleading exception shows up, if the directory does not exist.

BUGFIX: Remove double negative from error message

---

TYPO3.Neos/Documentation/CreatingASite/TypoScript/InsideTypoScript.rst

1) Missing colon in namespace definition
2) Namespaces are defined globally, and not for the scope of the current file

BUGFIX: correct documentation mistakes regarding the usage of namespaces

---

TYPO3.Neos/Documentation/CreatingASite/TypoScript/InsideTypoScript.rst
TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/DebugImplementation.php
TYPO3.TypoScript/Resources/Private/TypoScript/Root.ts2
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/DebugTest.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/Debug.ts2

A TypoScript Object "Debug" is added as an equivalent to the ``f:debug`` view helper.
The Object will display the value of all child-keys in a debug window.
```
tsPath = TYPO3.TypoScript:Debug {
value = "hello neos world"
documentTitle = ${q(documentNode).property('title')}
documentPath = ${documentNode.path}
}
```

FEATURE: ``TYPO3.TypoScript:Debug`` TypoScript-Object

---

TYPO3.Neos/Documentation/ExtendingNeos/CustomViewHelpers.rst

There was a typo in the section about "Context and Children". In the `if` block the variable `$title` got assigned and not checked.

TASK: Fix typo in custom view helpers documentation example

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Administration/SitesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/Site.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/SiteService.php

Currently it's not possible to prune a site with a primary domain or delete a primary domain in the Neos backend.
This change will first unset the primary domain of a site if it's the one which should be deleted and then deletes it.
NEOS-1839 #close

BUGFIX: Allow the deletion of the primary domain

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Asset.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Thumbnail.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Repository/AssetRepository.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Service/AssetService.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ThumbnailService.php
TYPO3.Media/Classes/TYPO3/Media/Package.php

In order to implement additional tasks for asset handling,
like meta data management, these new signals in the
central point of asset handling - the meta data repository -
notify on asset created / updated / removed.
Moved assetCreated and thumbnailCreated to the corresponding
services for consistency.

TASK: Add signals to notify on asset add / update / remove

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/CacheSegmentParser.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/ContentCache.php
TYPO3.TypoScript/Tests/Unit/Core/Cache/CacheSegmentParserTest.php
TYPO3.TypoScript/Tests/Unit/Core/Cache/ContentCacheTest.php

This change adds a random cache marker directly to the content cache
which will be used after cache segment tokens to add a better protection
against content that contains one of these characters. The parser will
only match against the cache segment tokens with added marker, so the
chance of accidentally breaking the content cache should be very low.
NEOS-365 #close

BUGFIX: Protect content cache against segment tokens in content

---

TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst
TYPO3.TypoScript/Resources/Private/TypoScript/Root.ts2

This change sets a default value of `itemName` to `item`, so you can use `TYPO3.TypoScript:Collection` object without specifying it each time:
```
helloLoop = TYPO3.TypoScript:Collection {
collection = ${[1, 2, 3]}
itemRenderer = ${item + '<br>'}
}
```
This change is backwards compatible, as your value for `itemName` would always override the default value.

TASK: set a default value of `itemName` in the `TYPO3.TypoScript:Collection` object

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/RuntimeContentCache.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/ContentCacheTest.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/ContentCache.ts2

The old behaviour was to try to construct the entryIdentifier from all
context vars, which did not make a lot of sense.
With the new behaviour, the entryIdentifier is filled with identifiers from the
`TYPO3.TypoScript:GlobalCacheIdentifiers` prototype.
So in many cases, it would not be necessary to provide any
entryIdentifiers at all and just configure GlobalCacheIdentifiers.

TASK: change caching behaviour when no `entryIdentifier` is set

---

TYPO3.Neos.Kickstarter/Resources/Private/Generator/Content/Sites.xml

Fixes an error so freshly kickstarted site packages can be imported again
Regression of 1dcf1f2e0db3d0d7bd5f31f033be975227aa9cd0

BUGFIX: Fix structure in ``Sites.xml`` for generated site packages

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Adjustment/CropImageAdjustment.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Adjustment/ResizeImageAdjustment.php
TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ImageService.php
TYPO3.Media/Classes/TYPO3/Media/Imagine/Box.php
TYPO3.Media/Tests/Unit/Domain/Model/Adjustment/ResizeImageAdjustmentTest.php

Images that have extreme dimensions (e.g. 2000x2) could cause exceptions
when scaling because of a zero width or height when calculating the
resulting thumbnail size.
This change introduces a custom Imagine Box implementation that prevents
boxes with zero width or height when scaling a box.
NEOS-576 #comment PR 564 is related to this

BUGFIX: Fix resizing of images with "extreme" ratios

---

TYPO3.Neos/Classes/TYPO3/Neos/Eel/FlowQueryOperations/ParentsOperation.php
TYPO3.Neos/Tests/Unit/FlowQueryOperations/ParentsOperationTest.php

The ParentsOperation in Neos expects a Neos `ContentContext` to work with,
so `canEvaluate()` should check for it to allow for proper function and
fallback handling if a "normal" CR `Context` is given.

BUGFIX: Check for expected context in ParentsOperation

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Service/NodesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/ContentElementWrappingService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/DateStringConverter.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/NodePropertyConverterService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/NodeReferenceConverter.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/NodeTypeStringConverter.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ContentElementWrappingImplementation.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ExceptionHandlers/NodeWrappingHandler.php
TYPO3.Neos/Classes/TYPO3/Neos/TypoScript/ExceptionHandlers/PageHandler.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/ContentElement/WrapViewHelper.php
TYPO3.Neos/Configuration/Settings.yaml

This removes all special type handling to format node properties for
the Neos user interface and replaces it with using ``PropertyMapper``.
The introduced ``NodePropertyConverterService`` is fully responsible to
provide a portable representation of the Node properties.
Node property types can be configured to use specific ``TypeConverter``
implementations to give all necessary information to the inspector
editor. Additionally a fallback ``defaultValue`` for property types
can be added in Settings.
Please note that we introduce some default values in case you didn't set
a default value in your ``NodeTypes.yaml``. All of those are common sense
but you might want to check if they work for you in all cases.
This allows to map arbitrary objects to node properties and interact with
them in the …

FEATURE: Allow relation between arbitrary entities and nodes

---

TYPO3.Neos/Resources/Private/Styles/_Tree.scss
TYPO3.Neos/Resources/Public/Styles/Neos.css

The expand icons in the node tree where off a few pixels along the y-axis (open and folded).
NEOS-1844 #close

BUGFIX: Align displaced expand icons in node tree

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Functional/Domain/Repository/NodeDataRepositoryTest.php

When querying for nodes based on (parent) paths, a LIKE query was used in
certain cases. This query would include unrelated nodes, if the paths involved
would share a common prefix:
/some/node-12
/some/node-123
Nodes below both paths would be included because of:
LIKE "/some/nodes-12%"
Now those queries append a slash, to read:
LIKE "/some/nodes-12/%"
NEOS-1849 #close

BUGFIX: Fix like queries using paths in NodeDataRepository

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/CreateContentContextTrait.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/ContentContextFactory.php
TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/BackendRedirectionService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/PublishingService.php
TYPO3.Neos/Classes/TYPO3/Neos/TypeConverter/NodeConverter.php
TYPO3.Neos/Tests/Unit/Domain/Service/ContentContextFactoryTest.php
TYPO3.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php
TYPO3.Neos/Tests/Unit/Service/PublishingServiceTest.php

The logic to fetch site and domain for the ``ContentContext`` was
duplicated in several parts of Neos. This duplication is rather useless
as the values derived by it can be seen as default values for the two
properties. Therefore the logic was refactored to the
``ContentContextFactory`` and removed from other places in favor of
letting the factory set it as default.

TASK: De-Duplicate site and domain logic

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeConstraints.rst

There are sometimes browser caching issues when working with node type constraints. This hint should help prevent some of them.

TASK: Add a hint for cache clearing to the Node Type Constraints docs

---

TYPO3.Neos.NodeTypes/Resources/Private/TypoScript/Root.ts2

Provides the iteration information for multi column elements per default as
context variable with the name ``columnIteration``.
Also provides the selected ``layout`` value of the column container to the
columns via context variable named ``columnLayout``.

FEATURE: Additional configuration for multi column elements

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php

This fixes an error when trying to switch from a subnode of one site to another site.
The lastVisitedNode session variable is always pointing to the node that was last open in frontend to redirect to that page. 
If you visit a subpage from one site and switch to another, Neos opens the last node in the new site. In most cases this will fail.

BUGFIX: reset lastVisitedNode on site switch

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeType.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Model/NodeTypeTest.php

No, the title is not an error. Here is what happens:
- You define a node type and inherit from "Document"
- In that NodeType unset a supertype declared in "Document"
- Now inherit from that nodetype again, and whatever the unset supertype
declared, will be back
This is caused by how the inherited supertypes are read using the method
getDeclaredSuperTypes, which only returns the used supertypes, not the
ones not used - even if "actively not used".
This change fixes that and is marked breaking because there might be things
disappearing from your nodetypes, depending on the nesting of your hierarchy.

!!! BUGFIX: Keep supertypes unset in supertypes unset

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php

This configures the property mapping when updating a workspace so that
the owner can be mapped properly.
NEOS-1804 #close

BUGFIX: Allow to change owner of workspace

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php
TYPO3.TYPO3CR/Tests/Functional/Domain/NodesTest.php

It would be convenient to change the name of a node while moving
it to a new destination. To avoid exceptions due to existing nodes
you only need to find an available name at the target location then.

FEATURE: Allow setting a new Node name in move operations

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/ContentElementWrappingService.php

If a nodetype has "virtual" properties configured (like when Elasticsearch
is used with Neos), trying to access those properties resulted in
The property "…" on the subject was not accessible.
This change introduces a check for property names starting with `__` and
skips those, like already done in the `NodePropertyConverterService`
NEOS-1860 #close

BUGFIX: Skip private node properties in ContentElementWrappingService

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Menu.ts2

If a starting point for a `TYPO3.Neos:Menu` is set the entryLevel won't work out of the box in all cases because it defaults to the first level of the site. If the starting point is below that you won't see any menu items.
This changes the default behaviour of the entryLevel. It will be set to 0 if there is a startingPoint configured otherwise stick to 1.
NEOS-1838 #resolve

TASK: `TYPO3.Neos:Menu` entryLevel should respect a starting point

---

TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosBackendEndpoints.html

Bust the cache for content dimensions settings so changes are visible in the backend instantly.

BUGFIX: Bust cache for content dimensions configuration

---

TYPO3.Neos/Documentation/CreatingASite/ContentCache.rst

The path ```page.content.main``` is "invalid", the missing ```body``` segment can be annoying when reading the documentation.

TASK: Fix code sample in content cache configuration

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php

Adding a flash message in `AssetController` results in an exception if the tranlsator service returns null for a label. If the service returns null the label will be returned as a fallback.
This change also removes an unecessary method `addFlashMessage` as it implements just the same logic as `parent::addFlashMessage`. This method also calls right now the parent method with an already translated id wich can not be translated again.

BUGFIX: Add message fallback for `addFlashmessage` in AssetController

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This change adds a couple of persistAll() calls to the different steps
in node:repair in order to save changes before the next steps begin.
That way, if one step fails, at least the previous steps have been
already persisted.
Additionally this may potentially prevent inconsistencies in cases where
the same node is created from NodeData multiple times without
acknowledging the Unit of Work.
Also contains a few smaller cosmetic changes to the console output.

TASK: Persist intermediate node:repair results

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This fixes an issue with node:repair which also removes valid and
healthy nodes while deleting nodes which are abstract or assigned to
an unknown node type.
removeAbstractAndUndefinedNodes() correctly found invalid nodes, but
only used the node path and workspace name as an identifier for removing
them. If there are further nodes matching this criteria, for example
with different dimension values, these would be deleted as well,
even though they may be completely valid.
This patch introduces a new method which allows for removal of a node
specified by node identifier and dimension hash.

BUGFIX: node:repair also removes valid nodes

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php

This fixes a regression introduced in #591 (commit:
1fd3fcabf61f922f9019773341d74ac17b04887d) which results in an internal
server error if a user tries to switch from one site to another using
the Neos user interface.
The code assumed that `$this->session` is already the new session the
`tokenLoginAction` is about to switch to and that this session is
already initialized. However, `$this->session` more often than not
is the session the user is about to leave and is not currently running.
The fix now unsets the `lastVisitedNode` in the new session the user
is about to switch to and makes sure that it is fully initialized.

BUGFIX: Site switch fails with "session not started"

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php
TYPO3.TYPO3CR/Tests/Functional/Domain/NodeDataTest.php

The setDimensions method on NodeData did simply replace the ArrayCollection
with a new one. This left previously attached NodeDimension entities in the
database, leading to issues.
This change fixes that by no longer replacing the full collection but working on
the contained entries instead.
This fix was the base for a new task to node:repair that removes any content
dimensions set on those nodes. Because when the root or the sites node have
content dimensions assigned, this can lead to issues with nodes not being found
when traversing from the root node.

BUGFIX: Correctly remove NodeDimension association in setDimensions

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php
TYPO3.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php

The ``FrontendNodeRoutePartHandler`` caused an php error when it was called with a node that originated from another site than the site in the content context. Since a comparison between the current-node and the siteNode was used as an exit-condition for the url-path generation the method did not detect the siteNode of the external node properly and traversed up to the /sites node where an error occurred because no uri-path-segment could be found.
This fix avoids this by detecting the siteNodes by checking wether the parentPath of of the node equals ``SiteService::SITES_ROOT_PATH``

BUGFIX: Fix crossdomain-linking error

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

Free memory after removing disallowed child nodes after each dimension combination
NEOS-1852 #comment This does not the resolve the issue of much memory being used per node but prevents multiplying memory usage by the number of dimension combinations available

TASK: Free memory after disallowed child nodes removal

---

TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Format/RelativeDateViewHelper.php

Resolves a bug that caused the month to be returned in a textual and numeric representation, by removing the months numeric representation and replacing it with the day.

BUGFIX: Day incorrectly formatted in media browser

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/HtmlAugmenter.php
TYPO3.Neos/Tests/Unit/Service/HtmlAugmenterTest.php

Escapes all `$` dollar signs to prevent accidentally replacement of placeholders like `$0` within the preg_replace of HtmlAugmenter.
NEOS-1865 #close

BUGFIX: Escape preg_replace placeholders to prevent accidentally replacements

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandController.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This change contains an improvement for node:repair which runs an
additional check for nodes which have dimension values which are not
allowed according to the current dimension configuration.
These nodes can be either removed or the user can decide to migrate them
by other means (for example a node migration).

FEATURE: node:repair: remove nodes with invalid dimension values

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/NodeCommandControllerPlugin.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandController.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This change introduces two new options for the ``node:repair`` command
which allows for selective execution of ``node:repair`` checks.
The ``--skip`` option accepts one or more check names (identifiers) which
should be skipped.
If the ``--only`` option is used, only the the checks which are specified
in ``--only`` will be executed.
The identifier for each check can be looked up in the ``node:repair`` help
screen. If multiple check identifiers are specified, they need to be
separated by commas.

FEATURE: Introduce --skip and --only to node:repair command

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Backend/ContentController.php

This adjusts the `Backend\ContentController` to set the
`CONFIGURATION_OVERRIDE_TARGET_TYPE_ALLOWED` property mapping flag
for incoming assets.
Background:
When selecting a single `Asset` in the Neos backend, its metadata
is retrieved via the `/neos/content/asset-with-metadata` endpoint.
This expects a list of asset identifiers.
However, in the case of `ImageInterface`-assets we instead send an
object `{__identity: <uuid>, __type: <type>}`.
Note: The fix is backported from #102

BUGFIX: Fix `asset-with-metadata` endpoint for images

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/NodePropertyConverterService.php

This results in `references` properties to not get wrapped with ContentElementWrappingService correctly.
Steps to reproduce: edit some property of a node of type `references`, hit apply, the property will become empty again.

BUGFIX: `references` property type not properly converted

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

The pull request #643 introduced two regressions where the
argument order of methods was no longer correct.

BUGFIX: Fix regressions introduced by skip/only change

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Tests/Functional/Domain/LayeredWorkspacesTest.php

In a multi-layered workspace scenario a removed node should only ever
really be removed when publishing into the root workspace (live).
When publishing in a workspace that has a base workspace we should
instead publish a removed node into that workspace to overlay any
existing nodes in the base workspace.
Additionally cleans the code as some of the checks are done deeper
down again and also rely on too much internal knowledge when done
in the Workspace publish methods.
NEOS-1872 #resolve

BUGFIX: Layered workspaces should retain removed nodes

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Functional/Domain/LayeredWorkspacesTest.php

Shadow nodes were only ever deleted on publish which leads
to strange results in case you publish into a workspace that
has another base workspace as then the shadow node is still
needed for proper function of the CR. With this change the
workspace checks if the shadow node is still needed and adjusts
it to the new workspace.

BUGFIX: Shadow nodes need to be published as well

---

TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosBackendHeaderData.html
TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js

This change adds a marker class to the Neos CSS link tag and will remove
and append all stylesheets into the document after loading a page in
the content module. This solves issues with document dependent CSS
includes on a site as well as the initial rendering of shortcut documents.
NEOS-830 #close
NEOS-99 #close

BUGFIX: Replace document stylesheets after loading a page

---

TYPO3.Neos.Kickstarter/Classes/TYPO3/Neos/Kickstarter/Command/KickstartCommandController.php

The previous error message did not say, that the format `Vendor.PackageKey` is mandatory.

BUGFIX: Fix error message when creating new site package

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This change introduces a new check into ``node:repair`` which scans all
nodes which have ``null`` as their workspace and offers to removed them.
When workspaces have been deleted manually or users have been deleted
in a non-standard way, the user's nodes will be left behind. Because
there is a constraint configured in the database between workspaces
and the workspace field in Node Data, the result of such an operation
will be that the respective nodes end up with `null` in their workspace
field.

FEATURE: node repair - remove nodes with invalid workspaces

---

TYPO3.Neos/Tests/Unit/ViewHelpers/IncludeJavaScriptViewHelperTest.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Repository/NodeDataRepositoryTest.php

Mocking a "virtual" class is no longer allowed, so we use real classes.

TASK: Adjust unit tests to use "real mocks"

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/FileTypeIconService.php

The ``getDocumentIconSize`` method is called in ``getIcon`` which is static, therefore
it should be static as well.
NEOS-1879 #resolve

BUGFIX: FileTypeIconService should have only static methods

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/SiteCommandController.php

This change will make site exports via `./flow site:export` tidy by default.
NEOS-1430 #resolve

TASK: Make the site export tidy by default

---

TYPO3.Neos/Configuration/Settings.yaml

Changes the session name from the default (TYPO3_Flow_Session) to
"Neos_Session".
This is breaking in case you configured your hosting in relation to the cookie
name (e.g. Varnish rules).

!!! TASK: Give Neos session (cookie) a distinct name

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Persistence/Ast/ToStringFunction.php
TYPO3.TYPO3CR/Configuration/Settings.yaml

Adds an explicit string conversion which is needed for PostgreSQL > 9.4
to convert a JSON type to string. This is needed when matching a string
pattern in the NodeSearchService against the node properties.
NEOS-1873 #resolve

BUGFIX: Node property search with PostgreSQL 9.5

---

TYPO3.Neos/Documentation/InsideOfNeos/UserInterface/Translation.rst

replaces https://github.com/neos/neos-development-collection/pull/663. Now for 2.0 instead of master.

fix wrong hint meaning

---

TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/DimensionsMenu.html

This change fixes a wrong usage if the render- viewhelper for the dimensions menu `itemLabel` section

BUGFIX: Render item label section correctly

---

TYPO3.Neos/Resources/Private/Templates/Media/Asset/ReplaceAssetResource.html
TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf

Replaced remaining texts with translation keys to allow translating the replace asset view.
Neos-1878 #close

BUGFIX: Add translation keys to replace asset view

---

Readme.rst

Point to a Neos LICENSE file in Readme.rst instead of pointing to the neos packagist presence

Point to a Neos LICENSE file in Readme.rst

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php

First check that the node is still of type NodeInterface and until then
get the parentPath.

BUGFIX: Fix condition in `getRequestPathByNode`

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

This change addresses an issue which results in a fatal error caused
by foreign key constraints when a user tries to publish her changes
to another workspace. The root cause is that the task in node:repair
which fixes "unstable" node identifiers of auto-created child nodes
only changes identifiers of nodes in a specific workspace (by default
the "live" workspace) and by that irreversibly disconnects corresponding
nodes in other workspaces.
The fix consists of two parts: First, the "create missing child nodes"
task of node:repair is modified so that node identifiers are always
changed accross all workspaces. Second, there is a new node:repair
task which detects and fixes inconsistencies caused by this bug.
If you experience the symptom described earlier, simply run a
node:repair to fix the …

BUGFIX: Workspace publishing fails after node:repair

---

TYPO3.Neos/Resources/Public/JavaScript/InlineEditing/Editors/Aloha/UiPlugin/multiSplit.js

There internal selectedValue of the tag name selection for aloha get's out of sync when changing via cursor/mouse. Since aloha already handles "changes" to same state well, no need to have this logic again.
NEOS-1883 #close

BUGFIX: Aloha format options

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Command/NodeCommandControllerPlugin.php

As this is not possible the call is replaced by code duplicated from
``NodeData`` for now.

BUGFIX: createShadow cannot be called from outside as it's protected

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php
TYPO3.Neos/Configuration/Policy.yaml

This fixes potential nesting level too deep errors caused
by comparing objects recursively.

BUGFIX: Use strict comparison in policies and UserService

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ImportExport/NodeImportService.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/ImportExport/Fixtures/SingleNodeWithLinebreaks.xml
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/ImportExport/NodeImportServiceTest.php

Adds a trim around all `DateTime` string values to prevent problems with DateTimeConverter.
Fixes: #710

BUGFIX: Trim date value to prevent problems in node import

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php

The ``NodeData::createShadow`` method was changed to protected
visibility in 2.2, as it is vital to repair certain constellations
of nodes it is changed back to public.

BUGFIX: Make ``NodeData::createShadow`` public again

---

TYPO3.Neos/Resources/Private/Translations/en/NodeTypes/Document.xlf

Currently the label is missing:

BUGFIX: add missing label for the document group

---

TYPO3.Neos/Resources/Private/Styles/Foundation/_reset.scss

Instead of showing a pointer cursor for all labels, only show for those that actually have a ``for`` attribute making them clickable.

BUGFIX: Only show pointer cursor for label tags with for attribute

---

TYPO3.Neos/Resources/Private/Templates/Module/User/UserSettings/Edit.html

Cancel in editing user settings links to user module instead of management module.

BUGFIX: Cancel in editing user settings links to user module

---

TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Form/CheckboxViewHelper.php

To prevent a recursive comparison which can lead to this error, strict comparison is used which only compares the reference.
This issue occurs in the edit asset collection view in the media module.

BUGFIX: Prevent nesting level too deep error in checkbox view helper

---

TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/EditAssetCollection.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/New.html

Since Fluid generates the ``name`` attribute based on the object relation, some of the fields need to be assigned a id to match their label tag.

BUGFIX: Clickable labels in the media views

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Application.js

Improves the replacement of stylesheets by avoiding removing them unless actually changed between page loads. Without it a FOUC (flash of unstyled content) appears under some conditions like slow connection, device, server or similar.
Regression introduced with #375 which takes a very basic approach to solve the issue.

BUGFIX: Replace stylesheets with less side-effects

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/TypeConverter/NodeConverter.php

This change makes the NodeConverter accept null for references properties,
a behavior also present for other property types (e.g. DateTime).
Fixes #1142

BUGFIX: Ignore null for references property in NodeConverter

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Classes/TYPO3/Neos/Package.php

- Flush routing cache when a node is discarded
- Use publishing service to publish workspace in workspaces module

BUGFIX: Two node publishing issues

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php

To make sure that after translation no null value is given as argument
to ``parent::addFlashMessage`` we should prevent null values.

BUGFIX: Check for null values after translation of FlashMessages

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php

The ``TYPO3.Neos:Editor`` role isn't always necessary for a user to have a personal workspace.
If there doesn't exist a workspace for that user, it will be handled in ``deletePersonalWorkspace()`` anyway.

BUGFIX: Personal workspace is always deleted when user is deleted

---

TYPO3.Media/Classes/TYPO3/Media/TypeConverter/AssetInterfaceConverter.php

This fixes an issue with the Asset converter which resulted in a broken
image upload function.
During the refactoring from `Resource` to `PersistentResource`, the
remaining occurrences of `Resource` haven't been adjusted in
`AssetInterfaceConverter`. This didn't lead to a direct error, but
the condition where `Resource` was still used, could never match.
Fixes #1149

BUGFIX: Image upload is broken: Asset instead of ImageInterface

---

TYPO3.Media/Classes/TYPO3/Media/Controller/AssetController.php

The upmerge from 2.2 to 2.3 introduced a regression because of
an undefined variable. This was probably introduced because of
a merge conflict with 427d0ed70e5365fa906f4196c936e4c9271d266e

BUGFIX: Undefined variable in AssetController

---

TYPO3.Media/Resources/Public/Scripts/edit.js
TYPO3.Media/Resources/Public/Scripts/new.js
TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/AssetController.php
TYPO3.Neos/Resources/Private/Partials/Media/ListView.html
TYPO3.Neos/Resources/Private/Partials/Media/ThumbnailView.html
TYPO3.Neos/Resources/Private/Styles/Media/_Media.scss
TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/New.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/RelatedNodes.html
TYPO3.Neos/Resources/Private/Templates/Media/Asset/ReplaceAssetResource.html
TYPO3.Neos/Resources/Private/Translations/en/Modules.xlf
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditor.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/SecondaryInspectorController.js
TYPO3.Neos/Resources/Public/Styles/Neos.css

Fixes and improves a bunch of different issues related to the media browser.
- Dropdown menu overflow
- Dropdown font size
- Notifications not shown inside media browser (iframe)
- Missing jQuery library when showing asset usages in media browser (iframe)
- Clicking image thumbnail again to close leads to an error
- Clicking image thumbnail and then usages and then cancel goes to overview instead of details
- Clicking image thumbnail in inspector and then clicking the close button leads to an error (fixes #1135)
- Translate labels
- No file selected in upload / replace doesn't display any error
- Make "Asset in use / not in use more clear"
- Clicking image thumbnail and then cancel goes to overview and then clicking an asset leads to an error
- Adjust styling of asset details in thumbnail …

TASK: Media browser fixes and improvements

---

TYPO3.Neos/Resources/Private/Templates/Module/Administration/Sites/Edit.html

When clicking the delete site button in the sites administration module's edit view, the following buttons jump a little due to overflow issues. This is circumvented by moving the dialog html outside of the footer.

BUGFIX: Prevent overflow issue when showing delete dialog in sites edit view

---

TYPO3.Neos/Classes/TYPO3/Neos/Utility/BackendAssetsUtility.php

If config for `TYPO3.Neos.userInterface.loadMinifiedJavaScript` is not set, we return TRUE as default.

BUGFIX: Return default for loadMinifiedJavaScript

---

TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html

When clicking the delete asset button in the footer of the edit asset view in the media browser/module the dialog isn't shown due to overflow on the sticky footer is hidden. To circumvent this the dialog html is placed outside the footer.

BUGFIX: Show delete asset dialog in edit asset media view

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Basic/RemoveNode.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php

When an editor creates a new page and then deletes the page again,
the workspace module will show pending changes because shadow nodes
exist for that delete page. Because the page has never been published,
Neos should just really delete the respective nodes from the user's
workspace instead of creating shadow nodes.
This change checks if a node marked for removal exists at all in one
of the base workspaces and if it doesn't, removes it completely instead
of creating a shadow node.
Resolves #1163

BUGFIX: Unpublished new nodes still have shadow nodes after removal

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeAttributes.html
TYPO3.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/PublishingService.php

The "discard selected nodes" feature in the Workspace Review module
leaves orphaned nodes after discarding moved document nodes. The result
is a seemingly empty workspace which in fact still contains nodes.
The workspace can't be deleted. The discarded document node still may
appear in the Content Module's navigation but won't render.
Steps to reproduce based on the Neos demo site:
- start with a clean user workspace
- move the page Download into the page Try me
- go to the review module (Publish Menu -> Review changes)
- select all changes
- press "Discard selected changes"
The document node has been removed, but the child nodes, including the
corresponding shadow nodes, still exist in the database.
Closes #953

BUGFIX: Discard selected nodes which were moved corrupts workspace

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Backend/UserInitialsViewHelper.php

Removal of `TranslationHelper::translateById` in Flow `3.3.4` (https://github.com/neos/flow/commit/09deb9e1e0041f20b7f3ec54af8f1fcbef92e6f0) broke the `UserInitialsViewHelper` and therefore the history module.

BUGFIX: Use up-to-date translation method in history module

---

TYPO3.Neos/Resources/Private/Templates/Media/Asset/Edit.html

This label class got lost during an upmerge in commit
a4f1091d25f2d53a1bd31566081ef16c517d47cf.

BUGFIX: Re-add CSS class in edit asset view

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/TranslateNodeTypes.rst

It fixes small typos where trans-unit tag in sample code is not properly closed.
So it changes `</trans-uni>` to `</trans-unit>`

BUGFIX: fix typos in sample code of Translate NodeTypes documentation

---

TYPO3.Neos/Documentation/ExtendingNeos/CustomEditors.rst

The path to the `TextFieldEditor` is missing the `Inspector` path part.

TASK: Fix typo, fix path to TextFieldEditor

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Strategy/ThumbnailGeneratorStrategy.php

This fixes `ThumbnailGeneratorStrategy::getThumbnailGeneratorClassNames()` making the
method `public`.
Without this fix, the method is silently skipped from static compilation and will always
use reflection to determine classes implementing `ThumbnailGeneratorInterface`.
Note: With resolution of neos/flow-development-collection#662 this will prevent compilation
in Production context

BUGFIX: Fix static compilation of ThumbnailGeneratorStrategy

---

TYPO3.Neos/Documentation/ExtendingNeos/CustomizingInspector.rst

It's `TYPO3.TypoScript:Template` instead of `TYPO3.Neos:Template`

BUGFIX: Wrong Namespace for Template in docs

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Frontend/NodeController.php

This check is already handled by policies:
- TYPO3.Neos:PublicFrontendAccess
- TYPO3.Neos:Backend.GeneralAccess
If that redundancy is removed it makes it possible to use the
`TYPO3.Neos:Backend.OtherUsersPersonalWorkspaceAccess` policy
to grant access to any workspace to e.g. other authenticated users.
This is necessary to build a preview mechanism without an authenticated
backend user to share the state of your content with external previewers.

TASK: Remove duplicate privilege check from NodeController

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/ImportExport/NodeImportService.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/ImportExport/Fixtures/SingleNodeWithLinebreaks.xml
TYPO3.TYPO3CR/Tests/Unit/Domain/Service/ImportExport/NodeImportServiceTest.php

With this change errors during element conversion are no longer silently ignored but
throw an exception during import. Before the value was simply converted to null.
Resolves: #711

TASK: Do not ignore errors when converting values in node import service

---

.travis.yml

The tests are currently supposed to be run in a UTC+1 timezone, due to DST
we switch to a timezone that doesn't observe DST. 
Africa/Tunis is a choice that fullfills these constraints.

TASK: Adjust test timezone to Africa/Tunis

---

TYPO3.Neos.NodeTypes/composer.json
composer.json

This updates the composer.json in `TYPO3.Neos.NodeTypes` and removes the packge-key entry wich was added by mistake and also updates the root `composer.json` with an autogenerated version of our ComposreManifestMerger.php

TASK: Update composer.json

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/Mapping/DateStringConverter.php

This lowers the matching possibility for this specialized type
converter to avoid it being used accidentally on DateTime instances
instead of the Flow ``StringConverter``.
This indirectly fixes a problem with tests exhibited in master
because Flow master has a changed ``StringConverter`` that is now
assigned a lower priority for ``DateTime`` objects than this
converter, which is unexpected.

BUGFIX: Let DateStringConverter accept ``DateTimeInterface``

---

TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/FileTypeIconViewHelper.php

The ViewHelper does not have the argument `asset` or `alt`, but `file` must be given.
**Checklist**

BUGFIX: Correct ViewHelper documentation block

---

TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Form/CheckboxViewHelper.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Format/RelativeDateViewHelper.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/ImageViewHelper.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/ThumbnailViewHelper.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Uri/ImageViewHelper.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Uri/ThumbnailViewHelper.php

With this the ImageViewHelper will always include an alt attribute, even if
not given.
Includes some namespace imports only present in 2.2 branch.
Fixes #1075

BUGFIX: Render empty `alt` attribute in ImageViewHelper

---

TYPO3.Neos/Classes/TYPO3/Neos/Command/SiteCommandController.php

This command adds the `site:create`command that allows to create a blank site with just a single empty document in the default dimension. The name of the site, the packageKey must be specified.
If no nodeType option is specified the command will use `TYPO3.Neos.NodeTypes:Page` as fallback. The node type must already exists and have the superType `TYPO3.Neos:Document`.
If no `nodeName` option is specified the command will create a unique node-name from the name of the site. If a node name is given it has to be unique.
If the flag ``inactivate` is set the new site will not be activated.
The commands `site:activate` and `site:deactivate` are added to bring the according feature of the neos-ui to the cli.
The command `site:list` is extended to display the online state of the sites now. …

FEATURE: Add Commands ``site:create``, ``site:activate`` and  ``site:decativate``

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/LoginController.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Repository/SiteRepository.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/ContentContextFactory.php
TYPO3.Neos/Configuration/Settings.yaml

This change adds a setting defaultSiteNodeName wich allows to configure the behavior for requests without matching host name pattern.
If a request is not mapped to a site via domain pattern Neos currently uses the first active site. 
This is difficult in multisite environments especially since there is no manual order of the sites and currently there is no way to control which site is shown in this case.

FEATURE: Add setting ``TYPO3.Neos.defaultSiteNodeName``

---

TYPO3.Neos/Documentation/References/PropertyEditorReference.rst

Adjust wrong indentations in PropertyEditorReference documentation.

BUGFIX: Fix wrong indentations in documentation

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Administration/SitesController.php
TYPO3.Neos/Resources/Private/Templates/Module/Administration/Sites/Edit.html

The editAction threw an error because a not existing title property in the sitePackageMetaData was accessed. Since getPackageMetaData is deprecated this is refactored to use the informations from the package domain model. The code to display the package title was removed since this property does not exist in composer files.

BUGFIX: Fix error in editAction in the siteController

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Administration/SitesController.php
TYPO3.Neos/Configuration/Policy.yaml
TYPO3.Neos/Resources/Private/Templates/Module/Administration/Sites/NewSite.html

Currently the backend module to create a new site only allows to import a site from an existing site-package or to create a new site-package if the kickstarter is installed.
This change allows to create a new site-node for an existing site-package in the administration-site module. Therefore a new section was added to the module where the user selects site-package-key and rootNode document-type and site-name.

FEATURE: Create empty sites for existing site packages in sites backend module

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Session/BrowserState.php

Changed sortDirection of the media browser back to DESC, so we see the most current media files in the media browser on the top.
This is a possible fix for Issue: https://github.com/neos/neos-development-collection/issues/1230 without the possibility for configuration.

BUGFIX: Set default sort direction of the media browser to `DESC`

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Node.php

Node properties that are empty now return ``null`` without propertyMapping instead of the value stored in the properties-json. This fixes a problem if an asset was selected but later on deleted that previously lead to the asset property returning an empty string.

BUGFIX: Return ``null`` for empty node properties

---

TYPO3.Media/composer.json
TYPO3.Neos.Kickstarter/composer.json
TYPO3.Neos/composer.json
TYPO3.TYPO3CR/composer.json
TYPO3.TypoScript/composer.json
composer.json

As the Neos packages rely on Fluid to render their templates
it makes sense to require the fluid adaptor in those packages.
Resolves: #1235

TASK: Depend on Fluid Adaptor

---

TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst
TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/AbstractCollectionImplementation.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/RawCollectionImplementation.php
TYPO3.TypoScript/Resources/Private/TypoScript/Root.ts2
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/CollectionTest.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/RawCollection.ts2
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/RawCollectionTest.php

Other than ``TYPO3.TypoScript:Collection`` the ``TYPO3.TypoScript:RawCollection`` returns
an array of the rendered items instead of a concatenated string.

FEATURE: Add fusion-prototype ``TYPO3.TypoScript:RawCollection``

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Page.ts2

- see #1238
- Changes applied in the inspector are only visible in the user interface
after a manual browser reload. Appears on the Demo Website.
* it turns out that the *content replacement* on-reload was broken.
* this led to the content area not-refreshing
* ... and also updated the publish button wrongly (as this data is loaded
from the content area).
The content-replacement on-reload was broken because of wrong HTML ordering
in the Page prototype; i.e. the "neosBackendContainer" is supposed to be
rendered at the *end* of the page (directly before the closing body tag);
but it was rendered even before the body.
This error is a regression introduced by https://github.com/neos/neos-development-collection/pull/684 - while adding another level of indirection,
the @position element was …

BUGFIX: on editing changes and backend reload, ensure the content area updates properly

---

TYPO3.Neos/Tests/Unit/ViewHelpers/ContentElement/EditableViewHelperTest.php

This resolves the issue #723 on the Neos side and complements PR neos/flow-development-collection#722

BUGFIX: Use correct namespaces in EditableViewHelperTests

---

TYPO3.Neos/Configuration/Objects.yaml

Removed in neos/neos-development-collection#1208 the configuration
for CommonMarkConverter in Objects.yaml was left in place.

BUGFIX: Remove outdated CommonMarkConverter setup

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/DefaultContentPrototypeGenerator.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/DefaultDocumentPrototypeGenerator.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/DefaultPluginPrototypeGenerator.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/TypoScriptService.php
TYPO3.Neos/Configuration/NodeTypes.yaml
TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst
TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
TYPO3.TYPO3CR/Resources/Private/Schema/NodeTypes.schema.yaml

- If `fusion.prototypeGenerator` is set to a className the class has to implement the interface
`\TYPO3\Neos\Domain\Service\DefaultPrototypeGeneratorInterface` and is used to generate the prototype-code
for this node.
- If `fusion.prototypeGenerator` is set to `null` no prototype is created for this type.
For nodeTypes based on `TYPO3.Neos:Node`, `TYPO3.Neos:Document` or `TYPO3.Neos:Content` a backwards compatible implementation is added to the configuration and a new prototype generator for `TYPO3.Neos:Plugin` is added.

!!! FEATURE: Configurable Fusion node type prototype generators

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Link/NodeViewHelper.php
TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Uri/NodeViewHelper.php
TYPO3.Neos/Tests/Functional/ViewHelpers/Link/NodeViewHelperTest.php
TYPO3.Neos/Tests/Functional/ViewHelpers/Uri/NodeViewHelperTest.php

The ``neos:link.node`` and ``neos.uri.node`` ViewHelpers already support the nodePath as alternative to the node-object this change adds support for the ``node://``-uris of neos.

FEATURE: Support node-uris in ``neos:link.node`` and ``neos.uri.node`` ViewHelper

---

TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/ImageViewHelper.php
TYPO3.Media/Classes/TYPO3/Media/ViewHelpers/Uri/ImageViewHelper.php
TYPO3.Media/Tests/Unit/ViewHelpers/ImageViewHelperTest.php
TYPO3.Media/Tests/Unit/ViewHelpers/Uri/ImageViewHelperTest.php

**What I did**
`ImageViewHelper` (including the URI variant) will now recover if no image is present. 
If the image argument is empty, the ViewHelper will now return empty.
Use the ViewHelper and and do not check if the image exists. No exception should be thrown.
**Checklist**

TASK: Do not throw exception if no image is present

---

Neos.ContentRepository/Configuration/Settings.yaml
Neos.Media/Configuration/Settings.yaml
Neos.Neos/Configuration/Settings.yaml

The code migration is not able to keep comments within yaml files. This change will add missing comments.
Resolves #1255

BUGIFX: Add missing comments in Settings.yaml

---

Neos.ContentRepository/composer.json
Neos.Fusion/composer.json
Neos.Media.Browser/composer.json
Neos.Media/composer.json
Neos.Neos/composer.json
composer.json

Tis necessary since the special logic of the class loader for loading tests will be removed from flow.

!!! TASK: Add autoload-dev section to composer.json for loading test classes

---

TYPO3.Neos/Resources/Private/TypoScript/DefaultTypoScript.ts2
TYPO3.Neos/Resources/Public/JavaScript/Content/EditPreviewPanel/EditPreviewPanelController.js

This change fixes an issue with the edit and preview modes in Neos which result in unexpected output if modes are based on the same Fusion object path.
Prior to this change, preview mode "Desktop" and the edit mode "In-Place" shared a Fusion content
cache. If a site integrator wanted to react on the current mode in her Fluid template (using the
{neos:rendering.inEditMode()} view helper calls) she will get wrong results, depending on which
mode has been called first with an empty cache.
This change now introduces the mode identifier as a new part of the content cache identifier.
Additionally, edit / preview mode buttons will now trigger a reload even for modes which are
based on the same Fusion object path.
Resolves #1249

BUGFIX: preview/edit modes share content cache

---

Neos.Neos/Migrations/Postgresql/Version20161125125249.php

The properties column is of type jsonb, so REPLACE needs to use CAST.

BUGFIX: Use type cast in PostgreSQL migration 20161125125249

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php

This change adds the visualization of changes on ``TYPO3.Neos:ContentCollection`` nodes that also have the type ``TYPO3.Neos:Content`` to the review module. 
Previously those changes were filtered out which prevented the visualization of changes and lead to the page beeing visualized as having changes without showing them in the review module.

BUGFIX: Show changes in ContentCollection-Nodes in review-module

---

.travis.yml

Now that PHP 7.1 is released, we should make sure we are compatible.

TASK: Add PHP 7.1 to .travis.yml

---

Neos.Fusion/Classes/Core/Cache/FileMonitorListener.php
Neos.Fusion/Configuration/Caches.yaml
Neos.Fusion/Configuration/Objects.yaml
Neos.Fusion/Configuration/Testing/Caches.yaml
Neos.Fusion/Migrations/Code/Version20161202215034.php
Neos.Fusion/Tests/Functional/FusionObjects/ContentCacheTest.php
Neos.Neos/Documentation/CreatingASite/ContentCache.rst
Neos.Neos/Tests/Behavior/Features/Bootstrap/FeatureContext.php

This changes the fusion content cache key to ``Neos_Fusion_Content`` and also provides a code migration to adjust the name in yaml and php files

!!! TASK: Rename fusion content cache key to ``Neos_Fusion_Content``

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/MoveNode.feature

In order to retain integrity for nodes we need to move an already
existing node that is to be reused to the target path including
all children. Afterwards the node can be published. That keeps
child nodes together with the published parent and avoids orphan
nodes. Also makes sure child nodes will not exist in two paths.
Fixes: #1277

BUGFIX: Move existing live node in publish

---

Neos.Neos/Classes/Controller/Module/Management/WorkspacesController.php
Neos.Neos/Classes/Service/Controller/WorkspaceController.php

The ``PropertyMappingConfigurationBuilder`` should no longer be used
and can be replaced by calling the
``PropertyMapper::buildPropertyMappingConfiguration`` method.

TASK: Do not use deprecated ``PropertyMappingConfigurationBuilder``

---

Neos.Neos/Classes/Service/Controller/NodeController.php

The action is replaced by ``Service/NodesController->indexAction()``
and was deprecated.

TASK: Remove deprecated ``searchPageAction``

---

Neos.Media/Classes/Domain/Model/ThumbnailConfiguration.php
Neos.Media/Configuration/Settings.yaml

The setting ``behaviorFlag`` simulated how Neos 1.2 handled
image cropping with "maximumWidth" and "maximumHeight".
This behaviour was deprecated and is now removed, "maximumWidth"
and "maximumHeight" need to be replaced by "width" and "height"
if you need fixed dimensions.

TASK: Remove deprecated thumbnail behavior

---

Neos.ContentRepository/Classes/Command/NodeCommandController.php

The command is replaced by ``node:repair`` and was deprecated
since Neos 1.2. It is therefore removed.

TASK: Remove deprecated ``node:createChildNodes`` command

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/AssetService.php

Currently, the Asset models of the Media package cannot be used without having an AssetUsageStrategy implemented. If no such strategy is implemented (e.g. by using Media without Neos and no need for usage information), using an Asset model will lead to a fatal error because the AssetService is trying to loop $usageStrategies which is not an empty array, but null. Therefore, $usageStrategies must be initialized as an empty array.

BUGFIX: Initialize usageStrategies as empty array

---

Neos.Neos/Classes/Setup/Step/NeosSpecificRequirementsStep.php

Some internals of the Flow ``ConfigurationManager`` changed,
making ``clearConfigurationCache`` the wrong method to call
in the setup, which could lead to broken configuration.

BUGFIX: Adapt to changes in ``ConfigurationManager``

---

Neos.Fusion/Classes/View/FusionView.php
Neos.Fusion/Classes/View/TypoScriptView.php
Neos.Fusion/Classes/ViewHelpers/RenderViewHelper.php
Neos.Fusion/Migrations/Code/Version20161219130100.php
Neos.Fusion/Tests/Functional/FusionObjects/AbstractFusionObjectTest.php
Neos.Fusion/Tests/Functional/FusionObjects/BasicRenderingTest.php
Neos.Fusion/Tests/Functional/FusionObjects/CaseTest.php
Neos.Fusion/Tests/Functional/FusionObjects/CollectionTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ConditionsTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ContentCacheTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ContextOverrideTest.php
Neos.Fusion/Tests/Functional/FusionObjects/DebugTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ExceptionHandlerTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ExpressionsTest.php
Neos.Fusion/Tests/Functional/FusionObjects/FusionArrayTest.php
Neos.Fusion/Tests/Functional/FusionObjects/NestedOverwritesAndProcessorsTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ProcessorTest.php
Neos.Fusion/Tests/Functional/FusionObjects/PrototypeInheritanceTest.php
Neos.Fusion/Tests/Functional/FusionObjects/QuotedKeysTest.php
Neos.Fusion/Tests/Functional/FusionObjects/RawCollectionTest.php
Neos.Fusion/Tests/Functional/FusionObjects/RendererTest.php
Neos.Fusion/Tests/Functional/FusionObjects/ReservedKeysTest.php
Neos.Fusion/Tests/Functional/FusionObjects/SimpleTypesTest.php
Neos.Fusion/Tests/Functional/FusionObjects/TagTest.php
Neos.Fusion/Tests/Functional/FusionObjects/TemplateTest.php
Neos.Fusion/Tests/Functional/FusionObjects/UriBuilderTest.php
Neos.Fusion/Tests/Functional/View/FusionViewTest.php

The previous method are move into the ``TypoScriptView`` that maps them
to the new ones. Also the ``setOption`` and ``getOption`` of the ``TypoScriptView`` still
support the `typoScript*`-options but map them internally.

TASK: Refactor the ``FusionView`` to use fusion in variable and method names

---

Neos.Neos/Classes/Controller/Frontend/NodeController.php
Neos.Neos/Classes/View/FusionView.php
Neos.Neos/Classes/View/TypoScriptView.php
Neos.Neos/Tests/Unit/View/FusionViewTest.php

The method names and internal variables that referred to TypoScript were
refactored aswell. 
Additionally a``TypoScriptView`` is provided that maps calls to the 
typoScript methods to their fusion-counterparts.

TASK: Rename ``TypoScriptView`` to ``FusionView``

---

Neos.ContentRepository/Configuration/Caches.yaml
Neos.ContentRepository/Configuration/Objects.yaml
Neos.ContentRepository/Configuration/Production/Caches.yaml
Neos.ContentRepository/Migrations/Code/Version20161219093512.php
Neos.ContentRepository/composer.json
Neos.Media/Classes/Domain/EventListener/ImageEventListener.php
Neos.Media/Configuration/Caches.yaml
Neos.Media/Configuration/Objects.yaml
Neos.Media/Migrations/Code/Version20161219094126.php
Neos.Media/composer.json
Neos.Neos/Classes/Domain/EventListener/AccountPostEventListener.php
Neos.Neos/Classes/Package.php
Neos.Neos/Configuration/Caches.yaml
Neos.Neos/Configuration/Objects.yaml
Neos.Neos/Migrations/Code/Version20161219094403.php
Neos.Neos/composer.json

This change provides core migrations to adjust the cache keys to the new vendor namespace. This change is considered as breaking as the old cache keys are no longer supported

!!! TASK: Adjust cache keys to the new namespace

---

Neos.Fusion/Classes/ViewHelpers/FusionContextTrait.php
Neos.Fusion/Migrations/Code/Version20161219092345.php
Neos.Neos/Classes/Aspects/FusionCachingAspect.php
Neos.Neos/Classes/ViewHelpers/ContentElement/EditableViewHelper.php
Neos.Neos/Classes/ViewHelpers/Link/NodeViewHelper.php
Neos.Neos/Classes/ViewHelpers/Uri/NodeViewHelper.php
Neos.Neos/Configuration/Caches.yaml
Neos.Neos/Configuration/Objects.yaml

This changes adjusts several classes to our new name Fusion. Therefore the ``TypoScriptContextTrait`` and the ``TypoScriptCachingAspect`` as well as the fusion cache key are renamed.
Also the current ``TypoScriptView`` will now be flagged as deprecated in favor for the new introduced ``FusionView``

!!! TASK: Deprecate and rename TypoScript classes

---

Neos.Neos/Classes/Domain/Model/UserInterfaceMode.php
Neos.Neos/Resources/Private/Fusion/DefaultFusion.fusion

The current path in the UserInterfaceMode object was renamed to fusion and thus the switching of the rendering mode that relied on the expression ``${documentNode.context.currentRenderingMode.typoScriptPath}`` did not work any more.
This change alters the used expression to  ``${documentNode.context.currentRenderingMode.fusionPath}`` and
additionally provides deprecated methods ``getTyoScriptPath`` and ``setTypoScriptPath`` for the UserInterface mode as backwards compatibility layer.

BUGFIX: Fix edit preview mode switching

---

Neos.Neos/Configuration/Policy.yaml

This adjusts the `Policy.yaml` to use the `UserService` in order to
determine the currently authenticated backend user rather than
`Security\Context::getParty()` which has been deprecated with 2.0 and
removed with 3.0.
Fixes: #1336

BUGFIX: Adjust Policy to removed Party relations

---

Neos.Neos/Classes/Command/SiteCommandController.php

The ``\Neos\Neos\Command\SiteCommandController::pruneCommand`` now
only reacts to the ``siteNode`` argument. Previously it also accepted
``siteNodeName`` which was deprecated in favor of ``siteNode`` both
having the same effect.

TASK: Remove deprecated ``siteNodeName`` argument

---

Neos.ContentRepository/Tests/Functional/Domain/NodeDataExportServiceTest.php

the ImportExport testing relies on comparison of DateTime
values, as the DateTime object is imported from a file and then
exported again, there can be differences on microsecond level.
With raising the allowed delta this does not lead to a failing
test.

BUGFIX: Allow more imprecision with DateTime in Test

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php
Neos.ContentRepository/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php

The ``NodeDataRepository::reset`` method was deprecated in previous
releases to be replaced by ``NodeDataRepository::flushNodeRegistry``
which is a full replacement for it. Consequently the former is hereby
removed.

TASK: Remove deprecated ``reset`` method in NodeDataRepository

---

TYPO3.Neos/Resources/Private/Templates/Error/NeosBackendMessage.html

Remove "TYPO3" from error page title tag and NeosBackendMessage title tag

BUGFIX: Adjust exception page title

---

Neos.ContentRepository/Classes/Domain/Model/NodeType.php
Neos.ContentRepository/Tests/Unit/Domain/Model/NodeTypeTest.php

You can use ``hasConfiguration`` and ``getConfiguration`` as
replacement for the functionality the magic method offered.

TASK: Remove deprecated magic ``__call`` method in NodeType

---

Neos.Neos/Classes/Aspects/FusionCachingAspect.php
Neos.Neos/Classes/Domain/Service/FusionService.php
Neos.Neos/Configuration/Production/Settings.yaml
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Migrations/Code/Version20161220163741.php
Neos.Neos/composer.json

This change also provides a migration to the no longer supported Setting ``Neos.Neos.typoScript`` to ``Neos.Neos.fusion``
Resolves #1344

!!! TASK: Change the autoInclude path for fusion

---

Neos.Fusion/Classes/FusionObjects/TemplateImplementation.php

Now that there is a way to access the Interceptors the template
package for the Fusion object can be set as default package for the
resource interceptor.
To reproduce use a relative resource path in a Neos template.

TASK: Use introduced ``Parser\Configuration`` access to set package

---

Neos.ContentRepository/Classes/Domain/Model/Node.php

Images removed within the backend no longer return an empty string instead of ``null``. This also fixes regression 2a1c89c7a4ee43c934d9e154fc9164cefc736a06 which returns ``null`` even if a default value like empty string or false is set.

BUGFIX: Return ``null`` if image property comes back empty

---

Neos.ContentRepository/Classes/Package.php
Neos.Fusion/Classes/Core/Cache/FileMonitorListener.php
Neos.Fusion/Classes/Package.php

The cach clearing steps compared to the wrong step identifiers
which are now neos.flow.
**What I did**
Fixed the identifiers
Content Cache and Fusion file caches are not automatically
cleared in development mode without this patch.

BUGFIX: Use neos.flow as step definition prefix

---

TYPO3.Neos/Classes/TYPO3/Neos/Domain/Service/UserService.php

This was broken by 5279a7489efcd3c5f5e411b6b5bda11ad1b4ca75.
Before, checks were done for the role TYPO3.Neos:Editor. However,
checking for AbstractEditor is pointless; workspaces are
now never deleted when a user is deleted. Since the deletePersonalWorkspace
method checks for existence anyway, there's no reason to do
this role check at all. If a user is deleted, his workspaces should be
deleted as well.
Fixes #1376.

BUGFIX: Remove role check when deleting workspaces for users

---

Neos.Media/Classes/ViewHelpers/ImageViewHelper.php
Neos.Media/Classes/ViewHelpers/Uri/ImageViewHelper.php
Neos.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html
Neos.Neos/Resources/Private/Templates/Service/Assets/Index.html
Neos.Neos/Resources/Private/Templates/Service/Assets/Show.html
Neos.NodeTypes/Resources/Private/Templates/NodeTypes/Partials/SimpleImage.html

Remove the deprecated ``asset`` argument within the ImageViewHelpers and also replace ``asset`` with ``image`` within various templates.

TASK: Remove deprecated ``asset`` argument

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/DateTimeEditor.js

Fixes the bug that the DateTime-picker gets an hour off after
daylight-saving-time switch.
Fixes: #851

BUGFIX: Set correct timezoneOffset in DateTime-picker

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Service/NodeService.php

Without this change, it's impossible to change the NodeType (from the inspector) for a NodeType with a default value for a non-scalar property (e.g. DateTime). The service tries to trim a non-scalar value, and throws an error. 
This change checks if the value is a scalar before trimming and adds a check for null value.

BUGFIX: Changing NodeType is broken

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Runtime.php

For `\TYPO3\TypoScript\Core\Runtime->handleRenderingException()`.
Fixed for 3.0 in #1389.

BUGFIX: Path parameter correctly annotated as string

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Session/BrowserState.php

Changes the default sort direction in the media browser back to descending (latest modified first).
Regression introduced in c7aed058d3a363db8e51e8e9b84a557e90bffd0e
Resolves #1230

BUGFIX: Incorrect default sort direction in media browser

---

Neos.Neos/Classes/Domain/Model/Domain.php
Neos.Neos/Classes/Service/LinkingService.php

Fully replaced by ``hostname`` and not used anymore.

TASK: Remove deprecated hostnamePattern from ``Domain``

---

Neos.Fusion/Tests/Unit/TypoScriptObjects/ResourceUriImplementationTest.php

Although the test actually uses the ``ResourceManager`` the doc block says it's
the deprecated ``ResourcePublisher`` this is fixed as the publisher is
bound to be removed.

TASK: Adapt to removed ``ResourcePublisher``

---

Neos.Media.Browser/Configuration/Settings.yaml
Neos.Neos/Classes/Command/UserCommandController.php
Neos.Neos/Classes/Domain/Service/UserService.php
Neos.Neos/Configuration/Settings.yaml
Neos.Neos/Documentation/Operations/CommandLine.rst
Neos.Neos/Documentation/References/CommandReference.rst
Neos.Neos/Migrations/Code/Version20170115114620.php
Neos.Neos/Migrations/Mysql/Version20170115114801.php
Neos.Neos/Migrations/Postgresql/Version20170115115240.php

Remove ``TYPO3`` reference from default authentication backend provider name and rename to ``Neos.Neos:Backend``.
#related https://github.com/neos/Neos.Demo/pull/23
#related https://github.com/Flowpack/Flowpack.Neos.FrontendLogin/pull/15

TASK: Rename default authentication backend provider name

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/AbstractNodeTree.js

**What I did**
Moving a content node across document nodes used to give a JS error:
The error happens inside DynaTree, the code which we do not control. The only way I found to prevent it is to check for existence of child nodes before calling DynaTree's move.
Cut some content node from the tree on one page and paste it on another.

BUGFIX: make moving a content node across document nodes work from the tree

---

Neos.Neos/Classes/Controller/Backend/MenuHelper.php
Neos.Neos/Classes/Service/LinkingService.php

`getHostPattern` was deprecated in Neos 3.0

BUGFIX: Don’t use deprecated hostpattern methods

---

Neos.Neos/Classes/Controller/Module/Management/HistoryController.php

The view was updated to `FusionView`, but `setTypoScriptPathPattern` was still called.
I updated it to the correct method `setFusionPathPattern`.

BUGFIX: Use setFusionPathPattern() in HistoryController

---

Neos.Neos/Documentation/GettingStarted/Installation.rst

The documentation requested ``system`` to be enabled but in fact ``exec``
is used for proxy building in Flow.
Related: neos/flow-development-collection#634

BUGFIX: Correctly require ``exec`` instead of ``system``

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Parser.php

The fusion parser cloned itself previously to handle includes but to keep the defined namespaces.
That made the use of aspects impossible since they were only applied on the initially created instance of the parser.
This change fixes this by using a new instance of the parser for each include and transfers the namespaces explicitly to the new parser.

BUGFIX: Make fusion-parser aspectable

---

Neos.Fusion/Readme.rst
Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Documentation/References/index.rst

In the [documentation](https://neos.readthedocs.io/en/stable/References/) are still some references to TYPO3 and TypoScript. This PR fix it for the fusion part

TASK: Remove TYPO3 & TypoScript in the Fusion documentation

---

Neos.Neos/Classes/EventLog/Domain/Model/NodeEvent.php
Neos.Neos/Classes/Service/BackendRedirectionService.php
Neos.Neos/Classes/Service/UserService.php

These are fully replaced by
``\Neos\Neos\Service\UserService::getPersonalWorkspace``
and
``\Neos\Neos\Service\UserService::getPersonalWorkspaceName``

TASK: Remove deprecated getters for ``userWorkspace`` and name

---

Neos.Media.Browser/Resources/Public/JavaScript/collections-and-tagging.js

Adding a media asset to a tag or collection in the thumbnail in the media browser by dragging it fails.
Resolves #1413

BUGFIX: Adding media element to tag or asset collection

---

Neos.NodeTypes/composer.json
composer.json

The 3.0 branch of neos/form is not compatible with the current codebase.

BUGFIX: Require ~4.0 of neos/form

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/AssetService.php

Fixes a regression introduced in https://github.com/neos/neos-development-collection/pull/1323,
causing the asset usage strategies to never be initialized.
Closes #1425

BUGFIX: Initialization of asset usage strategies

---

TYPO3.Neos/Configuration/NodeTypes.yaml

I changed the non prefixed `regularExpression`-validator to the correct `TYPO3.Neos/Validation/RegularExpressionValidator`-validator
**How to test**
You could easily try to change the `uriPathSegment` on every document node type.

TASK: Prefix `uriPathSegment` field inspector validator

---

TYPO3.Neos/Documentation/References/EelHelpersReference.rst
TYPO3.Neos/Documentation/References/PropertyEditorReference.rst

Adds a small example to the Eel Helpers Reference (Array.indexOf).
Adds an example on how to use the help messages inside properties (Property Editor Reference).

TASK: Documentation adjustments

---

TYPO3.Neos/Resources/Private/TypoScript/DefaultTypoScript.ts2

The page layout determination in `DefaultTypoScript.ts2` contains the query
`q(node).parents('[subpageLayout]').first().property('subpageLayout')`
However that immediately also matches nodes which have `subpageLayout` being an empty string, hence this being taken into account. This results in an empty value, even if there would be actual set layouts higher above.
The `.parents()` part need to be replaced with `.parents('[subpageLayout][subpageLayout != ""]')`
Fixes #1117

BUGFIX: Make layout sliding query match properly

---

Neos.Neos/Classes/EventLog/Domain/Model/NodeEvent.php
Neos.Neos/Classes/Service/BackendRedirectionService.php

f13a82c2d9d5a3185889d21c4cbfca4dbdfde579 introduced a regression: No workspace is created for new users.
This fixes it.

BUGFIX: getPersonalWorkspace()->getName() replaced with getPersonalWorkspaceName()

---

TYPO3.Neos/Documentation/HowTos/SelectingPageTemplate.rst

This adds missing colons to the resource paths in the examples on selecting a page template.

BUGFIX: Add missing colons to resourcepaths in documentation

---

TYPO3.Neos/Resources/Public/JavaScript/vie.js

Instead of applying VIE to all elements with `[rel]` or `[property]` attributes,
only apply to those starting prefixed with the `typo3` namespace.
This prevents side effects for other tags like `<a href="#" rel="nofollow">Link</a>`.
Resolves #1449

BUGFIX: Limit VIE to predicates with custom namespace

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/Editors/ImageEditor.html

Do not show the "remove" button in ImageEditor when no image is selected.

BUGFIX: Only show remove button when image selected in ImageEditor

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/ContextStructureTree.js
TYPO3.Neos/Resources/Public/JavaScript/Content/Navigate/NodeTree.js
TYPO3.Neos/Scripts/Gruntfile.js

This switches (bootstrap) tooltips from being triggered on hover
and focus to just hover. This avoids the tooltip being activated e.g.
by expand a subtree.
Should fix #1386

BUGFIX: Avoid stuck tooltip in node tree

---

Neos.Neos/Classes/Fusion/NodeUriImplementation.php
Neos.Neos/Documentation/References/NeosFusionReference.rst

The fusion argument 'arguments' in NodeUriImplementation was never used. The documentation was confusing saying it is possible to use 'arguments' argument in Fusion.
**What I did**
Removed `arguments` argument from `NodeUri` documentation.
Removed `getArguments()` method from `NodeUriImplementation` because it was never used.

TASK: remove arguments argument for NodeUri

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ThumbnailService.php

If refreshing a thumbnail fails (e.g. because a PDF cannot be converted
correctly), the media module dies with an exception screen.
This change catches and logs the error, and returns null as result. This
leads to a missing thumbnail, but the media management stays usable.

BUGFIX: If thumbnail refresh fails, handle gracefully

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/AbstractNodeData.php
TYPO3.TYPO3CR/Tests/Unit/Domain/Model/NodeDataTest.php

The ``AbstractNodeData::hasProperty()`` method checked
the existence of the given property with ``isset`` but that
leads to an exception if the property has a ``null`` value.
The check has been changed to ``array_key_exists``.
Same is done in the optimization check to avoid setting
existing values again in ``AbstractNodeData::setProperty``.
Resolves #1174

BUGFIX: Check for existing node data property works with null

---

TYPO3.Media/Resources/Private/Partials/ThumbnailView.html
TYPO3.Media/Resources/Public/Scripts/collections-and-tagging.js
TYPO3.Media/Resources/Public/Scripts/upload.js
TYPO3.Neos/Resources/Private/Partials/Media/ThumbnailView.html

Backports f169275c9a05071531dc5bd9b3d2533ebf093184 and d4efa8b305c925aa4e8482db74d5eaf8da9817dc from the 3.0 branch.
closes #1408

BUGFIX: Opening context menu in media browser list view

---

Neos.ContentRepository/Classes/TypeConverter/NodeTemplateConverter.php

Make NodeTemplateConverter::EXTRACT_CONTENT_TYPE_PATTERN match against
`Neos\ContentRepository\…`.
Fixes #1466

BUGFIX: Fix EXTRACT_CONTENT_TYPE_PATTERN namespace use

---

TYPO3.Media/Documentation/DeveloperInformation/index.rst
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Strategy/AssetUsageInNodePropertiesStrategy.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php

Currently the AssetUsageInNodePropertiesStrategy handles
all asset references in all nodes in the node data table.
The handling than is specific for nodes under the `/site` root node
and fails when a node references an asset that is located under another root.
This fixes the issue by only selecting site nodes.
**What I did**
Filter the nodes by site root.
Add an asset reference to a node that is not under sites.
The edit view of an asset fails.

BUGFIX: NodePropertiesStrategy in Neos should only handle site nodes

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/CreateContentContextTrait.php
TYPO3.Neos/Classes/TYPO3/Neos/Domain/Model/Dto/AssetUsageInNodeProperties.php

if no Site is defined.
- delete your sites in the site management
- got to the media browser and open an image
An exception occurres.
See: https://github.com/neos/neos-development-collection/issues/1483

BUGFIX: MediaModule asset edit should not fail

---

Neos.Neos/Documentation/ExtendingNeos/CreatingAPlugin.rst

**What I did**
- Changed  to  in Settings.yaml. It needs to be lower-case in order to work properly.

BUGFIX: Correct typo in plugin's Settings.yaml

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Adjustment/ResizeImageAdjustment.php
TYPO3.Media/Configuration/Settings.yaml

The resize filter can have considerable impact on file size and
processing power needed to do the resize, it's therefore sensible
to give the user a choice in this.
Additionally removes copying the image as that is entirely unnecessary
and impacts memory usage profoundly.

BUGFIX: Allow choice of filter for resizing images

---

TYPO3.Neos/Documentation/References/index.rst

The configuration reference was no longer included in the documentation TOC
at all, after a recent fix aimed at no longer including it twice.

BUGFIX: Include configuration reference in TOC

---

Neos.ContentRepository/Migrations/Postgresql/Version20170328183557.php
Neos.Media/Classes/Domain/Model/Adjustment/ResizeImageAdjustment.php

The wrong namespace/vendor name was pulled in from the 2.3 branch
during an upmerge.

BUGFIX: Fix upmerge mistake in ResizeImageAdjustment

---

Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/Edit.html
Neos.Neos/Resources/Private/Translations/en/Main.xlf
Neos.Neos/Resources/Private/Translations/en/Modules.xlf

**What I did**
- Add translation for labels with none in the XLIFF files to enable the translation to other languages
- Eliminated labels with duplicated IDs and different values
- Some simple sorting and cleanup of the XLIFF files
- I took the labels of the templates and searched the XLIFF files for them
- I put the specific Site Management labels to `Modules.xlf`
- I put the generic labels to `Main.xlf`
- Login to the backend and go to the Site Management module
- Click through it and check whether there are corrupted labels
- The labels should look like before

TASK: Enable translations for labels of the Site Management module

---

Neos.Neos/Documentation/References/PropertyEditorReference.rst

Replaces ``TYPO3.Neos`` with ``Neos.Neos``

TASK: Corrected naming in documentation

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Model/Asset.php

Using the resource media type to find an extension for an asset
is suboptimal because the asset knows the extension directly and
the media type -> extension conversion is ambiguous so you might
end up with a different extension than the resource has afterwards.

BUGFIX: Asset should return same extension as attached resource

---

TYPO3.Media/Classes/TYPO3/Media/Domain/Service/ImageService.php
TYPO3.Neos/Classes/TYPO3/Neos/Service/NodeNameGenerator.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeTemplate.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/ContentCache.php

This reduces the risk of collision on temporary names for nodes and
files, as well as cache markers.

TASK: Use generateRandomString() instead of uniqid()

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/NodeNameGenerator.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeTemplate.php

The changed generation of node names must avoid uppercase characters.
This is a followup to neos/neos-development-collection#1523

BUGFIX: No uppercase characters allowed in node names

---

Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml

The type 'null' has to be written in quotes to be distinguished from the NULL value of yaml.

BUGFIX: Correct the NodeType schema of a nulled fusion.prototypeGenerator

---

composer.json

This relaxes the constraints in order to be able to run stable versions of our development collections.
This is useful when you want to say use beard in production, without having to use the -dev versions.

TASK: allow to require stable version of `flow-development-collection`

---

TYPO3.Neos.NodeTypes/Migrations/Code/Version20130911165500.php
TYPO3.TYPO3CR/Migrations/Code/Version20130523180140.php

This change adjusts two code migrations (in a backwards compatible manner)
so that they don't produce invalid YAML files.
Background:
The two migrations `TYPO3.TYPO3CR-130523180140` and `TYPO3.Neos.NodeTypes-201309111655`
both replace some "superType"/"childNode" NodeType settings.
In cases where those already use the suggested format `['<value>' => true]` this leads
to invalid results (`['<value>' => '1']`).
With `TYPO3.TYPO3CR-20150510103823` these invalid values are fixed again, but applying
all migrations lead to three unnecessary commits, possibly corrupting the configuration
and/or removing important comments.
Fixes: #1351

BUGFIX: Fix code migrations to prevent unnecessary changes

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionSelector.html

**What I did**
Tranlate content dimension labels.
Just like it is already done for dimension labels
Add content dimension. Enter translation id as label. Add id in your translation. Enjoy!

BUGFIX: Allow content dimension preset translation

---

Neos.Neos/Documentation/ExtendingNeos/CreatingAPlugin.rst

The file Policy.yaml is missing in Sarkosh.CdCollection, clearly point out
it needs to be created.
Also explain that packages need to be rescanned (or the cache needs to
be flushed) before you can use the plugin after the optional move to a
"Plugins" folder.

TASK: Improve documentation on plugin creation

---

TYPO3.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
TYPO3.TYPO3CR/Resources/Private/Schema/NodeTypes.schema.yaml

The NodeType schemas can now handle the case that a property in a NodeType definition can be either a dictionary or null.
Additionally the keys `search`  and `options` as extension point for package-configuration.
The key `search` is used by several search implementations and currently causes validation errors.
The key `options` is allowed to avoid such problems in the future and to create a place where packages can place custom configuration.

BUGFIX: Fix the NodeTypes schema files and allow properties `search` and `options`

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Parser.php

Multi-line EEL expressions fail if the TypoScript file had
Windows linebreaks as the explode on line feed leaves the
carriage return in every line which then stops the parser
from detecting the end of a multi-line EEL expression.

BUGFIX: Clean TypoScript of windows line-breaks

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Rendering/LiveViewHelper.php

If the ``LiveViewHelper`` doesn't get a node as argument and neither
there is a node in the template variables it will always return true.
The adjusted doc block clarifies that you need either.
Fixes: #1416

BUGFIX: Clarified doc block for LiveViewHelper

---

Neos.Fusion/Classes/Core/Parser.php
Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestTypoScriptFixture21.fusion
Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestTypoScriptFixture22.fusion
Neos.Fusion/Tests/Unit/Core/ParserTest.php

This throws an exception if there is a direct or indirect prototype inheritance recursion.
Fix #1115

BUGFIX: Detect recursive prototype inheritance

---

Neos.Neos/Documentation/UserGuide/UserSettings.rst

Fixed a typo in documentation in the User Settings document.
Can we verified using : https://neos.readthedocs.io/en/stable/UserGuide/UserSettings.html

BUGFIX: Typo in User Settings doc

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Plugin.ts2

As plugins are uncached the prototype defines which context variables
will be available inside. As ``node``, ``documentNode`` and ``site`` are
defaults that apply everywhere else, the missing ``site`` variable
was added to the context for consistency.
Fixes: #841

BUGFIX: Context variable `site` is available in Plugin prototype

---

Neos.ContentRepository/Classes/Domain/Repository/NodeDataRepository.php

BUGFIX: Avoid null being used in trimExplode()

---

Neos.Neos/Classes/Service/Mapping/NodePropertyConverterService.php
Neos.Neos/Configuration/Settings.yaml

Since PR #1472 was merged the asset list was not correctly converted anymore,
this had two reasons, first the wrong converter was used for the array
itself (``ArrayTypeConverter`` vs. ``TypedArrayConverter``). This is
corrected by setting the correct converter for the respective node property
data type in the settings.
Note that user code should follow the added comment in settings on how to
configure custom types, especially array of objects. It is important to define
the ``TypedArrayConverter`` for the array data type.
Additionally the ``PropertyMapper`` prevent conversion of the inner objects
as with the change the targetType suddenly matched the expected type and so
the PropertyMapper just skipped those objects. That was an unexpected side
effect as the expectation was, that the …

BUGFIX: Asset list should be correctly converted for UI

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/ContentStructure.rst

Do we really need the comparison to TYPO3 CMS? I think this is a nice background information but not related anymore.
http://neos.readthedocs.io/en/stable/CreatingASite/NodeTypes/ContentStructure.html#nodes-inside-the-neos-content-repository

TASK: Remove comparison to TYPO3 CMS in documentation

---

Neos.Neos/Documentation/ExtendingNeos/CreatingAPlugin.rst

The kickstart package name is outdated in documentation (Creating a plugin: http://neos.readthedocs.io/en/stable/ExtendingNeos/CreatingAPlugin.html). I replaced it with the current and right one (https://packagist.org/packages/neos/kickstarter).

TASK: Correct kickstarter package name in documentation

---

TYPO3.Neos/Classes/TYPO3/Neos/ViewHelpers/Uri/ModuleViewHelper.php

The sample code inside the DocBlock used the wrong view helper

BUGFIX: Fix sample code

---

Neos.Media/Classes/Domain/Service/AssetService.php

This adds a missing namespace import for `Uri` after the upmerge of #1574.

BUGFIX: Add missing namespace import in AssetService

---

TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst

The fusion-prototypes `TYPO3.Neos:ContentElementEditable` and  `TYPO3.Neos:ContentElementWrapping`
are not documented.

DOCS: Document prototypes ContentElementEditable and ContentElementWrapping

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/AbstractNodeData.php

If the content of the `properties` property cannot be decoded from JSON
correctly, it will be `null`. This leads to errors when any operation is done
that expects it to always be an array.
This change adds a PostLoad Doctrine lifecycle method to reset `properties`
to an empty array if it is `null` after reconstitution.
Fixes issue #1580

BUGFIX: Reset broken properties to array

---

TYPO3.Neos/Classes/TYPO3/Neos/Package.php
TYPO3.Neos/Classes/TYPO3/Neos/Routing/Aspects/RouteCacheAspect.php
TYPO3.Neos/Classes/TYPO3/Neos/Routing/Cache/RouteCacheFlusher.php

This change fixes a problem with the routing cache which results in
inaccessible document nodes for cases where nodes with different
identifiers but the same URI path exist in separate workspaces.
Fixes #1602

BUGFIX: Nodes are inaccessible after base workspace switch

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php

A workspace having an owner of `null` (plus some other factors) is considered
an internal workspace. This change makes sure the owner is set to null if an
empty string is passed to `setOwner()`.
Fixes #1610

BUGFIX: Use null, not empty string in Workspace->setOwner

---

TYPO3.Neos/Tests/Behavior/Features/Content/PublishUserWorkspace.feature
TYPO3.Neos/Tests/Behavior/Features/EventLog/TYPO3CR/AddingNodes.feature
TYPO3.Neos/Tests/Behavior/Features/EventLog/TYPO3CR/EditingNodes.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Basic/PublishUserWorkspace.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Basic/RemoveNode.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Constraints/ChildNodeConstraints.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/CopyNodeWithDimensions.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/MoveNode.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/MoveNodeWithDimensions.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/RenameNode.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Crazy/RenameNodeWithDimensions.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/EmptyDimensionValues.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/FindSiteNode.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/LanguageDimension.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/LocalizationInWorkspaces.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/LocalizedStructure.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/MatchingMostSpecificLocale.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/MultipleDimensions.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/TranslateExistingNode.feature
TYPO3.TYPO3CR/Tests/Behavior/Features/Localization/Variants.feature

This change fixes an issue with failing Behat tests caused by
missing isolation between tests.
When certain tests were run in a specific order, they might fail
with an access denied error because no user is authenticated.
Fixes #1613

BUGFIX: Behat tests fail with fresh checkout

---

TYPO3.Neos/Classes/TYPO3/Neos/Service/PublishingService.php
TYPO3.Neos/Tests/Behavior/Features/Content/PublishUserWorkspace.feature
TYPO3.Neos/Tests/Unit/Service/PublishingServiceTest.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php

This changes an issue with using the `PublishingService::publishNode()`
which can result in an inconsistent structure in a user's workspace.
This change also changes the behavior of `PublishingService::discardNode()`
which now will also discard content of a given document node to protect
consistency.
Document nodes and their content must be published or discarded together
in order to protect against inconsistencies when the document node is
moved or removed in one of the base workspaces.
Fixes #1617

BUGFIX: Avoid orphaned content nodes when calling publishNode()

---

TYPO3.Neos/Classes/TYPO3/Neos/Controller/Module/Management/WorkspacesController.php
TYPO3.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html
TYPO3.Neos/Resources/Private/Styles/Modules/Management/_Workspaces.scss

This change fixes asset rendering in the workspace overview.
Fixes #1592.

BUGFIX: render asset changes correctly in workspaces overview

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Functional/Domain/Repository/NodeDataRepositoryTest.php

To detect links to assets as "usage" in the media management, the
search in the NodeDataRepository is amended as needed.
Fixes #1575

BUGFIX: Detect asset://so-me-uu-id links in node properties

---

Neos.Fusion/Classes/Core/DslFactory.php
Neos.Fusion/Classes/Core/DslInterface.php
Neos.Fusion/Classes/Core/Parser.php
Neos.Fusion/Configuration/Testing/Settings.yaml
Neos.Fusion/Resources/Private/Schema/Settings.schema.yaml
Neos.Fusion/Tests/Functional/Parser/Fixtures/Dsl/PassthroughTestDslImplemenation.php
Neos.Fusion/Tests/Functional/Parser/Fixtures/Dsl/ValueObjectExpressionTestDslImplemenation.php
Neos.Fusion/Tests/Functional/Parser/FusionParserTest.php
Neos.Fusion/Tests/Unit/Core/Fixtures/ParserTestFusionFixture23.fusion
Neos.Fusion/Tests/Unit/Core/Parser/PatternTest.php
Neos.Fusion/Tests/Unit/Core/ParserTest.php
Neos.Neos/Documentation/CreatingASite/Fusion/InsideFusion.rst
Neos.Neos/Tests/Functional/Configuration/ConfigurationValidationTest.php

DSLs are implemented for fusion-assignments using the tagged-template-string syntax of es6.
DSL-identifiers are configured in the configuration key `Neos.Fusion.dsl`. The configured objects must satisfy the `DslInterface` and return fusion code that is parsed by the fusion-parser afterwards.
```
value = dslExample`... the code that is passed to the dsl ...`
```
In addition this pr adds a schema for the fusion part of the Settings and integrates it into the automatic schema-validation.

FEATURE: Add extension point for domain specific languages to fusion

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/AbstractNodeData.php

Even if the property is set to `null` `AbstractNodeData::hasProperty()` should return `true`.

BUGFIX: NodeData property exists even if set to NULL

---

Neos.Neos/Configuration/Settings.yaml

This changes the occurrences of `Neos.Neos:Main:upload` to `Neos.Neos:Main:choose` in Settings.yaml, as this has been the label formerly used for upload-related Inspector editors.
The label `Neos.Neos:Main:upload` does not seem to exist currently, so the tooltips above upload buttons in the Inspector haven't been translated.
**What I did**
Fix the missing translation for the upload buttons in the image and asset inspector editors.
Change all occurrences of `Neos.Neos:Main:upload` to `Neos.Neos:Main:choose` in Settings.yaml.
Hover above the upload Button of the image editor. Without this change, the tooltip contains the fallback label "Upload file" in every language. 
**Checklist**

BUGFIX: Fix missing translation for inspector file uploads

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/NodeOperationsTrait.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Workspaces/MultiLayeredWorkspaces.feature

This change contains a fix and additional Behat tests which solves an issue with moving and publishing nodes in a nested workspace scenario which can lead to data corruption in the content repository.
Resolves #1608

BUGFIX: Publish moved nodes in nested workspaces

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/InspectorController.js

This change fix a JS console error, when ember try to call _applyChangeHandler
on property like _nodeType, because this property is not really an editor.

BUGFIX: Skip apply change handler if the editor is undefined

---

Neos.Media.Browser/Resources/Private/Partials/ListView.html
Neos.Media.Browser/Resources/Private/Partials/ThumbnailView.html
Neos.Media.Browser/Resources/Private/Templates/Asset/Index.html
Neos.Media.Browser/Resources/Private/Templates/Asset/New.html
Neos.Media.Browser/Resources/Private/Templates/Asset/RelatedNodes.html
Neos.Neos/Resources/Private/Partials/Backend/Menu.html
Neos.Neos/Resources/Private/Partials/Module/Management/Workspaces/ContentChangeDiff.html
Neos.Neos/Resources/Private/Partials/Module/Shared/EditUser.html
Neos.Neos/Resources/Private/Partials/Module/Shared/NewElectronicAddress.html
Neos.Neos/Resources/Private/Partials/Module/Shared/NodeContentDimensionsInformation.html
Neos.Neos/Resources/Private/Templates/FusionObjects/BreadcrumbMenu.html
Neos.Neos/Resources/Private/Templates/Login/Index.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Configuration/Index.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/Edit.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Sites/Index.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Index.html
Neos.Neos/Resources/Private/Templates/Module/Administration/Users/Show.html
Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Index.html
Neos.Neos/Resources/Private/Templates/Service/ContentDimensions/Index.html
Neos.Neos/Resources/Private/Templates/Service/ContentDimensions/Show.html

Comparing objects in Fluid templates using `==` may lead to "nesting
level too deep" errors, depending on the objects being compared.
This change adjusts all non-strict comparisons against strict ones.
Fixes #1626

BUGFIX: Use strict comparison to avoid nesting level error

---

Neos.Neos/Migrations/Postgresql/Version20170629102140.php

It seems that the default value set previously does not survive
renaming the sequence. This leads to errors when events are to be
persisted.
This change adds the expected default value (back).

BUGFIX: Set default value for event uid on PostgreSQL

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/ContentCache.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/RuntimeContentCache.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/ContentCacheTest.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/ContentCache.ts2

Currently, when using the content cache mode `dynamic` the `entryDiscriminator`
is only considered when _writing_ the Cache entry.
When trying to _retrieve_ the content segment, the discriminator is omitted
from the cache entry identifier.
Thus, the `dynamic` cache mode currently acts like `uncached`.
This change fixes the behavior and adds a functional test.
Fixes: #1630

BUGFIX: Respect `entryDiscriminator` when using Content Cache mode `dynamic`

---

Neos.Neos/Classes/Fusion/ImageUriImplementation.php
Neos.Neos/Documentation/References/NeosFusionReference.rst
Neos.Neos/Resources/Private/Fusion/Prototypes/ImageUri.fusion

Adds support for generating asynchronous image URIs in case the requested image does
not exist already. The feature is already supported in the `ImageViewHelper` but was missing
in the fusion objects.
This works as follows:
- If a resource still has to be processed a /media/thumbnail-uri is rendered that will do the
actual processing and return the image.
- Later if the resource is already processed the _Resource-uri is rendered as previously.

FEATURE: Add `async` flag to the `Neos.Neos:ImageUri` and `Neos.Neos:ImageTag` fusion-objects

---

Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php
Neos.Neos/Classes/Package.php

The content cache does not invalidate on changes to an asset. Expected behavior would
be to flush the content cache on changes to an asset (e.g title, caption).

BUGFIX: Trigger ContentCacheFlusher on asset update

---

Neos.Neos/Classes/Service/HtmlAugmenter.php
Neos.Neos/Tests/Unit/Service/HtmlAugmenterTest.php

If plaintext is given to the html augmenter now uses the fallback-tag
as it already does if multiple tags are found on the same level.
This fixed the problem of contents not beeing selectable in the backend 
if no tags are found but just some text.

FEATURE: HtmlAugmenter will augment plaintext with the given fallback-tag

---

Neos.Neos/Resources/Private/Partials/Module/SubmoduleOverview.html

When a module has been disabled using the `disabled` flag, the module is hidden from the main menu and cannot be accessed, however it was still being displayed in submodule overviews.

BUGFIX: Hide disabled modules in submodule overviews

---

Neos.Neos/Classes/Fusion/ContentElementWrappingImplementation.php

In the change https://github.com/neos/neos/commit/c4f64615297503b5577e5c863758d2a9b480433d,
the default @process.contentElementWrapping on Neos.Neos:Content was changed from
@process.contentElementWrapping to the long form
"@process.contentElementWrapping.expression" (so it was possible to specify
a position).
However, this meant the Fusion path in Frontend for such an element was calculated wrongly;
It appended __meta/process/contentElementWrapping/expression<Neos.Neos:ContentElementWrapping>
to the fusionPath in the DOM.
For the "old" Neos (ember-based) UI, everything works pretty much as expected (it's
quite hard to construct a scenario where this would trigger an actual bug); but
the new React UI gets confused with rendering the element when the Fusion path is wrong.
And as it is a …

BUGFIX: cut off long-form processor syntax in ContentElementWrappingImplementation

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php
TYPO3.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php

Makes sure that generated URLs observe the setting.
Fixes: #1644

BUGFIX: Valid URLs with `supportEmptySegmentForDimensions`

---

TYPO3.Neos/Resources/Private/TypoScript/Prototypes/Content.ts2

If no `attributes.class` is given the attribute always starts with space. Like that the attributes get trimmed.
`class=" foo-bar-content"`
`class="foo-bar-content"`

BUGFIX: Prevent space if no css class is given

---

TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/NodeData.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Model/Workspace.php
TYPO3.TYPO3CR/Classes/TYPO3/TYPO3CR/Domain/Repository/NodeDataRepository.php
TYPO3.TYPO3CR/Tests/Behavior/Features/Workspaces/MultiLayeredWorkspaces.feature

This change fixes a problem in the content repository which can lead to a uniqueness constraint error when a node is moved back and forth in a nested workspace.
Fixes #1639

BUGFIX: Moving node back and forth in nested workspace causes SQL error

---

Neos.Neos/Classes/Fusion/ImageUriImplementation.php

Until now the ``ImageUri`` prototype would return no image if the preset was set to ``false`` (only accepted fallback until now was ``null``). With this change it's also possible to reset the preset with ``false``.

TASK: Ignore preset value if ``false``

---

TYPO3.Neos/Documentation/CreatingASite/ContentCache.rst
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/ContentCache.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Cache/RuntimeContentCache.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/ContentCacheTest.php
TYPO3.TypoScript/Tests/Functional/TypoScriptObjects/Fixtures/TypoScript/ContentCache.ts2

With this change the caching can be disabled by setting the `entryDiscriminator`
to `false` when using Content Cache mode `dynamic`.
Previously a cache entry was created anyways with the `entryDiscriminator` casted
to an (in this case empty) string.
Background:
The Content Cache mode `dynamic` was introduced in order to allow for more flexible
caching behaviors depending on the context.
But one important feature did not work yet: Being able to *disable* the cache
for certain requests.
With this change performance can be improved by caching the display of an interactive
element (i.e. cache Forms for GET requests)
Related: #1630

TASK: Don't cache dynamic segments with disabled `entryDiscriminator`

---

TYPO3.Neos/Documentation/CreatingASite/NodeTypes/NodeTypeDefinition.rst

corrected path in documentation for thumbnail of nodetype

BUGFIX: Fix nodetype thumbnail path in NodeTypeDefinition.rst

---

Neos.Media/Classes/Domain/Service/AssetService.php

This adds a condition to compare the size of the old and new asset in order to verify
the size did not change. In this case the method `refit()` will not be executed to keep
asset adjustments. This is very handy if you upload/replace a image with enriched
meta data (eg. IPTC or Exif.)

TASK: Keep asset adjustments if asset size did not change

---

Neos.Neos/Resources/Private/Templates/Module/Management/Workspaces/Show.html

The workspace module shows changes grouped by document, but until now
there it was only possible to select individual or all changes for
further action.
This change adds the possibility to select all changes on a document
with a single click.

FEATURE: Allow to select all changes in a document with one click

---

Neos.Fusion/Classes/Core/Cache/CacheSegmentParser.php
Neos.Fusion/Classes/Core/Cache/ContentCache.php
Neos.Fusion/Tests/Unit/Core/Cache/CacheSegmentParserTest.php
Neos.Fusion/Tests/Unit/Core/Cache/ContentCacheTest.php

Rewrite the internals of the CacheSegmentParser to use a recursive
approach which should safe some memory and makes the code more readable.
Also refactors common logic for fetching tokens and content to methods
to avoid code duplication.
Additionally adds calculation of uncached segments in the currently parsed
content to make solid cache entries (full page cache) possible.

TASK: Rework CacheSegmentParser to a recursive pattern

---

TYPO3.Neos/Classes/TYPO3/Neos/View/TypoScriptView.php
TYPO3.Neos/Tests/Unit/View/TypoScriptViewTest.php
TYPO3.TypoScript/Classes/TYPO3/TypoScript/TypoScriptObjects/Http/ResponseHeadImplementation.php

The httpVersion which could be set in the `ResponseHeadImplementation`
was not used.
Additionally, if a header had multiple values (which can easily be done in
TypoScript via RawArray) only the first header was actually transferred to
the sent HTTP response.

BUGFIX: TypoScriptView should set response headers correctly

---

TYPO3.TypoScript/Classes/TYPO3/TypoScript/Core/Parser.php
TYPO3.TypoScript/Tests/Unit/Core/Fixtures/ParserTestTypoScriptFixture21.ts2
TYPO3.TypoScript/Tests/Unit/Core/ParserTest.php

Prototype declarations starting with digits previously were wrongly
parsed and resulted in broken names, this change fixes it by only
casting numeric strings to integers as object keys.
Fixes: #1114

BUGFIX: Allow Prototype names starting with digits

---

TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php
TYPO3.Neos/Tests/Unit/Routing/FrontendNodeRoutePartHandlerTest.php

If a node is visible but lies beneath a hidden parent, the URI path
generated for that node had "holes" and did not work. This adjusts the
route part handler to return the complete URI including the URI path
segments of hidden nodes in the chain up to the site node.
To disallow showing a node actually hidden itself has to be ensured
in matching a request path, not in building one.

BUGFIX: Build correct paths to nodes with hidden parents

---

Neos.NodeTypes/Resources/Private/Fusion/Root.fusion

To prevent errors within the form view helper it's necessary to set `overrideConfiguration` as array per default instead of null. The change of the signature of the form view helper has made this change necessary:
https://github.com/neos/form/commit/0cac9ef02043c9ae5e25eb41a7f746ba75e80f2d
The default tempate just by-pass the `overrideConfiguration`:
https://github.com/neos/neos-development-collection/blob/3.0/Neos.NodeTypes/Resources/Private/Templates/NodeTypes/Form.html

BUGFIX: Set empty array for overrideConfiguration as default

---

TYPO3.Neos/Documentation/References/NeosTypoScriptReference.rst

Example is missing the namespace.

TASK: Fix documentation of Debug Object

---

TYPO3.Neos/Resources/Public/JavaScript/Content/Inspector/PropertyEditor.js

This change makes sure editor listeners are called in the init of the editor. This can help in situations like hiding an editor based on depending properties on the first page load or inspector initialization.

BUGFIX: Register pending change must be called during editor init

---

TYPO3.TYPO3CR/Resources/Private/Schema/NodeTypes.schema.yaml

A NodeType can reset the `childNode` definitions of a
superType by setting it to `null`:
```yaml
'Some:NodeType':
superTypes:
'Some:Other.NodeType': true
childNodes:
'someChildNodes': ~
```
But doing so lead to a schema error.
This patch adjusts the schema accordingly.

BUGFIX: Allow childNode definitions to be reset

---

TYPO3.TYPO3CR/Resources/Private/Schema/NodeTypes.schema.yaml

In #1678 childNodes were allowed to be nullable. But the way the schema
was adjusted did not pass validation. This change fixes it.

BUGFIX: Fix NodeType schema to pass validation

---

Neos.Neos/Documentation/CreatingASite/RenderingCustomMarkup/Templating.rst

We have open/close quotation marks (””) in code examples so i replaced them with normal ("") quotation marks.
**What I did**
Replaced quotation marks

TASK: Replaced "wrong" quotation marks

---

Neos.ContentRepository/Classes/Security/Authorization/Privilege/Node/Doctrine/ConditionGenerator.php
Neos.Neos/Documentation/CreatingASite/Security.rst

This makes it possible to access global objects via the context variable in node privileges.
For example this can be used to hide nodes based on a node property which needs to
match a username or group. One use case is to have several sites in one Neos and restrict
each user to one site.
How it works: The values given to the `ConditionGenerator` of the node privileges are
first put through `getValueForOperand` instead of treating them just as string.

TASK: Allow using the context variable in node privileges

---

Neos.Media/Classes/Command/MediaCommandController.php

This command iterates over all existing assets, checks their usage count
and lists the assets which are not reported as used by any AssetUsageStrategies.
The unused assets can than be removed.
```
Searching for unused assets:
12/12 [============================] 100%
Found the following unused assets:
- 2a2952ce-ba38-45bc-9b88-03d013831fd6 (Bildschirmfoto 2016-11-01 um 14.14.15.png)
- 5279fcc0-4557-4033-be66-5fbe766aa2e2 (Bildschirmfoto 2016-11-01 um 14.11.43.png)
- 5890c270-9f35-4327-8876-46388403bacf (Bildschirmfoto 2016-11-01 um 14.14.57.png)
Do you want to remove 3 unused assets?y
3/3 [============================] 100%
```
```
./flow media:removeunused
Searching for unused assets:
9/9 [============================] 100%
No unused assets found.
```

FEATURE: Introduce command to remove unused assets

---

Neos.Neos/Documentation/CreatingASite/NodeTypes/TranslateNodeTypes.rst

Like https://github.com/neos/neos-development-collection/pull/1566 but for older branch.

BUGFIX: Fixing wrong path in documentation to translations folder
